### ISSUE TITLE
Loading progress messages being sent when the rendering is activated and loading screen not visible

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#1001]
We should stop sending those messages when the loading bar is not visible and feedback is not needed, as they use `SendMessage` and that can consume a lot of performance.

![image.png](https://images.zenhubusercontent.com/5d9756603fe18d00011cfcac/af903ca5-270a-4897-ac9f-345e58ff07c9)

**Comment by Suduck** [comment]
Mendez message:
Hello team, I've been debugging some hiccups and I found something interesting, 90% of the messages sent from unity->kernel are actually loading messages https://github.com/decentraland/kernel/blob/main/docs/tracing.md
It even happens after the loading screen is not visible, while walking the world. Is there a way we can at least filter duplicates to prevent sending twice the same messages if the % is ok?
