### ISSUE TITLE
Some wearables with emissive / alpha blend are not working

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1006]
Some emissive materials are not working properly.

![image](https://user-images.githubusercontent.com/41490935/129886537-eb5d74c6-128b-4a74-8cae-eebb6c924dfe.png)

Started happening in 1.0.10667

**Comment by BrianAmadori** [comment]
Any hints on what wearable / collection may be causing this issue? Because I see that some wearables work and some don't.

**Comment by 3rdEyeVisuals** [comment]
> Any hints on what wearable / collection may be causing this issue? Because I see that some wearables work and some don't.

Hi Brian, hope all is well. I wanted to touch base and let you know that some wearables that I have created are being affected. Let me know if there is anything I can do to help resolve this matter. Send you Shader Node data, etc... Cheers!

**Comment by 3rdEyeVisuals** [comment]
Glad to see you are narrowing it down :) Cheers! Thank you for your diligent work!

**Comment by 3rdEyeVisuals** [comment]
Seems to also be affected by Alpha Clip:
![image](https://user-images.githubusercontent.com/89211220/130251084-2a09824c-62fd-42a6-9ff6-8ee11b86eac1.png)

**Comment by 3rdEyeVisuals** [comment]
It most def has something to do with Alpha Clipping/Blending. Seems that in game the Alpha settings are dropped to zero for some reason. That is the only way to achieve fully transparency.

**Comment by BrianAmadori** [comment]
Ty for the info @3rdEyeVisuals! If you have more wearables with this issue please send me the collection name.

Adding reported wearables without emission:
* fire warrior face
* fire warrior katana
* hiroto kai fire warrior boots
* hiroto kai ceremonial kimono
* the full acid warrior set
* hiroto kai wooden katana
* blue dragon kimono set

**Comment by 3rdEyeVisuals** [comment]
> Ty for the info @3rdEyeVisuals! If you have more wearables with this issue please send me the collection name.
> 
> Adding reported wearables without emission:
> 
> * fire warrior face
> * fire warrior katana
> * hiroto kai fire warrior boots
> * hiroto kai ceremonial kimono
> * the full acid warrior set
> * hiroto kai wooden katana
> * blue dragon kimono set

So Far it is just my 'Eff-It NFTee' (Released) and my 'Sensimilla NFTee' (under review still due to this bug). I am trying a test case with the emissive on arms set to Opaque but of course now DCL doesn't want to work.... 
![image](https://user-images.githubusercontent.com/89211220/130263047-ba1275b0-ea27-4d11-9bc6-92a618102fe2.png)

**Comment by 3rdEyeVisuals** [comment]
I get the same error message EVERY time I try to put on the wearable over the Ropsten Test net in game.. I will stop convoluting this thread. Let me know if I can be of any help! We all want to find the solution :) Cheers!

**Comment by menduz** [comment]
@3rdEyeVisuals Hello, could you please share the full link that breaks that way? It will be very helpful to reproduce the issue, thanks in advance

**Comment by 3rdEyeVisuals** [comment]
> @3rdEyeVisuals Hello, could you please share the full link that breaks that way? It will be very helpful to reproduce the issue, thanks in advance

The error message appears cut off that way on screen too... :l I will try to replicate to see if it appears. I now can't get wearables to load while in Ropsten Network period:
![image](https://user-images.githubusercontent.com/89211220/130277378-56369d11-7c4e-4139-a859-ec8c58eb71d0.png)

**Comment by 3rdEyeVisuals** [comment]
It appeared cut-off again... 
![image](https://user-images.githubusercontent.com/89211220/130277650-b2ed1699-02fe-4c54-9575-ce58022c13ba.png)

**Comment by menduz** [comment]
@3rdEyeVisuals please share the ropsten link you are using

**Comment by BrianAmadori** [comment]
Please keep this thread about the emissive/alpha blend bug. Open another issue to talk about the error screen. Thanks.

**Comment by BrianAmadori** [comment]
Status update: The issues were fixed at https://github.com/decentraland/unity-renderer/pull/1036. About to put the PR on review and most likely will be in production on monday.

**Comment by olavra** [comment]
closing the issue
