### ISSUE TITLE
Settings - Sounds channels controls

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#102]
We need to add the possibility of turning on/off audio through different channels. Now, we only have a single general switch for the sound. The biggest issue we experiment with this barrier is on music events: we can't turn on/off UI sounds without turning off the music too, and is impossible to enjoy the music that is being played while the chat sounds are constantly popping.

If it's very complicated to implement all this sound channels controls, at least we can start separating UI sounds controls from scenes one.
![AudioSettings.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/53031192-2032-4ccc-8eb8-eb4dceb6880e)

**Comment by olavra** [comment]
This is being tackled by @Landeplage in #865
