### ISSUE TITLE
Debug scene that never finishes loading

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1033]
There is a big scene in the Aetheria Project district that never finishes loading, its coordinates are **150, 63** but spawning directly into the scene never enabled the rendering as the scene never finishes loading.

This spawning coord is right next to the scene (outside) but normally it never finishes loading either...
https://play.decentraland.org/?position=149%2C62&realm=fenrir-amber

The best is to start the explorer even farther away and walk to the problematic scene.

**Comment by sandrade-dcl** [comment]
#### Not reproducible issue

I have done several tests loading this scene and, although it is a heavy scene and it could take some time, it always finishes its loading correctly.

Some screenshots walking around the scene:

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/da321595-a65c-4311-8739-8b4b9c3cb080)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/24216f9e-ef1e-452a-a9c8-777bd8254ddb)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/9bd19360-a562-4908-88d3-2be213748ff3)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/f95ceea4-b552-4084-8f94-6c7638136d56)

**Comment by pravusjif** [comment]
I confirm now the scene loads!
That scene is super heavy, it could be a good profiling case.

**Comment by pravusjif** [comment]
I'm re-opening the issue since this is happening again with that same scene as reported by @nearnshaw .
I took a quick look and the nullreference exception that can be seen in the browser's console log is a null material at [this line](https://github.com/decentraland/unity-renderer/blob/232f8ae33adf8052df161659ea8c65e4542892e4/unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/MaterialHelpers/MaterialCachingHelper/MaterialCachingHelper.cs#L45)

**Comment by Suduck** [comment]
I am not able to load it in the Unity Editor, I have found differents errors all related to the Curl like the following error :

`Curl error 52: Send failure: Connection was aborted`

**Comment by Suduck** [comment]
The scene can be loaded so I am going to close the issue
