### ISSUE TITLE
Genesis plaza bar: beer mugs missing from the tables

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#1034]
If I go to genesis plaza, I don’t see any of the beer mugs on the tables. Everything else seems to work fine with the scene, except these missing models.

If I run a local preview of the scene, I do see them and they work well.
https://github.com/decentraland-scenes/Genesis-Plaza

![Screen Shot 2021-08-20 at 16.21.39.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/697b2b32-4031-4081-8924-befa2aea4422)

In prod I see the other coffee cups and bottles, but not the beers. It's strange because the coffee cups and the bottles share almost the same code with the beer mugs for picking up and putting down. The beer mugs just have a couple of extra animations for when you fill them up on the tap.

![Screen Shot 2021-08-20 at 16.20.03.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/867b35fe-5580-45e5-ac7f-57b4f945d4e4)

I tried different realms in case someone moved them, even realms with no other players and they're still not there
I tried redeploying the scene after verifying it worked locally, and still not there

---------------------------

- [x] Convert mug locally. DONE: the visual tests detect the conversion is not successful and the asset is not converted
- [x] Eliminate mug from S3
- [x] Run same checks on 154, 66 reported assets. DONE: didn't find those assets, looked at them without ABs enabled.
- [x] Update ABs fetching url Version to invalidate those cached requests

**Comment by nearnshaw** [comment]
Someone in the community reported this, that looks a lot like it could be the same issue

![Screenshot_20210823-084647_Discord.jpg](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/203b0ef6-3dcf-4473-9cf1-1b71d7cb4564)

**Comment by pravusjif** [comment]
The OnPointerEvent hover feedback is displayed but the mesh is not being rendered.

Already tested toggling culling setting and it's not the culprit

**Comment by pravusjif** [comment]
Confirmed this invisible ABs issue is not the same as the white ABs. I'm unblocking it and assigning it to myself of the future

**Comment by pravusjif** [comment]
Mug asset hash: QmWNwAgDSLMKYvRiQJu25wtohMe9UwWPzspsFb8EharwFy

**Comment by nearnshaw** [comment]
@pravusjif   would it fix this if we modified the mug asset and redeployed?

or do you prefer to keep this broken to investigate and find the root cause?

**Comment by pravusjif** [comment]
The mug must've been wrongfully converted before the latest converter updates, as it locally detects that the AB is not successfully created and ends up with no AB to upload.
I deleted that wrongfully converted AB from the S3 and just need to invalidate cloudflare's cache again.

**Comment by pravusjif** [comment]
I just tested with enabled ABs and now the asset is rendered correctly. If you re-deploy it shouldn't break the asset again, as the converter aborts this AB with its visual test detection.

![Screen Shot 2021-11-11 at 11.09.07.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/982a8476-73e6-432a-b335-fa5e6bebda8b)
