### ISSUE TITLE
Force double sided wearables to back culling for opaque objects to improve performance

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#1043]
- [x] Modify submissions limitation document
- [ ] Fix affected collections
- [ ] Unlock feature on `unity-renderer` (already has PR #1000)

**Comment by BrianAmadori** [comment]
Blocked until @ShibuyaMartin fixes affected wearables duplicating and reversing opaque geometry.

**Comment by olavra** [comment]
@ShibuyaMartin any update on this?

**Comment by olavra** [comment]
@BrianAmadori closing the issue
