### ISSUE TITLE
Automate code sign Explorer Desktop Launcher executables

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1045]
### Description
We have a manual step right now to create a release and we want to automate the process.

### Deliverables

- [ ] Automate windows license

**Comment by 2fd** [comment]
As specified in the [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted#microsoft-hosted-cicd), we requested Azure to increase our parallel jobs limits for private repos using the following form: https://aka.ms/azpipelines-parallelism-request

![Screenshot 2023-03-09 at 16.49.25.png](https://images.zenhubusercontent.com/5e3c030aa21fc98c7daa9b14/53c8ab41-a61e-4f57-9a2f-e7ea716c16dd)
