### ISSUE TITLE
Skin color changes on some body parts while changing wearables

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1048]
reported by @ShibuyaMartin 

https://images.zenhubusercontent.com/337227404/801fcbe1-736a-43d3-b2a0-daa87d49f5c4/bug_tint_color.mp4

**Comment by BrianAmadori** [comment]
Was able to reproduce a few times but didn't found the repro steps. Will not fix until we can confirm this has deterministic repro steps.
