### ISSUE TITLE
I hear sounds from entities attached to player when I enter the scene

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#105]
If I have an entity that produces a sound that's attached to the player's position, the entity will play its sound when I walk out of the scene and back in. Even if the sound is only meant to be played in special occasions and it wasn't triggered to be played.

This is quite evident in the Frisbee scene:

https://play.decentraland.org/?position=70%2C21&realm=fenrir-amber

Steps to reproduce:
- Pick up the frisbee
- Walk outside the scene and then back in, you'll hear the sound then

You're only meant to hear sounds when throwing and catching the frisbee. There's nothing in the code telling the sounds to play when you walk in.  This is likely related to the unmuting of sounds that are from the scene.

Code for this scene:

https://github.com/decentraland-scenes/websocket-frisbee

We also see the same happen on this other scene from the community:
https://play.decentraland.org/?position=42,58

If you pick up the gun and then walk out and back in, you hear a gun shot.

**Comment by kuruk-mm** [comment]
After testing a lot, and checking with @nearnshaw .

Seems that this bug stopped happening after the the migration to Unity 2020 decentraland/explorer#2249, but only in Mac and Linux with Chrome. But still happens on Windows with Chrome :fearful:.

So it's very weird, and it's not consistent. So more tests will be needed.

If someone could verify to have more information:

In this PR the bug doesn't happens in Linux and Mac:
https://explorer.decentraland.zone/branch/chore/unity-2020-3-0-f1/index.html?ENV=org&position=70%2C21&realm=fenrir-amber

https://images.zenhubusercontent.com/337227404/fbf099fe-8d1a-42a8-94e8-020e0dc0ca4e/2021_04_16_16_56_56.mp4

In this PR happens (previous working PR):
https://explorer.decentraland.zone/branch/fix/make-start-website/index.html?ENV=org&position=70%2C21&realm=fenrir-amber

https://images.zenhubusercontent.com/337227404/ca49d9fb-88ae-43c3-b3c2-d286cd9ec222/2021_04_16_16_55_41.mp4

Position: 70,23

**Comment by nearnshaw** [comment]
FYI. I also experienced the same
I tested this same scene in two machines, one Mac & one WIndows, same RC branch, Chrome on both
- in the Mac machine the issue was no longer there
- in the Windows machine, it was still there like in older versions

**Comment by kuruk-mm** [comment]
Some tests:

This bug happens in Windows 10 (5/5 testers).

And it doesn't happens in Linux/Mac (3/3 testers).

So we need to see what is happening in Windows.
