### ISSUE TITLE
Spike: Investigate Github Report a bug 

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1054]
- [x] Investigate GitHub report a bug, mate sure we can send parameters via URL, upload images, get technical specs. etc.

**Comment by kuruk-mm** [comment]
Yes, we can. Example: https://github.com/kuruk-mm/test-repo/issues

For example, if we want to put my e-mail as contact you can add:

https://github.com/kuruk-mm/test-repo/issues/new?template=bug_report.yml&contact=mateo@decentraland.org

To map the parameter with the form parameter, you need to add the `id` on the .yml format. It's very simple.

We need to defines which parameters we want.
