### ISSUE TITLE
Spike: verify checks on "no-longer-owned" wearables for other avatars. 

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1062]
As part of the third party wearables initiative, we need to check which validation does the explorer on other avatars wearing wearables that are owned or not.
Research if "no-longer-owned" wearables are validated by some part of explorer

**Comment by AjimenezDCL** [comment]
Just checked with platform. Sold wearables are removed by the lambdas when retrieving both user catalog and user profile. 

The only edge case affecting the renderer is about user profiles that suddenly doesn't contain wearables for required categories (such as `upper-body` or `lower-body`). I made a local test with profiles not containing said wearables and it's falling back to default wearables correctly.

Even empty profiles (with just bodyshape) are working fine.
