### ISSUE TITLE
Limit avatar visible names when too many avatars are on the screen

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#1086]
Right now, if we instantiate 200 avatars, 200 names will be rendered. This has a performance overhead we should mitigate.

We should only show a limited number of the closest names (i.e. 50).

**Comment by AjimenezDCL** [comment]
As discussed, I'm going to tie up the names to our LOD0/LOD1 so we take advantage of the players already sorted by distance.
