### ISSUE TITLE
Explorer crashes while walking on some big scenes

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1092]
from @nearnshaw :

> I’m getting this a lot when walking around Dragon City
> likely bc they have huge scenes next to each other and when they’re all loaded it’s a lot
> but it should at least crash the scenes, not the explorer

https://play.decentraland.org/?CATALYST=peer-testing.decentraland.org&ENABLE_QUESTS&QUESTS_SERVER_URL=https%3A%2F%2Fquests-api.decentraland.io&island=Igc&position=85%2C-79&realm=testing (edited) 

![Screen Shot 2021-08-30 at 08.59.31.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/05114113-33dc-445d-b8d5-d8c59ee6f204)

**Comment by olavra** [comment]
Do a profile of memory usage

**Comment by pbosio** [comment]
It's not crashing anymore for me.
Anyway, these use to be my waypoints for the path to destruction:
73,-79
73,-51
97,-72
114,-72
117,-78
124,-106
90,-111

**Comment by olavra** [comment]
This is no longer reproductible @nearnshaw
