### ISSUE TITLE
There are some parcels at 13, -138 that look like they aren't loading

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1096]
@menduz reported that there are 2 scenes, the first one at `13,-138` and the other one very close to it, that aren't loading.

There aren't green blockers around the scene, so for the Explorer it DID load, but there isn't any mesh (not even the floor) for those scenes.

We should confirm if it's a loding issue or if the scene is completely empty or what.

![Screen Shot 2021-08-29 at 13.13.08.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/f6a3df00-93e8-4834-ae2f-88e2349cf5ea)

**Comment by olavra** [comment]
I've just found another intersection that is not being displayed
https://play.decentraland.org/&island=Igb8c&position=-21%2C15
![image](https://user-images.githubusercontent.com/41490935/132348602-3c65a7e1-7922-4550-89c9-28c81a2d5e2b.png)

**Comment by BrianAmadori** [comment]
This issue is happening because the asset is misaligned on the scene and the scene bounds checker is hiding it.

![image](https://user-images.githubusercontent.com/6875814/132608231-eb9c23ad-aa3f-49a2-8a1f-ee3272f6f516.png)

cc: @nearnshaw
