### ISSUE TITLE
First person camera turns to a random direction on pressing ESC

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1104]
While you are in first person camera, and press ESC key, the camera direction changes to a random one. This does not always happen, but once it does, it happens all the time during that session.

No steps to reproduce.

Before pressing ESC
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/2056c882-96c2-4bc2-ba04-7c0d6b316c2c)

After pressing ESC
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/a5eb64a8-4bb3-4cce-bbf6-82c7bc172782)

**Comment by olavra** [comment]
This is still happening. Reopening the ticket

**Comment by lorux0** [comment]
Analysis of the issue:
- pointer gets lock/unlocked in renderer by an event raised by kernel/current browser. This event has a delay before reaching into the renderer.
- while ESC was pressed until the pointerLock event arrives, unity input system `Input.GetAxis("Mouse X/Y")` throws random input values which are stored into `InputAction_Measurable` scriptableobject, handled by `InputController`. This is what causes the flick. One frame is enough for this to happen.
- i've tested it on Chrome and Firefox, both browsers gives different results. This is harder to happen in Chrome but in Firefox happens most of the times (on Windows SO)

Approaches i took but did not solve the problem:
- use a custom bool every the time the user press ESC that forces the input to stop/resume handling mouse events
- smooth the input values by calculating an average of the last 8 mouse inputs. Feels laggy, the flick is slightly better but you can still see it

One possible solution is to report the bug to unity and hope they can fix their input system in browsers

**Comment by olavra** [comment]
This cannot be resolved with the ESC key as its browser related, but its resolved when the player exit usign right click
