### ISSUE TITLE
Avatar impostors polish

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1119]
These are some things we identified that would improve the feature to be less visually-shocking, along with a bit of bugfixing.

- [x] Implement new strategy for impostors (see comment below)
- [x] Avoid triggering the blue "spawn particles" on avatars that spawn beyond the LODDistance (regardless o full avatar or impostor state)
- [x] Take down Brian's code review from this PR: https://github.com/decentraland/unity-renderer/pull/1041.
- [x] Implement impostors fading when they move with their decreased movement interpolation. Let's first implement it in a quick manner to test it visually, regardless of performance impact [Decided to pause this after testing]
- [x] Implement GPU [skinning throttling](https://github.com/decentraland/unity-renderer/pull/1140) 
- [x] Change body snapshot request to be on-demand when the avatar is effectively turned into an impostor
- [x] On some avatars that spawn directly as impostors, we can see a black texture that then turns into the downloaded snapshot tex, we should avoid displaying that black square texture @pravusjif 
- [x] "MAX HQ AVATARS" slider in the Settings panel changes to 20 every time any other setting is changed. Update min-max values to 20-100.
- [x] Decrease users profile body snapshot size
- [x] Tackle avatar modifier area coping by putting the impostor GameObject as a child of the AvatarRenderer

**Comment by AjimenezDCL** [comment]
The current strategy is not working:
We are setting the nearby players invisible if the Avatars cap has been reached
Faraway players are Avatars (if avatars cap has not been reached) or impostors

This was producing strange behaviours with lot of users where some nearby would be invisible but then appear as impostor when moving away.


The new strategy for nearby players is to set them as impostors if the cap has been reached.

**Comment by pravusjif** [comment]
Debugging the "black texture" bug on impostors I found out that:
* It can be reproduced in Wondermine with almost 100% repro rate by getting away from the farest impostors so that they are unloaded because of comms radius, and when they get reloaded after getting a bit close again, the black texture can be seen when setupping the impostor.
* I couldn't reproduce it with the generic snapshots that the bots use, so its bound to the snapshot fetched from the content server
* The bug only happens in build
* It only happens to some server-fetched snapshots, if I force all avatars to use my user snapshot for their impostor the bug doesn't happen.

I continue debugging.
