### ISSUE TITLE
Fix GPU skinning bug in Unity Editor in macOS (aka Flash Mob error)

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1144]
It's almost impossible to debug 3D avatars meshes/animations stuff with this GPU skinning bug in macOS Unity Editor.

https://images.zenhubusercontent.com/337227404/217ab49e-fca5-446a-9c19-7bd8b77b1fb4/screen_recording_2021_09_02_at_18_20_13.mov

https://images.zenhubusercontent.com/337227404/8b060503-8684-4453-bd97-b768000a69e2/screen_recording_2021_09_02_at_18_17_11_2.mov

**Comment by BrianAmadori** [comment]
It's also worthy to note this may affect desktop OSX builds, so this can be more of a debugging sanity issue.
