### ISSUE TITLE
"Texture" Wearable requested multiple times

### ISSUE THREAD

**Issue by pbosio** [decentraland/unity-renderer#1155]
Related to #837
In crowded areas when avatars go far away and then come close again we can notice that wearables that are textures (not gltf) are being requested again to the content server. Since user go outside comms area, the avatar was cleaned up and the ref count for that wearable texture decreased to 0

**Comment by BrianAmadori** [comment]
@menduz I understand that the content server requests load aren't an issue right? 

This was requested by @pentreathm.

Please confirm that this really should be done.

**Comment by eordano** [comment]
In order to validate this:

* Open two explorer windows
* Move far away with one avatar with many wearables, until the avatar is unloaded, and then, move back again
* Check that the network tab in chrome dev tools does not trigger a network request again

**Comment by m3taphysics** [comment]
This is a very old issue but I would like to verify it

**Comment by sandrade-dcl** [comment]
I have been testing what Esteban said: using 2 browsers with different users (one of them with wallet and another one as guest), when the other user go far away and go back to the view of the first one, in the network tab we are always receiving a serie of requests related to `/content/contents/...` belonged (I don't know why) to some base wearables that has not to be with the equipped wearables of the avatar in the scene.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/81c2df03-c91f-4712-9543-3f8d6951be7d)

I guess it should belong to [this list](https://docs.google.com/spreadsheets/d/1KZTORsE0ZJvDKIpMD_jbz7JBSvRfIMXMhxfZOZugZwU/edit#gid=220842179) of non-cached things.

Should someone from platform retake [this issue](https://github.com/decentraland/unity-renderer/issues/837) to fix that list of non-cached content?

**Comment by sandrade-dcl** [comment]
I think the problem is that we're not implementing any kind of cache in the `LazyTextureObserver` class (or even `AssetPromise_Texture`), so each time we load a texture from an url (like an impostor texture), we are requesting the url again.

(Maybe another solution would be create a cache system ONLY for impostors textures from the AvatarShape.)

**NOTE:** _Solution pending to discuss with the tech leads._
