### ISSUE TITLE
Profiles body.png requested multiple times

### ISSUE THREAD

**Issue by pbosio** [decentraland/unity-renderer#1156]
Related to #837
body.png is requested when an avatar spawn.
when avatar goes far away from comms area it's cleaned up and the ref count for body.png decrease to 0 and is removed from library.
when avatar come close again the texture is requested one more time from the content server

**Comment by BrianAmadori** [comment]
@menduz I understand that the content server requests load aren't an issue right? 

This was requested by @pentreathm.

Please confirm that this really should be done.

**Comment by pravusjif** [comment]
Anyway this is fixed at https://app.zenhub.com/workspaces/unity-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/1119
