### ISSUE TITLE
Green blockers get removed before smart items are fully loaded.

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#116]
Brian: 

This can happen in: 
ORG -55, 142
ORG 12, 77

As far as I debugged, the builder scenes with smart items have some `await` statements that makes the scene send incomplete initialization messages. Waiting a bit before sending the remaining messages with all the addEntity and addComponent necessary to complete the scene. 

If I force a `setTimeout(1000)` after the first eval statement in worker code, the remaining messages to load scenes are magically sent. In this interval, no messages come from systems or events, so it should be an await. 

Before the rest of messages come, suspicious chest connect logs can be seen.

All the non-smart item objects should be added to the scene in the first frame or the loading lifecycle will fail.

@cazala @moliva

**Comment by nearnshaw** [comment]
I'm not sure this is even happening anymore, I don't think I've seen it happen for a long time.

I'd say we can close it, or at least lower its priority

**Comment by olavra** [comment]
Closing it as it can not longer be reproduced
