### ISSUE TITLE
Prevent avatar from triggering "falling" animation

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1170]
If a player is in the border of a geometry, or runs after jumping, its represented as "flying" for the rest of the players.

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/826f4cb9-4d5c-45f2-bb5d-7de41497e40f)https://images.zenhubusercontent.com/337227404/6d07815f-2e7d-4eb7-9729-701a93d593cd/2021_09_09_22_35_35.mp4

**Comment by JorgeDecentraland** [comment]
Fixed in https://app.zenhub.com/workspaces/unity-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/1316
