### ISSUE TITLE
Wearable fails to show on new published collection

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#1171]
Link to test:
https://play.decentraland.zone/?WITH_COLLECTIONS=urn:decentraland:matic:collections-v2:0x0a2924a8aaeadb438322328b95a9d2dffe8b90ba&NETWORK=ropsten 

Try to wear the wearable. Notice it never shows on the avatar.

100% repro rate.

**Comment by AjimenezDCL** [comment]
@ShibuyaMartin the wearable is wrong, mesh is not skinned.
