### ISSUE TITLE
Add Report a Bug panel

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1178]
- [ ] Add report a bug button in More Actions
- [x] Create Github Issues form for Bugs in the issues repository
- [ ] Hook slack notification to `#unity-support` channel.

Form should contain the next information
- Kernel Version (Injected)
- Renderer Version (Injected)
- System specs: (CPU, Memory, GPU, SO) (Injected)

- Description
- Steps to reproduce

**Comment by olavra** [comment]
@RominaMarchetti we need a place and style for this button. It may be in the more actions, or the profile tag, either way it needs high priority

**Comment by RominaMarchetti** [comment]
<img width="189" alt="Screen Shot 2021-09-10 at 14 33 03" src="https://user-images.githubusercontent.com/51088292/132894402-e869e977-aba9-4788-9aeb-a0f611333ec4.png">

**Comment by olavra** [comment]
https://github.com/decentraland/issues/issues/new?assignees=&labels=new%2Cexplorer&template=bug_report.yml

parameters to include in the url to populate the form
kernel
unity

**Comment by Kinerius** [comment]
Related PR: https://github.com/decentraland/kernel/pull/49
