### ISSUE TITLE
Emission value is not working for some wearables

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1182]
This user reports some wearables belonging to the same collection are not being displayed with the right emission values:

**How it should look**
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/f97e1690-5568-4bad-93ab-ad4b85e32966)

**How it looks**
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/651327de-110e-471e-91c8-9d421e88dce9)

**Collection Forum Thread**
https://forum.decentraland.org/t/collection-sannins-ninja-no-kunren-co-created-by-cryptsannin-is-ready-for-review/1707

**Collection ID**

Another example
https://play.decentraland.zone/?WITH_COLLECTIONS=urn:decentraland:matic:collections-v2:0x8209db483dceb4f23e4922d93c587022e1d47e01&NETWORK=ropsten

This is how it looks
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/cbe4b52a-6a0d-4063-898e-1c95157887b4)

This is how it should look using a older version (tried a version before any avatar changes)
https://play.decentraland.zone/?NETWORK=ropsten&WITH_COLLECTIONS=urn%3Adecentraland%3Amatic%3Acollections-v2%3A0x8209db483dceb4f23e4922d93c587022e1d47e01&island=Ih&position=0%2C1&realm=artemis&renderer-version=1.0.10266
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/f69035b6-5f4d-4a85-87d7-30cdaa94db1b)

**Comment by olavra** [comment]
Content creator of the helmet mention the wearable stopped working after the "expanded audio settings update"
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/8c449f1c-fdc4-46e2-816a-6703a156e087)

**Comment by AjimenezDCL** [comment]
More info

NOT WORKING collections.
https://play.decentraland.zone/?WITH_COLLECTIONS=urn:decentraland:matic:collections-v2:0x95fc1f675ba201ae69003af96b6f8bdcfa3c941a
https://play.decentraland.zone/?WITH_COLLECTIONS=urn:decentraland:matic:collections-v2:0x3bb75349bfd21176b4e41f8b9afe96b4b86059db
