### ISSUE TITLE
Avatars are displayed as rotated giants for a sec

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1185]
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/df2f846b-2511-490a-b2c4-66bb8f01ac38)

Avatars are being instantiated in the 0 of the scene with giant proportions and 90º rotation until they are reseted.

Also being shown like that in the avatar editor

https://decentralandteam.slack.com/archives/CLPEQCBNF/p1631419446097500

https://decentralandteam.slack.com/archives/CLPEQCBNF/p1631420360097800

One player address suffering from this problem
0xA0D3Dc0929dc5Fe46b93e28AA4238051c3deb372
Hardware specs:
iMac Intel Core i5 2.7 GHz 4 cores, AMD Radeon HD 6770M, 16GB RAM
Browser: Brave

**Comment by AjimenezDCL** [comment]
Cannot reproduce with the given address. Could it be related to his hardware/gpu? It would be great to have more info and console logs.

**Comment by olavra** [comment]
Debugging with the  player, I tried with different renderer versions
First is working (before mesh merge)
https://play.decentraland.org/?&renderer-version=1.0.10266
Second is working (one commit before GPU skinning)
https://play.decentraland.org/?&renderer-version=1.0.12491-20210902125500.commit-57c2429
Third is NOT working (GPU Skinning)
https://play.decentraland.org/?&renderer-version=1.0.12572-20210902172421.commit-768e24b

**Comment by olavra** [comment]
Cant reproduce
