### ISSUE TITLE
Some asset missing their texture when loaded as Asset Bundles

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1186]
Decentralgames report an asset that works without asset bundles, but with asset bundles in has no texture.

This is how it looks with asset bundles

![image (4).png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/38d5615a-6651-48f1-92b3-85ac2cccc772)
![image (6).png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/58ebd49d-ddc4-4f59-bafb-5b7129a6469f)

This is how it should look

![image (7).png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/c63bc0bc-b861-4e05-be15-01f52c9f3507)

Thread
https://decentralandteam.slack.com/archives/CS8SCNYUV/p1630661281023400

**Comment by olavra** [comment]
[https://app.zenhub.com/files/337227404/aa1ec5e4-6254-48bc-a654-7379783b2638/download](https://app.zenhub.com/files/337227404/aa1ec5e4-6254-48bc-a654-7379783b2638/download)

**Comment by pravusjif** [comment]
* Invalidated cached ABs by updating the ABs fetch URL version at https://dcl.tools/ops/global-config/-/blob/release/public/explorer.json
---
* Scene Data:
    - mappings: https://peer.decentraland.org/content/entities/scene/?pointer=-118,135 or https://peer.decentraland.org/content/entities/scene/?id=QmdFhxwGDgBwKa6YqcpsTHsgeQoaKEouSBqPjYWceN5oYw
    - scene id: QmdFhxwGDgBwKa6YqcpsTHsgeQoaKEouSBqPjYWceN5oYw
    - Reported problematic assets (in the video we can see there are many more like the trees and bridge):
        - models/poker/pokertable/pokerTable_7side_Emit.gltf -> QmNn5GjvMxQwMwfZUqkqiC7SBQuCwxwty6AjZycK7QfJew -> Converts OK
        - models/poker/pokertable/PokerTableUpper.gltf -> QmPcKvWsxUEDj5c8oTjJEYdEsb66obaWnuC8gneDpAgGkC -> Converts OK
        - models/blackjack/cards/hearts_card_unknown_double.gltf -> Qmc3ND9xsjQBmppnNvUpH1VRo78STgxhSencQFFxNYGdUu -> Converts OK
        - models/blackjack/blackjack_table_wood.gltf -> QmPxyqftWSCqCT1BfqYvNkA5fqpV6BiYQXsEnJ1Dcibre3 -> Converts OK
        - models/blackjack/blackjack_table_wood_TopPartOnly.gltf -> Qmd3nui47kcyKEzyA1BZ4qwmuo1gyBZyzsgosbmc8SLrte -> Converts OK but there is 1 texture that is invisible in the AB, passess the visual test regardless.
        - models/roulette/TominoyaVersion/roulleteTable_tominoya.gltf -> QmT3TsKHj6Pj3VH3gWdKqfndN6SMnXTpLMVhJnGXKL4P52 -> Converts OK
---
* Dumped whole scene:
    - Failed conversions
        - QmNhsgFGt6qzb9ubNy8jkJg1SReAoPArCAxcwqQ88hcQPh -> models/roulette/ui/digit_glow.glb
        - QmXURneQUeweYhKBuYrYuphUJuE3HG89CXeiuzkxfQXAJv -> models/poker/pokerRoom/PokerRoom.gltf
        - Qmaz2JoyzHwJzABqNZChc2ZNadMRLdxokPemqq4JGFWEp7 -> models/backgammon/board/Checker_Glowing/Checker_Glowing_White.gltf
        - Qmex9V77FcXtx84WjqFk7FpXDGubM6zzvMAnNfBSsxftgs -> models/backgammon/board/Checker_Glowing/Checker_Glowing_Black.gltf
---
* Debugged from Unity Editor:
    - In-building assets like tables, etc. look fine
    - Outer objects like the bridge and trees are full white, the material doesn't have any albedo texture configured.
    - Comparing the same material in AB format and original format, the AB loads a version of the material that has some CRC id and doesn't have the albedo texture.

![casino-editor-no-asset-bundles.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/aa05ca08-cea1-4193-97c6-b7959b13abde)

![casino-editor-ABs.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/408ee72b-7e4c-4820-9566-2d75c493208a)

---
Evidence on all of this can be found in the following zipped file (conversion comparison images, scene conversion editor log, and more):
https://drive.google.com/file/d/15Z-iprKuNe0ODfYzy-C7BESoNiCiwdRn/view?usp=sharing
    
I continue investigating the Materials problem...

**Comment by pravusjif** [comment]
* If I disable material caching in AssetPromiseSettings_Rendering, the problem persists
* Trying to convert the bridge isolated asset locally (models/structures/JapanSectionSmall.gltf -> QmUEMA9wPZfHWDHfY7Z9PsetyBedFZL8ghVNtvbcFA3zxo) the converted assets loads perfectly. No CRC Material involved.
    * The texture it uses (missing when loaded in runtime) is QmZVRDBmrP4Yi19MvtRtiJYpd8eEPuUR4oHwa5Ac6zrsn9 -> models/structures/Wood_RusticWoodPost_512_diffuseCherry.png
    * Converting only that texture asset locally converts just fine.
    * Are we loading that texture in runtime at any point in time?
        - AssetPromise_Texture never receives an url with that texture's hash, checked by logging
        - AssetPromise_AB.LoadAssetBundleWithDeps() doesn't use any dependency with that texture's hash, checked by logging
        
Next I'll check:
        - If we can access the mappings of the scene in Unity, check if the texture is in there

**Comment by pravusjif** [comment]
* Other checks 
    - AssetPromise_Texture never receives an url with that texture's hash
    - AssetPromise_AB.LoadAssetBundleWithDeps() doesn't use any dependency with that texture's hash
    - AssetPromise_AB.LoadAssetBundleWithDeps() never receives an url with that texture's hash
    - Our AWS S3 bucket DOES have the texture AB and its .depmap

---

- Depmap assets when converting the mesh locally:
    - QmcaHaPNxPfqEZi4nwXtTyf9q7hzSRGPTAsbEf8yjmvP4L -> models/structures/JapanBambooWood_light_basecolor.jpg
    - QmcBkiSXuwiDhTnu2g7ueLWMdfH67niuyHAtRCG9nbzQEM -> models/structures/JapanTatamiMatOffsetRectangle_normal.jpg
    - Qmcj34DvdebCmh5RfxrfJwEqeKcVgjopJNEyWxovs5zUau -> models/structures/Anthurium_baseColor.png
    - QmejZq9kXdbzgQexQMqiriFBELzuZanQqYGDvh2aDMJkV4 -> models/structures/GrassGreenHealthy_basecolor.jpg
    - QmeuYosSuJoPhJ2Lh9cZa16reiSwAEoHdBf7cnRhEhsCtD -> models/structures/RBR_pointyrock_LOD0_baseColor.png
    - QmfQ2zEwZ2M1TFmS3gqro9Xad9vFpo3eNWZhEpJ29F6YQr -> models/structures/ShojiScreenWall_GOLD_basecolor.png
    - QmfUHYwASUD7boLBpiWm1oF8xJZ5ZghKon1DD3HK5QNwTy -> models/structures/JapanTatamiMatOffsetRectangle_basecolor.jpg
    - QmNtrz3gJQnfsYM3KDBZytmqqeRXZunc54yehsWNX88pkj -> models/structures/underconstruction.png
    - QmQDdGq4n6oA88ckQBF8YPyLc4KX8Y58iriXDnyq4jb4VK -> models/structures/IvyGrass_baseColor.png
    - QmQdYZqSR4VLTDXkZx6QnA4BxeFtM57ZQn2nBLayqEG8oz -> models/structures/CopperFlatRoundRoofOld_normal.png
    - QmUpyN5ThTAhDQ6GftGafk3oc98Gugh2phNSr8HU4Pn5dd -> models/structures/IvyLower_baseColor.png
    - QmYbqYwKaxgbZrRLj25ThDXikXscnTmg2wpCmxjLEVbStp -> models/structures/Ground_KalahariSandSheet_2k_diffuse.png
    - **QmZ9jr9LfT51Lqy7dYedDLfJbpa9LdkN5JFTsXuZjEFJW8 -> models/structures/08_NORMAL.jpg -> [hash exists in runtime depmap!]**
    - QmZaVRZzWtJf37JXZTwZVvmQMmJxKbz6krjwdZJHWaqmAx -> models/structures/Artboardsxs.png
    - **QmZVRDBmrP4Yi19MvtRtiJYpd8eEPuUR4oHwa5Ac6zrsn9 -> models/structures/Wood_RusticWoodPost_512_diffuseCherry.png [target texture]**

---

- Depmap assets when loading the mesh in runtime, we get completely different dependency hashes that apparently point to the same files:
    - QmcgwhJvVmSDwcX6ggDQxxJ6ZivBG4faGMixMjdoiyqzcC -> models/structures/Artboardsxs.png -> [not found in scene mappings]
    - QmdFrJHWWruJArWfT1LCnTksVvCeK5GSWAKDz85tPxweJt -> models/structures/GrassGreenHealthy_basecolor.jpg -> [not found in scene mappings]
    - QmNSeM7KMjtXg97fNhsGVsEjN7XuKdqdi4DcEnbFPuj8kZ -> models/structures/IvyGrass_baseColor.png -> [not found in scene mappings]
    - QmQmrHCAt8e87QFPuR9R8oCAs1csDAcXC1Wd48M5GL9Y2f -> models/structures/CopperFlatRoundRoofOld_normal.png -> [not found in scene mappings]
    - QmR3atdVhf2F5jjy8hdpt7gQXTuGDGm3CZtw9hJW5mrun3 -> models/structures/JapanTatamiMatOffsetRectangle_normal.jpg -> [not found in scene mappings]
    - QmS85k27bhA2ccfdeMRMXbKwVQe44mYns4RDgAuTGfMWLw -> models/structures/ShojiScreenWall_GOLD_basecolor.png -> [not found in scene mappings]
    - QmTCKD78m25U96NV9QvCfY6DoqU123Kh5yqbfxSZJGtBbY -> models/structures/Ground_KalahariSandSheet_2k_diffuse.png -> [not found in scene mappings]
    - QmTQnAzQM2UR42tVTgCyYPnPrNMZJNJcjZdQHxZA2qJLJB -> models/structures/JapanTatamiMatOffsetRectangle_basecolor.jpg -> [not found in scene mappings]
    - QmTTyxiLzbxN2be4x971x4cRGieWAUGmNoiBzdssAjuxJA -> models/poker/pokerSaloon/Anthurium_baseColor.png
    - QmUKLJ9YizVZYdEQkNd4kBVozzoyxVdXDMJcriPNyWULsf -> models/structures/RBR_pointyrock_LOD0_baseColor.png -> [not found in scene mappings]
    - QmXJHxKRV72u2WNuS3nF5azrrkwK1A6waEKtGfp9Ue7STV -> models/structures/IvyLower_baseColor.png -> [not found in scene mappings]
    - **QmYXyQHpkw7PVFLfxcEzapskZVW5Etuk4uNSPLrzLCs9eN -> models/structures/Wood_RusticWoodPost_512_diffuseCherry.png -> [not found in scene mappings][target texture]**
    - **QmZ9jr9LfT51Lqy7dYedDLfJbpa9LdkN5JFTsXuZjEFJW8 -> models/structures/08_NORMAL.jpg -> [hash exists in local depmap!]**
    - QmZHcVNVuvMEHBx5fttypQvwg2hJYGxxn2inEPpYCxhUcr -> models/structures/underconstruction.png -> [not found in scene mappings]
    - QmZwPXdMBqX9e3iKcW9u56i4WtVWnqfX15REGuA3deGPWz -> models/structures/JapanBambooWood_light_basecolor.jpg -> [not found in scene mappings]

---

**All of those dependency ABs are effectively in the AWS S3, so one problem we can already see with this data is that we have many assets duplicated, maybe more than once**

Next I'll see:
* Download the mesh's depmap from the S3 and see to which of these 2 depmaps it corresponds (should correspond to the one we load in runtime)
* Try filtering the asset promise loading with the alternative hash for the same missing texture

**Comment by pravusjif** [comment]
* The S3 depmap of course corresponds to the runtime-loaded depmap of the asset
* The missing texture is being loaded with its new hash (that appears in the mesh dependencies) in runtime, so it should work anyways...
* Tested assigning the loaded texture AB to a debug gameobject in scene to be able to inspect it and the texture is being loaded without problems, so the issue is the assignation of that texture to the correct materials.
* Tried to check if GUID of Texture loaded in runtime corresponds to the GUID expected by the mesh/material, but I find it impossible to get the GUID of the downloaded texture AB in runtime.
* Re-enabled old ABs mechanism to load in order, prioritizing Textures before all, and the problem persists.
* Re-uploaded the locally converted ABs for the target mesh and texture (and other dependencies) to the S3 bucket but the files were not uploaded because they haven't changed compared to the ones in the bucket.
* If I log the name of all asset bundles loaded (using `AssetDatabase.GetAllAssetBundleNames()`) the runtime-depmap hash of the texture is not present, but the ORIGINAL hash of the texture actually is...

**Comment by pravusjif** [comment]
* Tried a bit of commit-hunting
    - We can only go as far as [26th of july](https://play.decentraland.zone/?ENABLE_ASSET_BUNDLES&NETWORK=mainnet&osition=-118%2C136&renderer-version=1.0.7698) (commit c3050fdf7a4a6c44fccda307f0ced3dee838644d), not further due to kernel and website refactors that crash with older renderer versions.
    - We still have the white ABs in that build
---
* I tried using all possible methods in `AssetDatabase` and `assetBundleInfo.assetBundle` to get the runtime-loaded texture AB GUID but I found it impossible.
---
* Tried again downloading the targetted mesh dependency map from the S3 bucket and this time I'm seeing it as the same as the one that gets created when converting the mesh to AB locally, so I probably messed up when I checked this a couple of days ago.
    - This motivated me to try a hack that proved successful: If I intercept the dependencies of the mesh, during the traversing in which we download those dependencies, and override the missing texture wrong hash (remember in runtime we get the depmap with different hashes that look like should be pointing to the same files) with its original hash (the one I see in the locally-generated and S3 depmap) the problem is solved and the material loads without issues!!!
    - This means **the core problem here is the alternative/wrong hashes that the depmap has in runtime instead of the one we get from the S3 or generate locally**.
    - This can be easily tested downloading the following depmaps and comparing them:
        - Mesh AB depmap in the S3 bucket: https://dev-assetbundles-8af4af4.s3.amazonaws.com/QmUEMA9wPZfHWDHfY7Z9PsetyBedFZL8ghVNtvbcFA3zxo.depmap
        - Mesh AB depmap fetched in runtime: https://content-assets-as-bundle.decentraland.org/v3/QmUEMA9wPZfHWDHfY7Z9PsetyBedFZL8ghVNtvbcFA3zxo.depmap

Will continue investigating this file-serving issue

**Comment by pravusjif** [comment]
OK, I've found a solution to the problem, it inolves 2 steps:

1. Update the asset bundle domain url version to force the cache invalidation in the clients (already done in production twice), but **this alone is not enough**.
2. Remove or change our persistent [devmap caching in playerprefs](https://github.com/decentraland/unity-renderer/blob/8cd0366152910b4f04f5649bebdfaadd817d4536/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/DependencyMapLoadHelper.cs#L90), as this caches old devmaps and never gets updated (step 1 doesn't reset this cache). The ["time reset" logic](https://github.com/decentraland/unity-renderer/blob/8cd0366152910b4f04f5649bebdfaadd817d4536/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/DependencyMapLoadHelper.cs#L78) in the persistent devmap cache is broken as it only works for same-session devmap caching, but if the client loads a devmap cached in another session, it never gets ovewritten (even though we save in the persisten cache on every rendererState change, not really sure what's the point of that, if the devmap never gets re-downloaded it will never get updated...).
