### ISSUE TITLE
A texture image is replaced by a red questionmark on white background for certain filenames or path wording.

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#120]
Some images used as textures show up as red question marks on white, rather than the correct image.
It appears to depend on the wording of the folder name/path containing the image, or on the file name.

I can reproduce it if the path contains a segment of "advertise" or if the filename starts with "YourAdHere".
This does not require my ad blocker to be on for the site, or even enabled, and happens both in preview and in-world.

https://gitlab.com/dcl-tech/texture-issue exemplifies the issue, and the game.ts has commented out lines that show what does and doesn't exhibit this for various filenames of the same file.
I have also seen it where the filename would work, but a segment in the path is "advertise"

Seems to be not too hard to work around once you understand how

**Comment by sandrade-dcl** [comment]
@cfravel effectively, we have confirmed that this is a problem provoked by the AdBlock browser plugin:

### AD BLOCK ACTIVATED
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/6d10ce89-d968-47ce-b84f-755be6a48aec)

### AD BLOCK DEACTIVATED
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/4acbc373-9ee4-4411-8e48-b0f2080116c4)

As this behaviour depends completely on third parties software and our recommendation is always to deactivate any plugin of this type during the execution of Decentraland, we are going to close the issue.

Thanks for the feedback!
