### ISSUE TITLE
Backpack gets too slow when many wearables are present

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#121]
Easy to test using TEST_WEARABLES / ALL_WEARABLES flags.

**Comment by BrianAmadori** [comment]
A suggestion is to implement a custom-made culling similar that one we already have for the mini-map and chat window. (to hide the thumbnails that are outside the scroll view)

**Comment by olavra** [comment]
This is no longer testable using the flags TEST_WEARABLES / ALL_WEARABLES.
