### ISSUE TITLE
[UI Components] Documentation

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#1217]
Write documentation in Notion about the new UI Components library:
- Architecture overview.
- List of available UI components.
   - Description.
   - How to configure and use.
   - Exposed methods and properties.
- How to create a new UI component.

**Comment by olavra** [comment]
https://www.notion.so/decentraland/UI-Components-Reference-f467a8d05d594718a2c12809dcfaf132
