### ISSUE TITLE
Gif Asset Promise memory leak

### ISSUE THREAD

**Issue by D4rWiNSS** [decentraland/unity-renderer#1220]
The gifs can be loaded from unity or from kernel, if the gifs is being loaded from kernel and the asset promise is canceled in unity, kernel is not notified and the asset will stay there forever

**Comment by pravusjif** [comment]
* Can't reproduce the memory crash with GIFs in master anymore
* @pbosio is right and the original code without this PR already cleans the GIFs from memory and handles cancellations
* With local builds I logged the whole flow in AssetPromise_Gif.Cleanup(), AssetLibrary_RefCounted.Release(), Asset_Gif.Cleanup() and Kernel's GIFProcessor.DeleteGIF() and all the GIFs are being cleaned up correctly.
