### ISSUE TITLE
User profile texture failing

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#1245]
This user profile is failing every time that I try, I have tried with 2 different accounts and in different sessions

Wallet address: 0x665d2b8b5079eb3dd15eb5a65dc34f7067a13026

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/bcab9421-42dc-4f59-9c4c-27a83ac999f2)

**Comment by kuruk-mm** [comment]
Maybe it is duplicated from a task from platform @pentreathm

**Comment by xavi-dcl** [comment]
@kwspgoliasz is this bug still open and can it be reproduced? Please close if not.
