### ISSUE TITLE
GLTF models seem to be rendered as pink on some cases

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#1284]
Reported by the decentral games team. Firefox provided us with a sample .zip to be able to isolate the issue.

![image](https://user-images.githubusercontent.com/6875814/135556465-e9428f10-4c27-4858-8d30-a5defdf69644.png)

https://decentralgames.slack.com/files/U011HFV3JS1/F02FV05JKE3/pinkpepe_test.zip

**Comment by olavra** [comment]
Can't reproduce anymore
