### ISSUE TITLE
Change installer, launcher and client icons

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1303]
Launcher and client icons should use the default DCL icon
The installer should use the DCL icon with the purple arrow

**Comment by olavra** [comment]
@RominaMarchetti we need 2 icons, one for the launcher and another one for decentraland while its running. The second one could be the one we already have, but the launcher may have something like an arrow pointing down? or a rocket? whatever, but it needs to be different :)

**Comment by olavra** [comment]
![decentraland-mana-logo.svg](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/a61976d9-ef78-42f0-b2ea-feb135859e7d)

**Comment by RominaMarchetti** [comment]
Let's use this one for the launcher. Let me know if the fortmat/sixe is okay @kuruk-mm 
<img width="144" alt="DecentralandInstallerIcon" src="https://user-images.githubusercontent.com/51088292/140945317-67b5c000-db34-4870-bf74-500a0cc633c0.png">

**Comment by kuruk-mm** [comment]
> Let's use this one for the launcher. Let me know if the fortmat/sixe is okay @kuruk-mm <img alt="DecentralandInstallerIcon" width="144" src="https://user-images.githubusercontent.com/51088292/140945317-67b5c000-db34-4870-bf74-500a0cc633c0.png">

Can you send me with 512x512 resolution? (it must be a square)

And if you have it as .SVG the better

**Comment by RominaMarchetti** [comment]
[DecentralandInstallerIcon.svg.zip](https://github.com/decentraland/unity-renderer/files/7505847/DecentralandInstallerIcon.svg.zip)
Here it goes!

**Comment by olavra** [comment]
@RominaMarchetti we need 3 icons:
- Installer
- Launcher -> This should be the Decentraland logo, as its the application that you will pin to your taskbar.
- Client: This is the application that the launcher will execute. This may be the same icon, for now both applications run at the same time, in the future, the Launcher will be minimized in the systray so we may not need change it.
