### ISSUE TITLE
AvatarRenderer should be better covered by tests

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#131]
- [ ] Reactivate Explicit test for AvatarRenderer

Right now, we lack a proper AvatarRenderer testing suite. We should re-organize the class and mock anything necessary to get to a deeper coverage. The aim of this task is to make the avatar loading logic more resilient and prevent invisible wearables bugs and such in the future.

**Comment by olavra** [comment]
Closing this issue as we will change the AvatarRenderer class
