### ISSUE TITLE
In Unity Editor / Desktop we get super frequent hiccups due to the MemoryManager

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1322]
We should modify the time frequency and/or max memory values that make the MemoryManager flush resources and triggers the performance hiccup: https://github.com/decentraland/unity-renderer/blob/5293d43e0991c32227a621e01dc644b666e89a4e/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MemoryManager/MemoryManager.cs#L52

**Comment by kuruk-mm** [comment]
Fix here: decentraland/explorer-desktop#30
