### ISSUE TITLE
Fix `featureFlags.flags.Get()` null in preview mode

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1327]
We had to apply [this null check](https://github.com/decentraland/unity-renderer/blob/355f4eac89331b1ee169e584bc099a21ac0437fc/unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs#L51) because `DataStore.i.featureFlags.flags.Get()` returns null when running in "preview mode".

`DataStore.i.featureFlags.flags.Get()` shouldn't be able to return `null`.

**Comment by olavra** [comment]
Already solved
