### ISSUE TITLE
Sometimes random assets are rendered as white, reloading fixes it

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1335]
I encountered this issue several times in random situations, reloading appears to fix it so it's not realted to "bad asset bundle conversion" (our visual tests there would detect this).

* A couple of days ago I saw someone with the Santa Claus outfit completely white
![Screen Shot 2021-10-13 at 16.21.03.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/5a27ce7b-f69c-413e-ba44-2f9cf07a5e67)
![Screen Shot 2021-10-13 at 16.20.59.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/837f58a2-fcf1-4559-abc3-cfd4c663af8d)

After reloading the mesh was rendered just fine
![Screen Shot 2021-10-13 at 16.22.23.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/933317c1-94ad-419d-8bf7-dfa90bd39844)

* In another occasion I saw a girl with white hair
![Screen Shot 2021-10-06 at 11.54.54.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/a1bf1fc0-223d-4cf4-a564-cb59adf428b9)

**Comment by pravusjif** [comment]
I'm setting this as high priority as Decentral Games keeps having this issue and it completely ruins the casino experience.

**Comment by pravusjif** [comment]
Apparently the affected assets lose their albedo texture in runtime, or it gets misplaced.

![Screen Shot 2021-11-11 at 16.09.37.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/2dfa3149-5c7f-408f-87c1-31c6b2f97aed)

**Comment by pravusjif** [comment]
After further inspection, the white cards case in DG casinos is not this same issue, that was just badly converted assets that got wrongfully uploaded and cached in cloudflare

**Comment by davidejensen** [comment]
Estimate may vary a lot, this issue needs validation and we need to find a way to reproduce this issue consistently, currently putting an high estimate

**Comment by davidejensen** [comment]
Closing, not happening anymore
