### ISSUE TITLE
These NFTs with animated thumbnails have stopped working in DCL, but still work in OpenSea

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#1350]
Some of my NFTs that have animated gif thumbnails have stopped working in DCL, and in the UI popups.
They were working fine until recently.
They still work in OpenSea, and you can see that by clicking through the UI to OpenSea.
I hope you can fix this, as i hear others are seeing the same, and of course NFTs cannot be changed retroactively.

You can see examples of broken NFT displays at:

9,98
(Go into the gallery, then up the stairs on the left)

21,78
(In the Carl Fravel booth in the Museum)

-37,26
Alan Howick's gallery, upstairs  on the second floor

An example of an NFT of mine that stopped being displayed as an animated GIF:
https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/45212788081105388007521116546269099584358446490568136574020829704406356197386

**Comment by kuruk-mm** [comment]
This problem was fixed here: #1411
