### ISSUE TITLE
Developer mode for `explorer-desktop-launcher`

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1374]
If we enter the `launcher` in `developer mode`, we should have the option to choose a branch of explorer-desktop, a kernel branch and to use a custom URL.

**Comment by olavra** [comment]
![image (1).png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/2134c719-da8e-47df-bd34-64127ad1f222)
