### ISSUE TITLE
BoxShape component has no uv values

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#139]
The BoxShape component can't have its uvs set, to determine how a texture gets wrapped around it.

It would be great to be able to set it just like we do for the PlaneShape, where you can use that to stretch, rotate or tile a texture how you like.

Would be great to also be able to map the inside of the cube, to use as a skymap

Would be great to also have them in other shapes like SphereShape

Related comment from someone in discord:
Please could we gain the option to reverse the texture normals on a primitive SphereShape as the usual -1 scaling tricks do not workaround.
Spheres mapped inside out and viewed from the inside outwards would allow scenes to lever skybox like qualities along with certain essential perks like external/dynamic video mapping. Something which afaik gltf's alone cannot currently match.
The platform already has everything else in place in this regard... only requires reverse mapping to complete.

**Comment by kuruk-mm** [comment]
https://github.com/decentraland/explorer/pull/2268
