### ISSUE TITLE
engine.rootEntity doesn't do anything

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#1416]
A major painpoint that content creators experience daily is having to rotate a scene, so that it faces another direction. It happens a LOT.

For a large scene with many things in it, it is a task that can often take a whole hour. The typical solution is to define a single parent entity and rotate just that, but it may result in circular dependencies and the code breaking in unexpected ways.

There already exists a `rootEntity` that in theory is the parent of every entity in the scene. The ideal solution would be to simply rotate that one. But today adding a Transform component has no effect on the scene.

Try taking any scene and adding this, you'll notice nothing changes.

```ts
engine.rootEntity.addComponentOrReplace(
  new Transform({
    rotation: Quaternion.Euler(0, 90, 0),
    position: new Vector3(0, 10, 0),
  })
)
```

**Comment by JorgeDecentraland** [comment]
@nearnshaw should this ticket be transferred to the sdk board?

**Comment by xavi-dcl** [comment]
On SDK7 roadmap, we can close this
