### ISSUE TITLE
Scene unable to start in preview 

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#1424]
Lastraum has reported that his scene has suddenly stop working with this crash

![Screen Shot 2021-10-29 at 12.57.27 AM.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/dfefc010-2f7e-45e1-8ede-d7c40f1cfa56)

The scene is in this link https://files.slack.com/files-pri/T9EJMTT7Z-F02KW2LCVRP/download/archive.zip

It seems to be related to a glb

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/3191fe50-188e-4334-ac43-9be08dd78faa)

**Comment by olavra** [comment]
@leanmendoza @pbosio do you know if this is still happening?

**Comment by leanmendoza** [comment]
Yes, it is. It's happening even with param &renderer-branch=master

**Comment by olavra** [comment]
@leanmendoza is this still happening?

**Comment by leanmendoza** [comment]
> @leanmendoza is this still happening?
Mmm I think it isn't, it's been a long time since I haven't seen this type of errors (at least one/two month).

**Comment by xavi-dcl** [comment]
Closing after consulting with Nico E, we would ideally re-test with that model but it's far from top of priorities anyway and it may be fixed.
