### ISSUE TITLE
Hiccup: LayoutRefreshWatcher "wall of death" issue

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#1437]

**Comment by AjimenezDCL** [comment]
Hiccups profiling: https://www.notion.so/decentraland/Hiccup-Profiling-14-10-2021-e8d8ff74e20d42c6a206f3824ba6dfa4

**Comment by AjimenezDCL** [comment]
The hiccup has not been solved, but now heavy usage of UI wont affect other scenes
