### ISSUE TITLE
Sell item wrong URL

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#145]
When clicking sell CTA on any collectible item, it took the players to their assets URL on the marketplace when it should be taking them directly to the wearable URL instead.![Screen Shot 2020-08-31 at 10.16.01.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/a15d9c28-ea44-42c0-9de2-ff7d87b40dd1)

**Comment by olavra** [comment]
Confirmed, Sell button takes you to https://market.decentraland.org/account. It needs to go to
https://market.decentraland.org/contracts/[COLLECTION-SMART-CONTRACT]/tokens/[WEARABLE-TOKEN-ID]
