### ISSUE TITLE
Shortcuts in the controls panel are not in order

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#1452]
If you open the shortcuts panel, you will see that builder in world has a 'J' assigned but that J is for quest, we need to move it

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/9c27ffe5-66c0-44f9-88be-38e96733b583)

**Comment by olavra** [comment]
This is no longer valid since those elements has been removed from the taskbar
