### ISSUE TITLE
Desktop: Sometimes, the launcher stays trying to log in forever

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1458]
We should add more metrics to explorer-desktop to trace the problem

**Comment by olavra** [comment]
Waiting for dApps team to implement a workflow of notifications while the UI is requesting the signing of a transaction during the wallet connect sessions

**Comment by kuruk-mm** [comment]
Closed by https://github.com/decentraland/explorer-website/pull/141
