### ISSUE TITLE
Desktop: Avatar facial features missing in backpack

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1466]
Reported by Waan Chin
OS: macOS

![image.png](https://images.zenhubusercontent.com/60647b38cc4b79842895cb82/fbc8ffff-1ad6-4648-af22-0c041e89d88f)

**Comment by Kinerius** [comment]
Cant seem to reproduce this right now

**Comment by olavra** [comment]
Cant be reproduced anymore
