### ISSUE TITLE
Terminate static parcel workers

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#147]
We should identify the static parcels in kernel to terminate their workers after the code eval.

We can base the implementation on https://github.com/decentraland/explorer/pull/1292

some profiling regarding this has been documented at https://docs.google.com/document/d/1alngddAcBxyOHQQ3ieuEGv2H7Y1GXR1LLxje05406sY

**Comment by olavra** [comment]
This needs to be revalidated

**Comment by pravusjif** [comment]
I'm closing this issue since this is not something that will be explored in the short-term, althouhg I do believe that we should re-evaluate what to do with the **webworkers of static scenes** and **how to detect static scenes**.

The new ECS overhaul with declarative language will probably already solve this possible problem or at least make it much easier to detect static scenes.
