### ISSUE TITLE
Notifications badge in Friends icon is wrong

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1481]
When you enter Decentraland, sometimes the number of notifications is why off the number of real messages or requests.
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/b6a030a2-f2e0-44e8-8660-99a30b0cc7e2)

After clicking on the icon, the number resests to the right one
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/be829d40-ee22-4ed5-af6d-7cf494c12615)

**Comment by pravusjif** [comment]
This wil be tackled when friends service is more stable
