### ISSUE TITLE
Setting to disable chat message sound

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#150]
In order to prevent a sound spam by the chat message sound, its requested to have a setting in the Settings panel.
Probably a good idea to create a sound section inside the settings to include all related ones.

Feature requested by Esteban to be done asap

**Comment by eordano** [comment]
The use case in general is: when listening to a live DJ, I don't want other users "spoiling" the audio. I can disable voice chat, but the chat messages are impossible to cancel at once!

**Comment by olavra** [comment]
We are considering have a setting to disable all UI sounds instead of only sounds from the Chat. Pending conversation with the product team.

**Comment by olavra** [comment]
This is being tackled by @Landeplage on #865
