### ISSUE TITLE
Cards lacking of texture in DG casinos

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1506]
![Screen Shot 2021-11-11 at 13.07.51.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/35d4939f-ce2d-4cd9-aed6-3b6e12b13b35)

![Screen Shot 2021-11-11 at 16.09.37.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/f0001bd7-9697-4dc0-a7ed-7c01d98a738b)

**Comment by pravusjif** [comment]
This was a case of wrongly converted assets that somehow ended up in the S3.

* Saw that the white cards were always the same models, took note of their hash
* Downloaded those assets from the S3, served them locally and saw them white as well
* Converted the scene locally, served those new ABs locally and everything looks good
* Uploaded new ABs to the S3
* Invalidated cloudflare cache buy updating the ABs fetching url version

**Comment by pravusjif** [comment]
Awaiting confirmation on DG's end before closing this issue.

**Comment by pravusjif** [comment]
I'm closing the issue as the problem hasn't been re-reported.
