### ISSUE TITLE
Order adding to engine changes parenting

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#1535]
It seems that the order with which we add entities to the engine can affect parenting in unexpected ways

At some point this changed. A simple example we have on the docs that used to work no longer works as expected, because the child is added to the engine before the parent is.

```ts
// Create entities
const parentEntity = new Entity()
const childEntity = new Entity()

const myTextParent = new TextShape("Parent!");
parentEntity.addComponent(myTextParent);

const myTextChild = new TextShape("child!");
childEntity.addComponent(myTextChild);

// Set one as the parent of the other
childEntity.setParent(parentEntity)

// Create a transform for the parent
let parentTransform = new Transform({
    position: new Vector3(3, 1, 1),
    scale: new Vector3(0.5, 0.5, 0.5),
})

parentEntity.addComponent(parentTransform)

// Create a transform for the child
let childTransform = new Transform({
    position: new Vector3(0, 1, 0),
})

childEntity.addComponent(childTransform)

// Add entities to the engine
engine.addEntity(childEntity)
engine.addEntity(parentEntity)
```

The expected result is to have the child on top of the parent, but this happens:

![Screen Shot 2021-11-17 at 09.13.27.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/33bbe4c1-e51d-4b10-bc10-88cd863aaac2)

If I just change the order of the last two lines, or if I remove the line that adds the child to the engine (that is optional bc it gets added to the engine via the parent), it behaves as expected.

![Screen Shot 2021-11-17 at 09.13.09.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/1eeb88bc-22f9-46a1-aa05-eef696c5b081)

In the past, the order in which I did those steps was irrelevant

**Comment by JorgeDecentraland** [comment]
@pbosio should you transfer this issue to your board?
