### ISSUE TITLE
Materials on some wearables have broken

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#1545]
I have this very rare outfit whose materials have broken.
Wearable NFTs are immutable, so I hope that the Decentraland team will restore the materials to where this works correctly.
(I cannot fix this myself with any workaround)

This is how the outfit used to look, and still looks in the SDK Preview:
![How wearable should look](https://user-images.githubusercontent.com/21015643/142469781-0095a3ff-8507-47d0-b9b9-39d85543c8f8.png)

This is how it looks in-world now:
![Broken Wearables Materialspng](https://user-images.githubusercontent.com/21015643/142470679-41797205-65e9-4dc3-809b-487ffe4a8e91.png)

**Comment by pmacom** [comment]
Hi Carl! I'll reach out to you individually as well. Posting here so anyone else who comes across it might also find the solution, and for tracking it.

I had a similar thing happen with my building. The bug is addressed here https://discord.com/channels/417796904760639509/437689723020902410/910663366064869377

```Pravus — Yesterday at 5:51 PM
Hey @patmacs after some tortuous debugging days I found the problem with the super-emissive-material bug: you are sharing a texture (models/env/alley/textures/Building_Alley_Emissive.jpg) among 4 models (models/env/buildings/env_building_textures_4.gltf, models/env/roof/env_roof.gltf,models/env/alley/env_alley.gltf and models/env/doms/env_doms_inside_textures_4.gltf), which is fine, but the issue is using that same tex as normal map in one of the models (models/env/doms/env_doms_inside_textures_4.gltf) and as emissive texture in the rest. 

Unfortunately there is no way to patch this during our asset bundle conversion (since the texture in asset bundle format will end up either as a normal map texture or as a default texture, can't be both) so if you fix that on your side and re-deploy the scene, after it gets automatically re-converted to asset bundles the issue should be solved.

debugging info at https://github.com/decentraland/unity-renderer/issues/1514
```

**Comment by pravusjif** [comment]
I'm closing this issue as we loaded this same problem in another that has more info: https://github.com/decentraland/unity-renderer/issues/1583
