### ISSUE TITLE
NFT Unit test needs the API of OpenSea to work in order to pass

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#1557]
This test are using the API of OpenSea to pass, is the API is down, the test can't pass

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/f02e3822-c165-4cc8-941d-240854ade4cf)

**Comment by sandrade-dcl** [comment]
Temporally, we have set these tests as `Explicit` (Done in this PR: https://github.com/decentraland/unity-renderer/pull/1786)

**Comment by AjimenezDCL** [comment]
Test are disabled and ECS7 will solve this issue automatically, closing it.
