### ISSUE TITLE
BIW: triangles in the limit are not counted as expected

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#1572]
![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/027c3e01-b2fd-40ba-9bb1-fcba6df35c61)

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/8809225d-1fc8-4c1e-9b36-4fd2fac4d97c)

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/58cad4ae-6b68-4157-b2a0-aad1bd47530b)

**Comment by davidejensen** [comment]
BIW has been deprecated
