### ISSUE TITLE
Remove triangles expensive check in GLTFSceneImporter

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#1579]
This check is very prohibitive for performance:

https://github.com/decentraland/unity-renderer/blob/f776bf2e80957ab116eb535a02b8e8a1684f2b42/unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs#L2093

We should remove it and rely on the try...catch flow.

**Comment by Suduck** [comment]
I will remove this task from me since it doesn't seems to be related to the builder and it seems like a mistake, reassign me it again if I must take this task anyway

**Comment by JorgeDecentraland** [comment]
@Kinerius please check this issue when you implement gltFast, and close it if needed
