### ISSUE TITLE
Cybermike wearable is rendering all wrong

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1583]
At some point these Cybermike wearables ("cybermike_cybersoldier_set") started rendering all red and broken. This also happens without asset bundles so it's a problem with the GLTFs

![cybermike.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/199dc073-fe6d-4f18-a868-9c246540af4c)

![cybersoldier_suit_bugged_A01.jpeg](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/62f0c0f1-37fd-45dc-8d2d-50e0ef0b5cda)

Testing with `DISABLE_ASSET_BUNDLES` also renders the wearables wrong:
![Screen Shot 2021-11-16 at 13.21.15.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/deed3e06-ff0f-4ed6-9607-e0e3e6cffb7e)

Apparently this started happening around **[November the 6th](https://github.com/decentraland/unity-renderer/issues/1478#issue-1046579242)**

**Collection test link**: https://play.decentraland.zone/?DISABLE_ASSET_BUNDLES&NETWORK=ropsten&WITH_COLLECTIONS=urn%3Adecentraland%3Aethereum%3Acollections-v1%3Acybermike_cybersoldier_set&island=I5m6&position=-110%2C-110

**Slack thread**: https://decentralandteam.slack.com/archives/C01UXV234JG/p1637082381076900

**Comment by pravusjif** [comment]
[One creator theorized](https://github.com/decentraland/unity-renderer/issues/1545#issuecomment-973136993) that this issue may be due to the problem of wrongly sharing a texture between GLTFs/Meshes, not sure if this is possible with Wearables but just in case we should check if [the new console error ](https://github.com/decentraland/unity-renderer/pull/1575) appears when using `DEBUG_MODE&DISABLE_ASSET_BUNDLES` when loading the affected wearables.

**Comment by pravusjif** [comment]
I confirm that the problem is using the same texture as **normal** (the system will set it in linear color space) and as **albedo** (the sistem will set it as srgb). So when at some point we started processing normal maps after the albedo, the texture ends up looking bugged.

![Screen Shot 2021-12-02 at 21.13.31.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/dcf7bf9b-2d60-4f62-beed-745890339353)

![Screen Shot 2021-12-02 at 21.14.10.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/08c552a2-bbe9-4893-8b78-ce55eb459bf1)

I also tested hacking the system to override the texture set as normal map and it looks fine after that:

![Screen Shot 2021-12-02 at 21.24.21.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/68480f2c-5fd3-46d4-acc9-394c050a2f3a)

![Screen Shot 2021-12-02 at 21.24.17.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/47f52e33-f462-418d-9463-f16ad3c79527)

I'll communicate this to the creator so that they can fix the model texture usage, re-deploy it and after notifying us we'll be able to re-convert and re-upload the asset bundle

**Comment by olavra** [comment]
Closed as it was a problem with the wearable

**Comment by cybermikedent** [comment]
Please reopen this, as the suit is still bugged, thank you

**Comment by olavra** [comment]
Hi @cybermikedent,
I'm sorry to see this has not been resolved for you yet. Please, I need to understand the context a bit more and identify where we are in the process: 

- Have you separated the albedo and normal into 2 different textures?
- Have you reassigned the textures in the material and reimported the glb / glft?
- Have you re-upload the files (glb + textures) to the wearable editor and ask for a second review by the curators team?
- Has the curators team accepted your wearable for the second time?

If its "yes to all", could you send me the link to the collection so I can see the file history and understand the current status?

Thank you and sorry for the inconvenience

**Comment by cybermikedent** [comment]
@olavra Its fixed now, thank you

**Comment by olavra** [comment]
Glad to hear that. Closing this issue.
