### ISSUE TITLE
Asset Bundles: Bind wearables deployments to conversion pipeline

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1603]
We should bind wearables deployments to our automatic Asset Bundle conversion pipeline to avoid having to manually convert collections. This may need changes in the [content-migrator](https://dcl.tools/dcl/content-migrator/-/tree/master) to listen to wearables deployments

When a collection is deployed to the content servers: each collection item (AKA each wearable) has a specific "content-entity" id.

Apparently if we call the regular batch mode conversion we use with scenes content-entity ids, but using a wearable content-entity id, the process converts the asset normally. For example @pravusjif tested that calling unity with [these instructions](https://github.com/decentraland/unity-renderer/blob/master/convert-asset-bundles.sh) but inserting a wearable content-entity id in the regular `$SCENE_ID` actually converts the wearables successfully.

For converting locally to test, please refer to the following bash scripts:
* https://github.com/decentraland/unity-renderer/blob/master/convert-asset-bundles.sh
* https://github.com/decentraland/unity-renderer/blob/master/convert-wearables-asset-bundles.sh (this may not be fully implemented, should be tested, although if we bind each wearable deployment instead of each collection, this approach may be unnecessary)

**Skeleton Stripping**
* Currently, when converting wearables that are not bodyshapes (AKA not base-male and not base-female) we strip the skeleton during the conversion, because that is re-applied in runtime for each wearable. So we should add a new parameter to the batchmode call, so that we instruct that change when sending a collection to the converter (for example for future new bodyshape collections). Maybe this should be at wearable-level instead of collection-level? maybe something to detect if a wearable is a bodyshape or not and filter that internally without the need of a new batch mode parameter?

Alternatively if we are sure there will be no new bodyshapes: we could embedd the bodyshapes into the client, and strip the skeleton of every processed wearable in the converter, as we would know that none of those would be a bodyshape.

ABs documentation: https://www.notion.so/decentraland/Optimization-Asset-Bundles-afd6335bd01b4ef1a9bc07ba95f86b3b

**Comment by JorgeDecentraland** [comment]
Duplicated in #2003
