### ISSUE TITLE
Spike: Migrate all integration tests from Legacy to IntegrationTestsSuite

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#161]
We need to do an assessment of all the tests that make use of the old **IntegrationsTestSuite_Legacy** suite to the new **IntegrationTestSuite**

The result of this tasks should be a list of all the classes / services / components that needs a refactor and an estimation to be achieved.

**Comment by aixaCode** [comment]
Pending until SDK 7 is completed
