### ISSUE TITLE
Update new armature on body shape

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1612]
- [x] upload new bodyshape to peer testing content server
- [ ] test current animations with the new armature structure
- [ ] update embedded animations if necessary
- [ ] release new body shape and animations: handle rollout problem with coexisting body shapes. 

Alert: consider new bodyshape must contain anchor points for left and right hand.

**Comment by AjimenezDCL** [comment]
https://play.decentraland.zone/?CATALYST=peer-testing-3.decentraland.org&

**Comment by AjimenezDCL** [comment]
We are facing issues with the new set of bones, the hierarchy seems to be messing with the old wearables.

**Comment by AjimenezDCL** [comment]
The last issue comes from the position of the head bone

**Comment by AjimenezDCL** [comment]
By the time we are gonna stick to the current armature.
