### ISSUE TITLE
When you teleport or when you init the app, you can be moved to another parcel

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#1626]
When you go to a position (for example 140,140) you can end in (139,140).

I think that this is caused because if you spawn near a world blocker, the world blocker can push you to the next parcel 

This is only done if the scene that you move has the spawn point in 0,0 ( in the scene) where if something moves you 0.0005 position to the left you end in 139,140

**Comment by kuruk-mm** [comment]
What is the best solution for this? Change the default spawn point to the center of the parcel?

**Comment by Suduck** [comment]
I think that the issue is because the loading parcel blockers have colliders that move you out, maybe we can just disable the blocker if it is the scene where we are teleporting
