### ISSUE TITLE
Add new Skin category for wearables

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1643]
A new category Skin will be integrated into the backpack.
This category hides all other wearables without restriction, showing just that one.

**Acceptance Criteria**
- [x] A new category appears along the rest of categories in the backpack
- [x] Equipping a skin hides all other wearables
- [x] Equipping any other wearable on top of the skin, disables the skin.
- [x] Equipping a skin on top of a wearable with a portable experience is NOT possible. A toast must appear notifying this to the player.
- [x] By extension, no wearable can be equipped if it hides a wearable with a portable experience.
- [x] Removing a skin reveals the avatar in its previous state

**Comment by RominaMarchetti** [comment]
https://www.figma.com/file/zMetMn5FptTKYXTnxcRtpW/Backpack-Hybrid?node-id=2869%3A2063

<img width="837" alt="Screen Shot 2022-01-03 at 20 19 33" src="https://user-images.githubusercontent.com/51088292/147990717-2509f0c8-e723-42a2-a9ac-44494945100a.png">

**Comment by lorux0** [comment]
I will continue this issue when the backend side is implemented so it can be tested with real skin wearables
