### ISSUE TITLE
Mouse right-click should release mouse lock 

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1649]
It is quite annoying to have to press the ESC key to unlock the mouse. Currently the right click is not used for anything in the gameplay, and temporarily, until we find another control system, we are going to use it to complement the ESC functionality.

It would be nice if there was some visual reference within the UI: some mouse icon with the right click on and an open lock, to remind users how to exit the lock mode.

Acceptance criteria
- [ ] Both ESC and Right Click must unlock the mouse.
- [ ] During mouse lock, an icon must appear somewhere on the screen showing how to unlock.
- [ ] This new way of unlock should be shown in the first step of the tutorial.

**Comment by RominaMarchetti** [comment]
I made 3 different proposals to check which one convince us the most.
The input in every flow is left click. After the toast disappear the flow restarts. 

https://www.figma.com/proto/jsaHSHpRGgGGmzKDKyUTX4/MouseClick?page-id=0%3A1&node-id=0%3A1&viewport=313%2C48%2C0.27&scaling=contain&starting-point-node-id=2%3A258&show-proto-sidebar=1 

If you don't see the left side bar listing all the flows, click in Figma's UI the highlighted button in this screenshot:
<img width="1190" alt="Screen Shot 2021-12-27 at 10 18 59" src="https://user-images.githubusercontent.com/51088292/147475609-5f1fcf60-b9aa-4490-9166-16f81a4ffcf5.png">

**Comment by lorux0** [comment]
I will merge the PR sometime in january to wait any changes produced by the feedback
