### ISSUE TITLE
All "Active since" in the passport have the same date

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1651]
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/3bb13565-35af-4d3b-ac99-121c561a0e8c)

We need to check if this date can be retreived from the profile. If not, this line needs to be removed.

**Comment by lorux0** [comment]
There is no data coming from kernel to show this. Im hiding the label for now, but it would be good that kernel sends this information

**Comment by lorux0** [comment]
An approach was taken to solve the activation date of a user by requesting it to the catalyst directly from unity. This approach had some problems, like catalyst throughput and the data its expensive to solve computationally and not consistent. We will be discussin with platform team to look for a better approach

**Comment by lorux0** [comment]
We discussed an approach with platform team but it has been decided that disabling the label is the best solution since the data may not be consistent between catalysts and we could be showing something wrong to the users.
