### ISSUE TITLE
Some entity meshesinfo renderers turn into null at some point. Remove patches.

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1654]
Debugging [this issue](https://github.com/decentraland/unity-renderer/issues/1645) we saw that at some point in some scenes given certain circumstances (debugged for 2 days and couldn't find those) in that scene 1 of the renderers in an entity's meshesinfo is turned null and we already had a bunch of nullref patches for that at:

* https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Builder/Scripts/DCLBuilderEntity.cs#L118
* https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Builder/Scripts/DCLBuilderEntity.cs#L135
* https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Builder/Scripts/DCLBuilderEntity.cs#L271
* https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs#L236
* https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_Simple.cs#L21

More info on what may be causing this in this other issue: https://github.com/decentraland/unity-renderer/issues/1645

We should find the root of the problem and fix that and remove those nullref checks.

**Comment by xavi-dcl** [comment]
If it happens again we'll notice
