### ISSUE TITLE
Allow scene music to be heard from nearby scenes

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#166]
Right now, some scene music/broadcasting is not being heard from the contiguous scene. It would be desirable that we change that behavior (using 3D positioning of the sound). We could make it so that the `scene.json` can disable the music from neighbouring scenes (in case I have a noisy neighbor).

**Comment by olavra** [comment]
By default all surrounding music can be heard, but the content creator may decide to switch this functionality off in order to isolate its scene from the rest.
