### ISSUE TITLE
Warning message in the chat UI to prevent SCAM

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#167]
Trigger a warning toast when we recognize that a user is about to send a wallet address. 
The toast UI should contain a text warning message and a "don't show again" checkbox.

**Comment by olavra** [comment]
@RominaMarchetti do we have a mockup for this?

**Comment by RominaMarchetti** [comment]
<img width="408" alt="Screen Shot 2021-08-03 at 10 21 03" src="https://user-images.githubusercontent.com/51088292/128022505-9021b52d-6006-4c76-836b-4d5d2e53d981.png">

Here is the Figma link: https://www.figma.com/file/kdJB75JHbGOWL8XyyuOr4j/Chat-and-Friends?node-id=965%3A0
