### ISSUE TITLE
Fps display not working on desktop

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#1680]
FPS Display is not being updated on desktop while on fullscreen

**Comment by pmacom** [comment]
Have there been any updates on this? I think it's related to the atlas textures and the scaled down uv maps on each model. Anything that uses this design pattern is experiencing an issue. You might have to somehow force at least 1px per triangle for this to fix. If you move your perspective around, you can sometimes see the texture roll over the model. I suspect it has to do with how the M1 handles floating point calcs.
