### ISSUE TITLE
Create meta transaction dialog for Wallet Connect

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1690]
Transactions initiated by the SDK scenes usually relies on the browser extension of Metamask to display a dialog to sign the transaction.
For wallet connect sessions, this dialog is no longer evident as requests are happening in your mobile phone. To prevent this, Explorer needs to initiate an informative dialog with the player:

```
"SCENE_NAME (X,Y)" wants to sing this message:
message: MESSAGE TEXT
in: NETWORK
```
or

```
"SCENE_NAME (X,Y)" wants to initiate a transfer:
TOKEN AMOUNT + TOKEN NAME
from: YOUR_WALLET_ADDRESS
to: OTHER_WALLET_ADDRESS
in: NETWORK
```
This dialogs will have a OK and CANCEL action buttons:
- OK = Player Acknowledges the message
- CANCEL = Cancels the transaction

We need to cover the cases defined in the SDK documentation:
https://docs.decentraland.org/development-guide/scene-blockchain-operations

**Comment by RominaMarchetti** [comment]
https://www.figma.com/file/IlNsUN6saT3d8a8VAdxFlX/Modals%26Dialogs?node-id=0%3A1

**Comment by Kinerius** [comment]
View prefab is created at `feat/transaction-popup`

**Comment by kuruk-mm** [comment]
To be able to release this feature correctly (including in .ZONE) we must set the rollout 100% to the 4aa9dbd commit.

The kernel PR (https://github.com/decentraland/kernel/pull/160) needs the renderer response to works.
