### ISSUE TITLE
MacOS Desktop client has some "invalid asset bundle format for this platform" errors

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1698]
In desktop client in MacOS we get the following errors sometimes:

```
Error while getting Asset Bundle: The AssetBundle 'https://content-assets-as-bundle.decentraland.org/v22/QmWH3LfP637rdKSQhzdELUWcy8cNB8g5zJtMxReDvRyNvh' can't be loaded because it was not built with the right version or build target.

The file can not be loaded because it was created for another build target that is not compatible with this platform.
Please make sure to build AssetBundles using the build target platform that it is used by.
File's Build target is: 20
```

However in Unity Editor in mac we load the ABs with no problems, so the desktop build shouldn't have problems as well, let's check out what's going on.

We could also use in the desktop launcher in development mode the unity-renderer branch that paints green/red the meshes according to their AB or GLTF format (https://play.decentraland.zone/?renderer-branch=feat/ab-view).

**Comment by kuruk-mm** [comment]
Superseed by https://github.com/decentraland/unity-renderer/issues/1810
