### ISSUE TITLE
Players should be able to change realms in-world

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1708]
Mainly motivated by the desktop build, but also to make it a frequent use on the web, players should be able to switch realms within the world. For this we are going to partially implement the concept we had of ~Dimensions~ Realms, a panel that launches when you click on the Decentraland button inside the Start Menu and shows all the available realms, the one you are currently in, the number of players in each one, and a button to jump between them.
Here you have to decide whether to jump directly or put a loading screen until the new connections have been established.

**Acceptance Criteria**
- [x] A new menu appear when clicking on the Decentraland logo in the Start Menu..
- [x] This menu shows all available realms, their current number of players (optional) and a button to Warp In
- [x] The current realm is as well visible

**Comment by RominaMarchetti** [comment]
https://www.figma.com/file/5YhRkm1NXme8MhgDxGT2zY/Explore-V2?node-id=641%3A4393

<img width="1125" alt="Screen Shot 2022-01-03 at 20 25 22" src="https://user-images.githubusercontent.com/51088292/147991075-cde1040e-794a-4e57-9e32-976a502f10ae.png">
