### ISSUE TITLE
Backpack not available on preview

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#1713]
When running a preview of any decentraland scene, the backpack is no longer available in the UI.

<img width="391" alt="Screen Shot 2022-01-03 at 11 22 04" src="https://user-images.githubusercontent.com/3507907/147942082-edbc816b-95fd-4d34-9c0c-9c4a8c16fe5e.png">

The problem appears using the @next version of decentraland-ecs, Using the @latest version of decentraland-ecs, it works fine.

I tried forcing to the latest version of the Unity renderer just in case, but the problem is still there
http://127.0.0.1:8001/?ENABLE_WEB3&SCENE_DEBUG_PANEL&position=0%2C0&realm=localhost-stub&renderer-version=1.0.23631-20211230211215.commit-afdc937

Being able to open the backpack is super important when working with smart wearables, since you need to be able to put the wearable on or off to test it.

**Comment by pravusjif** [comment]
This blocks a new SDK release
