### ISSUE TITLE
Define/fix the behavior of the close button from Avatar Editor on the first log in

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1738]
![image.png](https://images.zenhubusercontent.com/60647b38cc4b79842895cb82/29916d66-b5ca-437e-8bbc-48756a9af513)

The close button doesn't have a specific behaviour. It has different behaviours for example in the browser: it goes to the sign-in website, refresh the same avatar editor panel and sometimes it crashes.

On the desktop, the renderer shows the world, but you can't interact with other avatars.

Reproduction steps:
1. Open a Chrome Incognito tab
2. Enter play.decentraland.org
3. Press `Play as guest`
4. In the Avatar Editor, press the X for close

I propose to delete the button.

**Comment by olavra** [comment]
This button needs to be removed during first Avatar creation
