### ISSUE TITLE
Replace avatar hair/eyes color choices with RGB picker

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1743]
The range of colors for the hair and eyes is too limited for the players. They would like to have freedom to change it. Instead of having a discrete number of colors, we will have a color picker considering tone and brightness.

This do not involve emissive or HDR ranges above or below 0.

This also responds to this [DAO proposal](https://governance.decentraland.org/proposal/?id=4b0e5240-3523-11ec-ac84-77607720a240)

The integration of the feature is not that expensive, but all the small details and minor functionalities of it (such as the arrows to move right and left, the outline of the selected bar, ...) take a bit of time. 
After the initial plan the feature has slightly changed, new figma design: https://www.figma.com/file/zMetMn5FptTKYXTnxcRtpW/Backpack-Hybrid

Key points:
- [x] Create slider logic
- [x] Create new panel with the sliders
- [x] The focused slider needs to show the rainbow outline
- [x] The arrow on right and left move the slider
- [x] The arrows deactivate if reach the beginning or the end of the slider
- [x] The arrows should move also with right and left keyboard arrow when the slider is selected
- [x] Randomize button needs to take in account eyes and hairs color
- [x] Both the sliders and the preset colors needs to appear and be usable
- [x] The selected preset color will show the rainbow outline.
- [x] Once the player use a slider, if there was a preset color selected its highlight must disappear.
- [x] The color circle next to the button to open the color panel will be colored with the current pick
- [x] Closing the explore will close the panel if open
- [x] Clicking away from the panel will close the panel
- [x] Graphic refinements

Additionally the following things need to be considered:
- [ ] Change character preview loading to avoid stutter on slider usage
- [ ] Add a wait time of some fractions of second to avoid too many slider changed events
- [x] Verify randomizer behavior and check current issues related to it

**Comment by RominaMarchetti** [comment]
If we are going to change the color picker for hair we should also change it for skin and eyes color.
This menu can be opened clicking the color picker dropdown and closes clicking outside the container or pressing esc. The players can user the arrows or the sliders' handle to equalize the color.
  
![Screen Shot 2022-01-11 at 12.31.25.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/0a0d6e82-fef9-47ca-9dac-8bbc295f6a26)

[Figma project](https://www.figma.com/file/zMetMn5FptTKYXTnxcRtpW/Backpack-Hybrid?node-id=2954%3A1126)

**Comment by davidejensen** [comment]
> The left side hair options doesnt work ![image.png]

Fixed, it's building now with this change @olavra
