### ISSUE TITLE
Avatars default name tag appears before their meshes

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1746]
Apparently it happens when they are pointed at with the cursor:

https://images.zenhubusercontent.com/337227404/4cb81c21-8d59-4eaf-887b-12aa2765bf15/screen_recording_2022_01_11_at_13_23_00.mov

**Comment by davidejensen** [comment]
We can close this, it is not happening anymore:

https://user-images.githubusercontent.com/4254522/165717714-17235e92-61fb-4db8-9f12-1228733d211b.mov

Other than the video I tried multiple times in even more crowded areas like poker, but it is not possible to reproduce it anymore
