### ISSUE TITLE
Improve the way Friends feature fails

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1748]
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/c66b85d1-ef4c-40d3-bd55-c3b61029087d)

**Figma:** https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Module-%5Bwip%5D?node-id=604%3A13360

**Acceptance Criteria**
- [x] Remove Friends connection fail notification
- [x] While the Friends panel is loading, a loading spinner will be showed.
- [x] We won't never contemplate a "failed" status of the friends feature because we maked it be indefinitely retried from kernel.

**NOTE:** Use `feat/SocialBar` as base branch.

## Kernel side
https://github.com/decentraland/kernel/pull/282

**Comment by lorux0** [comment]
first it is needed to talk on what can be done from kernel side to make this happen and decide if there is some responsability that we could move to unity side

**Comment by sandrade-dcl** [comment]
Feature already implemented and merged in in https://github.com/decentraland/unity-renderer/pull/1994.

In the kernel side, the PR https://github.com/decentraland/kernel/pull/282 is waiting to be approved by Mendez.
