### ISSUE TITLE
Avatar movement speed is affected by FPS

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1753]
Considering the context of low FPS:
- Scene Load raidus = 6
- 100 avatars around you
- Ultra settings

The avatar movement speed is considerably slower than on good FPS conditions.

**Acceptance Criteria**
- [ ] Avatar walk / run speed is always constant independently of the FPS

**Comment by pravusjif** [comment]
Years ago we introduced a deltaTime cap, we should revise if it's still needed: https://github.com/decentraland/unity-client/pull/323
