### ISSUE TITLE
Implementation of Social Bar features

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1756]
[Figma](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Module-%5Bwip%5D?node-id=604%3A13360)
[Notion](https://www.notion.so/decentraland/Social-Bar-V1-96f418d37bfd4c35a40118d0fbcc4d89)
[Figma feedback & fixes](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Module-%5Bwip%5D?node-id=1510%3A17903)

# Friends
- [x] Rewire friends layout. Add friends/friends request search bar
- [x] rebase & merge to master

# Chat

- [x] decouple old views from controllers
- [x] implement new esthetic of chat windows
- [x] #general goes to the top of the window, followed by #private conversations (one for each user)
- [x] you can use the search bar to display channels or direct chats
- [x] remove chat heads for private chats
- [x] private chats will be sorted by last message's timestamp
- [x] private chats will display a loading spinner while chats are loading
- [x] when you click on a private chat, a new window (reskinned) should be opened showing the scrollable chat history.
- [x] when you click on a public chat, a new window (reskinned) should be opened showing the scrollable chat history.
- [x] private chats include a contextual menu for: blocking, adding the user
- [x] replace the behaviour of opening chats with ENTER key
- [x] refactor the controller tests so they can use & assert a mock instance of the view
- [x] integrate empty state for private chat list
- [x] add options button to private chats
- [x] private messages are being displayed like "/w [user] [message]" (this only happens on my fake simulation)
- [x] public messages are not including the user name
- [x] hide jumpin button when the user is offline
- [x] reskin del menu contextual
- [x] notification count gets bugged when searching channels
- [x] fix tests
- [x] normalize the size of windows
- [x] notification count is not getting cleared after you open a private chat
- [x] fix all visual issues to get an aproval from product side

**Defects 10/05/22**

- [x] friends window should be able to be opened while friends are loading
- [x] remove loading spinner of the friends button in the taskbar
- [x] specify which thing is loading when private chats are loading
- [x] retrocompatibility with seen messages from private chats **(not a retrocompatibiliy issue, check this [thread](https://decentralandteam.slack.com/archives/C02DP91V7RU/p1652221794883219). A patch has been implemented to filter messages older than 1 day)**
- [x] search friends in searchbar: no entries are being shown &  "No Results Found" is displayed always
- [x] when you add a friend, the scroll doesnt cover it in the list
- [x] #nearby should be opened at the start of the session
- [x] friendship requests arrives with the address instead of the name of the user
- [x] mouse locking should not hide the current taskbar window
- [x] rejecting a friend request does not clear the friend notification count when the friend request window is visible
- [x] the header of private chats should block clicks

**Defects 11/05/22**

- [x] search results in chat has an incorrect container style
- [x] chat button should open the last active conversation
- [x] scroll with the mouse wheel are slow in friend list and chat list
- [x] sort friends alphabetically
- [x] remove the friends loading spinner from the taskbar
- [x] apply a transparent effect on chat window when the cursor is locked
- [x] the spam filtering allows you to keep sending messages but you cannot see them as a sender in the ui

**Defects 12/05/22**

- [x] clicking the chat button should open the last opened window (no matter the message timestamp or active conversation)
- [x] #nearby should be transparent at the start of the session
- [x] change the style of all message types to have a black container and white text ONLY when is preview mode activated
- [x] fadeout chat window when cursor is locked
- [x] fadeout chat window after a couple of seconds after the cursor leaves the window area
- [x] fadein chat window when the cursor is moved over the window area
- [x] fadein chat window when the input field is focused
- [x] unlocking the cursor should not fadein the chat window

**Defects 13/05/22**
- [x] if you press ENTER with the empty input focused in the chat, it should be hidden instantaniously
- [x] all taskbar windows should be closed when locking the mouse, EXCEPT private/public chat windows
- [x] normalize the friends & chat notification count style. Both should have the same color

**Defects 16/05/22**
- [x] the taskbar chat button should open the chat list if was the one opened
- [x] remove online/offline headers of the friend list

**Comment by lorux0** [comment]
regarding to:
> replace the current visible state behaviour of the chat list window (the old version is opened all the time)

kernel is commanding the world chat to be active in the first place.. i gotta do a kernel branch to disable this functionality
