### ISSUE TITLE
Location coords patterns must be clickable

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1776]
Wherever text is displayed, if a pattern is found that matches a set of coordinates, it should be transformed as a link and teleport the user to that location if the player chooses to click on it.

**Possible Regex**
[-]?\d{1,3},[-]?\d{1,3}

**Acceptance Criteria**
- [ ] If a player writes a coordinate in the chat, passport, scene description or event, this must be clickable
- [ ] Clicking on this teleports the player to that place
- [ ] Coordinates outside of valid range wont be represented as links

**Comment by davidejensen** [comment]
I've started implementing a basic behavior and encountered some things to discuss:
* Should we highlight the coordinates in the chat with a different color?
* On the click should we immediately teleport or should we open a pop-up with a button to jump in to the coordinates?
