### ISSUE TITLE
Avatar modifier areas should display a toast

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1777]
Some scenes can make use of the avatar modifier that hides the avatar or passport, for the player and other players. This is not notified to the player anyhow. In the same way we are notifiying the camera lock, we should include a small toast+modifier status to show this temporary state to players.

**Acceptance criteria**
- [x] While players are inside avatar modifier areas that hide the avatar, a small icon will appear displaying this status
- [x] This icon wont dissapear until the player leaves the area
- [x] The first time in the session this toast appear, it will come together a explanatory text
- [x] That text will collapse after a few seconds
- [x] Mousing over the icon shows the text again

**Comment by olavra** [comment]
Figma Design
https://www.figma.com/file/jsaHSHpRGgGGmzKDKyUTX4/InWorldToasts

**Comment by dalkia** [comment]
1) Which is the explanatory text that should appear?

**Comment by RominaMarchetti** [comment]
@dalkia the title of this toast should always be **This scene is restricting the use of some features**. What comes bellow can change depending on the scene:
- The camera is locked
- The avatars are hidden
- Passports can not be opened

Preview of the message
<img width="357" alt="Screen Shot 2022-06-24 at 14 42 11" src="https://user-images.githubusercontent.com/51088292/175614229-289cea7b-92fc-492f-984f-73a13229a0fe.png">

[Here](https://www.figma.com/proto/jsaHSHpRGgGGmzKDKyUTX4/InWorldToasts?page-id=0%3A1&node-id=105%3A455&viewport=1416%2C3019%2C1&scaling=contain&starting-point-node-id=105%3A455) you have an interactive prototype to understand better its behavior. 
Use this [Figma file](https://www.figma.com/file/jsaHSHpRGgGGmzKDKyUTX4/InWorldToasts?node-id=105%3A455) to check font style, sizes, colors, etc.

This is the warning icon you need.
![WarningTriangleIcon](https://user-images.githubusercontent.com/51088292/175615063-37054f25-2b22-4da7-87ff-a199b2af11aa.png)
Use the asset called `RectRadius12` (path Assets/Textures/UI/RectRadius12.png) for the containers and rotate it depending the case. The pixels per unit must be set in 2.

Any question you may have don't hesitate to reach me out @dalkia

**Comment by dalkia** [comment]
Camera inforcement is being used in scene -68,125; and apparently not using a ModifierArea.
