### ISSUE TITLE
Offset in minimap gives an inaccurate position

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#178]
As in the screenshot, I'm standing on the corner of this road but the minimap shows me as in the middle of the next parcel
![image](https://user-images.githubusercontent.com/42750/111859759-e2630b80-8921-11eb-8230-2163cd00f55c.png)

The actual position should be something like this:
![image](https://user-images.githubusercontent.com/42750/111859794-27873d80-8922-11eb-97f0-fceb2560f9ef.png)

**Comment by olavra** [comment]
It seems like the pivot point of the red dot sprite is on 0,0 instead of the center of the image, and giving that space offset
