### ISSUE TITLE
Desktop: Connecting with Wallet Connect something get stuck for ever

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1780]
We have received several reports of people that never receive the signing event in their mobile app when using wallet-connect, so the landing/launcher is left in a state of "please follow the instructions of your mobile wallet provider to continue" with a spinner loading forever

Probably related to this code: https://github.com/decentraland/explorer-website/blob/557d9b5c845713abae18355ec60a04a0b49f637d/src/kernel-loader/index.ts#L297

**Comment by pravusjif** [comment]
Apparently Metamask mobile has been updated in these last days and improved the wallet connect experience
