### ISSUE TITLE
Tennis court at -132,74 scene messages freeze

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1785]
**Problem:**
After entering [the tennis court](https://play.decentraland.org/?realm=dg&position=-132,74), if there are other players around, the ball-throwing NPC freezes randomly for random times (the thrown ball also freezes in mid-air)

https://images.zenhubusercontent.com/337227404/d30c8022-3617-4ade-96cb-18291702c4dd/tennis_court_messages_freeze.mp4

**Data gathered debugging:**
- When the ball-throwing NPC freezes, that scene messages to the renderer stop being sent
https://images.zenhubusercontent.com/337227404/8d4d7ecf-71ec-48ad-8e3d-8825129cb3bc/tennis_court_messages_freeze_debug.mp4
- The browser's performance profiler doesn't show anything strange nor time-consuming in that scene's webworker
- If the AvatarModifierArea used in the court area is toggled off in Unity in runtime, the problem persists
https://images.zenhubusercontent.com/337227404/b7a9e68d-62dc-4c70-8e3e-b2336d74bddc/tennis_court_messages_freeze_without_avatarmodifierarea.mp4

- If we remove the AvatarModifierArea monobehaviour from its component prefab, the problem persists
- **If we use `LOCAL_COMMS` to avoid having other players around the problem no longer happens**
- **If we deactivate the global scene GameObject before any avatar is instantiated, the problem no longer happens**

I believe there is some issue with Kernel/SDK avatar/player events, otherwise this might be a problem in the scene's code logic. After having debugged in unity-side we should start debugging in kernel-side.

**Comment by pravusjif** [comment]
- Apparently the problem never appears when connecting through LOCALHOST.
- Whenever the scene execution **unfreezes**, we see the following `FS.syncfs` warning in the console:
![prod-4](https://user-images.githubusercontent.com/1031741/150009293-2ae219de-6650-4eaf-ae32-40e341ec1947.png)
- The scene dev is running more tests in production, hopefully some new clue will be discovered soon.

**Comment by JorgeDecentraland** [comment]
Issue in the scene
