### ISSUE TITLE
Tasks with requirements from other tasks should be hidden

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#179]
Tasks with previous tasks completion requirements should be hidden from the quest logs if the requirement has not been met.
As soon has the task is completed, the next tasks should be disclosed.

"requirements": [
"type": "completedPrevious"
],
"previousTask": {
       "id": "45d81fb8-84fe-466c-b756-a9b89d791117"
},

**Comment by AjimenezDCL** [comment]
Although Unity is not receiving requirements data we have a `status` value that we can use to hide blocked tasks
