### ISSUE TITLE
"Tutorial robot" and "character preview avatar renderer" shouldn't be animated/active when not rendered

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1794]
- TeacherCanvas GameObject shouldn't be active while not being rendered (after the tutorial finishes)
- _CharacterPreviewController->AvatarRenderer GameObject shouldn't be active while not being rendered (when not using the backpack)

https://images.zenhubusercontent.com/337227404/4f101ddd-846d-4246-8f10-47719b61b001/not_rendered_animated_objects.mp4

**Comment by olavra** [comment]
Her name is Alice
