### ISSUE TITLE
Debug weird performance drop on Ultra graphics in isolated areas

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1795]
https://user-images.githubusercontent.com/1031741/150222551-5fa9b4ad-a8d2-42f0-982b-db9e63815d79.mp4

https://user-images.githubusercontent.com/1031741/150222601-ef3668c1-fffd-48d5-b326-c5902f3c63ec.mp4

Reproduction steps:
1. enter at these coords full of empty parcels, use the chrome window in your highest-resolution monitor: https://play.decentraland.org/?position=-100,100
2. open the settings panel, go to graphics and set the ULTRA preset
3. enable the FPS panel with the /showfps chat command
4. Wait a couple of minutes and watch the FPS drop a lot (in my case is from 45~50 to 18~20). It may take from 2 to 7 minutes to happen.

Apparently this heavy performance drop only happens on big resolutions and with the ultra graphics settings preset (I think using the unlimited resolution is the trigger here) in my case is on a macbook pro with a 3072 x 1920 display.

It can even be observed in isolated areas like this zone full of empty parcels: https://play.decentraland.org/?position=-100%2C100&realm=loki&LOS=0

**Comment by pravusjif** [comment]
![Screen Shot 2022-01-19 at 15.03.52.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/b58ffadb-fc1c-467e-aec8-427f180fb7c8)

![Screen Shot 2022-01-19 at 15.03.59.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/017042b7-801f-486f-9fd0-9c57c5bb35b8)

profiling json
[https://app.zenhub.com/files/337227404/d5912094-0316-491a-a66f-8abd2eec07d9/download](https://app.zenhub.com/files/337227404/d5912094-0316-491a-a66f-8abd2eec07d9/download)

**Comment by pravusjif** [comment]
- Tested on different realms
- Tested in incognito mode
- Tested in Firefox
- Tested with `LOCAL_COMMS`
- Tested with `DISABLE_PROCEDURAL_SKYBOX`
- Profiled build from Unity Editor
- Profiled again from the browser tools:

**Comment by pravusjif** [comment]
This looks like a Unity bug...

A sample of the super slow task in the main thread:
![Screen Shot 2022-01-20 at 12 41 26](https://user-images.githubusercontent.com/1031741/150372108-d9cf482e-e7b9-4da1-8524-652d496fa4df.png)

The referenced slow method would be the [frame update call in javascript](https://github.com/decentraland/unity-renderer/blob/a2286db910383341a909b6452721d63cd539043c/unity-renderer/Assets/Plugins/CustomRequestAnimationFrame/CustomRequestAnimationFrame.jspre#L25):
```
// called every frame
    function tick(time) {
      lastHandler = null;

      if (!window.capFPS || time - prevTime >= FRAME_MS) {
        var oldCallbacks = callbacks;
        callbacks = [];

        for (var i = 0; i < oldCallbacks.length; i++) {
            oldCallbacks[i](time);
        }

        oldCallbacks.length = 0;
        prevTime = time;
      }

      scheduleNext();
    }
```

Profiling from Unity Editor using the build doesn't seem to provide much data on the problem either, I captured this 2 screenshots of a couple of very expensive garbage allocation processes, but you can see that the profiler reports higher framerate than what we see in our FPSDisplay:

![Screen Shot 2022-01-19 at 03 55 51](https://user-images.githubusercontent.com/1031741/150375375-64f39d0d-78a7-43a8-b70f-e204adb5e200.png)
[biuld-performance-drop-1.data.zip](https://github.com/decentraland/unity-renderer/files/7906730/biuld-performance-drop-1.data.zip)

![Screen Shot 2022-01-19 at 03 54 38](https://user-images.githubusercontent.com/1031741/150375360-2f4a18da-f9be-47e8-b006-c95dadfd0d6c.png)
[biuld-performance-drop2.data.zip](https://github.com/decentraland/unity-renderer/files/7906724/biuld-performance-drop2.data.zip)

Since this only affects a minority of users (mac users running on ULTRA with a high-resolution retina display), we're pausing this debugging for now. We'll check again once we are using Unity 2021 LTS.

**Comment by xavi-dcl** [comment]
@pravusjif would you like to check this again now that Unity2021 is there?

**Comment by pravusjif** [comment]
hey @xavi-dcl, sure, let me re-check and get back to you

**Comment by eordano** [comment]
@pravusjif any update on this?

**Comment by pravusjif** [comment]
I just tested in [this isolated empty scene](https://play.decentraland.org/?position=-63%2C133&LOS=1) with ULTRA graphics preset using the same macbook pro with retina display and I don't seem to be having the issue anymore, I get a 10~15 consistent FPS and it doesn't go lower than that.

So I'm closing the issue!
