### ISSUE TITLE
Upgrade Unity to 2021

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#1797]
Some of the developers (including me) are using the newest versions of the Macbook with M1 processors.

These are some of the issues that we are encountering:
- Multiple crashes per day due to the shader compiler.
- Weird issues with comms where we don't see other people ( editor only ) [ just speculation ]
- Profiler (even without a deep profile) stops working after a few seconds.

The most recent stable version that supports M1 processors is `2021.2.8f1` ( NOT LTS ) 

Task list
- [x] Upgrade Unity version and see how it goes.
- [x] We may have shader incompatibility.
- [x] Check that the CircleCI docker image exists for the given version and generate the license again.
- [ ] We may have WebGL loader incompatibility.
- [ ] We may have WASM custom plugins incompatibility.
- [ ] We may have Unity plugins incompatibility.
- [ ] Check if package updates are mandatory or we can implement them as another task.

**Comment by BrianAmadori** [comment]
Tentative task list:

- [ ] Upgrade Unity version and see how it goes.
- [ ] We may have shader incompatibility.
- [ ] Check that the CircleCI docker image exists for the given version and generate the license again.
- [ ] We may have WebGL loader incompatibility.
- [ ] We may have WASM custom plugins incompatibility.
- [ ] We may have Unity plugins incompatibility.

**Comment by Kinerius** [comment]
I'm closing this issue since I've separated all the corresponding bugs to their issues, this task is already complete, the PR will be merged once all those issues are solved
