### ISSUE TITLE
Emotes as NFT

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#1804]
- [x] Refactor the animations architecture to have them in a catalog.
- [x] Implement the embedded emotes in the catalog.
- [x] Create an equipper to add the animation clips to the Animation itself.
- [x] Add the equipper to the AvatarSystem
- [x] Download the GLBs, gather the animation clips and add them to the catalog.
- [x] Test suite

**Comment by AjimenezDCL** [comment]
#1992 sets the foundation for Emotes as NFTs, it includes:
- Compatibility with embedded emotes (that will probably be removed later)
- the new framework to equipo and load emotes

What is missing to complete this task:
- Download the GLB/GLTF and gather the animation clip

The last step will be done in another PR.
