### ISSUE TITLE
Change default port of the WebSocketCommunication

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#1807]
Currently, to debug we use port 5000. In Mac M1 that port is used by the ControlCenter and there are some programs that used it too according to wikipedia:

![image.png](https://images.zenhubusercontent.com/60647b38cc4b79842895cb82/49eb48eb-5d55-4fb6-9913-6d2b0afae433)
Reference: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

We have a system to detect available ports. But when we're debugging without SSL, we only are allowed to use port 5000. So there's no other option.

I propose to change the default port to 7666, which is not listed on the Wikipedia webpage.

Remember to change here:

https://github.com/decentraland/definitions/blob/108887b87546cb59b8b90764ec2e9b4548d1a25e/src/domains.ts#L16

https://github.com/decentraland/definitions/blob/108887b87546cb59b8b90764ec2e9b4548d1a25e/src/domains.ts#L34

**Comment by popuz** [comment]
@kuruk-mm, when changing `startPort` from **5000** to **7666**, should I also change `endPort` from **5100** to **7766**? (Line 88 of `WebSocketCommunication` constructor).
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/9765b1ce-1ae0-461a-81d1-b8005fab2734)
