### ISSUE TITLE
NFTs w bad data break scene loading

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#1823]
Looks like when a scene has badly loaded data about an NFT, it prevents scenes from loading

Here's a case where this was hurting the loading of neighbor scenes, seems creators couldn't get in at all because of this

![image](https://user-images.githubusercontent.com/3507907/150807438-5afe9e96-a952-490e-882d-a1ea828ec98e.png)

This case was resolved by fixing the neighbor's scene code

The same issue is probably also happening near -16,-126, 
https://play.decentraland.org/?position=-16%2C-126

If I walk to this location from 10 parcels away, the scenes around never finish loading. 

I can't confirm that this specific case is because of NFTs because we can't see what content is supposed to be in those parcels that don't load.

**Comment by AjimenezDCL** [comment]
I haven't found an issue with NFTs but an exception caused by duplications on content mapping hashes.
