### ISSUE TITLE
Add emote details card

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1836]
Extended information of an emote can be displayed by clicking on the info button of an Emote in the backpack. 
This card shows:
- Contract and token information
- Creator
- Name and Description
- Trading history
- Issue number (19/100)
- Rarity
- Actions to Sell, Buy, Transfer or Bid

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/e73e9975-80ce-4ff8-aa73-46e6077239ab)

**Acceptance Criteria**
- [x] Emotes panel appear on clicking info button of an emote card

**Comment by sandrade-dcl** [comment]
For now, for this emote details panel, we're going to use the same design as the wearables info panel.
