### ISSUE TITLE
Quest Rewards should be visible in the Quest Log

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#184]
Quest rewards should be shown next to the Quest description inside de Quest Log.
Rewards are aslo listed in the Read More popup of the Quest

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/7c3e6fad-c4ea-4eef-9d20-920c9644cf9f)

**Comment by AjimenezDCL** [comment]
![image.png](https://images.zenhubusercontent.com/5d91ff0b2836200001244acf/b3e7080e-d461-40b5-ad47-aaf153cf5f40)

Updated screenshot from the PRD
