### ISSUE TITLE
Implement backpack empty states

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#1881]
Currently, the accessories subcategories Mask, Hat, Helmet, Top Head and the category Collectibles are not showing an empty state. This makes the experience fill like broken and we are missing the opportunity to show users the marketplace.

The empty states shows:
- The Marketplace icon (replace the one that actually exist in the project for the following one)
![MarketIcon.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/f57f00eb-fc5e-413c-8fb1-1fd7ab1fc17d) 
- A title that changes depending its category.
- A description with a link to the category Marketplace.

[Figma](https://www.figma.com/file/zMetMn5FptTKYXTnxcRtpW/Backpack-Hybrid?node-id=3274%3A10025)
![Screen Shot 2022-02-03 at 13.54.31.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/c06f49b4-2403-4a99-860a-41652386fd0f)

**Comment by JorgeDecentraland** [comment]
@lorux0 @sandrade-dcl is this done yet?

**Comment by sandrade-dcl** [comment]
@JorgeDecentraland sorry for the delay! It is not yet implemented.

**Comment by olavra** [comment]
This will be implemented as part of the Backpack 2.0
