### ISSUE TITLE
Debug bug of scenes that never finish loading (with asset bundles disabled)

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1890]

**Comment by pravusjif** [comment]
After disabling video streaming to fix the nullrefs it triggers, I haven't been able to reproduce the "never-ending loading scenes" bug again.

@olavra @Kinerius let's check if this is still happening in master branch current state, if happens in a specific scene can you share the coordinates? thanks!

**Comment by Suduck** [comment]
Still happening

**Comment by pravusjif** [comment]
* Debugged a lot and found out that the best way to reproduce the issue is [entering directly at the railroad scene](https://play.decentraland.org/?DISABLE_ASSET_BUNDLES&DISABLE_WEARABLE_ASSET_BUNDLES&NETWORK=mainnet&realm=hephaestus&position=13,0) and keep walking a lot along that scene, since if is a very “long” scene, it allows a situation in which we are constantly loading and unloading all the other parcel/scenes around that long one (and even more using a scene load radius of 6), that’s what triggers the issue.
* In Unity Editor one can even crank up a bit the **running speed multiplier** in the Character Controller prefab to reproduce this more easily (as we move faster along the railroad scene, loading and unloading the surrounding scenes)
* I cornered the issue to being specifically the “silent forget” of GLTF asset promises... since there are GLTF asset promises whose “silent forget” is called instead of the regular forget (the silent forget is a special way of “forgetting” the promise but letting it finish downloading because it blocks other promises that have that asset as a dependency, that flow is bugged in this scenario) in those cases they never leave the DownloadQueueHandler (and somehow they never finish downloading...) and so they block other relevant assets to be downloaded, thus leaving those scenes in a never-ending waiting state
* This issue happens in the web client as well as in the desktop client, so it’s a core bug.

**Comment by pravusjif** [comment]
More info on the findings in the related fix PR: https://github.com/decentraland/unity-renderer/pull/1925
