### ISSUE TITLE
Render error in unity render

### ISSUE THREAD

**Issue by jbasoft** [decentraland/unity-renderer#1912]
I used Mozilla dev version and try to visit wonderland and saw this error : 

`d.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[81355]:0x17914eb __ZN6il2cpp2vm5Array3NewEP11Il2CppClassm@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[81352]:0x1791451 _il2cpp_array_new@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[80083]:0x176c3e2 __Z19scripting_array_new17ScriptingClassPtrmm@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[7232]:0x2ecb3c __ZN15DownloadHandler20InternalGetByteArrayEPS_P21ScriptingExceptionPtr@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[29275]:0xce94e5 __Z43DownloadHandler_CUSTOM_InternalGetByteArrayP12Il2CppObject@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[29307]:0xcead99 _DownloadHandler_InternalGetByteArray_m1B4D723FA86D064B492ADBE3A9A13DD03209A4DC@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[76732]:0x16fb9d1 _DownloadHandlerBuffer_InternalGetData_m69989D8688328151EF518F3E705C019D02C045C8@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[76737]:0x16fba3d _DownloadHandlerBuffer_GetData_mAFE5BF2E12AE24B162769E9B736280A802E1A3AB@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[76736]:0x16fba32 __ZN16VirtFuncInvoker0IbE6InvokeEtP12Il2CppObject@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[29885]:0xd03aac _PbeParametersGenerator_GetPassword_m852F67432AF126975A396F0B8BFEB64FF9E009E1@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[41052]:0xf52aaf _U3CCreateHTTPRequestU3Ed__19_MoveNext_mF84C9ED74F6CFA575F885AFA2B9DDD93045C51AA@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[117111]:0x1d8cf1c __ZN21InterfaceFuncInvoker0IP52ByteU5BU5D_tDBBEB0E8362242FA7223000D978B0DD19D4B0726E6InvokeEtP11Il2CppClassP12Il2CppObject@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[29883]:0xd03a5c dynCall_iiii@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[124014]:0x1f391cb unityFramework/Module.dynCall_iiii@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.framework.js.br?v=1.0.27113-20220209083208.commit-f3e3c54:408:521711 invoke_iiii@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.framework.js.br?v=1.0.27113-20220209083208.commit-f3e3c54:408:356282 _U3CRunU3Ed__1_MoveNext_m05638FD333C7B4898FDD3B3708F3614F4830DD0E@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[79286]:0x174304a __ZN21InterfaceFuncInvoker0IP52ByteU5BU5D_tDBBEB0E8362242FA7223000D978B0DD19D4B0726E6InvokeEtP11Il2CppClassP12Il2CppObject@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[29883]:0xd03a5c _SetupCoroutine_InvokeMoveNext_m036E6EE8C2A4D2DAA957D5702F1A3CA51313F2C7@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[105467]:0x1b3cc63 __Z164RuntimeInvoker_FalseVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5_VoidU2A_tC7FFEB695C165BD92A8656A0260E9CBC93892D9A_Int32_tFDE5F8CD43D10453F6A2E0C77FE48C6CC7009046PFvvEPK10MethodInfoPvPS4_@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[86601]:0x1828b61 dynCall_iiiii@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[124025]:0x1f39323 unityFramework/Module.dynCall_iiiii@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.framework.js.br?v=1.0.27113-20220209083208.commit-f3e3c54:408:523098 invoke_iiiii@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.framework.js.br?v=1.0.27113-20220209083208.commit-f3e3c54:408:358897 __ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[81379]:0x1791c85 _il2cpp_runtime_invoke@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[80155]:0x176c724 __Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[5479]:0x25560c __ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[5477]:0x2552f8 __ZN9Coroutine14InvokeMoveNextEP21ScriptingExceptionPtr@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[9752]:0x3b456c __ZN9Coroutine3RunEPb@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[9749]:0x3b4241 __ZN9Coroutine17ContinueCoroutineEP6ObjectPv@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[9755]:0x3b4792 __ZN18DelayedCallManager6UpdateEi@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[10010]:0x3cd85f __ZZ23InitPlayerLoopCallbacksvEN49UpdateScriptRunDelayedDynamicFrameRateRegistrator7ForwardEv@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[12605]:0x4b96e7 __Z17ExecutePlayerLoopP22NativePlayerLoopSystem@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[12220]:0x493ef2 __Z17ExecutePlayerLoopP22NativePlayerLoopSystem@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[12220]:0x493f07 __Z10PlayerLoopv@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[12208]:0x493a44 __ZL8MainLoopv@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[12196]:0x491d27 dynCall_v@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.wasm.br?v=1.0.27113-20220209083208.commit-f3e3c54:wasm-function[124127]:0x1f39f33 unityFramework/Module.dynCall_v@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.framework.js.br?v=1.0.27113-20220209083208.commit-f3e3c54:408:535779 browserIterationFunc@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.framework.js.br?v=1.0.27113-20220209083208.commit-f3e3c54:408:182627 runIter@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.framework.js.br?v=1.0.27113-20220209083208.commit-f3e3c54:408:185700 Browser_mainLoop_runner@https://cdn.decentraland.org/@dcl/unity-renderer/1.0.27113-20220209083208.commit-f3e3c54/unity.framework.js.br?v=1.0.27113-2022020908`

screen of error : 
![Screenshot 2022-02-10 at 23-55-41 Decentraland](https://user-images.githubusercontent.com/6248024/153491950-2fc39e91-44c6-4e6a-bd7d-17ae535a9d9a.png)

**Comment by JorgeDecentraland** [comment]
This is a non issue based on the lack of memory allocation. There are some initiatives tackling this down. Thanks for reporting.
