### ISSUE TITLE
Add aspect ratio info on window resolutions in settings

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#1916]
Current resolutions displayed in the dropdown menu of the Explorer Desktop Setting, does not show the aspect ratio.

**Acceptance Criteria**
- [ ] Show aspect ratio next to the resolution in the resolution dropdown
- [ ] (Cancelled) Show whole numbers for frequencies (ie. 60 instead of 59.7)
- [ ] (Cancelled) Separate refresh frequency to its own dropdown
- [ ] Resolution dropdown will loose the frenquency, preventing multiplication of options
- [ ] Selecting one resolution will automatically choose the higher frequency available for that resoltution

**Comment by olavra** [comment]
After a conversation with @davidejensen we have reevaluated the scope of this task. Although its a normal practice in a lot of popular games (The Sims 4, WoW, Call of Duty), having a separate Frequency dropdown may be confusing. 
It's is also painfull to show 1 row pero resolution X frequency. Until we have some advanced settings, we will display only the list of available resolutions + aspect ration, and the system will automatically select the higher available Hz for the one selected.

**Comment by davidejensen** [comment]
Done
