### ISSUE TITLE
Resharper codestyle pre-commit hook should be triggered only by .cs files

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#194]
The initialization of the CodeCleanup CLI is slow (up to 15 secs on my machine). The CLI is effectively filtering to apply only the reformatting to C# files, but we could avoid these 15 seconds by ending the hook early if no .cs has been changed.

**Comment by olavra** [comment]
This is no longer needed as we want to move to Clang #964
