### ISSUE TITLE
Steaming video not playing on desktop 

### ISSUE THREAD

**Issue by TheShoes** [decentraland/unity-renderer#1966]
I am building a tool for DCL that uses unity renderer.  For it to work correctly I need to create a desktop build.  Everything works great and as expected.  Except...  When I run onto a property that is streaming video.  
when I do that i get the error:  
WebVideoPlayer: Platform not supported

Is there a way i can get the video to play right now?
Do i need to build a different video player that would take over?
If i need to build my own player where can i tap in to get the information for the stream?

I am sorry if this is not he right place for this.  Is there a discord or something with people that work on the unity-renderer that i can talk to instead of having to post this here.  I am in the decentraland discord but not sure if any devs of unity-renderer at there.  If there is a better place for questions like this please let me know.

**Comment by kuruk-mm** [comment]
> I am building a tool for DCL that uses unity renderer. For it to work correctly I need to create a desktop build. Everything works great and as expected. Except... When I run onto a property that is streaming video. when I do that i get the error: WebVideoPlayer: Platform not supported
> 
> Is there a way i can get the video to play right now? Do i need to build a different video player that would take over? If i need to build my own player where can i tap in to get the information for the stream?
> 
> I am sorry if this is not he right place for this. Is there a discord or something with people that work on the unity-renderer that i can talk to instead of having to post this here. I am in the decentraland discord but not sure if any devs of unity-renderer at there. If there is a better place for questions like this please let me know.

Hi!
The Video Streaming for Desktop, only works (for now) on Windows. And it was disabled because of some crash problems.

Right now, it's enabled, you can see the changes here: https://github.com/decentraland/explorer-desktop/pull/93

Please, let me know if you have more issues.

Thank you!

**Comment by kuruk-mm** [comment]
Closing. Please, reopen if you don't find a solution to what I answered.
