### ISSUE TITLE
30FPS cap is not working on desktop environments

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#1977]
When you enable 30FPS  cap on desktop, the number of max FPS still the same.

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/5436ac08-234e-4c83-a70d-2cd8375c32a5)

**Comment by pravusjif** [comment]
Closing this one as the original issue [was already in explorer-desktop](https://github.com/decentraland/explorer-desktop/issues/110)
