### ISSUE TITLE
Quests Log scroll bar moves very little while using middle mouse

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#201]
If you try to use the middle mouse wheel to scroll the Quest Log, it moves very little and its unusable, you end up having to click on the scroll bar.

**Comment by AjimenezDCL** [comment]
Use `DynamicScrollSensitivity`

**Comment by AjimenezDCL** [comment]
Update the QuestDetails and the QuestsTracker scrollviews accordingly.
