### ISSUE TITLE
ESC key shouldn't open the Menu anymore

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2017]
ESC key is current not working as intended when unlocking the mouse cursor, as it opens the Start Menu.
- unlock mouse
- close menus

This was validated with @olavra

**Comment by davidejensen** [comment]
It was easier than expected the close menu/close interaction behaviour was already working everywhere, I just had to remove the opening of explore on esc press

**Comment by esisl** [comment]
Colleagues!
Help with advice. How do I unlock the cursor from smart-item?
