### ISSUE TITLE
BIW: Search shows more or less items than it should

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#205]
- [x] Collection Search doesn't work: If you look for "candle" you will receive a few results. If you look for "light" you will received some items named "candle" that were not shown in the previous search.
- [x] If you look for the word 'bell' it will shown more items that it should, we should investigate this and see if that is correct
- [x] We should add no result icon if there is no result in the search bar
- [x] If we click on the search bar, the text "Search Assets" should disappear until the search filter is no longer active
- [x] We have a bug in the search that after some condition ( just play a while in the biw with the search)
The problem is that if you try to filter by name, not all objects will appear --> **Can't reproduce it!**
- [x] Bird nest icon / Elixir not correspond with the model --> **This is because we have 2 items with the same assetId (`8b0b4300ace100b7cbced6ca0b17d852aa12ee59438bae9f8f023619251dbec2`)** in https://builder-api.decentraland.io/v1/assetPacks
- [x] Sort Categories and Asset Packs by name desc

**Comment by olavra** [comment]
This seems to be fixed magimatically
