### ISSUE TITLE
Add infinite loop emotes like dancing

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#206]
As a player, I would like to play an avatar emote that will be reproducing in loop until I decide to move or play another emote, like dancing. This could be really beneficial for parties and live concerts.

Requested by Carl Fravel.

The emote will loop until the player moves his avatar or interacts with the environment. For example, a “heavy metal headbanging” animation.

This feature is documented in this [link](https://www.notion.so/decentraland/PRD-NFT-Emotes-M1-7a32110391f94ac884303712733602f8#693d62823b38459e880c1228ed50fb60).

**Comment by JorgeDecentraland** [comment]
This will be tackled down in #2119
