### ISSUE TITLE
AssetBundle Meshes are not being destroyed correctly after usage

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2082]
**Snapshot at 0,0 ( LOCAL_COMMS )**

![image](https://user-images.githubusercontent.com/7646450/160483387-635b68ba-8b18-44ff-8c5e-67ac527d0e27.png)

**Snapshot at 0,0 after teleporting to 100,100 and coming back ( LOCAL_COMMS )**

![image](https://user-images.githubusercontent.com/7646450/160483427-7c119c60-8e71-4861-ac2f-5aac706ab5ef.png)

**Comparison**

![image](https://user-images.githubusercontent.com/7646450/160482796-680e2a28-3ceb-43bb-b75c-70fd88edd4a1.png)

We can see that:
- The first instance is still alive. And has only 1 reference on the second snapshot.   (this is wrong!)
- The pooled object got deleted and created again
- A new instance was created

Here's more info on where is this Mesh referenced:
![image](https://user-images.githubusercontent.com/7646450/160484541-6611ab14-9f2b-4b4f-828b-0b1a3f7b2b24.png)

All of the occurrences I've found are references to meshes that were created by AssetBundles

**Comment by BrianAmadori** [comment]
I started debugging this and found that:
- It seems that all the resources that come from AB are leaking, not only meshes
- AssetBundle.Unload(true) is being called for the ABs, and this is correct. So this may be a bug coming from Unity?
