### ISSUE TITLE
UI sometimes doesn't finish loading and gets stuck if closed.

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2106]
![image](https://user-images.githubusercontent.com/7646450/161104585-5ecc9825-33ec-46f5-bf55-bb92ad2ef0c3.png)

Steps to reproduce this issue:

Press X to open the explorer and press X again while it's transitioning not too fast but not too slow, it might take a few tries but its very reproducible, this also can make the minimap disappear until you load the map again with M.

**Comment by Kinerius** [comment]
![image](https://user-images.githubusercontent.com/7646450/161105256-2fd51888-1aaa-4db5-9986-9eafec23d826.png)

**Comment by Kinerius** [comment]
![image](https://user-images.githubusercontent.com/7646450/161105283-bea45844-4e65-4edf-9e48-12f341fc2bcc.png)

**Comment by davidejensen** [comment]
I've did additional testing about the minimap disappearing in production and I found out how to reproduce it, if you open the explore with a shortcut to a panel different from the map and you close it with the same shortcut the minimap disappears. If you then open and close the map it reappears, will try to find a solution now
