### ISSUE TITLE
Scenes are loaded in memory when you go far and come back

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#2115]
If you go far away and go back the scenes stays in the hierarchy

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/9d6c9cc4-b86e-486f-b1b1-99d3a704e7ad)

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/d770106f-b033-4e5a-bb60-34ab91528171)

**Comment by Kinerius** [comment]
This is not happening right now.
