### ISSUE TITLE
Assets loading issues in Etheremon scene

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2122]
There are a couple of buildings near `79,47` that sometimes fully load and most of the time don't.

https://user-images.githubusercontent.com/1031741/161557881-64c2417e-7858-4330-b686-7e49ac74d952.mp4

It can happen in any realm, this happened in `dg` realm.

More info on that scene:
- it has some animations (the tentacle arms)
- uses 10+ materials
- has just under 19k faces
- deployed on a 2x2 scene

**Comment by Kinerius** [comment]
Reproduced this consistently and I think this scene is being created correctly and then moved by the sdk, im not sure about the blinking tho, I need to spend more time on this.

**Comment by pravusjif** [comment]
The scene creator confirmed that they are loading the meshes on initialization and the few ones that are loaded on proximity are not the building ones or the reported ones.

Since this is now working better (the buildings don't disappear anymore) I think we could close the issue and re-evaluate the flickering issue in the future

**Comment by davidejensen** [comment]
Alright, closing
