### ISSUE TITLE
Map chunks consumes a lot of memory space

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2160]
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/2d23db1c-4ef0-4d67-9a4e-c309788be231)

Each chunk of the map consists of a 7.9 MB Texture, given that we have a 7x7 map, the total memory usage is 387MB.

We should find a way to reduce this number.

**Comment by menduz** [comment]
The proposed solution goes like follows:

- Drop the current minimap implementation composed by NxM chunks of 256x256. Period, it was a hack and it is wrong.
- Create a minimap using a bitmap texture mode R8 of 350x350 (100KB total), one parcel per pixel. Use NEAREST filter or this bitmap. Use red channel bit 1 to specify if it is connected to the left, use red channel bit 2 if it is connected to the right, bit 3 to specify ROAD, bit 4 to specify estate.
- Create a shader that renders the map with any level of detail, on the GPU, using the information from the bits on the red channel
- Profit

That way, we stop wandering around with texture loading/storage problems in ram+vram

**Comment by JorgeDecentraland** [comment]
As profiled in #2177, memory space is being allocated in the GPU and therefore, not affecting memory issues.

**Comment by JorgeDecentraland** [comment]
As profiled in #2177, memory space is being allocated in the GPU and therefore, not affecting memory issues.

**Comment by JorgeDecentraland** [comment]
We will implement the shader as stated in the following ticket: #2198.

**Comment by JorgeDecentraland** [comment]
As described in #2177, memory is not affected by the minimap. The shader will be implemented as stated in #2198.

**Comment by AjimenezDCL** [comment]
https://codesandbox.io/s/github/menduz/test-dcl-map/tree/main/?file=/src/Shader.js
https://39kckw.csb.app/
