### ISSUE TITLE
Profiling - base memory usage of core systems

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2180]
Take a look at the consumption of our base systems (not scenes).

**Comment by AjimenezDCL** [comment]
There are some problems to evaluate memory usage on webGL. The heap increases on size by fixed amounts (not representing the real allocation) and Unity's API to profile memory usage only works on Editor or dev builds `Profiler.GetRuntimeMemorySizeLong`.

My findings have been the same as in the benchmark here:
https://www.notion.so/decentraland/RFC-Memory-scene-limits-30cacb40735d469b877814787d5dd80a#c5473f50ce464aa69f0ea960ffb2a828

Something we could implement for the future is a test scene that gradually allocates more and more memory (maybe by memory), we could measure how many textures are allocated before crashing to benchmark builds.
