### ISSUE TITLE
Implement infinite floor plane

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2182]
The grey floor plane will be replaced with a triplanar shader on top of a moving disk that creates an illusion on infinite floor. This floor will now have a green texture, with the grid lines on top

- [x] Add grid texture to floor disk
- [x] Make texture color match the grass from the floor
- [x] Fix grid movement bug

**Comment by olavra** [comment]
@ShibuyaMartin we talked about having a green grass floor texture with the grid lines on top of it ( a bit faded, maybe in a brighter green color)

**Comment by JuanSalice** [comment]
Initial implementation of texture with grid on floor plane.
![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/b167471e-df5d-4eb5-884d-dad04ae9498b)
![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/fa8f6e04-0dd2-4aa0-8b69-f239aa7a405e)
![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/d73d6800-9988-4e3d-9290-deaf49b82e6c)

**Comment by JuanSalice** [comment]
Changed the grid texture for one with matching grass color and fixed bug which caused the grid to move in an odd way.
![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/76547539-d7fb-4580-b528-aff55c7f09a8)
