### ISSUE TITLE
Replace Loading spiner texture by shader base animation

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2185]
Some UI elements require a loading spinner while they load their content. This spinner is currently a big texture sprite which requires lots of memory. This will be replaced with a shader based animation with a wheel mask.

**Acceptance criteria**
- [x] Replace all spiners with shader based spinner
- [ ] Remove unused sprite texture from pproject
- [x] Add anti-aliasing to shader
- [x] Add mask capability for shader
- [x] Allow the spinner to update during while loading.
- [x] Adjust spinner properties

**Comment by JuanSalice** [comment]
Unverified commits signed and PR merged. Loading wheel elements ready to be integrated into UI

**Comment by JuanSalice** [comment]
Created new branch for implementation. Upgraded loading wheel shader to add a background and a background color.
