### ISSUE TITLE
Implement chat and friends metrics

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2205]
### Metrics documentation
**Social metrics:** https://www.notion.so/decentraland/PRD-Social-Improvements-6956800acddc4a88a623060ebc94d0fa#0025308098984433990a2b8bd1d4e175

**Current implemented metrics**: https://www.notion.so/decentraland/1ab70141466e4a8d83ddd9cef6f7e414?v=f46b513dd3ee4620901fe1231feedf1a

### Metrics implemented in this PR
- [x] **PLAYER_MUTED**
  - Implemented in: `Unity`
  - Event Name: `user_muted`
  - Params:
    - `to`: "Wallet" | "Guest"

- [x] **PLAYER_UNMUTED**
  - Implemented in: `Unity`
  - Event Name: `user_unmuted`
  - Params:
    - `to`: "Wallet" | "Guest"

- [x] **VOICE_MESSAGE_STARTED_BY_FIRST_TIME**
  - Implemented in: `Unity`
  - Event Name: `voice_chat_start_recording`

- [x] **CHANNEL_MESSAGE_SENT**
  - Implemented in: Moved from `Kernel` to `Unity`
  - Event Name: `send_chat_message`
  - Params:
    - `from`: "Wallet" | "Guest"
    - `length`: Lenght of the sent message.
    - `channel`: Chat channel where the message was sent.

- [x] **DIRECT_MESSAGE_SENT**
  - Implemented in: Moved from `Kernel` to `Unity`
  - Event Name: `send_direct_message`
  - Params:
    - `from`: "Wallet" | "Guest"
    - `to`: "Wallet" | "Guest"
    - `length`: Lenght of the sent message.
    - `friends`: True if both users are friends.
    - `content_type`: "Text" | "Coords" (for future implementations) | "Link" (for future implementations)

- [x] **FRIEND_REQUEST_SENT**
  - Implemented in: Moved from `Kernel` to `Unity`
  - Event Name: `friend_request_sent`
  - Params:
    - `from`: "Wallet" | "Guest"
    - `to`: "Wallet" | "Guest"
    - `text_length`: Lenght of the message associated to the request (for future implementations).
    - `source`: "Passport" | "ProfileContextMenu" | "FriendsHUD"

- [x] **FRIEND_REQUEST_APPROVED**
  - Implemented in: Moved from `Kernel` to `Unity`
  - Event Name: `friend_request_approved`
  - Params:
    - `from`: "Wallet" | "Guest"
    - `to`: "Wallet" | "Guest"
    - `source`: "Passport" | "FriendsHUD"

- [x] **FRIEND_REQUEST_REJECTED**
  - Implemented in: Moved from `Kernel` to `Unity`
  - Event Name: `friend_request_rejected`
  - Params:
    - `from`: "Wallet" | "Guest"
    - `to`: "Wallet" | "Guest"
    - `source`: "Passport" | "FriendsHUD"

- [x] **FRIEND_REQUEST_CANCELLED**
  - Implemented in: Moved from `Kernel` to `Unity`
  - Event Name: `friend_request_cancelled`
  - Params:
    - `from`: "Wallet" | "Guest"
    - `to`: "Wallet" | "Guest"
    - `source`: "Passport" | "ProfileContextMenu" | "FriendsHUD"

- [x] **FRIEND_DELETED**
  - Implemented in: Moved from `Kernel` to `Unity`
  - Event Name: `friend_deleted`
  - Params:
    - `from`: "Wallet" | "Guest"
    - `to`: "Wallet" | "Guest"
    - `source`: "ProfileContextMenu" | "FriendsHUD"

- [x] **PASSPORT_OPENED**
  - Implemented in: `Unity`
  - Event Name: `passport_opened`

- [x] **PASSPORT_CLOSED**
  - Implemented in: `Unity`
  - Event Name: `passport_closed`
  - Params:
    - `time_spent`: Spent time (in seconds) from the last opening of the passport until it closing.

- [x] **PLAYER_BLOCKED**
  - Implemented in: `Unity`
  - Event Name: `user_blocked`
  - Params:
    - `friend`: True if the blocked user is a friend.
    - `source`: "Passport" | "ProfileContextMenu"

- [x] **PLAYER_UNBLOCKED**
  - Implemented in: `Unity`
  - Event Name: `user_unblocked`
  - Params:
    - `friend`: True if the unblocked user is a friend.
    - `source`: "Passport" | "ProfileContextMenu"

- [x] **PLAYER_REPORT**
  - Implemented in: `Unity`
  - Event Name: `player_report`
  - Params:
    - `issue_type`: To be used in future implementations.
    - `text_length`: Lenght of the message associated to the report (for future implementations).
    - `source`: "Passport" | "ProfileContextMenu"

- [x] **PLAYER_JOIN**
  - Implemented in: `Unity`
  - Event Name: `player_join`
  - Params:
    - `source`: "Passport" (for future implementations) | "Conversation"

- [x] **PLAY_EMOTE**
  - Implemented in: `Unity`
  - Event Name: `used_emote`
  - Params:
    - `id`: Id of the reproduced emote.
    - `name`: Name of the reproduced emote.
    - `rarity`: Rarity of the reproduced emote.
    - `isBase`: True if the emote is one of our base collection.
    - `source`: "EmotesWheel" | "Shortcut" | "Command"
    - `parcel_location`: Coords where the emote has been reproduced.

### Documentation
- [x] Update metrics documentation

**Comment by lorux0** [comment]
I need the metrics to be defined to be able to estimate and implement this issue. Also i need a report of the metrics that are already working on kernel side related to this feature

**Comment by JorgeDecentraland** [comment]
Metrics definition can be found in the following link: https://www.notion.so/decentraland/PRD-Social-Improvements-6956800acddc4a88a623060ebc94d0fa

**Comment by AjimenezDCL** [comment]
Don't forget to re-evaluate the friends metrics implemented in kernel here: decentraland/kernel#267

Since now we have to track the source of the action:  (from the passport UI or the friends UI) we cannot longer do it in kernel, move it to Unity.

**Comment by sandrade-dcl** [comment]
Metrics that we can currently send:
- Signal on mute a player
- Signal on voice message sent
- Signal on channel message sent
- Signal on direct message sent
- Signal on reload direct messages
- Signal on friend requests / accepted / rejected
- Signal on reload friends
- Signal on passport open
- Signal on passport close
- Signal on player blocked / unblocked
- Signal on player report
- Signal on player join
- Signal on player plays an emote

**Comment by sandrade-dcl** [comment]
Feature already implemented and merged in in https://github.com/decentraland/unity-renderer/pull/1994.

In the kernel side, the PR https://github.com/decentraland/kernel/pull/290 is waiting to be approved by the SDK team.
