### ISSUE TITLE
Update notification count on taskbar for chat & friends

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2207]
- [x] update the latest changes of `master` to the social bar redesign implementation the get the latest changes from the taskbar
- [x] the notification count for chats should be all unread private and public messages
- [x] the notification count for friends should be all the pending requests received
- [x] integrate the style proposed in [figma](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Module-%5Bwip%5D?node-id=604%3A13360)

**Comment by lorux0** [comment]
the update with the latest changes from master is going to be the one that will take most of the time
