### ISSUE TITLE
 Replace the current visible state behaviour of the chat list window 

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2208]
This change applies for the new [social bar redesign](https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/1756)

The unity-renderer branch is: `feat/chat-reskin`

When the application starts, kernel sends a message saying the chat should be visible by default, but the behaviour of the new redesign should be hidden by default and only be visible when you click the chat icon or press enter.
The reason why the ui is getting shown is `HUDController.ConfigureHUDElement` builds an initial configuration for `HUDElementID.WORLD_CHAT_WINDOW` which contains `config.visible = true`. This could be fix in two ways:
- make a kernel branch & replace the configuration sent to unity for `HUDElementID.WORLD_CHAT_WINDOW`
- replace in unity side the configuration sent for `HUDElementID.WORLD_CHAT_WINDOW`, for example: `configuration.visible = false;`

**Comment by lorux0** [comment]
it could be estimated with `1` but kernel adds uncertainty

**Comment by sandrade-dcl** [comment]
This is ready to be merged, but we will keep it blocked until the Social Bar features are merged.
