### ISSUE TITLE
Evaluate having more lossy messages

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2217]
The issue was detected when implementing an iSystem that keeps track of time passed. The timer kicks off when a video is played.  The video has an on timer burned into the video for testing. When FPS is below 30, the system timer is slower than actual time passed / than the video time played.

dt seems to match real time when FPS stays above 30 FPS, but the divergence increases overtime when FPS is below 30.

![Screen Shot 2022-04-26 at 9.52.16 AM.png](https://images.zenhubusercontent.com/622efee4c7d78e16ecd9ff40/9efa80b0-5343-49bb-9bee-33d81dbf866d)

As seen in the screenshot, a test was run that seems to confirm that the lag is in the UI, not the system. The time was logged to the console and was very close to the video. The UI appears to queue up every value it was ever told to render and renders them in order (loss-less).

**Comment by JorgeDecentraland** [comment]
According to @nearnshaw the root of the problem seems to be that all UI updates are loss-less, and probably we should discriminate between different types of UI updates.
Given that we’re planning to redo all of the UI for SDK7, this might be something to tackle then.
In the meantime, the workaround would be for creators to throttle their UI updates.

**Comment by AjimenezDCL** [comment]
Evaluate having more kind of lossy messages.

**Comment by AjimenezDCL** [comment]
We are gonna wait until ECS7 is done to assert if this is no longer necessary.
