### ISSUE TITLE
cap scene load radius to improve experience and avoid kernel crahes

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2220]
- [x] Web client capped to 4
- [ ] ~Desktop client capped to 5 (Evaluate if we can crash kernel with 5, otherwise cap to 4)~ Kernel also crashes with SLR 5 so we should keep it capped at 4

**Comment by davidejensen** [comment]
So on Web client the maximum slider value will be 4?
I'm wondering how to handle situations in which someone has 6 in the settings, currently if we go to a max of 4 and this person doesn't open the options panel il will stay at 6
