### ISSUE TITLE
Profiling: Seek source of hiccups while walking around the world

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#2227]
Hiccup Analisys: https://www.notion.so/decentraland/Hiccup-Analisis-4-5-22-633dfea45cdf487ba7a0878ef2fea5d0

**Comment by Kinerius** [comment]
For some reason after going down the waterfall, the graphic raycaster goes crazy for a moment
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/58de2b40-b145-44ae-acd8-493162a2506d)

**Comment by Kinerius** [comment]
We have a lot of hiccups when the garbage collector is triggered, so I've started reducing the amount of memory that is allocated on certain parts of the code here #2440

**Comment by Kinerius** [comment]
DownloadHandlers copy a lot of data every time we have to use them, unity provides an allocation free getter which returns a NativeArray<byte>, we might want to use some MemoryStream pools to avoid allocating every time we get the data, so we can safely copy NativeArray data to our pre-allocated array.
