### ISSUE TITLE
Implement blur effect for darkening mask on detail views

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2230]
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/8e4beb26-a084-4c44-98f7-8fb959c5596f)

**Comment by MichaelBitsakis** [comment]
Can find the UI section that requires the blur shader .

**Comment by MichaelBitsakis** [comment]
Found the emote info panel , inspecting on adding an extra panel to blur the ui behide that element.![emote_info_panel.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/5fc27d86-46ac-4213-a6fd-aa8d67d03cbf)

**Comment by MichaelBitsakis** [comment]
Analysing existing UI to come up with a place for the blur panel
So far i get different cameras setups , looking into this.

![emotes_sections.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/a06a39c1-0b60-4142-9e18-5f7aec3bc80c)
