### ISSUE TITLE
Spike: Research the usage of SVG images in the project

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#2250]
https://docs.unity3d.com/Packages/com.unity.vectorgraphics@2.0/manual/index.html

- [ ] Create an RFC

**Comment by JuanSalice** [comment]
Installed the vector graphics package into the project. Tested with svg shapes in UI and as a sprite.
![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/42bd0897-774d-414f-9e82-5def832be1d7)

**Comment by JuanSalice** [comment]
Created RFC:
https://www.notion.so/decentraland/RFC-Implementation-of-SVGs-ca5f2d07604c4ec489eea848ae88d337
