### ISSUE TITLE
Can't do emotes on platforms

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#2251]
When a player is standing still on a moving platform, they can't perform any emotes

You can see this clearly in genesis plaza
If you get on the floating train or the balloon that take you around the plaza, you can't do any emotes while the platforms move. My avatar is still doing only an idle animation. Once the platforms finish their path and stay still, then you can do emotes.

This would be especially good to have for parades, where players on moving mobiles can dance or wave at the crowds

**Comment by davidejensen** [comment]
I'm currently debugging this issue, the problem appears to be related to the handling of moving platform speed in the AvatarAnimatorLegacy script.

When blending different animations there is an exit condition that has different flags, one of those is `Math.Abs(bb.movementSpeed) > Mathf.Epsilon`
This should be zero considering the fact that the moving platforms speed is usually taken into consideration, digging more to understand better what's going on
