### ISSUE TITLE
Assemble list of things to investigate for Unity Native VM

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#227]
- [x] List of unknown things that we will require for the VM integration in the unity client, including port to mobile platforms.

**Comment by kuruk-mm** [comment]
Link del documento:
https://docs.google.com/document/d/1Ml1_tfT3NVW6XWQJq1Q6fKdlhOnl2hRrfSPD3Pig6CQ/edit?usp=sharing
