### ISSUE TITLE
Debug "The avatar could not be loaded correctly" error

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2285]
https://rollbar.com/decentraland/World/items/59519/?item_page=0&item_count=100&#instances

This error is usually in the top 5 (sometimes in the top 3) most recurrent errors.

Specifically there was a spike a this date:
![Screen Shot 2022-05-09 at 14.59.21.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/885690ba-a86b-4ea9-afa3-6ead198e07d9)

It's difficult to reproduce as it looks kind of random and looks like a problem when fetching the wearables from the catalysts, we could check the occurences in Rollbar and their callstack to see if there's any clue there, also we could check under which conditions we throw that error (not sure if in kernel or the client).

**Comment by xavi-dcl** [comment]
Not happening now in rollbar
