### ISSUE TITLE
Component count never reset in Preview Mode

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#2296]
Similar to this issue: https://github.com/decentraland/sdk/issues/296
... but with Components instead of Materials

<img width="496" alt="image" src="https://user-images.githubusercontent.com/12563266/167721389-58152708-7752-4276-969d-bc5736732582.png">

Example scene to see this problem: https://github.com/decentraland-scenes/conway-game-of-life

**Comment by m3taphysics** [comment]
@kwspgoliasz can you verify this - let us know if you need explanation of how to test.

**Comment by kwspgoliasz** [comment]
@m3taphysics Unfortunately, we are unable to test this case, as we are unable to access to the preview mode.

**Comment by xavi-dcl** [comment]
@nicorajcodcl please consider as task for Content Creators workstream
