### ISSUE TITLE
Add support for multiple actionButtons in OnClick and OnPointerDown components (SDK)

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#23]
In kernel's side we should add a new opions `type`, like the `OnPointerUUIDEventOptions`, and a new constructor overload in the 3 `OnPointerUUIDEvent` classes (detecting inside which options where used somehow)

more info in the one pager:
https://docs.google.com/document/d/1I2bcntDm3KIp2rO_J7cNIYQ94D2zrEG2-jY92wpfgBk/edit#heading=h.lsdbyfkkfvem

**Comment by olavra** [comment]
Too old, doesnt apply anymore
