### ISSUE TITLE
Can't move the player avatar on first mouse lock

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2307]
Reported problem with the avatar movement with the player clicks and locks the cursor for the first time, its not working.
- After clicking anywhere else or unlocking the cursor, it start working
- Moving the character without clicking anywhere for the first time allow movement

**Environment**
Happening in Mac with Google Chrome

**Evidence**
Video bigger than 15MB, request to @olavra 
Reported by @menduz

**Comment by davidejensen** [comment]
The problem appears to be related to the chat, when we click the first time the focus is put on the chat so walking commands are intercepted by it, in the branch with the chat improvements this doesn't happen, will close this issue as soon as that PR is merged

**Comment by davidejensen** [comment]
Solved with the latest release that included the social redesign, closing
