### ISSUE TITLE
Sometimes, a non friend person remains in the friend list

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2312]

**Comment by xavi-dcl** [comment]
@kwspgoliasz could you please verify and improve description?

**Comment by kwssbocian** [comment]
@xavi-dcl Cannot reproduce. During retesting no issue with incorrect or leftover entries in the friends list occurred

**Comment by xavi-dcl** [comment]
Closing as it cannot be reproduced.
