### ISSUE TITLE
Implement hologram when loading wearables

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2315]
Currently, when the avatars around you are loading, they appear invisible until they finish downloading all their wearables. 
Instead, we will have an avatar placeholder using the base mesh with a hologram shader, indicating that the avatar is still loading its features.

**Examples**
https://images.zenhubusercontent.com/337227404/e0624228-d20c-4684-957b-44fb9f18df15/1297167031.mp4

![uploads_1518131943047-Hologram_Exercise_Promo.gif](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/debb8bda-5684-4f09-9497-3ec37e019d7d)

**Acceptance criteria**
- [x] While loading wearables, player avatar will be represented with a genderless, no features body shape
- [x] This body shape will be rendered with an hologram shader
- [x] This body shape should gracefully fade in when appearing in the world
- [x] When all wearables are loaded, the hologram bodyshape should gracefully transition to the fully dressed avatar

**Technical Notes**
- LOD2 (billboards) wont make use of this system, so holograms will not be displayed in the background

**Comment by olavra** [comment]
@davidejensen @JuanSalice I've enhanced the description of the ticket for better clarification

**Comment by davidejensen** [comment]
Blocked due to 2 problems:
* The shader works only in 0,0 (probably related to the world/local changes in the shader)
* The armature provided in the prefab doesn't currently work with the animations of the avatar, hence it's not possible to move forward with the animation system

![Screenshot 2022-05-26 at 11.19.24.png](https://images.zenhubusercontent.com/61e566afd594605681c8aeb7/3d98e659-b43c-4d98-b5ed-0880c9876956)

Waiting for @JuanSalice 's feedback

**Comment by davidejensen** [comment]
Fixed the shader issue, still missing the animation part, I'm trying to schedule a call with Shibu to manage the problem of the armature

**Comment by davidejensen** [comment]
After the call with @olavra the following things have to be done:

- [ ] Verify and fix issues with render at a distance
- [ ] Avoid particles for far away avatars
- [ ] Show name on hologram
- [ ] Remove ring particles

**Comment by davidejensen** [comment]
Additional improvements:
- [ ] Have some variations in colours, a random value between bluish and greenish
- [ ] Change shader to avoid inner face rendering
- [ ] Increase shader variety

**Comment by JuanSalice** [comment]
- Fixed issue where the back faces of the mesh are also being rendered.

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/f4b43094-112d-4bb5-90df-7a45dae393d1)

- Created different variations of the shader with different effects.

https://images.zenhubusercontent.com/337227404/7c34ac4a-19c6-4a48-88e7-04075adbafac/v1.mp4

https://images.zenhubusercontent.com/337227404/97d457ac-5013-433c-b7ef-3e655a4f08e2/v2.mp4

https://images.zenhubusercontent.com/337227404/02b706bb-b959-49c3-a7b4-7dedd007a0d5/v3.mp4

https://images.zenhubusercontent.com/337227404/54fd785f-48cb-4295-afd9-1fd08f8debbf/v4.mp4

**Comment by JuanSalice** [comment]
- Fixed an issue where the hologram didn't fade in when instantiated.

**Comment by JuanSalice** [comment]
- Found an issue with the new camera configuration. The skybox is not being rendered causing white glowing artifacts.
- Experimented different approaches to solve the issue with no succes.
