### ISSUE TITLE
Block "Explore & Play" and "Tutorial" buttons from the taskbar while in BiW

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#233]
Players can activate the "Explore & Play" and "Tutorial" functionality while editing a land, which can result in unsaved or unpublished changes.

This funciton should be deactivated while editing a land, greying out the icon.

![image](https://user-images.githubusercontent.com/64659061/116407606-3838a680-a832-11eb-9ec5-0595e1e6f381.png)

**Comment by Suduck** [comment]
We should take into account that /teleport should be disable too!
