### ISSUE TITLE
Cleanup feature flags

### ISSUE THREAD

**Issue by menduz** [decentraland/unity-renderer#2331]
There are many feature flags that haven't been changed for months. Like the new skybox.

With the objective of:
- Helping the daily OPS reducing the number of possible combinations
- Reduce feature flag calculation time, metrics and bandwidth
- Remove `if`s in many places in the code
- And to be less dependent on the feature flags system

I propose to start eliminating feature flags that have been turned on for more than a month and are not operational kill-switches (like a load balancing configuration)

Please edit this checklist adding all the feature flags to be removed. Convert every check elem of the list into an issue or PR to track progress.
- [x] explorev2
- [x] avatars_lods
- [x] procedural_skybox
- [ ] rollout-unity-renderer-version
- [ ] stream ???
- [x] cull-opaque-heuristic
- [x] avatar_skins
- [x] emotes_customization
- [x] gpu_only_meshes

![Screen Shot 2022-05-19 at 10 57 33](https://user-images.githubusercontent.com/260114/169311109-9f3026b6-0638-4408-a277-b3cf05581ec1.png)

**Comment by pravusjif** [comment]
FYI these 2 **shouldn't be removed** as are always used for debugging:
- `asset_bundles`
- `wearable_asset_bundles`

**Comment by dalkia** [comment]
Conclusions from flag analysis between code and Unleash:

- `explorev2`:  Flag was not found in the code. Probably have been eliminated already
- `rollout-unity-renderer-version`:  Flag was not found in the code. Probably have been eliminated already
- `stream`:  Flag was not found in the code. Probably have been eliminated already
- `GPU_ONLY_MESHES`: Present in code; but not present in Unleash. Should it be eliminated from code?
- `builder-dev`: Off in Unleash for over a month. Should it be eliminated from code?
- `procedural_skybox`: Flag is not there anymore, but there is a `useDynamicSkybox` attribute still in code. Should it be eliminated?
- `friends_by_online_status `: Kill-switch, so left untouched.
- `wearable_asset_bundles `: Kill-switch, so left untouched.
- `third_party_collections`: Kill-switch, so left untouched.
- `profiler_metrics`: On, but it only has two weeks. Left untouched
