### ISSUE TITLE
Spike: Render Decentraland map in renderer

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2353]
We currently load our map by downloading chunks of images from the content server, and we do not have control over the colors or materials that each parcel is represented.

In order to avoid the high traffic of textures /bandwidth usage and to be able to control the aesthetic rendering of the map, we will create a renderer in world with feed information.

**Tracking**
- [x] Define format and information of the image and where it will be generated (talk with @menduz)
  - [ ] Generate the image in a server to be consumed by the renderer (depends on the avobe)
- [x] Define color schemas to render the map for the shader parameters
- [x] Adapt shader and render the map in unity
- [x] Apply zoom controls and hover information to the shader
- [ ] Render PoIs on top of the new map
- [x] Render single tiles overlay in shader
- [x] Render overlay that paints complete estates
  - [ ] Add special effect on overlay
- [x] Render outlines of districts subdivisions 
  - [x] Render some outlines in a different color
- [ ] Profit

- Added : 

- [ ] Further optimization of the shader
- [ ] Fix the gradient effect 

**Acceptance Criteria**
- Create a system to feed parcel information
- Create a renderer that use the parcel information to render the slots
- Define color schemes for each type of parcel

**Technical Notes**
This demo was already implemented by @menduz using a texture of 512x512 as a input of the parcel information.
https://codesandbox.io/s/github/menduz/test-dcl-map/tree/main/?file=/src/Shader.js

**Comment by davidejensen** [comment]
As a next step to understand the best solutions we will analyze the demo made by Mendez, we will analyze how the catalysts generate the snapshots we use of the map and form some possible directions

**Comment by JuanSalice** [comment]
Experimenting with different shader features and effects using a single texture.
Also testing how to create a completely new texture from shader using an hlsl script. 

https://images.zenhubusercontent.com/337227404/6130f24a-0e6c-459b-9917-57aacef9b7bf/map_rendering_test.mp4

**Comment by JuanSalice** [comment]
Added a grid to the map, that aligns with each pixel of the original image no matter the scale of it.
Added a color for the grid.
Added an image the same size as the original map to determine witch pixels of the map will render the grid.

https://images.zenhubusercontent.com/337227404/7d58cb9f-12b9-4b29-bd20-48b16853a693/map_grid.mp4

**Comment by JuanSalice** [comment]
Added custom HLSL node with original map functionality.
Now the output of the new node is used as a base for all the effects applied to the map
![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/2b9d934a-fb29-4561-9fa1-aab8cc51c9e8)

https://images.zenhubusercontent.com/337227404/a4963aee-7dc1-4968-83df-aa61cff64222/custom_map.mp4

**Comment by JuanSalice** [comment]
- Modifications to HLSL script to better adapt it to shader graph.
- Added custom colors to the grid and the pointer, and a thickness value to the grid.
- Now the map is render using the UV of the object. This allows the map to be used in 3D objects, but if the object is stretched, the map will also be distorted.
https://images.zenhubusercontent.com/337227404/002abe72-fcf6-4cfb-a3df-ee73b9d37a8b/new_map_v2.mp4

**Comment by JuanSalice** [comment]
- Created a version of the shader that is responsive to the screen resolution, adapting the mouse position and the zoom to different resolutions.
- Normalized mouse position values.
https://images.zenhubusercontent.com/337227404/be5d475e-6d93-4130-827d-2f66dac1fef9/new_map_v3.mp4

**Comment by davidejensen** [comment]
At the following link a dummy version of the new map can be checked and tested:  
https://play.decentraland.zone/?renderer-branch=feat/Map-Render
It currently has just the map show in the map tab, with move and zoom functionality.

There are a multitude of tasks that will be required when we decide to procede with the update of the map, also because the old map system would require a big refactor, here's a list of the most important ones:

- [ ] Integrate POIs with the new map
- [ ] Integrate the parcel highlight and click functionality on the new map
- [ ] Create a new minimap system (that will be different from the old minimap)
- [ ] Integrate all the map functionalities like automatic re-centering based on player position, other player icons, ...

Those behaviors cannot be adapted from the existing map but need to be re-written from scratch and will take a considerably higher amount of time than the estimated initial one in order to create a new solid stucture for the map system. I would suggest treating this as different tickets for each functionality

**Comment by JuanSalice** [comment]
- New version of the map shader which can be adapted to the current's map behavior easier.
- Optimized hlsl script for new shader.

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/7843112b-cc5a-4cf3-a6fa-a69107faff16 )

**Comment by JuanSalice** [comment]
- Changes in map shader to be able to adapt to screeen size.
- Added the ability to mask the map shader.
https://images.zenhubusercontent.com/337227404/71b5d6dc-e978-42a8-884c-91d9c68b570b/map_v3.mp4

**Comment by JuanSalice** [comment]
- Found issue when rendering the map. Can be solved by changing the canvas to Camera Space, but still investigating for alternative solution.

**Comment by JuanSalice** [comment]
- Created 2 hlsl scripts to optimize common behaviours in shader graph, those being getting the aspect ratio of an input UV, and scale textures and mask from its center.
- Added a screen space mask to the map shader, which can be customized to be used as the minimap.
- Modified the mask so the map image can be moved without moving the mask of it's screen position.

https://images.zenhubusercontent.com/337227404/dcea97d6-34a5-4946-8d1f-2a9588c16dbd/maskeablemap.mp4

**Comment by JuanSalice** [comment]
- Research and testing of a flood fill implementation for the highlights of the parcels when the mouse is over them.

**Comment by JuanSalice** [comment]
- Changes to the source image are needed in order to add custom shapes to the selection overlay for parcels and states.

**Comment by JuanSalice** [comment]
- Small modification to ID texture generator.
- Used the texture to create the overlay of the current map.

https://images.zenhubusercontent.com/337227404/eece62bf-5eb0-4d6c-b952-1617c453f05f/mapoverlay.mp4

**Comment by JuanSalice** [comment]
- Added outline to shapes that previously didn't have one by using the Estates ID.

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/6a3e6a51-e037-48c4-99e1-4c5cd97c8412)

**Comment by JuanSalice** [comment]
- Added pointer for single parcels and streets
- Created a material called M_MapMaskeable which contain the shader with the ability to be masked by UI elements
- Shader cleanup and optimization

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/c3c84f0d-a8c8-4a51-a323-f7dadd1d50e6)

**Comment by JuanSalice** [comment]
- Remove some unused values from the shader.
- Added color change for grid over districts.

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/adac6c2e-7d9b-425a-9247-d4901d854727)

**Comment by JuanSalice** [comment]
- Fixed inconsistencies found on the grid thickness
- Grid color alpha now controls the visibility of the full grid

https://images.zenhubusercontent.com/337227404/e67bedbf-9446-4e49-995a-8810433c046a/mapv5.mp4

**Comment by JuanSalice** [comment]
- Added highlight effect to map shader

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/cc26ae56-0637-4f22-a1aa-15357f9583b9)

**Comment by JuanSalice** [comment]
- Added correct gradient colors.
- Gradient center now aligns with mouse position.

**Comment by JuanSalice** [comment]
- Added light grid to all parcels

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/153b9908-f4fe-4f9f-92d6-c30439395e4e)

**Comment by JuanSalice** [comment]
Initial implementation of map shader.

https://images.zenhubusercontent.com/337227404/dda1cb62-956e-4d33-be24-fe8c94a38658/mapimplementation_1.mp4

**Comment by JuanSalice** [comment]
- Advancements in the map implementation.
- Fixed a bug in the highlight gradient.
- Values adjustments.

https://images.zenhubusercontent.com/337227404/5b8fa156-033d-480d-a082-9ad38d19bf11/map.mp4

**Comment by JuanSalice** [comment]
- Migrated latest shader changes to implementation branch

**Comment by MichaelBitsakis** [comment]
Infinite Floor To Skybox Blender Part 1

Model - Uvs - Procedurals : Houdini

Shader : CG - Shaderlab

State : WIP (need to add transparency to the shader for even seamless blending.

Although it blends great from the first attempt , i will add transparency to the shader as well so i can drag it a bit higher and blend seamlessly with the trees etc.

https://images.zenhubusercontent.com/337227404/63f1e283-a81e-41de-9c5b-062cd3659ebd/infinitefloorblender_1.m4v

**Comment by MichaelBitsakis** [comment]
- Optimized the shader further
- Fixing the gradient effect

**Comment by olavra** [comment]
This ticket has been refreshed and reallocated to #3666
