### ISSUE TITLE
Video streaming is ONLY working on Desktop

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#2358]
A developer is having issue with video streaming. He said the screen works in desktop client (image 2) but it doesn't work in explorer (image 1).

**Image1:**
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/adb2a908-2aa2-4047-8813-c4534a2d6668)

**Image 2:**
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/2b270fbb-ae48-4d6e-866e-941651127b4f)

Reported by Waan Chin here: https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1653552811734129

### Steps to reproduce
1. Enter the world from the web version.
2. Go to 43,-3 coords.
3. Notice the video screen is not showing anything when it should.

(If you repeat the same steps in Desktop, it works)

### Debugging from browser
We see this CORS error in the browser console:
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/47afa908-c11a-4e14-bfc1-4c44c62ee46d)

### Debugging from Unity editor
We see this error in the console when we are near of the video streaming screen:
```
WebVideoPlayer: Platform not supported
UnityEngine.Debug:LogError (object)
DCL.Components.Video.Plugin.WebVideoPlayer:Update () (at Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.cs:44)
DCL.Components.DCLVideoTexture:UpdateVideoTexture () (at Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs:202)
DCL.Components.DCLVideoTexture/<OnUpdate>d__22:MoveNext () (at Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs:178)
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
CoroutineStarter:Start (System.Collections.IEnumerator) (at Assets/Scripts/MainScripts/DCL/Helpers/CoroutineHelpers/CoroutineStarter.cs:21)
DCL.Components.DCLVideoTexture:Initialize (DCL.Components.DCLVideoClip) (at Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs:161)
DCL.Components.DCLVideoTexture/<ApplyChanges>d__19:MoveNext () (at Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs:102)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
```

**Comment by pravusjif** [comment]
This issue is due to a CORS problem (desktop doesn't have CORS problem, the browse does), so it's not a problem in the client. The scene creator should change their streaming server CORS policy to make this work.
