### ISSUE TITLE
All chat commands should also work in private chat

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#2361]
As an example, when we put the `/goto <any cords>` command in a private chat, the message is sent like another normal message and the teleport is not working when it should.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/ed7c6636-3d1f-42a8-9261-41787053b0ba)

**Comment by xavi-dcl** [comment]
Dup with #3210
