### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2392]
https://www.notion.so/decentraland/PRD-Channels-open-for-comments-1a51033cc6134889a4d863d0bd1cb607

https://www.notion.so/decentraland/PRD-Chat-Notifications-open-for-comments-5ab89b9ab5794e1aa8e7759ad3163c1c

**Comment by xavi-dcl** [comment]
Closing this Channels Epic since all user stories are completed (note: we have other Channels epics with open tickets).
