### ISSUE TITLE
Add search view to join channels

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2394]
Players need a simple way to know which channels are available, and how many players are connected to them.

![ChannelsBrowser.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/d6d7de6c-cd6b-46c7-beee-56099f0e43a6)

[Documentation Link ](https://www.notion.so/decentraland/PRD-Channels-open-for-comments-1a51033cc6134889a4d863d0bd1cb607#55a64d9532914d1b9ba49e414344b522)

**Acceptance Criteria**
- A new button will be added to the conversation panel, to search for a channel. 
- Clicking on it, will show a list of all the channel containing at least 1 player. 
- A spinner will be show every time the panel is loading channels
- The list will be sorted by number of players, and will have the structure `#channel-name (34)`
- The player will also be able to search the channel by name in the search bar.
- If the name of the channel is not found, it will add a button to create a channel. 
- Clicking on the Join button (appears while hovering) on any of these channels will automatically join in and add it to the conversations panel.

**Technical Notes**
- The list of channels may be too be to retrieve an render, should consider a limit in the number of results, and a button to continue loading more.

**Comment by sandrade-dcl** [comment]
### Technical tasks
- [ ] Add the new SEARCH BUTTON in the UI.
   - [ ] Implement the sending of the **[GET_CHANNELS] message to Kernel** (maybe it could be done through an API?) to order the searching.
   - [ ] Implement the reception of the **[SEARCHED_CHANNELS] message from Kernel** (maybe it could be done through an API?) to list them in the search list UI.
- [ ] Implement the SEARCHBAR for channels in the UI.
   - [ ] Implement the sending of the **[GET_CHANNELS_BY_TEXT] message to Kernel** (maybe it could be done through an API?) to order the searching.
   - [ ] Implement the reception of the **[SEARCHED_CHANNELS] message from Kernel** (maybe it could be done through an API?) to list them in the search list UI.
   - [ ] Add the CREATE CHANNEL button for the cases when the search returns nothing.
- [ ] Implement the sorting of the channels.
- [ ] Implement the JOIN button in each search result row.

**Comment by sandrade-dcl** [comment]
We have defined the data flow here: https://www.notion.so/decentraland/RFC-Technical-proposal-for-Channels-8fdbd914091f4d2194424caf9e3e096b#2ca555395f264ce0bcf4af86cf8c1f73
