### ISSUE TITLE
Add ability to create a channel

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2395]
In order to create a channel, players will be able to use the `/join name-of-channel` command in the chat input or click on the `Create channel` button from the Chat panel or the search view. 

If the channel does not exist, it will automatically created. Otherwise, the player will join the ongoing conversation.

Something similar happens while you search a channel in the [Search panel](https://www.notion.so/PRD-Channels-open-for-comments-1a51033cc6134889a4d863d0bd1cb607). Entering the name of the channel in the input, if the channel does not exist, it will prompt the players to click and create it. 
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/bda301be-d99e-447a-aa08-9a462139a3ad)

[Documentation Link](https://www.notion.so/decentraland/PRD-Channels-open-for-comments-1a51033cc6134889a4d863d0bd1cb607#e4bc6bcc59234e6a904c825ff83b85c0)

**Acceptance Criteria**
- Clicking on the add channel button, in the chat view, the search results, or the search header, promts the Create a channel dialog
- This dialog has an input to introduce the name
- If the name of the channel already exists (have more than 0 users) it will notify the player and propose to join instead
- If the channel is created, the channel conversation will open with only you in it
- At the start of the conversation in the new channel, the message "This is the start of the #name-of-channel. Invite others to join by quoting the channel name in other chats or include it as part of your bio." will be prompt.

**Technical Notes**
`#nearby` channel is a fake channel automatically created by the system with the people around, that means, this channel name cannot be created, left or joined and need to be restricted.
</aside>

**Comment by sandrade-dcl** [comment]
### Technical tasks
- [ ] Add CREATE CHANNEL button in the UI.
