### ISSUE TITLE
Add ability to join a public channel

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2396]
Players can join an existing channel by using the `/join name-of-channel` command.

[Documentation Link](https://www.notion.so/decentraland/PRD-Channels-open-for-comments-1a51033cc6134889a4d863d0bd1cb607#5a57ff652881423ba861cff30d827d26)

**Acceptance Criteria**
- Players are able to join a channel using the /join command
- If the channel does not exists, its automatically created
- Joining a conversation, automatically opens it
- Joined channels appear on the Channels section inside the Chat panel
- Channels will be sorted by name in this section

**Comment by sandrade-dcl** [comment]
### Technical tasks
- [ ] Implement the `/join` command. It should send the corresponding **message to Kernel** for join or create the channel.
- [ ] Implement the reception of the corresponding creation/joinning **message from Kernel** to open the conversation in the UI.
- [ ] Implement the addition of the created/joined channel in the Channels section of the Chat panel.
- [ ] Implement the sorting of the channels list.

**Comment by lorux0** [comment]
We have defined the data flow here: https://www.notion.so/decentraland/RFC-Technical-proposal-for-Channels-8fdbd914091f4d2194424caf9e3e096b#d295ca8a453b465e9a0b60125992e501
