### ISSUE TITLE
Manage the unread messages notifications

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2398]
As soon as the player start the session, we should display how many unread notifications the user has for each channel. Once the user enter in each chat, we should clear the corresponding notifications for that channel.

[Documentation Link](https://www.notion.so/decentraland/RFC-Technical-proposal-for-Channels-8fdbd914091f4d2194424caf9e3e096b#3484fbba5ab94f0586ebf4e972f270ae)

**Acceptance Criteria**
- At the start of the session, display how many unread chat notifications the user has including channels.
- If the user opens a channel window, clear the unread notifications count.
- During the session, new incoming messages should increment the notifications counter only when the channel window is not opened.

**Comment by sandrade-dcl** [comment]
### Technical tasks
- [ ] Implement the reception of the corresponding message from kernel that will give us the list of channels where we're currently joined.

**Comment by sandrade-dcl** [comment]
We have defined the data flow here:
- https://www.notion.so/decentraland/RFC-Technical-proposal-for-Channels-8fdbd914091f4d2194424caf9e3e096b#3484fbba5ab94f0586ebf4e972f270ae
- https://www.notion.so/decentraland/RFC-Technical-proposal-for-Channels-8fdbd914091f4d2194424caf9e3e096b#f50df0da5c994dffadf8dc77b58fa5f6

**Comment by lorux0** [comment]
its only missing the #nearby channel notifications
