### ISSUE TITLE
Implement notifications area

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2399]
The notification area will replace the space of the `#nearby` conversation.
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/856ddff4-4fe4-46a5-8563-d038f3c110f0)

[Documentation Link](https://www.notion.so/decentraland/PRD-Chat-Notifications-open-for-comments-5ab89b9ab5794e1aa8e7759ad3163c1c#2a9ad340ca0e4986ba0912c2d699fcb0)

**Acceptance Criteria.**

- [x]  In this block of limited height, notifications from channels and private conversations, which the player has marked as "active notifications", will be accumulated.
- [x]  Clicking on a notification will open the corresponding conversation.
- [x]  Depending on the source (channel or private message) it will display the following information:
-- Channel: channel name, username, message preview, time.
-- Private: avatar snapshot, player name, message preview, time.
- [x]  Notifications will have a fixed minimum and maximum width, so the text overflow will be delimited with `...`.
- [x]  New notifications will appear from bottom to top, showing a maximum total of 5 entries.
- [x]  The notification area can be scrolled to show up to 30 previous notifications, either using mouse scroll or drag and drop. - Those above 30 will be destroyed. 
- [x]  A new entry in the notification area will force the scroll down if you are not interacting with the panel (mouse over).
- [x]  If there are no new messages, the notification area will fade out after 8 seconds. 
- [x]  If a new notification comes in, it will reappear. 
- [x]  Hovering the mouse over the notification area will also make it appear.

**UX Notes**
- Animation of fade in / fade out, and new notifications needs to be very polished and iterated during development

**Comment by sandrade-dcl** [comment]
### Technical tasks
#### Common
- [ ] Create the `ChatNotificationMessageComponentView` UI Component.
- [ ] Implement the BELL button (for enabling/disabling notifications) in the conversation window.
- [ ] Implement the `ChatNotificationsController`: It would implement the core flow for receiving and manage all the notifications.

#### For the **main Notifications Viewer** (when NO chat window is open):
- [ ] Create the `ChatNotificationsMainComponentView` UI Component.
- [ ] Implement the `ChatNotificationsMainController`: It would implement the specific behaviour for managing the notifications in the main notifications viewer.

#### For the simplified Notifications Viewer (when a chat window is open):
- [ ] Create the `ChatNotificationsSimplifiedComponentView` UI Component.
- [ ] Implement the `ChatNotificationsSimplifiedController`: It would implement the specific behaviour for managing the notifications in the simplified notifications viewer.

**Comment by sandrade-dcl** [comment]
This task will be divided in 2:
- Views implementation
- Business logic implementation

**Comment by davidejensen** [comment]
Refinement:

- [ ] Default image for player
- [ ] Slide in new notification animation
- [ ] Mask for the top message
- [ ] When closing panel reset notification fadeout routine
- [ ] Emotes shouldn't reset notifications
- [ ] Scroll to bottom after fade out
- [ ] Longer fade out (slow)
- [ ] Faster fade in
- [ ] Circle in profile pic background

**Comment by davidejensen** [comment]
Blocking while waiting for Nico's feedback and Romi's asset

**Comment by davidejensen** [comment]
Showcase of the current used animation, will need to talk with Alvaro to see in which direction to go with it

https://user-images.githubusercontent.com/4254522/180749506-82d8d4e4-1765-4ef3-8798-b6f238da788d.mov

**Comment by RominaMarchetti** [comment]
In the last review meeting we decided to add some UI component in the notification area to add some context (background + title and scroll bar reference when the player is interacting with the notification area). 

[Here](https://www.figma.com/proto/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?page-id=2947%3A17440&node-id=2947%3A17714&viewport=675%2C406%2C0.26&scaling=contain&starting-point-node-id=2947%3A17714) is a prototype to clarify the different behaviour between this elements and the notification.

- When the player hovers the notification area the contextual UI will appear plus the notifications history.
- When the mouse leaves the area the contextual UI immediately disappears while the notifications do it later.
