### ISSUE TITLE
Some scenes are not loading in prod

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#240]
For the last couple of days the Discord user "Doug | NFTWorld.io" has been reporting a loding issue with his scenes:

83,-18
-65,-108
-39,-37
-139,-109

Apparently the same 1-parcel scene has been deployed to those different coords, and neither of them loads in production.

A bit of debuging from Unity Editor shows that the client is left waiting for the init messages of that scene (the surrounding scenes load just fine), so it's a problem happening in kernel's scene initialization flow.

**Comment by pravusjif** [comment]
Debugging shows that the involved scenes:
- Don't have any `game.js` or similar in their mappings (even though the scene.json points at a "bin/game.js" as the main file)
- Their worker is started but the `SceneRuntime` / `WebWorkerScene` is never started
- Their `runCode()` to eval the scene's code is never called

**Comment by olavra** [comment]
Pending of receiving the scene from the content creator

**Comment by pravusjif** [comment]
Today I've been debugging using the scene locally and testing its deployment on one of my lands.

Looking closer at its files I see some strange things:
- main culprit: the `.dclignore` file has been modified and the `bin/` directory has been added, that's why the scene isn't deploying its `bin/game.js` file.
- The changes in `tsconfig.json` mess up the land image in the deployment link webpage
- There are 2 things pointing at the fact that the original scene was created with the builder even though the owner says everything has been built with the SDK and not the builder: scene.json's `source` element and the `builder.json` file existence

I'll notify the creator of these findings, delete the scene to avoid leaking its content, and also create a fresh scene with the owner's code to give him an example of a more cleaned up scene instead of this strange non-builder-scene with builder stuff...

**Comment by pravusjif** [comment]
The creator confirmed that the scene loading was fixed so I'll proceed to delete the scene on my side and close this issue.
