### ISSUE TITLE
Enable / Disable channel notifications

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2400]
Depending on the number of channels and private conversations in which the player is involved, the number of notifications can grow exponentially. For this, the player should be given the freedom to deactivate those conversations in which they still want to be involved but do not want them to generate noise.

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/69f07b52-649b-495b-8044-77879b295b49)

[Documentation Link](https://www.notion.so/decentraland/PRD-Chat-Notifications-open-for-comments-5ab89b9ab5794e1aa8e7759ad3163c1c#e1fb67e60c274e78b36fef33a847a96e)

**Acceptance Criteria**
- The player will be able to deactivate notifications by entering the channel or private conversation by clicking on the **notification bell**. This will toggle between active and inactive notifications.
- All conversations by default will have active notifications.
- Those channels that have notifications disabled, will show an icon in the chat menu, and will not affect the notification counter of the chat icon, nor will they appear in the notifications area.

**Comment by sandrade-dcl** [comment]
### Technical tasks
- [ ] Implement the BELL button (for enabling/disabling notifications) in the conversation window.
- [ ] Modify the chat entry in the Chat list for taking into account when the notifications for this channel is enabled or not.
- [ ] Modify the flow of the main notifications controller for including or not the notifications depending on if they are enabled or not.

**Comment by sandrade-dcl** [comment]
We have defined the data flow here: https://www.notion.so/decentraland/RFC-Technical-proposal-for-Channels-8fdbd914091f4d2194424caf9e3e096b#a8eadd6cab5a49b89ae3a2a05c099664

**Comment by lorux0** [comment]
The issue remains blocked until [#2735](https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/2735) is solved, because of prefab conflicts.
