### ISSUE TITLE
Implement top chat notifications

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2401]
The chat, friends and voice chat panels compete for the same space as the notifications. When these are open, the notification area moves up and narrows in size showing only one entry.

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/c320ed0e-ca15-40a4-aaf1-fd0974770ff2)

[Documentation Link](https://www.notion.so/decentraland/PRD-Chat-Notifications-open-for-comments-5ab89b9ab5794e1aa8e7759ad3163c1c#1a9a4fa60b7a4de89967eb24a544f84f)

**Acceptance Criteria**
- These notifications have a fixed width, unlike the others. 
- They will also include the number of unread messages from each conversation.
- If the entry comes from a private chat the avatar snapshot, now larger in size, is centered to the left with respect to the name and message.
- You will not receive notifications about currently open conversation (if any).

**Notes**
There is a pending decision on what is going to happen when several notificacions are popping at the same time, we need to iterate on development

**Comment by sandrade-dcl** [comment]
### Technical tasks
- [ ] Create the `ChatNotificationsSimplifiedComponentView` UI Component.
- [ ] Implement the `ChatNotificationsSimplifiedController`: It would implement the specific behaviour for managing the notifications in the simplified notifications viewer and will use the main notifications controller already implemented in previous tasks.
- [ ] Implement the tests coverage.

**Comment by sandrade-dcl** [comment]
This task will be divided in 2:

- Views implementation
- Business logic implementation

**Comment by davidejensen** [comment]
Merged the first iteration of the top chat notification in the channels branch, will open new issues with the different refinements and iteration to keep track of the different estimates and evolutions
