### ISSUE TITLE
Every time I open the emotes wheel 20 errors appear in the console

### ISSUE THREAD

**Issue by menduz** [decentraland/unity-renderer#2411]
![Screen Shot 2022-06-05 at 02 34 55](https://user-images.githubusercontent.com/260114/172036811-b9e68cf4-0465-4ca7-b22c-541d5c0ca2d9.png)

**Comment by davidejensen** [comment]
I'm tagging @JuanSalice because I think the error is related to the rainbow outline shader, I'll take a look and update here with the findings

**Comment by xavi-dcl** [comment]
@kwspgoliasz @kwssbocian could you please see if this still happens?

**Comment by kwssbocian** [comment]
@xavi-dcl Issue still occurs. I've actually raised a separate ticket for it a few days ago: #3748

**Comment by aixaCode** [comment]
Closing as duplicate #3748
