### ISSUE TITLE
A/B Test for Texture Compression

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#2450]
Validate the need of using Texture Compression in the client for textures that are gonna be send into the GPU by performing an A/B test and checking metrics.

- [x] Implement a feature flag that we can rollout at a certain %.

**Comment by pravusjif** [comment]
PR: https://github.com/decentraland/unity-renderer/pull/2489
Status update:
- From Desktop Client we need to find a way of disabling textures compression with this new approach
Unregistering the new plugin after it's been registered doesn't work
Forcing the datastore bool in MainDesktop Awake() doesn't work (combined with the previous step either)
- Missing tests
