### ISSUE TITLE
Migrate documentation to Github

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2455]
We need to move all the documentation as listed in the picture below from Notion to the `unity-renderer/docs` repository.

![Screen Shot 2022-06-12 at 12.09.25.png](https://images.zenhubusercontent.com/622efee4c7d78e16ecd9ff40/76df129c-696c-49cb-9a64-3e77c2011904)

**Acceptance Criteria:**

[ ] Create a proposal about which of those documents should be moved to GitHub.

**Comment by aixaCode** [comment]
I would propose to move those pages to GitHub" 
- Explorer
  - Architecture
- ExplorerGuidelines
- Explorer/How tos?
- Performance Meter Tool
- Bots Tool
- UI Components Library

**Comment by aixaCode** [comment]
Proposal: https://www.notion.so/decentraland/Migrating-docs-to-GitHub-b0f3dfd5fed7481eaa612f61ac56615e
