### ISSUE TITLE
Spike: New avatar armature migration's effort

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2457]
In order to make a decision on if we will be migrating the armature of the avatar to the new bone structure, we need to do an assessment on costs and risks.

Attached,[ the document](https://www.notion.so/decentraland/New-Armature-Assessment-57d2e4080b244291af59d4f8e7222fbc) made by the Art team in favor of this change.

**Acceptance Criteria**
- [x] Technical Asssesment document with task break down and ballpark estimation

**Comment by AjimenezDCL** [comment]
https://www.notion.so/decentraland/New-Armature-Conversion-Breakdown-a9bc4e06642148c89b3c9c3f4fd68bae
