### ISSUE TITLE
every time gets stuck at "Loading LAND assets 75%" 

### ISSUE THREAD

**Issue by ActiveRadek** [decentraland/unity-renderer#2483]
### What happened?

every time gets stuck at "Loading LAND assets 75%"

### Steps to reproduce

Builder
Lands
Parcel 128, -15  EDITOR

"Loading LAND assets 75%"

### Operating System

Chrome or Brave and Windows 11

### Wallet

Metamask

### CPU

AMD Ryzen 9 5950X

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1215) 512MB

### RAM

128

### Kernel Version

1.0.0-2036429826.commit-e96a984

### Unity Version

1.0.31286-20220326153912.commit-55b9e15

### Realm

dg

### NameTag

ActiveR#6f59

**Comment by JorgeDecentraland** [comment]
Closing this issue due to lack of information and response from the reporter
