### ISSUE TITLE
Loading screen frozen when a player try to teleport from my scene to somewhere.

### ISSUE THREAD

**Issue by c4ntin** [decentraland/unity-renderer#2486]
Hi,
I have a strange bug on my scene.
If you try to teleport on any other scene via the map. The loading screen freeze (desktop and web client).
But if you exit my scene then teleport it works.
On the webclient, I've got this errors: 
![image](https://user-images.githubusercontent.com/7249833/174118106-ab4c6352-e88d-4d17-87f5-20738b8eebe1.png)
![image](https://user-images.githubusercontent.com/7249833/174118065-d539eedc-cd14-45de-bf7d-c838d2c0fd8d.png)

Scene: https://play.decentraland.org/?realm=artemis&position=-38%2C103&island=Ixtfo

**Comment by kwspgoliasz** [comment]
@xavi-dcl The issue could not be reproduced. No freezing was observed during the test.

**Comment by xavi-dcl** [comment]
Closing as cannot be reproduced.
