### ISSUE TITLE
Apparent rendering bug with shadows

### ISSUE THREAD

**Issue by maraoz** [decentraland/unity-renderer#2487]
### What happened?

![image](https://user-images.githubusercontent.com/287189/162509304-e5f5e121-000b-4a2d-9ed6-ce6e8e08b0b3.png)

### Steps to reproduce

go to (54,90), look at the trees behind the "tower"

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Wallet Connect

### CPU

11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

### GPU

NVIDIA T500 3968MB

### RAM

48871MB

### Kernel Version

1.0.0-2098154396.commit-22a0cf9

### Unity Version

desktop-main.commit-64822b7

### Realm

athena

### NameTag

maraoz

**Comment by xavi-dcl** [comment]
Is it scene specific?

**Comment by kwssbocian** [comment]
@xavi-dcl Issue is not scene specific and appears to be related to the presentation of the tree assets themselves. Screenshot of the same trees on another parcel:
![image](https://user-images.githubusercontent.com/110463715/209167507-85df68db-8c60-4a3e-ab38-afca8beb84a9.png)
