### ISSUE TITLE
Implement "loose" aim support and playtest

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#25]
This issue should cover the `Making the click detection more “loose”` section of the TDD:
https://docs.google.com/document/d/1I2bcntDm3KIp2rO_J7cNIYQ94D2zrEG2-jY92wpfgBk/edit#heading=h.c08r7aii51yq

**Comment by olavra** [comment]
We wont implement this as there is a better option in card #1318
