### ISSUE TITLE
Changes necessary for L2 Wearables

### ISSUE THREAD

**Issue by nchamo** [decentraland/unity-renderer#251]
After https://github.com/decentraland/explorer/tree/release-2021-04-09 is released, we need Unity to make some changes so that we can start supporting L2 wearables. The changes necessary are supporting both URNs and the new wearables format.

**URN support**
I think that all that is necessary to support URNs is to:
* Change all instances of the code of `dcl://base-avatars/{name}` for `urn:decentraland:off-chain:base-avatars:{name}`
* Change all instances of the code of `dcl://{not-base-avatars}/{name}` for `urn:decentraland:ethereum:collections-v1/{not-base-avatars}/{name}`

**New wearables format**
The wearables payload has slightly changed, and we need Unity to support the new format.

The current wearables payload is
```
export type Wearable = {
  id: string
  type: 'wearable'
  category: string
  baseUrl: string
  baseUrlBundles: string
  tags: string[]
  hides?: string[]
  replaces?: string[]
  rarity: string
  representations: BodyShapeRepresentation[]
  i18n: { code: string; text: string }[]
  thumbnail: string
}

export type BodyShapeRepresentation = {
  bodyShapes: string[]
  mainFile: string
  overrideHides?: string[]
  overrideReplaces?: string[]
  contents: FileAndHash[]
}

export type FileAndHash = {
  file: string
  hash: string
}
```

The new one is:
```
export type Wearable = {
  id: string
  rarity: string
  i18n: { code: string; text: string }[]
  thumbnail: string
  data: {
    category: string
    tags: string[]
    hides?: string[]
    replaces?: string[]
    representations: BodyShapeRepresentationV2[]
  }
  baseUrl: string
  baseUrlBundles: string
}

export type BodyShapeRepresentation = {
  bodyShapes: string[]
  mainFile: string
  overrideHides?: string[]
  overrideReplaces?: string[]
  contents: KeyAndHash[]
}

type KeyAndHash = {
  key: string
  hash: string
}
```

**Comment by olavra** [comment]
@pbosio could you please comment why this task is blocked?
