### ISSUE TITLE
Dice Masters ALPHA

### ISSUE THREAD

**Issue by Flex-Bowman** [decentraland/unity-renderer#2517]
### What happened?

Coordinates: 149,-10

Crafting Table Dialog Box

The text after selecting which item you want to craft is rendering unreadable. 

### Steps to reproduce

Step1: Go to coordinates (149,-10)

Step2: Interact with crafting station.

Step3: Select item to be crafted. 

![BugReportDCLND6 20 22](https://user-images.githubusercontent.com/102634366/174684672-920f6e12-63be-4e3b-bd8d-3c0ff2e5bbba.PNG)

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3600X 6-Core Processor 

### GPU

NVIDIA GeForce GTX 1060 6GB 6052MB

### RAM

16309MB

### Kernel Version

1.0.0-2503059035.commit-0dd1ae6

### Unity Version

desktop-1.0.393-20220620162122.commit-88e3597

### Realm

dg

### NameTag

FlexBowman#2843

**Comment by JorgeDecentraland** [comment]
This issue is in the scene
