### ISSUE TITLE
Implement 'CheckURLParam()' and 'GetURLParam()' debug methods using Kernel communication

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2519]
### WHY
Previously there were 2 very useful debug methods to check URL query params in the client but they had to be removed as everything URL-related should happen in Kernel.

These are the previously implemented methods:
`Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs`
```
[DllImport("__Internal")] public static extern bool CheckURLParam(string targetParam);
[DllImport("__Internal")] public static extern string GetURLParam(string targetParam);
```

`Assets/Plugins/JSFunctions.jslib`
```
  CheckURLParam: function(targetParam) {    
    return window.DCL.queryString.has(Pointer_stringify(targetParam))
  },
  GetURLParam: function(targetParam) {
    const stringifiedTargetParam = Pointer_stringify(targetParam)
    
    if(window.DCL.queryString.has(stringifiedTargetParam)) {
        const urlParamValue = window.DCL.queryString.get(stringifiedTargetParam);
      
        // How to return strings: https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html
        var bufferSize = lengthBytesUTF8(urlParamValue) + 1;
        var buffer = _malloc(bufferSize);
        stringToUTF8(urlParamValue, buffer, bufferSize);
        return buffer;
    }
    
    return '';
  }
```

### WHAT
We should implement a way of knowing if a certain URL parameter exists, and know its value, from the Unity Client.

**Comment by AjimenezDCL** [comment]
This was a debugging tool for the editor, we shouldnt convert it into a feature. It could lead to workarounds to retrieve URL params instead of using feature flag or kernel communication.
