### ISSUE TITLE
WonderMine Meteor Mining

### ISSUE THREAD

**Issue by babbuski** [decentraland/unity-renderer#2520]
### What happened?

When mining a meteor the reward for gems on the second line does not display the name correctly, something seems to be obscuring it.
![gem names obscured](https://user-images.githubusercontent.com/106375619/170664134-ffb8306a-cdd6-42c9-89a1-f94c946d26a8.jpg)

### Operating System

Windows 10  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 9 3900X 12-Core Processor 

### GPU

NVIDIA GeForce GTX 1060 6GB 6052MB

### RAM

65479MB

### Kernel Version

1.0.0-2392404250.commit-1b886c4

### Unity Version

desktop-1.0.339-20220520162118.commit-ccddcf0

### Realm

dg

### NameTag

babbuski#03f1

**Comment by JorgeDecentraland** [comment]
Issue in the scene
