### ISSUE TITLE
Web client in Chrome is reporting no GPU despite an NVidia GTX 1070 running and configured

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#2521]
On my MSI GS65 Stealth Thin, which has an NVidia GTX 1070 GPU, I get a "your machine is not using a dedicated graphics card..." when i enter scenes.

I attach an example, plus images showing that the GPU is configured to be on 

Windows 10 Home, with curren tupdates
Latest NVidia driver 512.95 5/24/2022
Chrome: Version 102.0.5005.63 (Official Build) (64-bit)

*** This "lack of GPU" warning is NOT reported in Brave but it IS reported in Edge and Fireforx

![2022-05-25_no_gpu_message](https://user-images.githubusercontent.com/21015643/170373561-64150e76-0261-4608-b1c0-7d4bf8614761.png)

![2022-05-25_Chrome_HW-Accel](https://user-images.githubusercontent.com/21015643/170373578-dfe47552-4d25-4e45-9d7a-9a24acfe2bd9.png)

![2022-05-25_NVidia_On_by_Default](https://user-images.githubusercontent.com/21015643/170373594-106c57fb-8b8b-4e89-8061-132135677842.png)

![2022-05-25_NVidia_On_for_Chrome](https://user-images.githubusercontent.com/21015643/170373606-b4fca953-063e-41a9-95dd-3ad0f2a2cbd6.png)

**Comment by eordano** [comment]
Modify
* https://github.com/decentraland/unity-renderer/edit/dev/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningHUDController.cs
* https://github.com/decentraland/unity-renderer/blob/dev/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningNotification.prefab

To add:


"and restart your browser" if the user is using the browser
"and restart the experience" if the user is using the desktop launcher

**Comment by guidota** [comment]
Is this labeling change enough to fix the problem? It seems to be a compatibility issue more than a wording clarification

**Comment by eordano** [comment]
Yes, let's just change the label. The user that reported it seems to have understood, but was lacking that last step.

**Comment by AjimenezDCL** [comment]
IIRC windows override this behaviour, can you try with this? https://pureinfotech.com/set-gpu-app-windows-10/
