### ISSUE TITLE
fix "ERR_INSUFFICIENT_RESOURCES" error that prevents from entering the world

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2522]
Many times this error has been observed when trying to access the world using the web client regardless of the OS (it's been reproduced in Windows and MacOS chrome browsers).

It's always accompanied by the `LoadProfile` error that should be messaged by Kernel in the `Main` gameobject.

![Screen Shot 2022-06-20 at 11.18.14.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/3b5d44e1-3a38-4c17-87ca-b3ad04c8fcc4
)

When this happens the world never loads and the loading % is never shown in the loading screen.

It's been observed happening at least entering as guest, not sure if logging with metamask can also trigger this problem.

May it be. arace condition?

### Acceptance Criteria
- [ ] Find a way to force the issue and test that it has been resolved

**Comment by AjimenezDCL** [comment]
The "Error while sending Message to Unity"  is really misleading.

It happens beacuse kernel subscribes to a handler that gets triggered when an exception is threw. In C# the best practice for Tasks management and cancellation tokens is to throw `OperationCanceledException`, and it doesnt matter if we catch or not that exception, the handler triggers that an exception ocurred and kernel things somethings bad happened.

We must investigate this for sure, but it's probably not related to the log errors attached to the ticket.

**Comment by pravusjif** [comment]
Closing as it's a duplicate of: https://github.com/decentraland/unity-renderer/pull/2793
