### ISSUE TITLE
Show a toast when a player doesn't own any items from a Linked Wearable collection

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#2529]
Players that don't own any items don't receive any type of feedback after clicking a collection name in the linked wearables dropdown. 
To improve this use case we need to add a toast explaining what is going on. 

![Screen Shot 2022-06-22 at 12.53.45.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/dc5386e3-459c-48cf-9579-750dcfd12df8)

**[Toast design]**(https://www.figma.com/file/zMetMn5FptTKYXTnxcRtpW/Backpack-Hybrid?node-id=3676%3A6468)
☝️ Pay attention to detail. Use Figma information to build this toast perfectly 🌈

Requirements:
- [x] Appears with a fade in animation after clicking a collection in which the user doesn't own any item.
- [x] Disappears automatically after 5 sec, or when the player clicks in any part of the screen, with a fade out animation.
- [ ] The button [Browse Marketplace] opens a new tab in the collectibles section.

Ping @RominaMarchetti  if you need access to Figma and help on how to use it. Romina must review this PR as well to confirm visual implementation.

**Comment by dalkia** [comment]
Duplicate #2264

**Comment by dalkia** [comment]
Duplicate #2264

**Comment by dalkia** [comment]
Browse marketplace button does not apply to this case
