### ISSUE TITLE
Fix CLI renderer package download consistency issues

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#253]
Right now we have inconsistent behaviours regarding the renderer package download from the CLI when running `make watch` (always overwrites with master build) or `make update-renderer` (deletes build files and doesn't download anything) or `make update-renderer-branch` (downloads the current branch build files).

I think the ideal state would be:
* `make watch` : **if there is no local build found**, it should download the **current branch** build renderer package (or from master if there is no branch-build package published yet) as part of the make watch process.
* `make update-renderer`: should download and overwrite the current build files with the ones from the **current branch** build renderer package (or from master if there is no branch-build package published yet)
* `make update-renderer-master` (removing old `make update-renderer-branch`): should download and overwrite the current build files with the ones from the **master branch** build renderer package

**Comment by BrianAmadori** [comment]
I agree with the approach! 

Just a comment for the first point. We have to make sure the vanilla `make watch` still works with the CI when deploying to production and master, and at the same time download the proper branch when we are debugging in a specific branch. Getting ahead of @pbosio on this one.

**Comment by Suduck** [comment]
The only thing I will like to add is that when implemented, we should add it to the explorer kernel README, 

Right now there is no information about that in any visible part
