### ISSUE TITLE
Most wearables don't load as Asset Bundles

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#254]
When wearables were migrated into the content servers recently, the hash/id of EVERY wearable changed, so the ones we previously converted and uploaded to the S3 are not being used at all...

- [x] Update the wearables AB conversion logic to use the [new endpoint]( https://peer.decentraland.org/content/deployments?entityType=wearable) and adapt to the new JSON data retrieved, as it is pretty different than the previous response we used

- [x] Dump all wearables again and re-convert them to AB

- [x] Upload them again to S3

**Comment by pravusjif** [comment]
A quick test using the Unity Editor and checking the S3 for one of the wearables shows that effectively most wearables appear to be missing from the S3.

Will continue to investigate

**Comment by pravusjif** [comment]
[ ] 1. The endpoint we use to get all the collections and their wearables when converting the queue of werables to ABs is changing from https://wearable-api.decentraland.org/v2/collections (it's getting deprecated) to https://peer.decentraland.org/content/deployments?entityType=wearable. So we should update de wearables AB converter to filter the data according to that new endpoint and use that.

[ ] 2. When the wearables were migrated into the content servers recently, the hash/id of EVERY wearable changed, so the ones we previously converted and uploaded to the S3 are not being used at all... so after finishing **[1]** I'll re-dump them all and upload them to the S3

**Comment by pravusjif** [comment]
After uploading all the newly-dumped wearable ABs to the S3 I tested in prod with many users and saw ABs working correctly.
