### ISSUE TITLE
Investigate optimization of PR creation process

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2544]
The team when creating PR is posting manually on information about the request to the slack channel #explorer-pr-sync.
Most of the time, each member proactively reviews some of the PR during the day, if they are ready to be reviewed.
In some specific cases, the reviewer is manually selected due to specific knowledge of different parts of the project.

Goals:
- Distribute PR evenly among the team
- Increase productivity and the pace of the code review by automating steps during the PR creation

Requirements:
- Distribute reviewers evenly inside the team
- Handling of urgent PRs
    - We found a bug in production
    - Special cadence of release is a needed
    - The system can assign a person with the wrong timezone and manually re-assigning the reviewer can trigger false notifications
    - Support for custom label filtering, i.e.
        - `big change` could set an additional reviewer
        - `hotfix` could set no reviewer at all so you manually pick the one in your timezone.
- Custom amount of reviewers
    - For bug fixing and small tasks, we usually require 1 approval, but for big tasks, we request 2 approvals.
- Specific Reviewers
    - When working on a specific feature (i.e. UI) we need to have the possibility to specify a concrete developer that has the most knowledge about the system
    - Possibility to specify developer from other team for bigger changes that have dependencies on SDK/Kernel changes
    - Both can be achieved with proper configuration of code owners features
- Filter draft PRs
- Skip auto-assign when the reviewer is already selected (i.e. when draft PR was created)
- Filter assignees based on the status i.e. someone is on vacations
    - That can be achieved with usage of status in GItHub
    - Or through config default auto-assign feature
- Send automatic notification to slack channel about new PR

Proposal:
- Auto-assign GitHub feature with a combination of Code Owners
    - [https://docs.github.com/en/enterprise-server@3.2/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team](https://docs.github.com/en/enterprise-server@3.2/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team)
- Research ready solutions on the marketplace that offers more customization via GitHub actions
    - i.e. [https://github.com/marketplace/actions/auto-assign-action](https://github.com/marketplace/actions/auto-assign-action)
- Custom solution via GitHub (with/or without GitHub features)
- Setup bot to automatically send notification about new PR to slack

**Acceptance Criteria:**
[ ] Investigate and document the necessary work we need to do in order to achieve the proposal above.

**Comment by AjimenezDCL** [comment]
After evaluating multiple github actions I went with the one proposed in the ticket: https://github.com/marketplace/actions/auto-assign-action

It's easy to use and configure.
