### ISSUE TITLE
It is not possible to set quality to Ultra in Mac client

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2550]
This issue was reported by @nicorajco when testing the Mac client.

**Description:**
Can't set quality to Ultra. When I do, it changes back to Normal. 

**Steps to reproduce:**
1. Press P. Graphics. 
2. Set Graphics quality to Ultra. 
3. Wait 3 seconds

**Comment by davidejensen** [comment]
I'm on a mac and to me if stays in Ultra:

https://images.zenhubusercontent.com/337227404/5710dda8-df8e-471c-b7df-9564c17a912a/screen_recording_2022_07_04_at_17_46_31.mov

**Comment by JorgeDecentraland** [comment]
@kwspgoliasz @kwssbocian can you try to reproduce this, please?

**Comment by kwssbocian** [comment]
We have tried it and on our end the settings stayed on Ultra. We additionally tried changing between windowed and fullscreen as well as changing between various resolutions  - it would always stay on Ultra.

**Comment by olavra** [comment]
Cant reproduce
