### ISSUE TITLE
In remote PC session, the avatar cannot be rotated using the mouse (Decentraland BETA for desktop)

### ISSUE THREAD

**Issue by vladgaby** [decentraland/unity-renderer#2557]
### What happened?

If I'm using the Decentraland application from a remote workstation the I cannot rotate the avatar with the mouse. All the buttons ar working correctly but not the rotation.
If the application is opened and used on the local computer then it's ok, only in remote session has problems.

### Steps to reproduce

1. Using Remote Desktop Connection take remote the station where the Decentraland application is installed.
2. Open the Decentraland application -> OK
3. Login using your wallet credentials -> OK
4. Login was succesfull -> OK
5. Start moving the avatar with the keys 'w' , 'a' , 's' , 'd' -> OK
6. Try to look arround using the mouse -> NOK

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz

### GPU

NVIDIA GeForce GTX 1080 Ti 11127MB

### RAM

32702MB

### Kernel Version

1.0.0-2450204627.commit-f9c6a13

### Unity Version

desktop-1.0.361-20220527144557.commit-e48ddbc

### Realm

dg

### NameTag

egoboost#a8c7

**Comment by vladgaby** [comment]
> This seems to be an issue with the IO of the remote connection not detecting you mouse input. Have you tried if the mouse works on other things beside Decentraland on that remote connection?

**Comment by JorgeDecentraland** [comment]
Closed based on the previous comment
