### ISSUE TITLE
Implement fluid color shader

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2559]
Some of the components for the new UI design requires a shader that will make use of several color points, moving and blending with each other, with an aggressive blur distortion.

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/71914cae-91f4-4dc6-9a9f-e1abd428b075)

This will be required for the new [Loading Screen](https://www.figma.com/file/y4y7nXywE0IvY3ULAVXioJ/Loading-Screen?node-id=664%3A2) and [New Passport](https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Passport-%26-Profile?node-id=830%3A661)

**Acceptance Criteria**
- [x] Shader can define up to 4 color samples
- [x] Each color will have a variable size in radius
- [ ] Colors can move at different speed inside the texture
- [x] Blur factor can be controlled

**Comment by JuanSalice** [comment]
- Created an initial shader that uses 4 colors and merge them using elipses with distortions.

**Comment by JuanSalice** [comment]
- Created new version of the fluid effect.
- Each color moves in a direction and has different customization values.

https://images.zenhubusercontent.com/337227404/8c0c5df5-5dd8-4b84-bebb-b9998822b550/fluideffect.mp4

**Comment by JuanSalice** [comment]
- Added values to improve each color customization.
- Refinement of values

**Comment by JuanSalice** [comment]
- Changed blend mode of the colors
- Added random rotation to the movement of each color

https://images.zenhubusercontent.com/337227404/ab7dc5bf-999e-4b6f-b48d-bb66132d8fe2/fluid.mp4
