### ISSUE TITLE
"The avatar could not be loaded correctly" error for scene previews hosted on Heroku

### ISSUE THREAD

**Issue by daltonmachado** [decentraland/unity-renderer#2573]
Hello. I'm using Heroku to host scene previews during development and everything was working fine yesterday. Today it started to show the "The avatar could not be loaded correctly" error message when trying to access any of my scenes on Heroku, even the ones without any changes made since yesterday, so I think this might be an issue in the renderer.

I'm using Windows 10 and the error occurs on all the browsers I have installed (Brave, Chrome and Edge).

The browser console says this:
```
Failed Loading avatar

index.js:83 Avatar.Load failed with wearables:[urn:decentraland:off-chain:base-avatars:elegant_sweater,urn:decentraland:off-chain:base-avatars:brown_pants_02,urn:decentraland:off-chain:base-avatars:classic_shoes,urn:decentraland:off-chain:base-avatars:moptop,urn:decentraland:off-chain:base-avatars:lincoln_beard,urn:decentraland:off-chain:base-avatars:matrix_sunglasses,urn:decentraland:off-chain:base-avatars:BaseMale,wave,fistpump,robot,raiseHand,clap,money,kiss,hammer,tik,tektonik,dontsee,handsair,shrug,disco,dab,headexplode,dance,snowfall,hohoho] for bodyshape:urn:decentraland:off-chain:base-avatars:BaseMale and player 
```

Here's the screenshot of the error:
![image](https://user-images.githubusercontent.com/1218271/176946103-7669da21-a646-4b2b-b99a-2ef16b860895.png)

I appreciate any help.

**Comment by daltonmachado** [comment]
I tried to remove the query parameter `renderer-branch=master` from the URL and the scene loads correctly now. If this parameter must not be used anymore then the [docs](https://docs.decentraland.org/development-guide/deploy-third-party/) should be updated to reflect that.

**Comment by JorgeDecentraland** [comment]
This was fixed, can you confirm if it keeps happening?

**Comment by daltonmachado** [comment]
Yes, I can confirm this was fixed and is no longer happening. Thank you.
