### ISSUE TITLE
change `sceneId: string` to `sceneNumber: int`

### ISSUE THREAD

**Issue by menduz** [decentraland/unity-renderer#2582]
To:
- Optimize incoming and outgoing messages
- Faster random access (Dictionaries, Hash tables)
- Save memory allocated to strings and help the garbage collector by removing all that load

Kernel counterpart: https://github.com/decentraland/sdk/issues/362, please add to this issue all the necessary changes from kernel messages

- [ ] ...
- [ ] ...

**Comment by pravusjif** [comment]
Tackled at https://github.com/decentraland/unity-renderer/pull/2977

**Comment by pravusjif** [comment]
merged https://github.com/decentraland/unity-renderer/pull/2977
