### ISSUE TITLE
Drop base64 source support for SDK image components and move large mesages payload check

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#259]
In order to avoid blocking the new genesis plaza release and the unity2020+ssao release we implemented a compromise fix detailed at #256

We should return the message payload check to its original place and drop base64 support to avoid the risk of crashing the explorer using that type of images.

- [ ] Include console note notifying the drop of the feature

-  [ ] Update `decentraland-ui-utils` and `decentraland-npc-utils` libraries to have their images uploaded and fetched from IPFS or the content servers (anywhere not centralized)

- [ ] Drop base64 support throughout the SDK and client

- [ ] Remove message payload size check from protobuf scene messages encoding step and place it again in the `componentUpdated()` in [SceneRuntime](https://github.com/decentraland/explorer/blob/558e5fe7eaa46af1513bc021afe897c3461b53ca/kernel/packages/scene-system/sdk/SceneRuntime.ts#L434) as it was before #256

**Comment by Kosta1994** [comment]
100K

**Comment by olavra** [comment]
@menduz @pravusjif do you think we can move this ticket to the SDK backlog?

**Comment by menduz** [comment]
Sure

**Comment by m3taphysics** [comment]
Closed, see most recent issue: https://github.com/decentraland/sdk/issues/64
