### ISSUE TITLE
No puedo jugar al ice poker

### ISSUE THREAD

**Issue by Rodriasd** [decentraland/unity-renderer#2599]
### What happened?

![image](https://user-images.githubusercontent.com/108191327/175783316-59e22b7f-c287-4eb6-9b2c-d6187d88e56b.png)

### Steps to reproduce

Apenas logeo no me aparece nada de poker ice. paarece q no tengo el item, pero entro desde otra pc y tengo el item y puedo jugar, me pasa en este ordenador hace 3 dias 

### Operating System

chrome, windonws 11

### Wallet

Metamask

### CPU

ryzen 7 1700x

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16 ram 3200

### Kernel Version

1.0.0-2548884389.commit-1a1bc66

### Unity Version

1.0.40765-20220622131414.commit-3603482

### Realm

artemis

### NameTag

rodri#3326

**Comment by JorgeDecentraland** [comment]
This is an issue from the scene, please get in touch with the developers.
