### ISSUE TITLE
Spike: Investigate tweening library

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#2605]
We currently use coroutines for simple animation, which requires a lot of boilerplate code and duplication, making it harder to have unified animation for different UIs that could be easily reused across the project.

There are a few already very popular free tweening libraries for Unity that could be used, i.e. DOTween, or LeanTween

#### Acceptance criteria: 
* [x] Comparison of tweening libraries with permissive license that could be used in out project is documented
* [x] Performance comparison between selected libraries (CPU, memory allocation) compared to baseline (default coroutine behavior) is documented
* [ ] Tech assesment of the task is documented.
* [ ] Tasks breakdown is documented.

**Comment by AjimenezDCL** [comment]
A bunch of Tween libraries have been consider.  In the end, three of them were evaluated for benchmarking based on licensing, capabilities and state of the project.

- Duck Tween: https://github.com/dubit/duck-tween
- Lean Tween: https://github.com/dentedpixel/LeanTween  
- DoTween: http://dotween.demigiant.com/license.php

**Comment by AjimenezDCL** [comment]
The benchmark evaluation will consider frame time and memory allocation. Every tween library will perform the same tween, a translation of N objects with the same Ease (InBack) and the same duration.

- Duck Tween:
![image.png](https://images.zenhubusercontent.com/5d91ff0b2836200001244acf/0e91f576-f64d-48c6-bbe9-437e2e6452c5)

- Lean Tween:
![image.png](https://images.zenhubusercontent.com/5d91ff0b2836200001244acf/9d0a324f-d320-4fa5-b86e-9668f5bf2e03)

- DoTween:
![image.png](https://images.zenhubusercontent.com/5d91ff0b2836200001244acf/2ac8ea49-4a8e-4a84-acaa-435bada27446)


Results are not conclusive enough. DoTween uses slightly less memory allocation and frame time to perform the same operation.

**Comment by AjimenezDCL** [comment]
DoTween brings a bunch of cool tools, like async awaiters: http://dotween.demigiant.com/documentation.php#coroutines

It's also the most recently updated and one of the most used tween libraries in the market. We are gonna stick with it until proven

**Comment by AjimenezDCL** [comment]
The tech assessment and breakdown of including the choosen library equals the effort of actually including it, so gonna do it right away.
