### ISSUE TITLE
Models not loading completely/not animating

### ISSUE THREAD

**Issue by palryan** [decentraland/unity-renderer#2635]
### What happened?

This was a bug on the webclient earlier which got fixed and now I can see the same thing happening on the desktop client. 

Some of the 3D Models we use at Wilderness P2E (-25,90), won't load fully and thus won't animate (also won't go invisible for some reason).

### Steps to reproduce

Goto -25,90. Enter Green Portal

### Operating System

Mac OS X 11.6.0

### Wallet

Metamask

### CPU

Apple M1

### GPU

Apple M1 5461MB

### RAM

8192MB

### Kernel Version

1.0.0-2612423386.commit-79edd23

### Unity Version

desktop-1.0.449-20220705152714.commit-2686632

### Realm

dg

### NameTag

Wilderness

**Comment by JorgeDecentraland** [comment]
@plaryan could you share a video with the expected behavior, please?

**Comment by davidejensen** [comment]
I've tried locating this problem in the mac client but I cannot find any differences between the browser version and the desktop client in the scene. 
Closing the issue, if the problem persists re open it or open a new one with examples of the non working mondels and/or a video showcasing the wrong behavior
