### ISSUE TITLE
Profil Pic.

### ISSUE THREAD

**Issue by asilhanfirat** [decentraland/unity-renderer#2638]
### What happened?

Profile photo is not visible after changing wearable clothes
![1](https://user-images.githubusercontent.com/100471557/156257724-62169b91-2193-4893-b43d-0afebd93cc30.jpg)
.

### Steps to reproduce

Profil pic.

### Operating System

Windows 10  (10.0.19042) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-3210 CPU @ 3.20GHz

### GPU

NVIDIA GeForce GTX 660 1998MB

### RAM

8150MB

### Kernel Version

1.0.0-1918065042.commit-710b300

### Unity Version

desktop-main.commit-7e33653

### Realm

dg

### NameTag

Asilhan#e02b

**Comment by JorgeDecentraland** [comment]
@asilhanfirat can you confirm if this keeps happening?

**Comment by JorgeDecentraland** [comment]
Closing the issue due to lack of response from reporter
