### ISSUE TITLE
Report a Bug

### ISSUE THREAD

**Issue by saeedrg19** [decentraland/unity-renderer#2639]
### What happened?

A bug has been observed in the right corner of Wonder zone (report a bug). Please fix it for me.
Thank You

### Steps to reproduce

Beta version
![bug](https://user-images.githubusercontent.com/109059351/178197620-9f1964fb-a54b-453e-ad69-068939a65e1e.jpg)

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

### GPU

NVIDIA GeForce MX450 1928MB

### RAM

7957MB

### Kernel Version

1.0.0-2638443584.commit-696a74b

### Unity Version

desktop-1.0.455-20220707134647.commit-e3e69ac

### Realm

saeedrg19

### NameTag

sdrg#37fa

**Comment by JorgeDecentraland** [comment]
This is an issue in the scene. Please contact the owner.
