### ISSUE TITLE
Bug jumping avatar stuck on air

### ISSUE THREAD

**Issue by siddh-artha** [decentraland/unity-renderer#2640]
### What happened?

When I jumped my avatar using the space bar key and Up arrow key at the same time it stuck on air.

### Steps to reproduce

Just jump and move forward.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0

### Wallet

None, played as guest

### CPU

Intel core i5 10th gen

### GPU

ANGLE (AMD, Radeon HD 3200 Graphics Direct3D11 vs_5_0 ps_5_0) 512MB

### RAM

8GB

### Kernel Version

1.0.0-1876297332.commit-9804de6

### Unity Version

1.0.28189-20220218145015.commit-b289f57

### Realm

dg

### NameTag

TheShankara#3823

**Comment by xavi-dcl** [comment]
@kwspgoliasz can you please validate?

**Comment by kwspgoliasz** [comment]
@xavi-dcl The issue could not be reproduced on the QA side. For the jumping mechanic, only the issue [#3306](https://github.com/decentraland/unity-renderer/issues/3306) was observed.

**Comment by xavi-dcl** [comment]
Closing then, thanks!
