### ISSUE TITLE
Map location names are missing

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#2644]
When you open the map (`M`) sometimes you cannot see the starred location names.

![Screen Shot 2022-07-14 at 15.05.49.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/0fcedc52-0f3e-4c63-ae0c-9f8c692d5ae6)
https://images.zenhubusercontent.com/337227404/84a8998f-6e7f-43da-810d-b70d7cebd6ea/2022_07_13_11_56_41.mp4

### Acceptance Criteria
- [ ] Map names appear

**Comment by dalkia** [comment]
Cannot reproduce; neither in dev or in prod.

The pipeline for icon creation starts in the method `UpdateMinimapSceneInformation()` in `MinimapMetadataController.cs`. This method is called by Kernel.

After that, it goes into `AddSceneInfo()`, which tiggers the event `OnSceneInfoUpdated()`. The method `MapRenderer_OnSceneInfoUpdated()` is suscribed to this event. This is the one that instantiates the Icon POI.

At first sight, there is nothing weird or wrong in this pipeline. My first theory is that Kernel was not sending the call necessary for the whole process to start.

**Comment by dalkia** [comment]
Apparently fixed here:
https://github.com/decentraland/kernel/pull/375
