### ISSUE TITLE
Randomly the avatar is not seen in the Avatar Preview

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2648]
This happens regardless of the realm and there are no clear reproduction steps, to random users at random moments.

![image (14).png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/656a3e49-94c9-4938-babf-9edac5c843eb)

![image (15).png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/c427ee28-9771-4cee-9ce0-15ce42161022)

**Comment by davidejensen** [comment]
When we open the backpack the first time the character preview is instantiated and rendered in the UI.

If we open the backpack in 0,0 the character preview is correctly displayed, if instead we open the backpack after moving to 10,10 or 100,100 the preview doesn't appear.

After debugging here are my findings:

* When you open the backpack in 0,0 the character preview has the ABs and the Combined Mesh correctly placed and aligned.

![Screenshot 2022-07-18 at 12 11 00](https://user-images.githubusercontent.com/4254522/179490433-0b4cce14-c5d5-4561-91d6-bf447e1b2b89.png)

* If we open the backpack for the first time in 10,10 the ABs and combined mesh are not correctly placed, we can see that the actual merged avatar appears in a completly different position

![Screenshot 2022-07-18 at 12 18 44](https://user-images.githubusercontent.com/4254522/179493073-29c2f016-9a99-4fc8-aa6e-d0c3c8a1ab17.png)

**Comment by pravusjif** [comment]
So this is bound to the world's reposition we do to keep everything close to 0,0,0 (to avoid floating point problems when positioning stuff very far from 0,0,0).

This started happening only recently so maybe it has something to do with the latest changes made to the avatar scripts or shader, maybe with the new hologram effect PR?

**Comment by davidejensen** [comment]
@pravusjif yes it is most likely related to that, I'll try to do a bit of commit hunt because we have 4 different PRs related to the hologram
