### ISSUE TITLE
Cleanup feature flag explorer_friends_by_online_status

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#2649]
Cleanup feature flag `explorer_friends_by_online_status` 
![image.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/875a91ce-0d8d-4ef1-bdb9-828b6b7bf261)

Acceptance criteria

- [x] Code depended on that FF is removed
- [ ] FF is removed from Unleash https://features.decentraland.systems/#/features

**Comment by Antivortex** [comment]
Since the new default behavior here is what we had for this flag in the ON status we should first release the Renderer code changes and only after that remove the flag from GitLab, otherwise production Renderer will turn the feature OFF while we want to keep it ON

**Comment by Antivortex** [comment]
We'll remove FF from Unleash after the next release to make sure we will not affect current prod clients dependent on that feature flag in its ON state
