### ISSUE TITLE
Join feature not working as expected

### ISSUE THREAD

**Issue by moliva** [decentraland/unity-renderer#2671]
There used to be a feature that when a friend was online, their status would be reported as well as its whereabouts and it was possible to jump to the position of that user. However as of today, it seems this is not longer possible:

**Steps to reproduce:**
1. Login to play.decentraland.org
1. Check friends that are online
1. Verify that the position and realm are not visible in the friends list or the chat window
1. Verify it's not possible to jump/join the user by clicking the join button

<img width="372" alt="Screen Shot 2022-07-20 at 16 16 55" src="https://user-images.githubusercontent.com/3766397/180065051-5288da73-cdcd-477b-8da5-bcc5b885dc83.png">

From current debugging it seems the data is being sent from kernel to renderer with the actual realm and position but the `BrowserInterface#JumpIn` is never called after clicking the `join` button in the UI.

**Comment by sandrade-dcl** [comment]
It is already fixed in the branch `feat/social-lazy-loading`.

**Comment by sandrade-dcl** [comment]
There already existed an issue related to the same problem: https://github.com/decentraland/unity-renderer/issues/2619. We're going to close this and keep the other ticket.
