### ISSUE TITLE
Black screen on wonder mine

### ISSUE THREAD

**Issue by pHASShon** [decentraland/unity-renderer#2691]
### What happened?

After trying to mine for the first time on WonderMine Game, I've received the loot and suddenly the screen went to black. I've tryed lowering the graphics to medium but stills happens

### Steps to reproduce

Enter WonderMine Game
Mine two times
receive the loot
screen goes black with no interaction,
![image](https://user-images.githubusercontent.com/62249710/150689057-7d7128bc-3390-44da-acb7-603e18aacaba.png)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

### Wallet

Metamask

### CPU

intel Core i5 11th 11400k

### GPU

Nvidia RTX 3050 Laptop

### RAM

16Gb

### Kernel Version

1.0.0-1729947058.commit-aa13346

### Unity Version

1.0.25467-20220121232645.commit-3974cfb

### Realm

dg

### NameTag

blemysh#7687

**Comment by JorgeDecentraland** [comment]
Closing due to lack of response from user
