### ISSUE TITLE
Special characters are not working in the chat entries

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#2694]

**Comment by RominaMarchetti** [comment]
Special characters are not being supported in the chat bubbles but working fine in the chat input.

![Screenshot 2022-07-22 at 06.13.56.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/70a857af-242a-4646-ad6f-84e2f54831dd)

**Comment by AjimenezDCL** [comment]
https://github.com/decentraland/kernel/pull/540 This kernel PR will fix it.
