### ISSUE TITLE
AvatarReporterController performance improvement

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2701]
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/dd3bedd1-0f69-4650-9c6b-a803c0317c8e)

# What

`AvatarReporterController` contains a method called `GetcurrentSceneIdNonAlloc` that gets the scene ID by iterating over all loaded scenes and checking if they contain that parcel position to return its ID, this is slow and allocates a lot of memory if we have lots of avatars on the scene.

# How

We have to maintain a new Dictionary<Vector2Int, string> that should contain all the current parcel positions with their respective scene ID, we have to update this dictionary every time a scene gets loaded/unloaded, we are going to avoid multiple iterations and allocations per frame, this may bring us a performance boost when there lots of nearby avatars.

**Comment by Kinerius** [comment]
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/7d59b44b-ff30-4175-8171-629b5598bde3)

Potential performance improvement in ICE Poker by 1.67 ms

**Comment by menduz** [comment]
May I suggest to encode the vector2 as int32 position hash? That way you can use a faster structure like a hashtable

```ts
  const maxParcelX = 255
  const maxParcelZ = 255
  const x = (parcel.x + maxParcelX) >> 2
  const z = (parcel.y + maxParcelZ) >> 2
  const hash = x << 16 | z
  return hash
```
