### ISSUE TITLE
[Unity 2021] Passport UI closes when using any of its tabs

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2705]
Check branch `feat/unity-2021` 
The problem was found here https://github.com/decentraland/unity-renderer/pull/2602

Passport UI closes when using any of its tabs [Happens both in Editor and in build]
This can be tested by clicking any other user and trying to check their wearables tab in the passport

**Comment by Antivortex** [comment]
Commited to the same Unity 2021 upgrade branch

**Comment by xavi-dcl** [comment]
@Kinerius is this still an issue, or can we close it?

**Comment by Kinerius** [comment]
@xavi-dcl this yes this is fixed but its not merged, it is going to be closed automatically after we merge https://github.com/decentraland/unity-renderer/pull/3223
