### ISSUE TITLE
[Unity 2021] Transparency not working on WebGL

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2706]
Check branch feat/unity-2021
The problem was found here #2602

Transparencies rendering issue [Happens only in build]
This can be seen in Genesis Plaza's waterfall pipe that takes to the main hall, as well as in some user's wearables:

![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/c7056650-374b-45c9-b1db-02d117cd420e)
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/422b8ddc-5aac-408c-b009-4c7cd5664c84)
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/0b26f441-e720-4d37-bd32-340c429da243)

It seems the alpha cutoff is not working correctly, there is no error in the shader while building.

**Comment by MichaelBitsakis** [comment]
Cloned feat/unity-2021 and created branch https://github.com/decentraland/unity-renderer/tree/feat/unity-2021-shadersCompatibility.

Checking shaders and will modify accordingly to make them compatible with WebGL.

**Comment by MichaelBitsakis** [comment]
Progress : 

Created a modified --> DCL/Universal Render Pipeline/LitMod shader and fixed Alpha Cutoff .

**Comment by MichaelBitsakis** [comment]
Fixed Alpha Clip 
![Fixed_Alpha_Clip.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/ec2e0fff-7160-4163-b5b7-1023ccba6f62
)

**Comment by MichaelBitsakis** [comment]
Transparency is fixed , we came up to a unity bug , not setting up the _ALPHATEST_ON on the material during the version upgrade , once we use a 2021 material with the shader it works fine.

**Comment by MichaelBitsakis** [comment]
Cleaned up testing area and documented / cleaned up Lit shader.
