### ISSUE TITLE
[Unity 2021] Convert materials created on AB in Unity 2020

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2707]
Check branch feat/unity-2021
The problem was found here #2602

Specular/Metallic rendering issue [Happens only in build]
This can be seen in Genesis Plaza waterfall water, Salmonomicon's ground and head (-54, 1), and at Ropsten's material test scene (58, -71).

Prod:
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/2140129a-8a68-44d3-97a3-8a6da6d68531)

Unity 2021:
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/1dc52265-28f0-49ee-90bb-e65e9142f60c
)

**Comment by AjimenezDCL** [comment]
So far I've been able to fix most of the issues. 

Now I'm dealing with metallic issues. 
Production:
![image.png](https://images.zenhubusercontent.com/5d91ff0b2836200001244acf/de86f877-5bcd-46a3-95c8-9c2df0d4a994)

Unity 2021:
![image.png](https://images.zenhubusercontent.com/5d91ff0b2836200001244acf/db9246f5-0ab6-46df-b992-98bae4edc667)
