### ISSUE TITLE
Shadows issue

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2708]
Check branch feat/unity-2021
The problem was found here #2602

Shader/Shadows issue [Happens only in build]
This can be seen in Ropsten's scene bounds checking scene (62, -68).

![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/ac4ff337-3e44-4a31-9b6b-2f9b48211c78)
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/d0677714-b85e-4576-81db-bd69d83ee969)

**Comment by Antivortex** [comment]
dev branch CI build:

![image.png](https://images.zenhubusercontent.com/62fb937fa41da238b0ed7951/15a2a77a-86dc-4912-9ac0-4e30d76814e3
)

**Comment by Antivortex** [comment]
dev branch Unity Editor (skybox at noon):

![image.png](https://images.zenhubusercontent.com/62fb937fa41da238b0ed7951/63efd4a7-8737-45d6-a215-618b281789cf)

**Comment by Antivortex** [comment]
Conclusion: 

The shader itself has issues with shadows, not sure if we need to fix it since this particular scene configuration is only present in Goerli. In any case it is not part of Unity-2021 upgrade.

**Comment by Antivortex** [comment]
We discussed with with Kinerius and decided to bring this to backlog for now since it does not affect production and not related to 2021 upgrade.

**Comment by xavi-dcl** [comment]
Removed dependency since Unity upgrade does not depend on this as per comments

**Comment by xavi-dcl** [comment]
Closing since it's on testnet and doesn't seem to bother us
