### ISSUE TITLE
Tech Assessment for "New Friends Requests"

### ISSUE THREAD

**Issue by JorgeDecentraland** [decentraland/unity-renderer#2733]
Acceptance criteria:

- [x] Document a tech assessment based on [this document](https://www.notion.so/decentraland/PRD-New-Friend-Requests-188555225272448f91f3eea5e84f1cd3).

**Comment by sandrade-dcl** [comment]
**RFC created**: https://www.notion.so/decentraland/RFC-Technical-Assessment-New-Friend-Request-WIP-24e8259c26544df68c1f715edbb1b896

**Comment by sandrade-dcl** [comment]
RFC approved by dServices
