### ISSUE TITLE
Add Animations to the backpack

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2734]
The avatar will now reproduce different animations when changing the wearables. Those animations are related to:
- Upper body wearables
- Lower body wearables
- Foot wearables
- Accessories

After a successful change, the avatar will reproduce another animation in world as the 3D model swaps.
This will be visible by other players.

[https://app.zenhub.com/files/337227404/926f0247-8307-48bf-9e5b-dd1a053d82dc/download](https://app.zenhub.com/files/337227404/926f0247-8307-48bf-9e5b-dd1a053d82dc/download)

### Acceptance Criteria
- [x] Corresponding animation plays in backpack when changing wearables
- [x] Another animation plays in world after change

**Comment by dalkia** [comment]
Reference placeholder animations sent by Shibu and Isa
[https://app.zenhub.com/files/337227404/f4819ffb-7bbf-4529-a8b9-4c3371fedfe4/download](https://app.zenhub.com/files/337227404/f4819ffb-7bbf-4529-a8b9-4c3371fedfe4/download)
