### ISSUE TITLE
Implement channel list of players and counter

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2735]
In order to know who are you talking with within channels, players need a way to know the number of players connected to the same channel.

- The players will be listed in a new section, accessible by a button in the channel conversation view
- The channels will display the number of connected players next to their name in the conversations list view

This definition is pending design

**Comment by olavra** [comment]
@RominaMarchetti add the design here please

**Comment by RominaMarchetti** [comment]
Here are the figma [link](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=2829%3A21201) to the channel window, and [here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=2829%3A21320) the members list window.

Functional description: a player can open the members window after clicking its button, represented by a silhouette and a number. From the members list the player can go back to the previous stage, search a specific person and open the context menu of each of them.
The players are listed without a background container at least the row is focused (same case in the voice chat list).

<img width="853" alt="Screenshot 2022-08-12 at 11 00 31" src="https://user-images.githubusercontent.com/51088292/184333507-92dfc8ea-14d0-48d5-9948-9fae7c4d8c5c.png">

**Comment by sandrade-dcl** [comment]
@RominaMarchetti we see in Figma 2 different versions for the members list: one of them replacing the channel window, and another one expanding the channel window. What would be the correct one?

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/9a749fbe-08a4-4673-ba3e-532e58526d1c)

**Comment by RominaMarchetti** [comment]
@sandrade-dcl we decided with Alvaro to go with the second option. This means that from now on the channel view will have an extra button that allows the player to expand its window to show/hide the members list. The members number in the nav bar must do the same. 
[Here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3303%3A39380) is the figma screen for reference.
