### ISSUE TITLE
Fix: Texts appearing outside their scene UI near Genesis Plaza

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2741]
Repro steps:
1. Load world at genesis plaza
2. Exit genesis plaza at -13,0, get to the nearest railroad station and you will see the light-blue texts in the viewport

https://user-images.githubusercontent.com/1031741/181346904-dd42f023-72c8-47ab-bb2b-7fab42de5c42.mp4

![hud-text](https://user-images.githubusercontent.com/1031741/181350075-00dba157-3839-4819-96ea-2c8597dd90fc.png)

**Comment by AjimenezDCL** [comment]
Fixed here: https://github.com/decentraland/unity-renderer/pull/2782
