### ISSUE TITLE
Backpack losing all custom wearables and changing outfit

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2744]
Discovered by @sandrade-dcl, repro steps:

1. Open the backpack
2. Change your shoes
3. Save
4. Notice your avatar has been corretly modified
5. Open the backpack again (do this step quickly after the previous one)
6. Change tour shoes to another ones
7. Save
8. Notice your avatar has been corretly modified
9. Open the backpack again (do this step quickly after the previous one)
10. Notice your avatar preview has lost all your custom wearables (if you go to the COLLECTIBLES tab, you won't see any wearable loadad there)

![backpack-broken](https://user-images.githubusercontent.com/1031741/181349711-eaf42c7a-86a9-4008-b9cd-bc10e06dd67d.png)

**Comment by JorgeDecentraland** [comment]
Duplicated from #2595
