### ISSUE TITLE
Fix guest name not being saved during onboarding

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2758]
Repro steps:
1. Enter https://play.decentraland.org/ in a new incognito window as guest
2. During character creation, specify any name
3. After entering the world **the name has been randomized and it's not using the one that was configured during character creation**

**Comment by lorux0** [comment]
From the renderer side, this is what i've checked:
1. `LoadProfile` message is sent from kernel with a random name, as soon as you authenticates as a guest
when you follow the signup flow, the renderer sends SendPassport message with the correct name the user typed in
2. kernel sends `LoadProfile` instantly with the correct name
3. kernel sends again `LoadProfile` with the incorrect name, the same sent in the first step
