### ISSUE TITLE
Change camera behavior when opening the main menu

### ISSUE THREAD

**Issue by JuanSalice** [decentraland/unity-renderer#2767]
Replace the current camera behavior when opening the main menu to avoid turning it off. 
Instead, change the far clipping plane to a small value to avoid rendering 3D objects and keep the camera turned on.
When the main menu is closed, the camera far clipping plane should go back to it's previous value.

**Comment by lorux0** [comment]
the blur approach will change, so we will wait until those changes are confirmed to check if this task is still valid

**Comment by sandrade-dcl** [comment]
With the new UI effects approach that @MichaelBitsakis is developing, where it is not needed any secondary camera, this task is no longer necessary to do. So we close it!
