### ISSUE TITLE
Early return to prevent flooding console

### ISSUE THREAD

**Issue by menduz** [decentraland/unity-renderer#2771]
https://github.com/decentraland/unity-renderer/blob/18897d1eaca98ecbd268bbf80253e9237c699449/unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/States/EditorMode/FreeCameraController/FreeCameraMovement.cs#L572-L574

If the `targetPosition` and `transform.position` are the same then it creates a mathematical error. An early noop return is recommended for that case.

**Comment by dalkia** [comment]
Fixed on #2775
