### ISSUE TITLE
Plaza names not visible on the map

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2798]
Description:
All plaza names are no longer visible when the map screen is opened. Issue occurs for the web and Windows desktop platforms both when logged in as a guest and with a wallet.

Steps to reproduce:
1. Log in to the game either as a guest or with a wallet.
2. After the game loads launch the map window.
3. Zoom back and navigate the view to one of the plazas.
4. Observe the issue.

Results:
No names are shown on the map for any of the plazas.

Expected results:
Plaza names are visible on the map.

Notes:
- The issue was confirmed on both wallet and guest accounts.
- The issue occurs for both the production and dev branch.
- Platform: Windows web and desktop client.
- Please see the attached screenshot for reference.

![map.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/57c3afe4-0a5d-48a1-ba83-3534532eecd4)

**Comment by davidejensen** [comment]
Findings:
In the unity side we display in the map only the parcels tagged as point of interest. For some reason the main plazas are no longer flagged as that. the error could be coming from one of the following levels:
* Kernel doesn't send the correct metadata
* Lambdas don't return the correct metadata
* Catalysts are not handling the POIs properly
* The smart contract is not handling POIs correctly

**Comment by davidejensen** [comment]
As next step I'll check on kernel level if something changes

**Comment by davidejensen** [comment]
The issue appears to be on one of the labdas/dao/smart contract, because kernel doesn't receive the plazas in the list of POIs from the following lambda: https://peer-eu1.decentraland.org/lambdas/contracts/pois

**Comment by menduz** [comment]
This should not be fixed due DAO signaling polls:
- https://governance.decentraland.org/proposal/?id=d43ed210-fd5f-11ec-8fbf-839e0f96469a
- https://governance.decentraland.org/proposal/?id=78635ac0-c4d8-11ec-86b8-5dac6b550fc4

**Comment by davidejensen** [comment]
Closing issue
