### ISSUE TITLE
[QA] The player clips through the tram

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2805]
**Description:**
The player can clip through the tram by either walking into a moving tram from the outside, or jumping multiple times while being inside the tram. In order for the issue to occur, the tram needs to gain some speed.

**Steps to reproduce:**

1. Log into the game as a guest or through a wallet.
2. Wait for the game to load.
3. Enter the map and teleport to any of the tram stations (ex. coordinates -49,-51).
4. Wait for the tram to arrive to the station.
5. Position the player in front of the tram and wait for it to start moving.
6. Begin walking into the tram.
7. Observe the issue.

**Results:**
The player can clip through the tram from inside and outside.

**Expected results:**
The player is not clipping through the tram.

**Notes:**

1. The issue was confirmed on both wallet accounts and guest accounts.
2. The issue was confirmed on the development and production configs.
3. Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/184a0897-3b63-4445-802a-a67e2414c80b/_2805.mp4.
4. Platforms: Windows Web client, Windows Desktop Client.

**Comment by anicalbano** [comment]
https://images.zenhubusercontent.com/337227404/487218fe-20fb-430a-9d96-b6da0bb267a7/17_07_2023_16_32_02_rec.mp4
