### ISSUE TITLE
Alice the robot not visible in tutorial prompts

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2806]
Description:
Alice the robot is not shown in the tutorial prompts when triggered in the vicinity of the tram line between the Genesis Plaza and the Forest Plaza (0,-10 - 0,-71). The robot reappears after leaving the tiles belonging to that vertical tram line or the Genesis Plaza or Forest Plaza.

Steps to reproduce:

1. Log in to the game either as a guest or with a wallet.
2. After the game loads launch the map window.
3. Teleport to any tile belonging to the tram line (0-1,-12 - 0-1,-69) or the Forest Plaza.
4. Open up the settings menu and launch the tutorial.
5. Observe the issue.

Results:
Alice the Robot is not shown in the tutorial prompts when the tutorial is triggered from the specified locations.

Expected results:
Alice the robot is shown in the tutorial prompts.

Notes:
- The issue was confirmed on both wallet and guest accounts.
- The issue occurs for both the production and dev branch.
- Platforms: Windows Web and Desktop clients.
- Please see the attached screenshot for reference.

![Capture.PNG](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/ab5af217-fe22-4b8e-85a4-f30d7f4a323a)

**Comment by dalkia** [comment]
Being solved in #2755

**Comment by dalkia** [comment]
Merged #2755 into dev! Please give it a look and we can close this issue to. @kwssbocian

**Comment by kwssbocian** [comment]
I verified the fix on dev and the robot would always appear for each tutorial prompt. Looks good for merging!
