### ISSUE TITLE
Missing avatar picture in passport view for guest

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#2812]
When displaying the passport of a guest user, the avatar image is missing. For users with wallet the avatar is displayed properly. 
Can repro both on web and desktop.

![Screenshot_973.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/176cc5c8-dd76-4b5e-8416-a81b48366fe9)

**Comment by PalauiDCL** [comment]
This error is due to the method `SetFaceSnapshot` in `PlayerInfoCardHUDView`:
```
public void SetFaceSnapshot(Texture2D texture)
{
    avatarPicture.texture = texture;
}
```
Contains a null texture as a parameter.

The next step is to check the avatar texture generation for guest users

**Comment by PalauiDCL** [comment]
![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/150958ea-5038-4287-997c-fc0f184a95c5)

![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/fa44d133-3735-4ba8-abd6-3869d6963bfb)

![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/36395129-dd11-4aeb-81be-6067241f7a20)

This error is not only for Guests, can be reproduced on users with connected wallet too

**Comment by PalauiDCL** [comment]
Issue should be solved by this PR https://github.com/decentraland/unity-renderer/pull/3072
