### ISSUE TITLE
Noticeable lag when opening and closing main menu

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#2813]
- The performance of the Start Menu while opening and specially while closing is really bad. 
We need to aim for a smooth and instant transition between the world and the menu, and right now is taking up to 3 seconds in some cases, ruining the experience.
- There is quite a significant lag when opening or closing the main menu from any of its modules ( Events, Map, Backpack).

## Opening 

The performance drop when opening any tab is caused by a reparenting of the whole module, we should avoid that and instead, we should spawn the UI in their respective places or find a better solution to prevent reparenting an entire hierarchy of game objects.

![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/b0bca158-0f8d-4720-90ba-aad4bfae12ae)

## Closing

When closing the whole UI, the disable is taking a lot of time ( I'm not sure if we can avoid this ) but the avatar editor is loading the user profile again for some reason

![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/c5fab678-42f1-4316-b47a-3c13f798f562)

**Acceptance criteria**

- [ ] Performance improved

**Comment by popuz** [comment]
during my investigation I saw, that 
- open/close from UI is faster than shortcut in all cases
- Events and Settings sections don't have .SetParent when Opened/Closed from UI

**Comment by popuz** [comment]
results from previous comment was from Standalone Profiler. Inside Unity profiler behaves the same for both scenarios

**Comment by popuz** [comment]
Transfrom.SetParent() happens because of moving from MinimapHUD inside Map section of Explorer and vice-versa

**Comment by popuz** [comment]
- Settings: 10 ms - all good 
- Events: 90/31 ms for enable/disable - PlacesAndEventsSection GO enable/disable eat half of it
- Backpack: 90 ms - Image/TMPro/etc OnCanvasHierarchyChanged/OnCanvasGroupChanged from active and non-active NFTItemToggle(Clone) GOs
- Map: 500/1000 ms for enable/disable - reparenting Map from ExploreV2 MapSection into MinimapHUD. On disabling there is also disabling of ScrollRect in MapScection, which eats 1/3 of it (but reparenting is twice bigger). Also, after enabling Map section once, then it will affect all other sections OnDisabling

**Comment by xavi-dcl** [comment]
@popuz what is the status of this?

**Comment by popuz** [comment]
@xavi-dcl @m3taphysics, I extracted Backpack performance to the #3570

**Comment by xavi-dcl** [comment]
Closing as we have followup issues
