### ISSUE TITLE
Performance degradation introduced by fixes scene bounds checker

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#2814]
After releaseing `1.0.47078-20220803165043.commit-08eab36` we have notice degradation in performance.
The suspected culprit is changes made to the scene boundaries checker.

The changes affected average fps on both platforms:
![Screen Shot 2022-08-09 at 10.02.11.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/10f64da7-7827-41bd-bcd3-ae8fdf0e67cf)

It caused also 5ms per frame regression on the p50, which is quite significant.
![Screen Shot 2022-08-09 at 10.30.41.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/5fad5c4d-7356-4ff0-b5b5-0834a87f623f)

**Comment by davidejensen** [comment]
The investigation consisted in: 
* Analyzing the changes introduced with this PR: https://github.com/decentraland/unity-renderer/pull/2164
* Profiling without and with those changes
* Discussing about the changes with Pravus

The changes themselves introduces some optimiziations, more info can be found here: https://github.com/decentraland/unity-renderer/blob/dev/docs/scene-boundaries-checking.md

The main change that affected performance has been an increment of the `MAX_GLOBAL_MSG_BUDGET`, this change affects slightly the performance but it allows the SceneChecker to run at a decent speed, lowering the value could improve the performances back again but might slow the SceneBoundaries checker too much and cause some bug to reappear.

If we decide to experiment with different values we need to always test thoroughly the following bugs:
### https://github.com/decentraland/unity-renderer/issues/2132 issue
1. Spawn [at -12, -10](https://play.decentraland.zone/?renderer-branch=fix/OutOfSceneBoundsEntitiesCheck&LOCAL_COMMS&position=-12%2C-10) and wait until Genesis Plaza finishes loading (make sure the Scene Load Radius value in the settings is 4) 
2. Open Settings, change the Scene Load Radius to 1 and wait 5~ seconds
3. Change Scene Load Radius to 4 and close the settings panel, wait for 5~10 seconds after the Genesis Plaza finishes loading and notice that he "black and white" bug doesn't happen anymore
4. Steps 2 and 3 can be reproduced many times and the black and white bug won't happen again 
[Doing those steps from master's build will trigger the black and white bug]

### https://github.com/decentraland/unity-renderer/issues/844 issue
1. Spawn [at -12, -10](https://play.decentraland.zone/?renderer-branch=fix/OutOfSceneBoundsEntitiesCheck&LOCAL_COMMS&position=-12%2C-10)
2. Walk towards the tramline at -12, 0
3. Walk through the tramline to the west, and notice that no mesh is instantiated int the middle of the street
