### ISSUE TITLE
Problems refreshing the profile information after changing it

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#2823]
### What?
After update our profile information (name and/or description) from the Profile HUD, the information is being successfully saved internally but if you close and open again the Profile HUD, the information showed is he previous one, not the last saved.
The issue seems to occur only on the wallet version.

### Steps to reproduce:
1. Open the ProfileHUD.
2. Change the description.
3. Check the description has been updated corretly in https://account.decentraland.org
4. Close the ProfileHUD and open it again.
5. Notice the description shows the old text instead the new one.

Notes:

- Adding some logs with the specification of the machine on which the issue occurred: [https://app.zenhub.com/files/337227404/77afd50a-dc13-44d0-aca9-cd6bb974db6d/download](https://app.zenhub.com/files/337227404/77afd50a-dc13-44d0-aca9-cd6bb974db6d/download)

- **IMPORTANT:** We have noticed that this issue is also affecting to the equipped wearables of the user, and not only to the profile name/description.

### Acceptance Criteria
- [ ] Name and description updates correctly after editing it
- [ ] Wearables update correctly after changing them

**Comment by dalkia** [comment]
https://images.zenhubusercontent.com/337227404/03904eee-2e3f-4f6a-8a4d-bfbdbab7c6a5/2022_08_10_10_53_19.mp4

Video example on Windows

**Comment by sandrade-dcl** [comment]
It should be probably solved from the kernel side. Kernel should always send us the last profile saved. Anyway we have to research deeper.

**Comment by JorgeDecentraland** [comment]
@dalkia could you confirm if Kernel is sending the correct profile, please?

**Comment by dalkia** [comment]
I can indeed confirm that Kernel is not sending the correct profile after update.
When changing the name, Kernel sends the correct profile after saving. However, when opening the modal for a second time, the old profile is returned.

**Comment by dalkia** [comment]
Fixed in kernel in this commit
https://github.com/decentraland/kernel/commit/f7c14342bd8a89736e6c6357334ea957f43552d2
