### ISSUE TITLE
Voice chat input not being registered on MacOS Desktop client

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2824]
Description:
Voice chat feature on MacOS DESKTOP is not registering voice input. The voice chat prompt appears for all the nearby users but no voice is being registered. 

Steps to reproduce:

1. Log in to the game either as a guest or with a wallet with two different accounts, one of them on MacOS DESKTOP client.
2. Navigate both characters to be near each other.
3. On MacOS character press the talk button on the taskbar.
5. Observe the issue.

Results:
Voice input is not being registered.

Expected results:
Voice input is being registered.

Notes:
- The issue was confirmed on both wallet and guest accounts.
- Platforms: MacOS DESKTOP.

**Comment by JorgeDecentraland** [comment]
This is going to be solved once #2844 is done

**Comment by xavi-dcl** [comment]
@kwspgoliasz is this still happening?

**Comment by kwssbocian** [comment]
@xavi-dcl Cannot reproduce. On both prod and dev the issue no longer occurs

**Comment by xavi-dcl** [comment]
Closing as it cannot be reproduced
