### ISSUE TITLE
Plane on texture broken with unexpected alpha and missing emission effect

### ISSUE THREAD

**Issue by pabloes** [decentraland/unity-renderer#283]
Since last rendering update (2021-04-20), texture on plane appears corrupted, is like some colours are converted to alpha 0 when they don't have alpha. Also emissive effect is missing while in graphics options "bloom" is activated. 
Those details were working well before the update.

Screenshots:
https://ibb.co/KGHQQJR
https://ibb.co/vXbP6HF

Original texture file image applied to plane:
https://ibb.co/19yQ0wM

Location to test: https://play.decentraland.org/?position=-30,61

Environment:
MacBook Pro (Retina, 15-inch, Mid 2015) - macOs Bug Sur 11.2.3 (20D91)
Chrome Browser - Version 89.0.4389.128 (Official Build) (x86_64)

These are the properties used on the material on SDK code:
```
const spriteTexture = new Texture(spriteUrl, {samplingMode:0, hasAlpha:true});
spriteMaterial.albedoTexture = spriteTexture;
spriteMaterial.alphaTexture = spriteTexture;
spriteMaterial.emissiveTexture = spriteTexture;
spriteMaterial.emissiveIntensity = 0.5;
spriteMaterial.emissiveColor = new Color3(1,1,1);
spriteMaterial.transparencyMode = 1;
spriteMaterial.specularIntensity = 0;
spriteMaterial.roughness = 1;
```

**Comment by BrianAmadori** [comment]
Issue transferred to https://github.com/decentraland/unity-renderer/issues/283

**Comment by pabloes** [comment]
here you can see approximation of range of colors that are render as alpha 0: https://ibb.co/bW6HbVh

here original texture sprite: https://ibb.co/DKJBmKG
