### ISSUE TITLE
Issues with the interaction for some teleportation prompts on the boards located in the game's entrance area above the Genesis Plaza

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2834]
**Description:**
The player is unable to interact with some of the teleportation prompts located on the boards in the game's entrance area above the Genesis Plaza. The issue most often occurs for the events and places located in the upper part of the Events and Crowd boards. In those cases, it is impossible to interact neither with the coordinates nor the jump in button. For the Classics board, the player is not able to interact only with the coordinates button.

**Steps to reproduce:**

1. Log in to the game as a guest or through a wallet.
2. Wait for the game to load.
3. Approach the Events board.
4. Scroll to the Events located in the upper part of the board.
5. Attempt to interact with the teleportation prompt buttons.
6. Observe the issue.

**Results:**
The player is unable to interact with some of the teleportation prompts on the board in the game's entrance area.

**Expected results:**
The player can use any teleportation prompt located on the boards.

**Notes:**
1. The issue was confirmed on both wallet accounts and guest accounts.
2. The issue was confirmed on the development and production configs.
3. For the Events and Crowd boards, the prompts can sometimes become interactable after some time passes.
4. Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/a12ee4bb-ecac-4a38-998e-46b21bb3d39d/_2794.mp4.
5. Platform: Windows Web client.

**Comment by davidejensen** [comment]
This issue can be closed because it has been fixed with the following commit: https://github.com/decentraland/unity-renderer/commit/a12238b6147fc1684b362307b513663a7cd3cd86 it is still present in production but with the next release it will be solved
