### ISSUE TITLE
cant move

### ISSUE THREAD

**Issue by carolinarocket** [decentraland/unity-renderer#2835]
### What happened?

just jone,started titorial and it says push ASDW to move around or arrows and i try and nothing?

### Steps to reproduce

let me know how to fix or move aorund

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 5500U with Radeon Graphics 

### GPU

AMD Radeon(TM) Graphics 3760MB

### RAM

7521MB

### Kernel Version

1.0.0-2800112869.commit-daa9447

### Unity Version

desktop-1.0.508-20220803173003.commit-fa5b53d

### Realm

dg

### NameTag

CarolinaRocket#d71b

**Comment by JorgeDecentraland** [comment]
@kwssbocian can you reproduce this issue?

**Comment by kwssbocian** [comment]
@JorgeDecentraland No, unfortunately not. I checked for the issue on Windows desktop, web and even MacOS clients and every single time movement was working correctly during the initial tutorial.

**Comment by JorgeDecentraland** [comment]
Closing the issue due to the lack of response from user and we were unable to reproduce it
