### ISSUE TITLE
Implement manual connection to Voice Chat

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2844]
Due the technical problems related to browser permission, some players may need to manually connect to the voice chat.
So far, the system automatically connect to it, and if the player decides to leave, the voice chat HUD dissapears.
Now, it will always be present, even if your are not connected to it.

In the case the player is not connected, the HUD will become a button to Join in a single click.

**Acceptance Criteria**
- [x] The system will always automatically try to connect to the voice chat
- [x] When voice chat is disconnected, the HUD will be a button
- [x] Disconnecting from the voice chat will turn the HUD into a button to rejoin

**Comment by RominaMarchetti** [comment]
[Here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3204%3A29625) is design of this new state of the voice chat module. [Here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3206%3A30352) the module with the rest of the world UI.

![Screenshot 2022-08-12 at 17.24.46.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/027e7e59-9231-468a-8e6c-cba1be10646b)

@olavra the copy is quite explicit about what the button does. Do you still think the toast is necessary?

**Comment by sandrade-dcl** [comment]
Slack conversation about this: [here](https://decentralandteam.slack.com/archives/C03PNEAE38B/p1659450540160789?thread_ts=1659362085.465559&cid=C03PNEAE38B).

**Comment by RominaMarchetti** [comment]
- [ ] Implement the new UI style for the instance of the voice chat module `JOIN`.
- [ ] Implement the `Automatic connection failed` toast. The word `JOIN` must connect the voice chat.

[Figma for reference here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3206%3A30352).

**Comment by olavra** [comment]
UI Changes will be implemented in another ticket , lets close this one. #3630
