### ISSUE TITLE
Collectibles tab in backpack appears blank when logged in using a wallet

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2857]
Description:
The Collectibles tab in the backpack menu appears blank and does not show any message when not having any collectibles when logged in with a wallet. Such message is visible for the Skins tab but is not visible for the Collectibles tab.

Steps to reproduce:
1. Log in to the game using a wallet.
2. Open up the backpack and navigate to the "Collectibles" tab.
3. Observe the contents of the collectibles interface.

Results:
Interface for the Collectibles tab in the inventory appears blank.

Expected results:
Interface for the Collectibles tab shows a message informing of not having any collectibles.

Notes:
-Platforms: Windows web, production and dev branch.
-Issue occurs only for the wallet login and not for the guest login.
-Please see the attached screenshot for reference.
 ![image.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/1476d2e9-a7be-4006-97c3-6b08c6e60449)

**Comment by JorgeDecentraland** [comment]
@kwssbocian do you actually own any collectibles?

**Comment by JorgeDecentraland** [comment]
@kwssbocian can you confirm that you can reproduce this while having collectibles?

**Comment by kwssbocian** [comment]
At the time of reporting that account did not have any collectibles however I have been informed that the Collectibles section should be showing a notice of no collectibles being owned, like the one in the Skins section. When having collectibles the section is showing them correctly.

**Comment by JorgeDecentraland** [comment]
Ok, could you update the description of the ticket specifying that the problem is the lack of a message when the user does not have collectibles, please?

**Comment by JorgeDecentraland** [comment]
@RominaMarchetti could you provide a text for the message to show when a user does not have collectibles, please?

**Comment by RominaMarchetti** [comment]
<img width="481" alt="Screenshot 2022-09-07 at 13 31 07" src="https://user-images.githubusercontent.com/51088292/188931630-29a86e9e-8f16-4a48-9149-5ae418bc4d3b.png">

Title: `You don't own any collectible yet.`
Subtitle: `Explore the Marketplace and start enjoying amazing wearables!`

**The image and texts font styles must be the same than the ones used in the skins section.**

**Comment by PalauiDCL** [comment]
![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/70a5ff8b-f9ba-46cc-9756-8ebc0ae757d3)
Currently collectibles do not have an EmptyItemList, I will be adding one to the prefab and update the code accordingly

**Comment by PalauiDCL** [comment]
![image](https://user-images.githubusercontent.com/113350816/190366706-3ee1858a-d9fa-4b85-85c0-b754a66d5d66.png)

Added the collectible empty entry, I suggest testing with an account that has collectibles too to check if there are no overlaps.

**Comment by RominaMarchetti** [comment]
@PalauiDCL it works fine without any overlapping 👍 
You already have 2 approves so it's ready to merge :)
