### ISSUE TITLE
The emotes shortcut is incompatible with the NUM Lock

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2863]
**Description:**
The 'hold B + number' emotes shortcut cannot be used with the NUM Lock keys.

**Steps to reproduce:**

1. Log into the game as a guest or through a wallet.
2. Click 'I' button to enter the main menu.
3. Set any emote in the emotes section.
4. Return to the game.
5. Activate the NUM Lock.
6. While holding 'B' press any of the NUM Lock's numerical keys.
7. Observe the issue

**Results:**
The emotes shortcut cannot be used with the NUM Lock keys.

**Expected results:**
The player can use the NUM Lock keys to activate the emotes.

**Notes:**

1. The issue was confirmed on both wallet accounts and guest accounts.
2. The issue was confirmed on the development and production configs.
3. Please see the attached video in which the shortcut is used with both the regular number key and the NUM Lock key - https://images.zenhubusercontent.com/337227404/0cbf15b6-a469-4ddd-947c-4c64d2c5e61c/_2863.mp4.
4. Platforms: Windows Web client, Windows Desktop Client.

**Comment by JorgeDecentraland** [comment]
Closing this issue as @olavra confirmed this is expected behavior
