### ISSUE TITLE
OnPointerDown can't be removed

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#287]
This was reported by the Decentral Games team

Hey guys, I noticed a potential bug with OnPointerDowns after the latest explorer update. It appears that when removing the OnPointerDown component within the OnPointerDown callback like so, the component will be removed from the engine but a "ghost" hoverText will remain and it will still appear clickable, though the callback won't run anymore

```
let x = new Entity();
x.addComponent(new BoxShape());
x.addComponent(
  new Transform({
    position: new Vector3(3, 1.5, 3),
  })
);
x.addComponent(
  new OnPointerDown(() => {
    log('Clicked!');
    x.removeComponent(OnPointerDown);
  })
);
engine.addEntity(x);
```

![image.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/807e65c7-c227-43f7-8d88-00634117caab)

This was tested locally using decentraland-ecs@next but it's replicable on prod with our blackjack tables

**Comment by BrianAmadori** [comment]
Mea culpa maxima...
![image](https://user-images.githubusercontent.com/6875814/115905606-b402af80-a43c-11eb-9081-1527a72dc9b3.png)

**Comment by BrianAmadori** [comment]
Addressed in:
https://github.com/decentraland/explorer/pull/2321
