### ISSUE TITLE
Teleportation modal over map screen not appearing during character movement

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2874]
Description:
During any sort of character movement occurring horizontally the teleportation modal in the map interface refuses to appear after clicking on any tile on the map. Example situations would be the horizontal portion of the balloon flight at Genesis Plaza or the tram ride near Genesis Plaza whenever the tram is moving and is not exclusive to those locations..

Steps to reproduce:
1. Log in to the game using a wallet or on a guest account.
2. Go to the Genesis Plaza at -4,2 where the Air Balloon is located.
3. Enter the balloon.
4. While flying the balloon open up the map interface and click on any of the tiles on the map.
5. Observe the map interface.

Results:
Teleportation modal does not appear.

Expected results:
Teleportation modal appears.

Notes:
- Platforms: Windows and Mac web and desktop, production and dev branch.
- Issue occurs for both wallet and guest login.
- Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/9d7a55df-1e68-42bb-bf5f-ec27dd040e89/2022_08_17_16_12_15.mp4

**Comment by JorgeDecentraland** [comment]
kwssbocian can you please try to reproduce this issue under different circumstances, like the character standing on any platform, elevated, performing emotes, or any other circumstance you can think of, please?

**Comment by kwssbocian** [comment]
I was able to reproduce the issue only when there occurred a horizontal movement of the character. During the tram ride the whole time the tram was riding I was unable to open up the teleportation modal. If I pre-opened it while the tram was still stationary it would close immediately after the tram started going.
I was unable to reproduce the issue during a vertical ascent on a platform, while being stationary at bigger heights or while performing any emotes.

**Comment by JorgeDecentraland** [comment]
Understood, please update the title/description of the ticket so that it's clear that the issue is not exclusive to the balloon flight
