### ISSUE TITLE
Searching for the #nearby channel makes it multiply in the chat list

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2875]
**Description:**
The player can multiply the '#nearby' channel in the chat list. In order to reproduce the issue, the player needs to search for the 'nearby' channel and then press 'Enter' two times for the searched phrase to become highlighted. The #nearby channel gets multiplied after deleting the highlighted phrase.

**Steps to reproduce:**

1. Log into the game as a guest or through a wallet.
2. Open the chat.
3. Click the arrow in the upper left corner to enter the chat list.
4. Search for the 'nearby' chat.
5. Press 'Enter' two times in order to highlight the searched phrase.
6. Delete the highlighted phrase.
7. Observe the issue

**Results:**
The '#nearby' channel can be multiplied in the chat list.

**Expected results:**
The chats cannot be multiplied in any way.

**Notes:**

1. The issue was confirmed on both wallet accounts and guest accounts.
2. The issue was confirmed on the development and production configs.
3. Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/e4ecc1f5-f6ae-4455-b469-fc34486a8472/_2875.mp4.
4. Platforms: Windows Web client, Windows Desktop Client.

**Comment by sandrade-dcl** [comment]
**NOTE:** This issue is already fixed in the Lazy Loading branch.
