### ISSUE TITLE
Friend's profile displayed out of bounds

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2882]
**Description:**
When right-clicking on a private message from a friend in order to access their profile, the profile's action list is displayed partially outside of the window boundaries.

**Steps to reproduce:**

1. Log into the game through a wallet.
2. Add someone as a friend.
3. Have the friend write a direct message.
4. Access the message in the chat.
5. Right-click on the message. 
6. Observe the issue

**Results:**
Friend's profile is partially displayed outside of the game window.

**Expected results:**
Friend's profile is displayed inside the boundaries of the game window.

**Notes:**

- The issue occurs only on wallet accounts.

- The issue was confirmed on both the development and production configs.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/18487422-d111-4890-8025-36e8cd9e25cf/_2882.mp4.

- Platforms: Windows Web client, Windows Desktop Client.

**Comment by davidejensen** [comment]
This issue appears to be related to the anchor point of the context menu of the user profile, it happens in webgl but it doesn't happen in unity, I'm trying to find the cause
