### ISSUE TITLE
MaterialTransitionController placeholder renderer is not being toggled based on entity's inside scene boundaries state

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#2886]
Basically: the [`MaterialTransitionController`](https://github.com/decentraland/unity-renderer/blob/dev/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MaterialTransitionController/MaterialTransitionController.cs) placeholder renderer is not being toggled based on the entity "inside scene boundaries" state. Also, we are showing the final renderer (not the placeholder one) with a one-time hologram effect when the [`MaterialTransitionController`](https://github.com/decentraland/unity-renderer/blob/dev/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MaterialTransitionController/MaterialTransitionController.cs) finishes, thus showing the asset regardless of being outside its scene boundaries, for example in the scene mentioned in this issue's original description.

[This old bug](https://github.com/decentraland/unity-renderer/issues/978) keeps happening and can be used to test and debug the problem (the bucket entity ID is `13312`).

**Comment by xavi-dcl** [comment]
Closing since GLTFast is integrated
