### ISSUE TITLE
MacOS App - No sound from video stream

### ISSUE THREAD

**Issue by chappydboz** [decentraland/unity-renderer#2887]
### What happened?

i have a video screen playing... the video works, but theres no sound using the new macos app.. the browser version has sound.  (I do hear other DCL sounds like sound effects, ui etc) 

### Steps to reproduce

testing at -49,81 

### Operating System

Mac OS X 12.5.0

### Wallet

Wallet Connect

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro 10922MB

### RAM

16384MB

### Kernel Version

1.0.0-2877189490.commit-01c0714

### Unity Version

desktop-1.0.525-20220817160826.commit-8b01482

### Realm

dg

### NameTag

PURPLEBEETV#473b

**Comment by davidejensen** [comment]
We are already investigating this issue, you can find the progress of it here https://github.com/decentraland/explorer-desktop/issues/322
