### ISSUE TITLE
Implement NFT emotes loop property

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#2892]
Emotes flagged as "loop" needs to be played as a loop

[Documentation](https://www.notion.so/decentraland/PRD-NFT-Emotes-7a32110391f94ac884303712733602f8#693d62823b38459e880c1228ed50fb60)

**Acceptance Criteria**
- Emotes flagged as loop are played continuously
- Moving the player in any direction or jump cancels the emote loop
- Other players can see players reproducing loop emotes in a seamless way (no gaps between iterations)

**Comment by Antivortex** [comment]
https://github.com/decentraland/unity-renderer/pull/2937

**Comment by Antivortex** [comment]
https://github.com/decentraland/unity-renderer/pull/2937
