### ISSUE TITLE
Missing or corrupted letters of ICE Poker's interface buttons

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2893]
Description:
Letters for the floating action buttons of the ICE Poker's interface are either missing or appear corrupted. Issue appears to occur only for the leftmost button of the top row as well as for the red and blue buttons of the lower row.

Steps to reproduce:
1. Log in to the game using a wallet account with an ICE Enabled wearable.
2. Go to the ICE Poker - Stronghold at -102,129.
3. From the popup that appears choose "Find me a table" and move over to the table designated by the green arrow.
4. Enter the poker game.
5. Observe the poker game's interface buttons.

Results:
Letters on the poker game's buttons are missing or corrupted.

Expected results:
Letters on the poker game's buttons are present and forming words.

Notes:
- Platforms: Windows and Mac web and desktop, production and dev branch.
- Please see the attached screenshot for reference.
![Screenshot 2022-08-23 092838.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/4d211881-15f8-4577-9a80-4530af5ba07c)

**Comment by davidejensen** [comment]
This issue appears to be related to the TextShape prefab, the texts that are shown correctly are with a congruent material between the mesh renderer material and the text mesh pro material:

![Screenshot 2022-08-30 at 10.50.04.png](https://images.zenhubusercontent.com/61e566afd594605681c8aeb7/b78caa53-e7fb-4630-9c65-589df56ca024)

The broken texts have different materials on the two slots:

![Screenshot 2022-08-30 at 10.52.01.png](https://images.zenhubusercontent.com/61e566afd594605681c8aeb7/c1ad2e52-25bc-4c89-ace0-5f57a7f2c247)

**Comment by davidejensen** [comment]
At first all the texts are working fine, after the first time they get disabled they appear to be broken, might be the scene that is sending a font change when disabling

**Comment by davidejensen** [comment]
The following performances have been measured during a play in ice poker, they might vary a lot also due to the amount of surrounding users that changes constantly

Performance with optimization
```
 * PERFORMANCE SCORE (0-100) -> 99
 * lowest frame time -> 21.9ms
 * average frame time -> 26.7ms
 * highest frame time -> 100.0ms
 * 1 percentile frame time -> 22.5ms
 * 50 percentile frame time -> 26.4ms
 * 99 percentile frame time -> 39.3ms
 * error percentage -> ±1.1%
 * total hiccups (>0.05ms frames) -> 4 (0.36% of frames were hiccups)
 * total hiccups time (seconds) -> 0.361496
 * total frames -> 1123
 * total frames time (seconds) -> 30.01492
 * lowest allocations (kb) -> 41.881
 * highest allocations (kb) -> 1567.207
 * average allocations (kb) -> 152.959
 * total allocations (kb) -> 171773.828
```

Performance without optimization:
```
 * PERFORMANCE SCORE (0-100) -> 99
 * lowest frame time -> 20.9ms
 * average frame time -> 26.8ms
 * highest frame time -> 100.0ms
 * 1 percentile frame time -> 22.7ms
 * 50 percentile frame time -> 25.3ms
 * 99 percentile frame time -> 40.2ms
 * error percentage -> ±1.1%
 * total hiccups (>0.05ms frames) -> 4 (0.36% of frames were hiccups)
 * total hiccups time (seconds) -> 0.3608398
 * total frames -> 1121
 * total frames time (seconds) -> 30.00563
 * lowest allocations (kb) -> 38.833
 * highest allocations (kb) -> 2053.658
 * average allocations (kb) -> 171.109
 * total allocations (kb) -> 191814.008
```
