### ISSUE TITLE
Unable to get owned wearebles on zone

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#290]
When we are trying to recover the owned werables from zone calling `RequestOwnedWereables` with the userId `0xdedd78d3ff1533979f7f5302c95cfa63d9e0d09a,` the result is empty. 

We know that the user has 2 owned wearables.

We need to figure out where the problem is, it is kernel?  It is in the call to Thegraph? Is in another site?

**Comment by olavra** [comment]
Waiting for the PR #2300
