### ISSUE TITLE
New avatar is mostly invisible after spawn

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2906]
**Description:**
When creating a new character, confirming the default appearance as soon as the option becomes available results in the the avatar being mostly invisible after spawning in the Genesis Plaza.

**Steps to reproduce:**

1. Clear the Decentraland's website data cache or launch the incognito mode.
2. Launch the game.
3. Accept the default character appearance as soon as the 'Done' button becomes clickable.
4. Continue setting up your profile.
5. Observe the issue after the avatar spawns in the Genesis Plaza.

**Results:**
A new player Avatar is mostly invisible after spawn, if the default appearance is accepted as soon as possible during the character creation.

**Expected results:**
A new character is always properly spawned.

**Notes:**

- The issue occurs only on the Web client.

- Changing the avatar's appearance in the backpack fixes the issue.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/3c473bca-afa2-45f1-b61c-c819fe6c2eb1/_2906.mp4.

- Platform: Web Client.

**Comment by JorgeDecentraland** [comment]
@kwspgoliasz what's the reproduction rate of this issue? And is it happening in production?

**Comment by kwspgoliasz** [comment]
@JorgeDecentraland The issue occurs in both the production and development configurations. As for the reproduction rate I would say it's around 4/5 attempts.

**Comment by davidejensen** [comment]
@kwspgoliasz could you please check if this is still happening? I'm not managing to reproduce it and it might be that it was fixed with recent changes to the hologram and transition

**Comment by davidejensen** [comment]
Not happening anymore for what I can see, closing
