### ISSUE TITLE
Sound of audio guide cutting off and looping for multiple exhibitions at Metaverse Art Week

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2920]
Description:
The sound of the audio guide keeps cutting off and looping for multiple exhibitions at the Metaverse Art Week area. Issue usually occurs at the first word of the whole speech and therefore not allowing to hear the audio guidance prepared for that exhibition.
Confirmed affected exhibitions:
- OpenSea Gallery
- AI Pixelmind Art Gallery
- Gernic Primo
- Burton Morris - Pop!Wall

Steps to reproduce:
1. Log in to the game with a wallet account. 
2. Go to 61,61 to the Metaverse Art Week Welcome Area. Ensure you have picked up the audio guide wearable and put it on.
3. From the Welcome Area walk over to the OpenSea gallery at 62,57. 
4. On the audio guide prompt underneath the minimap press the "Play Audio" button.
5. Notice the sound of the guide cutting off.
6. Walk over to the AI Pixelmind Art Gallery nearby at 65,55.
7. Play the audio guide for that exhibition.
8. Notice the sound of the guide cutting off for this exhibition as well.

Results:
Sound for the audio guide keeps cutting off.

Expected results:
Sound for the audio guide does not cut off.

Notes:
Platforms: Windows web and desktop, production branch.

**Comment by wacaine** [comment]
[audiostream-bug-scene.zip](https://github.com/decentraland/unity-renderer/files/9427203/audiostream-bug-scene.zip)

```
AudioStream
playing=false is not working even if   I must set it volume 0 to give the illusion it was removed
  playing=false - does not stop it
  removeComponent - does not stop it
  engine.removeEntity - does stop it
playing=false = false then play = true restarts the audio.  need a way to resume where paused like video

On certain audio streams it just randomly restarts the audio while others it plays through
````

**Comment by wacaine** [comment]
https://decentralandteam.slack.com/files/U0368CBHSDS/F03V67XAC74/audiostream-bug.mov

**Comment by kwspgoliasz** [comment]
The issue is fixed. No more looping and cutting off was observed for the audio guides.

**Comment by wacaine** [comment]
@kwspgoliasz    We switched from using AudioStreams to AudioSource to workaround this bug.  AudioStream is still VERY BROKE

**Comment by wacaine** [comment]
New issue created here https://github.com/decentraland/sdk/issues/428
