### ISSUE TITLE
Art Week - The pause button for the audio lacks functionality for specific scenes

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2921]
**Description:**
The audio continues to play after pressing the pause button in specific scenes of the Art Week area. Moreover, leaving the scene while the audio is set to paused makes the audio keep playing outside of the scene area.
In order to reproduce the issue, the player needs to log in with a wallet account in order to receive the Art Week headphones collectible.
The issue occurs at the following locations:

- VVSVS - (54,63)

- CryptoArg - (54,68)

- Meta Borealis - (56,67)

- Gavin Saphiro - (62,69)

- Digital Panopticon - (69,55)

- Burton Morris - Pop!Wall - (65,52)

**Steps to reproduce:**

1. Load into the game via a wallet.
2. Reach the Art Week Welcome area (61,60)
3. Receive the event headphones from the main building.
4. Equip the headphones from the backpack menu ('I').
5. Go to one of the locations mentioned in the description.
6. Play the audio.
7. Pause the audio.
8. Observe the issue.

**Results:**
The audio pause button does not work for specific scenes.

**Expected results:**
The audio pause button always works as intended.

**Notes:**

- The issue occurs on only on the wallet accounts.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/8c236e16-63d2-49a3-9c2b-f4af9ef40c29/_2921.mp4.

- Platforms: Windows Desktop Client, Web Client.

**Comment by wacaine** [comment]
```
AudioStream
playing=false is not working even if   I must set it volume 0 to give the illusion it was removed
  playing=false - does not stop it
  removeComponent - does not stop it
  engine.removeEntity - does stop it
playing=false = false then play = true restarts the audio.  need a way to resume where paused like video

On certain audio streams it just randomly restarts the audio while others it plays through
````
[audiostream-bug-scene.zip](https://github.com/decentraland/unity-renderer/files/9427210/audiostream-bug-scene.zip)

**Comment by wacaine** [comment]
https://decentralandteam.slack.com/files/U0368CBHSDS/F03V67XAC74/audiostream-bug.mov

**Comment by kwspgoliasz** [comment]
The issue is fixed. After the latest fixes the pause button is functional at all of the mentioned locations.
