### ISSUE TITLE
Issues with hair clipping caused by the Head Explode emote

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2934]
**Description:**
The 'Head Explode' emote animation causes the hair to clip with the head for specific hairstyles.

**Steps to reproduce:**

1. Load into the game as a guest or via a wallet.
2. Press 'I' to enter the backpack.
3. Equip the 'Head Explode' emote from the emotes section.
4. Choose the Hair section of the Head tab.
5. Choose any of the **non crossed out** hairstyles from the screenshot. ![#2934_01.jpg](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/4858497c-d0bd-43cb-85ff-73b0e8c195b8)
5. Exit the menu.
6. Use the 'Head Explode' emote.
7. Observe the issue.

**Results:**
The animation for the 'Head Explode' emote causes clipping issues with multiple hairstyles.

**Expected results:**
Lack of clipping issues when using the emotes.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- The issue occurs for all of the hairstyles besides the ones crossed out in the screenshot.

- The degree of the clipping depends on the hairstyle. 
![#2934_02.jpg](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/e0778e3f-a8e1-4421-acc6-76e86aa23d48)

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/7ed6a3c5-fdc8-45bb-8da0-d2ec6eb31697/_2934.mp4.

- Platforms: Windows Desktop Client, Web Client.

**Comment by davidejensen** [comment]
Only some hairs are generating this problem, the broken ones in an isolated scene they are behaving correctly attached to the skeleton we use at runtime as per the following screenshot

![Screenshot 2022-09-14 at 12 07 18](https://user-images.githubusercontent.com/4254522/190161884-b309fa13-b0a3-433a-9eba-a7f10f8c4eae.png)

The broken ones are visibly having an issue with the lower part, it looks like they are not animated partially:

![Screenshot 2022-09-14 at 12 06 35](https://user-images.githubusercontent.com/4254522/190162243-77254fe3-e987-4961-9c6e-7990280da099.png)
![Screenshot 2022-09-14 at 12 06 23](https://user-images.githubusercontent.com/4254522/190162251-f3f89ce3-93f5-4f70-aba0-71a2369d066b.png)

Blocking the issue while waiting for Shibu's feedback

**Comment by m3taphysics** [comment]
@ShibuyaMartin can you provide feedback on the above?

**Comment by ShibuyaMartin** [comment]
Hey guys! Yes, i need to fix these! I'll let you know when i have them ready!!

**Comment by xavi-dcl** [comment]
@davidejensen attached the assets as Shibu sent them to me, now this can be fixed.
[Uploading... hair.rar]

**Comment by davidejensen** [comment]
@xavi-dcl this cannot be fixed on our side, the new hairs needs to be uploaded to the content server, we don't have the models in the project
