### ISSUE TITLE
[QA] Beam-up teleport at Genesis Plaza registers beyond the edges of its model

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2940]
Description:
The beam-up teleport at Genesis Plaza has its effective range outside the boundaries of its model. This issue occurs in a few places at the edge of the teleportation device.

Steps to reproduce:
1. Log in to the game either on guest or a wallet account at the default spawn-in location.
2. Walk down the whirlpool in the middle of the platform.
3. After falling down walk over to the edge of the teleportation device.
4. Keep walking around the edges of the teleport.
5. Observe the teleportation popup in the upper section of the screen.

Results:
Walking around the edges of the beam-up teleportation device causes the beam-up to be triggered.

Expected results:
Walking around the edges of the beam-up teleportation device does not cause the beam-up to be triggered.

Notes:
-Platforms: Windows and Mac, web and desktop
-Issue occurs for both production and dev branch.
-Please see the attached screenshots for reference.
![teleport1.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/68e0d1a1-98e1-4ca4-9a1c-efe3bfd72087)
![teleport2.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/e457e4b2-4ada-4e08-9d60-add8a1beb5ac)
![teleport3.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/b11ba00d-dc9d-4398-b58c-d8de05d97a5b)
![teleport4.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/fa9ea50a-2649-43c0-8483-aefa18a648da)

**Comment by anicalbano** [comment]
The edge appears to be correct:
![image.png](https://images.zenhubusercontent.com/64ad62442a830229041f8802/f174c3f5-c7b3-4877-ab0b-59899fff8f9c)
