### ISSUE TITLE
Prevent opening the chat window if typing in an input box

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#2949]
When you type into the input box and press enter to submit the text, that enter also opens the chat, which is quite distracting. You can see it when chatting to the old guy NPC here: https://play.decentraland.org/?position=-25%2C90

**Comment by popuz** [comment]
InputAction_Trigger should be set to blocked (vai isTriggerBlocked property) when input box is focused. Path to the ScriptableObject instance - Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ToggleWorldChat.asset

**Comment by popuz** [comment]
resolved in the https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/3020
