### ISSUE TITLE
Voice chat panel: update empty state texts

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#2958]
- [x] Replace` You are the only player in this scene` for` You are the only person in this scene`
- [x]  Replace `The metaverse is better with friends` for `The metaverse is better with people!`

![Screenshot 2022-08-22 at 09.41.23.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/6e3595f2-6963-4e43-9764-6ceac2124a82)

**Comment by RominaMarchetti** [comment]
![Screenshot 2022-08-22 at 09.41.23.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/3506f22d-fa15-46c6-9d92-38ff159f8e89)

- [ ] Replace `You are the only player in this scene` for `You are the only person in this scene`
- [ ] Replace `The metaverse is better with friends` for `The metaverse is better with people!`

**Comment by davidejensen** [comment]
Done

![Screenshot 2022-10-20 at 11.52.37.png](https://images.zenhubusercontent.com/61e566afd594605681c8aeb7/93af2a1f-3ded-49cf-af83-eafd70347850)

**Comment by RominaMarchetti** [comment]
@davidejensen the dot is missing at the end of the first sentence (my bad), and the dot must be an exclamation mark at the end of the second one.

**Comment by davidejensen** [comment]
I'm soo sorry, here's the fixed one! 

![Screenshot 2022-10-21 at 17 21 28](https://user-images.githubusercontent.com/4254522/197231267-5520407a-24a2-4e80-b48a-7fc93549a624.png)
