### ISSUE TITLE
Opening the backpack multiple times makes the emotes swap position

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2964]
**Description:**
The assigned emotes get swapped if the player enters the backpack's emote menu multiple times while some of the spots are unassigned. In the backpack the position of the assigned emotes is rearranged, however, on the emote wheel a single emote often gets duplicated.

**Steps to reproduce:**

1. Load into the game as a guest or via a wallet.
2. Enter the Emote section in the Backpack ('I').
3. Set the emotes while leaving some spaces unassigned.
4. Accept the changes.
5. Enter and exit the backpack multiple times by using the 'I' button.
6. Observe the issue.

**Results:**
Entering the backpack's emote section multiple times makes the assigned emotes swap.

**Expected results:**
The emotes don't get randomly swapped.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs only on the development configuration.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/2b71137b-c142-4601-aacb-c51c2c028870/_2964.mp4.

- Platforms: Web Client.

**Comment by anicalbano** [comment]
Unable to repro with the new backpack https://images.zenhubusercontent.com/337227404/c5856126-4103-4f54-a7ee-829d121ccf84/19_07_2023_15_38_06_rec.mp4.
