### ISSUE TITLE
[QA] Traversing via specific route causes the platform to crash

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#2967]
**Description:**
The platform crashes or permanently freezes if the user walks around the inner 'Museum' area which was accessed by using the teleportation prompt located in the Soho Plaza. In order for the crash to occur, the user needs to traverse from Genesis Plaza to the teleport in the Soho Plaza by foot.
The issue was reproduced on Ultra settings with the Scenes Load Radius set to 4.

**Steps to reproduce:**

1. Load into the game as a guest or via a wallet.
2. Traverse west towards the Soho Plaza by foot.
3. Reach the teleportation prompt located at **-87,4**.
4. Teleport to the 'Museum' area.
5. Walk around the inner section of the 'Museum' (area near  **18,77** ) in accordance with the video.
6. Observe the issue.

**Results:**
The platform crashes in the 'Museum' area accessed by traversing a specific route. 

**Expected results:**
The platform remains stable at all times.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- The issue tends to be easier to reproduce on the wallet accounts.

- Sometimes, running around the museum area for a moment may be required before the platform crashes.

- Please see the attached videos for reference: https://images.zenhubusercontent.com/337227404/a49d9e0f-f241-49a6-ac36-81b905b32249/_2967.mp4, https://images.zenhubusercontent.com/337227404/ed7e55e7-2a8d-4442-9edf-af0e1153728b/_2967_freeze.mp4.

- Platform: Web Client.

**Comment by m3taphysics** [comment]
@kwspgoliasz can you confirm this still occurs?

**Comment by kwspgoliasz** [comment]
@m3taphysics The platform still crashes, however, it the current crash might be related to the PlayerLoop crash, as the error message changed to some degree. Attaching the console logs for comparison: [#2967.txt](https://github.com/decentraland/unity-renderer/files/10245097/2967.txt).

**Comment by kwssbocian** [comment]
Cannot reproduce on prod via webGL from QA side
