### ISSUE TITLE
Some wearables on head explode casues the avatar to be cut down

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2970]
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/9f40125c-26c3-4eaf-b5ee-55e17f27aaa4)

- [ ] Investigate the cause of this
- [ ] Check with the team if we want to fix this

**Comment by davidejensen** [comment]
@Kinerius the cause is for sure the hologram avatar, the object that is used to fade between hologram and real avatar is most likely where the head cuts
