### ISSUE TITLE
Home point marker disappears upon zooming in on the map screen

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2971]
Description:
The home point marker disappears upon closely zooming in on the map screen.

Steps to reproduce:
1. Log in to the game either on guest or a wallet account. 
2. In the chat window type in /goto random to teleport to a random tile.
3. Upon teleporting click the triple dot menu underneath the minimap and tick the "Set Home" option.
4. Open up the map screen and zoom in closely on the tile designated as the home point.
5. Observe the home point marker.

Results:
Home point marker disappears upon zooming in.

Expected results:
Home point marker stays visible.

Notes:
-Platforms: Windows, web and desktop, wallet and guest login.
-Issue tested for PR #2904 on the branch https://play.decentraland.zone/?renderer-branch=feat%2Fhome-point&kernel-branch=feat%2Fsend-home-point&realm=artemis
-Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/adca33d5-5530-4278-ae13-91061f85678c/2022_09_06_11_09_40.mp4

**Comment by popuz** [comment]
@kwssbocian , can you re-test it, please? I cannot reproduce this bug

**Comment by kwssbocian** [comment]
I have retested it on both prod and dev and I was also unable to reproduce it. The issue no longer seems to occur
