### ISSUE TITLE
Tiles for Trending Scenes board in Genesis Plaza not loading

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2981]
Description: 
The Trending Scenes board located in the login platform section of the Genesis Plaza has its tiles not loading. All tiles appear with the Decentraland logo placeholder instead of a preview picture, "Loading Scene" text instead of the scene name and player count showing 1.
 
Steps to reproduce: 
1. Log in to the game either on guest or a wallet account. 
2. In the chat window type in /goto 0,0 to be teleported to the login platform in Genesis Plaza. 
3. Observe the "Trending Scenes" board located to the right.

Results: 
Tiles of the "Trending Scenes" board are showing placeholder pictures, names and player counts.

Expected results: 
Tiles of the "Trending Scenes" board are showing the preview pictures for the scenes, the scene names and accurate player counts.

Notes: 
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue tested for production and dev branch.
- Please see the attached screenshot for reference.
![Screenshot 2022-09-07 110214.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/3bbf92fb-9976-48f5-a389-f031df237d3c)

**Comment by popuz** [comment]
@kwssbocian , can you re-test it, please? I cannot reproduce this bug

**Comment by kwssbocian** [comment]
I have retested it on both prod and dev and I was also unable to reproduce it. The issue no longer seems to occur
