### ISSUE TITLE
Exodus 127,44 not loading

### ISSUE THREAD

**Issue by CXRF** [decentraland/unity-renderer#2983]
### What happened?

I've been having this issue since yesterday. I tried uninstalling the client, clearing cache and cookies, restarting my computer, and all possible things that I could've think of, but nothing helped. Please can you guys fix it?
![Exodus](https://user-images.githubusercontent.com/93418666/188323903-feb8d8fa-da59-4033-9b8f-3e0b90cac0fa.png)

### Steps to reproduce

I would say verify bugs and communicate with land owner and devs.

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

### GPU

NVIDIA GeForce RTX 3050 Ti Laptop GPU 3990MB

### RAM

16085MB

### Kernel Version

1.0.0-2962066080.commit-0d7454e

### Unity Version

desktop-1.0.572-20220902135606.commit-6c11e72

### Realm

hera

### NameTag

METACXRF#2299

**Comment by JorgeDecentraland** [comment]
@ kwspgoliasz could you adjust the description of the issue adding details, please?

**Comment by CXRF** [comment]
Problem has been addressed. 

Thank you

**Comment by JorgeDecentraland** [comment]
Closing the issue based on the comment above

**Comment by CXRF** [comment]
Thank you, have a great rest of your day
