### ISSUE TITLE
[QA] Elevators in Genesis Plaza main building do not go down from the 2nd floor

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#2984]
Description: 
The platforms of all the elevators at the Genesis Plaza main building after going up to the 2nd floor are refusing to go back down to the 1st floor. Issue occurs regardless of walking or jumping on the platforms.
 
Steps to reproduce: 
1. Log in to the game either on guest or a wallet account. 
2. In the chat window type in /goto 0,0 to teleport to the Genesis Plaza.
3. Jump down into the vortex in the middle pf the platform and walk over onto a platform of one of the nearby elevators.
4. Go up to the 2nd floor on the elevator's platform.
5. Walk off from the elevator's platform then walk back onto it.
6. Observe the elevator.

Results: 
The elevator's platform does not go down from the 2nd floor.

Expected results: 
The elevator's platform goes down from the 2nd floor back to the 1st floor.
 
Notes: 
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue tested for production and dev branches.
- Please see the attached video for reference. 
https://images.zenhubusercontent.com/337227404/2c0c7c35-4661-4e11-a9b8-8032cc04731b/2022_09_07_15_49_10.mp4

**Comment by olavra** [comment]
@PalauiDCL did you had any trouble solving this issue? any blockers?

**Comment by PalauiDCL** [comment]
@olavra I will investigate a bit more, but seems scene related, I contacted the content team and gave me a lead about animations, but I am trying to see where I can start attacking this issue from

**Comment by PalauiDCL** [comment]
I did observe a very weird behaviour in the elevators, the first time you step on them, they take you to the second floor and stay there, but:
If you disable and enable the gameobject, they start animating again with inconsistent behaviour. Sometimes they go up and down, sometimes they loop teleporting from the second to the first floor, just going up infinitely and teleporting when on top.
It can also happen to go down infinitely and teleporting to the first floor when reaching the base.
Those behaviours change from one to another when the player steps on the elevator but the changes are not consistent.

**Comment by anicalbano** [comment]
This issue is still active
