### ISSUE TITLE
Performance drop when enabling portable experience

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#2989]
During Art Week we had an event that utilized portable experience (`avatar attach`). However, when that was enabled we saw a performance drop.

![Screenshot_993.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/0c111437-d767-40d6-b834-a69b35c56109)

This feature is planned to be used during the Metaverse festival.

You can preview it as a portable experience using this link: https://play.decentraland.org/?GLOBAL_PX=urn%3Adecentraland%3Aentity%3Abafkreiftrnddyg62zk5uo6esmotxh2nk7wck7qoeierxmfh4hdnfxw3foq%3FbaseUrl%3Dhttps%3A%2F%2Fsdk-content-server.decentraland.org%2Fipfs%2F

Preview as Space: https://play.decentraland.zone/?kernel-branch=chore%2Fspaces&SPACE=urn%3Adecentraland%3Aentity%3Abafkreiftrnddyg62zk5uo6esmotxh2nk7wck7qoeierxmfh4hdnfxw3foq%3FbaseUrl%3Dhttps%3A%2F%2Fsdk-content-server.decentraland.org%2Fipfs%2F

### Acceptance Criteria
- [ ] Have portable experience not affect performance

**Comment by xavi-dcl** [comment]
@aixaCode shall we put this back to the backlog (Tech column) since MVMF is over so perhaps this optimization is not urgent anymore?

**Comment by popuz** [comment]
When I tried to investigate in this issue, I wasn't able to reproduce it. But maybe, some more advanced testing scenario is needed - like more people with portable experience around

**Comment by aixaCode** [comment]
Closing, as we could not repro this issue.
