### ISSUE TITLE
RealTime Blur Shader

### ISSUE THREAD

**Issue by MichaelBitsakis** [decentraland/unity-renderer#2994]
**RealTime Blur Approximation** 

The idea that was proposed by product is : 

We want to have a blur that can be applied
when and where we need it.

The blur could be something that blurs

only UI,
only the world
or both of them

As a reference of the graphical look of the blur
you can see the image in this

issues:

https://github.com/decentraland/unity-renderer/issues/2183
https://github.com/decentraland/unity-renderer/issues/2230

this is the case of the blur affecting only the UI

Another reference could be this screenshot,
this scenario is blurring both the UI background
and also the world behind

(not really that visible because it’s a really
light effect, but the notification messages
have a small blur on the world behind):

Gathered information can also be found here

https://www.notion.so/decentraland/8d7f740f558a4b4c92267f70f38e3f6c?v=9dd4f379da264e9494051a8e05cb4dc0

![Blur_on_ui_and_world.png](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/3d04eb5a-09dc-4174-bd84-b654db6941b3)

![Blur_On_World.png](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/5031f14a-ac76-46a1-96df-6ea44e2e68f0)

![Blur_On_UI.png](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/dfd10847-deae-4fa3-9490-64276798637c)

**Acceptance criteria**

- [x] Blur UI Only
- [x] Blur World Only
- [x] Blur UI and World Only

Additional Self added criteria

- [x] Automation for Blur UI Only (Devs support)
- [x] Setup
- [x] Demo Scenes
- [x] Demo Scenes - Look Dev with Real UI Elements
- [ ] Integration to the system with a Dev

**Comment by MichaelBitsakis** [comment]
Shader is completed for UI and WORLD , currently implementing the logic to : 

separate UI ONLY (to affect the UI that appears BEHIDE the ui we get the blur shader on 

Get Blur on the WORLD only

**Comment by MichaelBitsakis** [comment]
Current Progress can be seen [here](https://decentralandteam.slack.com/files/U040DBW2RFU/F0418VAVD2R/blur_ui_rt_boxblur_implementation.m4v)

**Comment by MichaelBitsakis** [comment]
Progress : 

After talking with Davide , we clearly got the specs.

Current shader implementation applies blur to BOTH WORLD AND UI 

Need need 3 cases:

Blur applied to : 

1.World and UI (done)

2. UI BEHIDE the UI in Focus , this requires a different setup BUT i will automate the procedures do DEVS dont have to deal with it other but applying the shader  (Working on it)

3. Blur on the world , this is easy , we just need a in shader split with logic. (working on it)

**Comment by MichaelBitsakis** [comment]
UI Only RealTime blur ready as well , will test it a bit and post visuals .

So far we have 

UIandWorld RealTime blur (Done)

UIOnly  RealTime blur (Done but under testing)

World only  RealTime blur (Done just needs separation from the UIandWorld and some refine to make it easier to operate on)

Automation and project integration part (half way there)

**Comment by MichaelBitsakis** [comment]
Visual Progress and WebGL Testing 

https://decentralandteam.slack.com/files/U040DBW2RFU/F042E225YPN/rt_blur_ui_only_progress-1.m4v

RT Blur ONLYUI progress Realtime (Editor and WebGL)
Will be ready today and then i will separate the world only today as well.
Automation and Integration is half way through.

**Comment by MichaelBitsakis** [comment]
Blur RT World Only done , separated and simplified

https://decentralandteam.slack.com/files/U040DBW2RFU/F0429K0JB2R/rt_blur_world_only_progress-1.m4v

**Comment by MichaelBitsakis** [comment]
Setup for all 3 shaders variations is READY. Moving on to finish the other half of the automation and if all good tomorrow Friday 09/16 we can see the final integration with the system along with Davide.

**Comment by MichaelBitsakis** [comment]
Done with UI Blur Only Automation

**Comment by MichaelBitsakis** [comment]
Shaders presented and delivered to Davide for testing and integration .
Including automation , demo scenes , setups etc.

**Comment by MichaelBitsakis** [comment]
Pitch black option for World Only blur with masked shape.

It works fine we just need a better resolution texture to follow the curves.

![World_BlurRT_v2_PitchBlack.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/23dde9da-933e-4cbc-b338-5236dc6aa0f4)

**Comment by MichaelBitsakis** [comment]
Updated World Blur Only with Alpha Texture.
Again , he better the texture quality the better the end result

![World_BlurRT_v2_PitchBlack_AlphaTextureOption.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/e60e7208-fdb7-4f78-be70-00e3f047a0d4)

**Comment by MichaelBitsakis** [comment]
World Blur RT from the UI have been also approved by Alvaro and Romi.

**Comment by MichaelBitsakis** [comment]
Full Procedural 4 corners setup 

![4 corners setup.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/2020f828-aa21-4bb4-b48d-65b0a86f1d66)

**Comment by MichaelBitsakis** [comment]
Full corners OR lower OR upper all in one shader

![4 corners setup.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/d61e71c6-3ffe-4700-a94c-eaa60d4af855
)
![lower.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/c89d4891-291e-4ec2-91d1-fe293c2e12b0)
![upper.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/b76f22af-7d23-4701-a843-8fc51ee0dcea)

**Comment by MichaelBitsakis** [comment]
HLSL Math Approach CORNERS ONLY

Shows only the round edges on a black shader , if you approve it , we can implement this solution for the corners

https://images.zenhubusercontent.com/337227404/9b915f2f-8376-4db6-9b52-a160b1a27644/hlsl_approach_cornering_1.m4v

**Comment by MichaelBitsakis** [comment]
Active Blur UI Only with using only one shader , no setup , no render texture , nothing , just one shader applied to component of the ui that support texture and material.

![ActiveBlurUIOnly.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/91a60348-33e8-4d29-9038-faa5d68f7bf2)

**Comment by MichaelBitsakis** [comment]
CleanUP and extra settings 
![ActiveBlurUIOnly.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/4a249282-68a5-4c96-9636-bbf5a645c6da)

**Comment by xavi-dcl** [comment]
@MichaelBitsakis what's the status, what is still pending?

**Comment by MichaelBitsakis** [comment]
@xavi-dcl This is a fully working solution , 2 version for blurring UI behide another UI , and blurry world from a UI. Its working , integration with current version of Decentralands UI is pending , as it requires some time and we never had it with the festival.

**Comment by MichaelBitsakis** [comment]
After doing an implementation with Davide we need to take under consideration 2 things for the BlurRT World only shader to work as expected.

1) Main camera Render Type MUST be base (so we dont use another camera) , currently is Overlay.
When switched to Base BlurRT works as expected , personally i dont see any difference when switching to Base on the rest of the scene (visually).

2) If you want to use theSource Image on the Image component we need a higher resolution as it gets compressed during runtime and it gives less data to the shader

Here are some screenshots with the integration as it must be done

![Blur_Integration_1.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/f6b89143-ea1e-41ba-bc42-293970ebfb78)

![Blur_Integration_2.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/6c6c42fd-4977-48a3-bcff-037d96eeb2d5)

![Blur_Integration_3.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/339e2043-f99a-4760-9338-82cab07bca25)

![MainCamera_Must_NOT_Be_Overlay.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/e3ebe439-d1b2-4491-abbe-57f485a1732a)

**Comment by MichaelBitsakis** [comment]
- Added BluRT to spike/base-main-camera

- Configured Material on Minimap UI info area

- Effect is working but camera is shown inverted , we need to check this , this was not happening on 2020

![inverted_camera.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/7a6cc90c-0c6a-40e7-93a5-673019cce42b)

**Comment by MichaelBitsakis** [comment]
RT Blur on Minimap 

![RT_Blur on minimap.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/7d050bc3-5380-4d7a-8b5f-269a278f57ae)

Specific UI is cutting the corners , on runtime only , will investigate on that.

**Comment by MichaelBitsakis** [comment]
WebGL Build test with effect and Textures incompatibility fix 
![WegGLBuildTest.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/3b9ca769-2921-4778-ae96-4c2662a51b40)

**Comment by MichaelBitsakis** [comment]
Updated the renderer feature to include the UI along with the world , can be separated by a feature flag on the renderer feature.

![BlurUIFromRendererFeature.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/d9708fc4-70db-409c-85e4-f70527e05887)

**Comment by MichaelBitsakis** [comment]
Working on new implementation for the round edges

**Comment by MichaelBitsakis** [comment]
Finished with the corners updates as well , now we can use the shader where ever needed with any ui image and control it from the image component. 

Applying on tickets #2183 and #2230 , DONT MERGE as i will work on the same branch.
[Uploading... Blurrtuiimageroundcorners-1.m4v]
