### ISSUE TITLE
AvatarShape glitch

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#2997]
Video of the issue: 

https://user-images.githubusercontent.com/7646450/189163597-cd61f411-f93b-4b51-a609-09de20fb5086.mp4

Possible issues:

- AvatarShape is getting combined with its parent meshes for some reason so everything goes crazy.
- Sometimes it does not glitch, maybe there's a race condition causing an issue
- Some errors about some objects having infinity scale

**Comment by wacaine** [comment]
![Screen Shot 2022-09-09 at 11 57 17 AM](https://user-images.githubusercontent.com/2999141/189392570-253c636d-5f06-4848-80ef-eb30d36ff4e4.png)

The skin color my userData returns does not match my actual avatar skin color.  But the AvatarShape replicates it fine.  Also should the AvatarShape have eyes as they seem to be missing
