### ISSUE TITLE
The user can get stuck inside the counter of the bar at Vegas Plaza

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3001]
**Description:**
Jumping on top of the counter of a bar in the Vegas Plaza results in the avatar getting stuck by falling inside the object.

**Steps to reproduce:**

1. Load into the game as a guest or via a wallet.
2. Teleport to **-51,54**.
3. Move towards the bar at **-53, 54**. 
4. Jump on the counter.
![#3001.jpg](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/6fa65506-f83e-4896-8fa3-8dd6f327539d)
5. Observe the issue.

**Results:**
The user gets stuck inside of the counter of a bar in Vegas Plaza.

**Expected results:**
The user can freely traverse through the area.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/9a5d5908-726b-41f9-9752-32ab11299f55/_3001.mp4.

- Platform: Web Client, Windows Desktop Client.

**Comment by xavi-dcl** [comment]
Scene issue
