### ISSUE TITLE
Loading spinner not being masked

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#3013]
When forcing the scroll to the top the spinner appear over the nav bar.
It may be because the loading spinner shader does not supports the stencil buffer used by the `Mask` UI component.
You can reproduce this issue on the `feat/channels` branch.
![Screenshot 2022-09-01 at 10.35.54.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/c0169ef5-4725-4e97-b7c4-d51141665f15)

**Acceptance criteria**

- [x] Ensure that Shader is working properly in a test scene
- [x] Create Demo Scene Simple Solution for Mask
- [x] Create Demo Scene Prefab solution (as in project)

- [x] Check Runtime in Editor with a Dev to verify the current setup
- [x] Ensure that Shader is working properly on WebGl Test Build

**Comment by MichaelBitsakis** [comment]
Investigation Stage started

**Comment by MichaelBitsakis** [comment]
Setting up spinner shader in a demo scene and making sure it works as expected on webgl build.
After that i need to get in a quick meeting with Niko to check the current realtime setup in editor and take it from there.

**Comment by MichaelBitsakis** [comment]
Progress : 

Setup is ready[Uploading... setup.jpg]

**Comment by MichaelBitsakis** [comment]
Please note that LoadingSpinner prefab was using M_ChargeBarv2 and not M_ChargeBarV2Fixed material.
Other than that setup is ready so we know what is working and what is not , shaders are fine.

Next thing is to connect with Niko on Monday to check the current ingame setup versus the Demo Scene

**Comment by MichaelBitsakis** [comment]
Prefabs , setup , etc in editor is fine , shader is fine.
Will do one last check tomorrow for an hour max and will start investigating the runtime part from tomorrow.

**Comment by MichaelBitsakis** [comment]
Issue 1 

On PrivateChatHud --> LoadingSpinner --> SpinnerBackground working material (The one that works) must be M_ChargeBarV2Fixed instead off M_LoadingSpinnerBackground.

Demo scene : Assets/Rendering/UI/ChargeWheel/DemoScenes/PrivateChatHUD.unity

![PrivateChatHUD.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/ce3b402e-1113-46be-8b98-8739f32cf516)

**Comment by MichaelBitsakis** [comment]
NFTItemToggle , LoadingSpinner prefab comes as X (broken).
Added the prefab again and it works fine.

Demo Scene : Assets/Rendering/UI/ChargeWheel/DemoScenes/NFTItemToggle.unity

![NFTItemToggle.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/bc460072-41b1-4f73-a341-73f4edcf08db)

**Comment by MichaelBitsakis** [comment]
Avatar Editor Hud 

One spinner of 3 needs to be replaced and it will work .

Demo Scene : Assets/Rendering/UI/ChargeWheel/DemoScenes/AvatarEditorHud .unity

![AvatarEditorHud.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/52493776-5a61-4838-adc6-0a2943e8ebb2)

**Comment by MichaelBitsakis** [comment]
/feat/channels

2 Changes on PrivateChatHud as shown below

![PrivateChatHud_Change_1.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/d9d88555-5a4d-441c-a5a4-462903d88f1f)

![PrivateChatHud_Change_2.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/ea3a6b2d-b881-4bac-9473-f2903aa3d383
)

**Comment by MichaelBitsakis** [comment]
Changes work on official project , just been verified.

**Comment by MichaelBitsakis** [comment]
New fixes on 

FriendsHUD and ChatChannelHUD

https://github.com/decentraland/unity-renderer/commit/94fa74b9160e70066cac52b9ec28891b6bbc65b8
https://github.com/decentraland/unity-renderer/commit/aa83192ae2b677362b4f0146faea0022916cb4bb

Similar approach changed materials v2 with v2fixed and added appropriate mask on the spinner container.
