### ISSUE TITLE
AvatarShape AttachTo seems to be failing in preview mode

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#3015]
**Description:**
The AvatarShape AttachTo function is not working as intended in the latest version of the platform: dcl --version 3.12.1. The avatar is now swapped after traversing over the boundary for the avatar swap. Moreover, when entering the swap area, red boxes are temporarily displayed on the screen.
Downgrading the version to 6.11.4 appears to fix the issue.

**Steps to reproduce:**

1. Load into the latest version of the platform: dcl --version 3.12.1. SDK.
2. Reach the area where the avatar gets swapped.
3. Attempt to swap the avatar.
4. Observe the issue.

**Results:**
The object affected by the AvatarShape AttachTo function is not displayed correctly.

**Expected results:**
AvatarShape AttachTo function is implemented correctly.

**Note:**

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/36b5873b-c924-4e61-a2e2-1273a1d0a431/_3015.mp4.

**Comment by wacaine** [comment]
One interesting note.  Downgrading the version to 6.11.4 appears to fix the issue however if I passed renderer-branch=dev it broke and while running  6.11.6 if I passed renderer-branch=main it worked

**Comment by pravusjif** [comment]
Implementing fix at https://github.com/decentraland/unity-renderer/pull/3040

**Comment by pravusjif** [comment]
Solved at https://github.com/decentraland/unity-renderer/pull/3040
