### ISSUE TITLE
Settings bug in zone

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#304]
Right now the Settings panel options start to duplicate sections due to the creation of scritable objects

This only happen in zone, not in production

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/a52bfea4-47eb-4150-b596-3954dfeea0b2)

**Comment by olavra** [comment]
This is also happening with other HUDs

Steps to reproduce:
- Refresh URL while you have Unity in play mode

**Comment by olavra** [comment]
@kuruk-mm check this out, this is what is happening in the desktop build

**Comment by kuruk-mm** [comment]
> @kuruk-mm check this out, this is what is happening in the desktop build

Yes, I don't have control in the `explorer-desktop` of what happens here. So we need to fix it in `unity-renderer`.

**Comment by kuruk-mm** [comment]
I'm not able to reproduce this problem
