### ISSUE TITLE
Page number gets reset on backpack

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#3055]
When changing pages through a category in the backpack, sometimes hitting the next button resets to the page 1.

### Repro steps:
1. Have many wearables
2. Open the backpack
3. Navigate to a category which contains many pages
4. Start click next button
5. At some point resets to page 1

https://images.zenhubusercontent.com/337227404/366978d4-bdef-4031-bfb8-770bd45dcb04/2022_09_16_15_24_53.mp4

### Acceptance criteria

- [ ] Pages should cycle correctly when clicking next or back buttons

**Comment by Antivortex** [comment]
Could not reproduce this one even after generating a lot of duplicate wearable entries in the backpack to simulate a lot of pages
