### ISSUE TITLE
Analyze compatibility tests results

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#3058]
Analyze compatibility test results

Reports can be found [here](https://drive.google.com/drive/folders/1Ln2fzzKLssnVbS8HbnCFfpw0jqTMo1F9?usp=sharing)
### Acceptance criteria

* [ ] Analysis findings documented
* [ ] Minimum hardware requirements updated
* [ ] Tasks to address performance issues created

**Comment by AjimenezDCL** [comment]
https://www.notion.so/decentraland/Compatibility-Test-4a9bb50de1b04c1192b7a91fb4c6089a
These compatibility tests by themselves don't allow us to update the hardware requirements or to find performance issues.
The former could be found if we had more granularity in the setups (less variability of components), the later might be impossible.
