### ISSUE TITLE
Issue with adding a friend with the use of the user's contextual menu

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3076]
**Description:**
When accepting a friend request via the contextual menu, the friends are added incorrectly. The receiver of the request is added as a friend for the sender, however, the sender is not added as a friend for the receiver. Moreover, a request to add the sender is sent from the receiver's account after clicking the Add friend button.

**Steps to reproduce:**

1. Load into the lazy loading RC branch with two wallet accounts.
2. Sent a friend request from one account to the other.
3. Open the request section in the friends tab.
4. Open the contextual menu for the sent request (the three dots on the right side of the request).
5. Click the Add friend option.
6. Observe the issue.

**Results:**
The friend request accepted via the contextual menu doesn't add a friend for both users.

**Expected results:**
The friends are correctly added for both users when accepting the request via the contextual menu. Alternatively, the option to add the friend via the contextual menu is removed.

**Notes:**

- The issue occurs only on the wallet accounts.

- The friend is properly added for the receiver after logging in to the platform again.

- The issue occurs only on the RC branch for lazy loading: https://play.decentraland.org/?renderer-branch=release/release-20220921&kernel-branch=feat/friends-lazy-load-only.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/e4466ae1-8b53-4587-84ba-1e88d3092e3b/_3076.mp4.

- Platforms: Web Client, Windows Client.

**Comment by sandrade-dcl** [comment]
After confirm with Romi, we decided to remove the friendship section of the contextual menu for all the request entries.
