### ISSUE TITLE
Bug on movement and facing of other avatars 

### ISSUE THREAD

**Issue by acrosscoder** [decentraland/unity-renderer#3088]
### What happened?

In all realms with a large crowd

what my avatar sees
* some avatars are running but backward
* some avatars are running  sideways
* some avatars are at a 45-degree angle

### Steps to reproduce

Try visiting places with crowded areas

(Note: sometimes this occurs randomly)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 5 CPU

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.0-3091217358.commit-6c7ec91

### Unity Version

1.0.54128-20220919201839.commit-6faaa73

### Realm

dg

### NameTag

JimSedric

**Comment by Kinerius** [comment]
https://github.com/decentraland/unity-renderer/pull/3083 was never merged, the change that caused this issue was rolled back from production, so this should be fixed already.
