### ISSUE TITLE
Improve performance of Start Menu open / close

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3092]
The performance of the Start Menu while opening and specially while closing is really bad. 
We need to aim for a smooth and instant transition between the world and the menu, and right now is taking up to 3 seconds in some cases, ruining the experience.

**Acceptance criteria**

- [ ] Performance improved

**Comment by popuz** [comment]
- duplication of https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/2813
- description and AC were moved there
