### ISSUE TITLE
Make more room for the avatar in the backpack

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#3104]
Currently the space assigned for the avatar in the backpack is too small. Also, in some occasions the UI overlaps the avatar space like in the following screenshot.
![Screenshot 2022-09-23 at 16.54.03.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/d7435c6f-72d0-43cb-aca0-e060b090a90b)

With the pagination implemented, which makes easier to navigate a huge amount of items available, we can decompress the avatar space prioritising how it looks and moves.
To make this happen, we need to modified the max amount of columns. Also the distance between the buttons of the avatar sections.
As in the following example, the items can't not exceed the bound that draws the linked wearable dropdown menu.

![Screenshot 2022-09-23 at 16.54.14.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/17e2e80f-261a-4860-81da-5f46a6ac98bd)

**Comment by olavra** [comment]
We will implement this as part of the Backpack 2.0
