### ISSUE TITLE
Outline Shader Advance AVATAR

### ISSUE THREAD

**Issue by MichaelBitsakis** [decentraland/unity-renderer#3108]
Shader info

![THIS_ONE.webp](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/1d122d02-17fa-4031-942f-ef1be69d9225)

![I0YKF.png](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/a7899b43-c30d-47c3-87b4-b59f6b3e08c0)![images.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/88741b72-eef4-415e-ba1a-05ac9be75f40)

![HuntShowdownTrinity.png](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/8a561eb5-d765-4a27-bdca-d5be2b697efb)

MUST : 

--> outlining alpha

--> control the online shape.

--> single solid color

--> or  gradient outward

--> or it could also act as a mask for ultrarainbow color movement

--> rendered behind objects, and the inner mass of color may be faded with a overlay color mass
when clicking, the effect may blink or change color.

MUST NOT -- DONTS

X : red lines: cant use duplication of geometry, and cant replace the geometry shader
X : not based on geometry displacement

checklist

---

- [x] Shader Base
- [x] Specs
- [x] Demo Scene
- [x] outlining hull
- [x] control the online shape.
- [x]  single solid color
- [x] Script control
- [x] Internal Fill 
- [x] rendered behind objects, and the inner mass of color may be faded with a overlay color mass
when clicking, the effect may blink or change color.

-- GPU Skinning 
- [x] Avatar Outline (GPU Skinning)

Extra Features To Add 
- [x] outlining alpha (Later Upgrade)
- [ ] or  gradient outward (Later Upgrade)
- [ ] or it could also act as a mask for ultrarainbow color movement (Later Upgrade)

Acceptance Criteria : 

- [x] outlining hull
- [x]  control the outline shape
- [x] Internal Fill 
- [x] Change colour of outline
- [x] ALL EFFECTS MUST BE DONE FROM INSIDE THE SHADER ONLY
- [x] IMPLEMENT THE OUTLINE ON THE TOON SHADER TO AVOID RENDER FEATURES , LAYERS , ETC

**Comment by MichaelBitsakis** [comment]
Advance Outline Progress

Technique : - Hull - Edge Scanned based

Programming Language :  URP HLSL (non CG)

Stage : Controls in Stable Mode / Project Implementation / Review

https://decentralandteam.slack.com/files/U040DBW2RFU/F044G76Q7MH/advance_outline_control-1.m4v

**Comment by MichaelBitsakis** [comment]
Working on feedback adjustments

Transparent objects issue (ZDepth related)
Objects with open uvs
Multiple mesh objects

**Comment by MichaelBitsakis** [comment]
For transparent objects that have problems solution is 

1. Add this transparent object to a Layer ( TransparentOutlined on my example here)
2. Add those 2 render features that only apply on this layer

![AddRenderFeatures-TransparentFix.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/cb9e0611-ce9f-499d-b90e-1ab96e87d415)

**Comment by MichaelBitsakis** [comment]
We can keep the outlines connected by setting the Overlay Amount to 0 in such scenarios

**Comment by MichaelBitsakis** [comment]
Transparency issue solved within the shader and the transparent material (use v2 shader and on the shader material disable the receive shadows)

**Comment by MichaelBitsakis** [comment]
New Post Effect Core To URP (WIP / during translation)
![PostEffectCoreToURP.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/8b2b2886-8ec2-40bb-93cc-0926ffb74dad)

**Comment by MichaelBitsakis** [comment]
Outline Replica from PostProcess to URP Render Feature

Current Features : Color , Width , Object Occlusion ,  Pseudo Blur

State : Wip , need to write the controls , clean it and stabilize the code.
![URP_Outline_PostProcessReplicaWIP.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/557c8837-a947-43b7-8559-fa8f4180b6f0)

**Comment by MichaelBitsakis** [comment]
Progress : 

All cases EXCEPT CPU Skinning (Toon Shader) are working fine.

I will need some time to implement the outline to the custom GPU Skinning.!

[progress_1.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/b70ea689-078d-4afc-b255-e7b26b8ceafc)

![progress_2.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/67dc1826-4d51-4ad5-ae27-5dc6508ef062)

![progress_3.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/b60fae49-ce07-40f7-b2b5-6a5ee4b38153)

![progress_4.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/cfdf7b08-f93b-49d7-ba6e-18d66a1eea1a)
![avatar_problem.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/3072c0a7-35f7-4ba7-83fa-22e627dd3995)

**Comment by MichaelBitsakis** [comment]
Shader based (per object without layers control) WIP progress.
Based on the previous Render Feature version but in shader .

![shader_based_per_object.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/ac1128a8-3acf-482f-8f74-f03de53e3056)

**Comment by MichaelBitsakis** [comment]
Finalizing this shader only approach with internal on/off feature flag

**Comment by MichaelBitsakis** [comment]
Outline Combined Solution to a shader only setup 

WIP on Avatar (on rest of the items works as expected)

Work in progress

https://images.zenhubusercontent.com/337227404/6de3d415-aed7-47d3-933d-f914a9c3fd5a/outline_combinedsolution_progress_1_1.m4v

**Comment by MichaelBitsakis** [comment]
Progress 2 on Outline Avatar , 

More stable but i need to separate and use more passes to behave as we need it.
Plus i need to separate objects from Avatar as i am forced to use different algorithms , again everything is going to be controlled from one shader only

Working on it.

https://images.zenhubusercontent.com/337227404/4c18cf36-a0c3-4974-bf88-958fd69614bb/outline_on_avatar_progress_2_1.m4v

**Comment by MichaelBitsakis** [comment]
Implemented Outliner Straight into Toon Shader

Working GPU Skinning included (also in separate version)

Needs some tweaking to get the exact same look.
![Toon_With_Outline_Implementation.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/a2e28d1a-3b11-4ecc-801b-80ff7dedc0f2)

**Comment by MichaelBitsakis** [comment]
- Fixed glitch now as you can see in the video we have rock steady outline .

- Unfortunately now we have partial transparency passing through the shader ONLY in camera view , so it probably a combination passes again , will find fix that one as well.

**Comment by MichaelBitsakis** [comment]
Transparency coming through ALMOST solved!!!

![transparency_passingthrough_progress_1.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/dc158482-acb9-4831-b625-f42e9430bc5a)

**Comment by MichaelBitsakis** [comment]
Solved all issues with Toon shader , now it accepts the outline internally.

Some tweaks are left to complete this for the avatar .

Object outline needs some tweaking as well and its done.

![OutlineToToon.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/9a45ab53-6d75-4f0e-859a-e2b3a722fdcd)

https://images.zenhubusercontent.com/337227404/08ef9b50-da71-4a87-bd46-72f143e21396/toon_outline_merge_1.m4v

**Comment by MichaelBitsakis** [comment]
Outline in Toon Shader

https://images.zenhubusercontent.com/337227404/217660a4-204f-4249-9658-114cd63c0d46/outline_in_toon_1.m4vr

**Comment by xavi-dcl** [comment]
@MichaelBitsakis is everything ready for integration? Please ask @olavra to review when so.

**Comment by MichaelBitsakis** [comment]
@xavi-dcl We need to review this with @olavra and do an integration with @AjimenezDCL .

**Comment by MichaelBitsakis** [comment]
- Outline on Avatar on single material
- No extra work from Devs works as is.

![outline_one_shadr.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/65b67be6-fb48-4e46-96e1-4f6b09598b17)

**Comment by MichaelBitsakis** [comment]
- Tested on wearables
 ![works_on_transparency.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/0672aeb2-e94a-4cd2-801c-3ca87186f833)
