### ISSUE TITLE
Changes in game settings are not saved automatically

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3112]
**Description:**
The changes in the game settings are not saved until the user exits the main menu, or changes the tab (for ex. to map or backpack). As a result, exiting the game from the settings menu after applying the changes, causes the settings to revert back to their previous state upon the next login.

**Steps to reproduce:**

1. Load into the platform as a guest or via a wallet.
2. Open the Settings menu ('P').
3. Change any of the settings.
4. Exit the platform (log out or close the tab).
5. Log into the platform again.
6. Access the Settings menu.
7. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
The changed settings are not automatically saved.

**Expected results:**
The changes applied to settings are saved automatically.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/f5c31085-6569-4cc8-aef2-07b2a3bcdb50/_3112.mp4.

- Platforms: Web Client, Windows Client.

**Comment by JorgeDecentraland** [comment]
@kwspgoliasz does this issue affect ALL settings? If it only affects some, could you clarify which ones? Thanks.

**Comment by kwspgoliasz** [comment]
@JorgeDecentraland Yes, the issue affects all of the options in the Settings tab (graphics, audio, etd.).

**Comment by xavi-dcl** [comment]
Suggest we move this back to backlog (bugs) as we have higher priority issues.

**Comment by xavi-dcl** [comment]
Can you please validate and let us know repro rate as well? @kwspgoliasz

**Comment by kwspgoliasz** [comment]
@xavi-dcl The issue still occurs as described in the ticket. The description was updated with the reproduction rate.

**Comment by eordano** [comment]
Hi @kwspgoliasz , could you verify that this also happens when you just *close the tab*? It is expected that local changes can be forgotten after *Log out*

**Comment by kwssbocian** [comment]
@eordano @xavi-dcl Issue also occurs if the tab is closed. Additionally the issue also occurs on desktop - if the app window is closed before exiting the Settings menu the changes are not saved.

**Comment by eordano** [comment]
Replaced by #3999
