### ISSUE TITLE
Be able to join a channel using a deep link

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3116]
In order to attract communities from other social networks, we need to be able to create links that can be posted anywhere, and people can click, so they automatically join the channel. 

Independently, this will prompt the confirmation dialog to join the channel in-game. 

This will be done using a url param like **&channel=name-of-channel**

**Acceptance Criteria**
- [x] Channel view must automatically open when a channel param is declared in the URL.

**Comment by sandrade-dcl** [comment]
This task is blocked by this issue that has to be fixed in the kernel side: https://github.com/decentraland/kernel/issues/717

**Comment by m3taphysics** [comment]
Should be fixed by: https://github.com/decentraland/kernel/pull/710
