### ISSUE TITLE
[QA] Unlocking the cursor during movement causes the avatar to start moving on its own

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3121]
**Description:**
The Avatar continues to walk after releasing the movement key, if the mouse cursor is unlocked while the user moves around with their character. Moreover, the issue persists even after the cursor is locked again. The issue occurs regardless of which movement key is pressed (WSAD) when unlocking the cursor.

The automatic walking can be stopped by pressing the same movement key which was held when the cursor was unlocked. Additionally, while the issue occurs, the movement key opposite to the pressed one becomes non-responsive.
 
**Steps to reproduce:**

1. Load into the Web client as a guest or via a wallet.
2. Start moving the avatar in any direction.
3. Press Esc to unlock the cursor while holding any movement key.
4. Release the movement key.
5. Observe the issue.

**Results:**
Unlocking the cursor during movement causes the Avatar to move on its own.

**Expected results:**
The Avatar always stops moving after the movement key is released.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/08f6a377-5761-4ec8-9e60-b6a3b8e873ab/_3121.mp4.

- Platforms: Web Client.

**Comment by anicalbano** [comment]
Not able to repro anymore:
https://images.zenhubusercontent.com/337227404/3f342ed3-1a52-4098-8539-255d87b00681/19_07_2023_15_51_05_rec.mp4
