### ISSUE TITLE
Collectibles tab glitches out after updating when switching the active menu

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3122]
Description:   
Upon transferring a wearable and switching tabs in the backpack of the sender, the Collectibles tab starts to show the transferred wearable as well as the "You don't own any collectibles" message. On the receiver's account, a blank Collectibles menu is shown instead of the received wearable if the tabs are switched after receiving the item.

Steps to reproduce:   
1. Launch the client using the fix [branch](https://play.decentraland.zone/?renderer-branch=fix/update-backpack-on-refocus) then log in using two wallet accounts, one of them possessing an NFT wearable available for transfer.
2. On both accounts open the Collectibles tab in the backpack menu.
3. Open the account.decentraland.zone and log in with the wallet that has the NFT wearable.
4. Send the wearable to the other wallet.
5. After the sending process is confirmed go back to the tab with the sender's login and go back and forth between the Collectibles tab and another tab/menu (do not close the menu altogether).
5. Observe the contents of the Collectibles interface on the sender's account.
6. Move over to the receiver's account and switch the tabs in the same way as in step 5.
7. Observe the contents of the Collectibles interface on the receiver's account.

Results:   
Collectibles tab on the sender's end continues to show the transferred wearable as well as the "You don't own any collectibles" message after switching the menus. Collectibles tab on the receiver's end appears blank after switching menus.

Expected results:   
Collectibles tab on the sender's end does not show the transferred wearable and shows "You don't own any collectibles" message after switching menus. Collectibles tab on the receiver's end shows the received wearable after switching menus.

Notes:   
-Platforms: Windows, web, wallet login.   
-Issue occurs for the [#3069](https://github.com/decentraland/unity-renderer/pull/3069) branch.
-Please see the attached video for reference. https://images.zenhubusercontent.com/337227404/a45f360d-a78c-45dd-b86c-b93a0c918ae1/2022_09_26_16_42_18.mp4

**Comment by anicalbano** [comment]
Applied to the old backpack. Closing the issue.
