### ISSUE TITLE
Channels refinement iteration 4

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#3130]
### HIGH-PRIORITY
**Channel browser**
- [x] The message shown after trying to join the sixth channel is incorrect: we are displaying the one that must be shown when trying to create a new channel. 

**Channel view**
- [x] The notifications icon size looks way smaller that in the design. 
![Screenshot 2022-09-28 at 10.23.13.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/4a785d39-31f8-4035-aa69-47ee6b3cf4f8)
- [x] The context menu of the channel is not well aligned when the members list is opened. 
![Screenshot 2022-09-28 at 10.42.18.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/8aca83ef-321a-497f-84f1-a549a134fa33)
- [x] While loading the players don't show the message to see more people.
![Screenshot 2022-09-28 at 10.35.17.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/5b4d1ec2-e4b3-49f5-a553-4dbbb9ed7f36)
- [x] The message above should be invisible while all the members are visible.

**Create channel pop up**
- [x] When reaching the max amount of characters the message is incorrect. The counter and outline input color in red are enough. 
![Screenshot 2022-09-28 at 10.32.07.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/cefad8bb-2ff7-4504-960e-92f8d35403a8)

### MID-PRIORITY
**Channel browser**
- [ ] The [pop up](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3167%3A24291) that prevents the player to create a new channel after reaching the limit is not being shown. We shouldn't be showing that feedback here:
![Screenshot 2022-09-28 at 10.12.53.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/3855d831-4684-4999-96a6-56c33b18fbe3)
This affects the flows when you try to create a channel from the searching error message [example 1](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3423%3A34559) [example 2](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3423%3A34781) and from the chat window as well.

**Create channel pop up**
- [x] We should recognise that there is a special character in a first place.
![Screenshot 2022-09-28 at 10.31.15.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/cf1073a6-06b3-4bc5-aa11-88cf593cb5c7)
- [x] Remove the close button (product desition).

**Channel view**
- [x] The arrow overlaps player's context menu. 
![Screenshot 2022-09-28 at 10.42.01.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/0e7a7d70-3b10-49a0-9066-0d9c738eeb78)
- [x] The arrow overlaps player's context menu. 
![Screenshot 2022-09-28 at 10.42.01.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/0e7a7d70-3b10-49a0-9066-0d9c738eeb78)

**Notifications panel**
- [x] Avatar snapshots are not being shown and the asset ellipse's quality looks poor.
- [x] Test that each channel is differentiated by a different color. `#nearby` must always be grey.

### LOW-PRIORITY
**Channel browser**
- [ ] The pop up with the message saying that you can't create a new channel after reaching the limit doesn't match the design: container size, buttons, fonts, etc. Use the modal `Are you sure you want to leave this channel` as reference which is correctly implemented. 
- [x] Check that the pop up with the message max of channels reached when you try to join is aesthetically well implemented too (I couldn't test it on the branch, not working).
- [x] Increase the width of both buttons to reach the width of the text input.
![Screenshot 2022-09-29 at 12.12.20.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/0f2361f7-3cc0-42ff-82b0-f4e129597ef9)

**Notifications panel** 
- [x] Fix position and size of the bell icon. Then move the icon and title some pixels below making them match the [original design](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=2829%3A24186).
![Screenshot 2022-09-28 at 10.45.22.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/1bb2355b-8e48-4d27-aa09-80f32a725f7c)
- [x] Channels names colors: replace the existing ones and add the new ones detailed in the [design system](https://www.figma.com/file/HEjNjFOQUcCgLK3lDMFrw5/DCL-Design-System-%26-Guidelines?node-id=360%3A972). 

**Channel view**
- [ ] The members button width container must be dynamic. The distance between the icon and the number a constant. [Example 1](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3197%3A31407), [Example 2](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=2829%3A21201)
 ![Screenshot 2022-09-28 at 10.23.07.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/83c5faf8-264e-4725-bea9-569c517a4c09)
- [x] When the members list is visible the container of the members amount in the nav bar must be visible, otherwise invisible. [Invisible](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=2829%3A21201), [visible](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3303%3A39380).
- [x] The arrow container corners' radius looks wrong. 
![Screenshot 2022-09-28 at 10.22.55.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/fd84b7a1-6811-4f23-b45f-a9c8e1dabb80)

**Notifications panel**
- [ ] Create an empty state when the notification panel is empty. [Figma](![Screenshot 2022-10-04 at 23.50.21.png][Uploading... Screenshot 2022-10-04 at 23.51.53.png]

**Comment by davidejensen** [comment]
Closing this issue considering all the high priority issue has been fixed, opened this one with the last ones: https://github.com/decentraland/unity-renderer/issues/3317
