### ISSUE TITLE
[QA] Looping emotes do not stop playing after teleportation

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3134]
Description:
Triggering a looping emote and then teleporting has a chance to cause the emote to continue playing after the teleportation occurs. Issue appears to have a higher chance of occurring if the emote is allowed to play out for at least one full cycle before the teleportation.

Steps to reproduce:
1. Log in with either a guest or a wallet account.
2. Press B key to open up the emote wheel and select the Dance emote or any other looping emote.
3. Allow the emote to play out for at least one full cycle.
4. In the chat menu type in the /goto random command.
5. Observe the player character.

Results:
After teleportation the looping emote continues playing.

Expected results:
After teleportation the looping emote is no longer playing.

Notes:
-Platforms: Windows, web and desktop, wallet and guest login.
-Issue occurs for both production and dev branches.
-Please see the attached video for reference. https://images.zenhubusercontent.com/337227404/f1716e6b-615b-45ac-a479-0431fef00ed0/2022_09_29_12_55_12.mp4

**Comment by anicalbano** [comment]
Not able to repro anymore:

https://images.zenhubusercontent.com/337227404/3106856e-625b-4b66-bbe4-05d09dbd0f5f/19_07_2023_16_20_42_rec.mp4
