### ISSUE TITLE
The Ice Poker scene is not loading correctly

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3137]
**Description:**
The HUD and game assets are not loaded after teleporting to the Ice Poker Stronghold scene, resulting in the game being unplayable. The avatars present in the area are correctly displayed.
In order for the assets to properly spawn, the user must exit the scene area by foot and re-enter it again.

**Steps to reproduce:**

1. Load into the platform via a wallet.
2. Teleport to the Ice Poker Stronghold scene via the board or the map.
3. Wait for the avatar to spawn.
4. Observe the issue.

**Results:**
The assets associated with the Ice Poker are not loading correctly.

**Expected results:**
The Ice Poker assets are loading correctly at all times.

**Notes:**

- The Ice Poker can only by accessed on production configuration via a wallet account.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/3c4d2a61-1804-4d87-b537-775c80a73f35/_3137_ice.mp4.

- Platforms: Web client, Windows client.

- Based on multiple user reports, the issue appears to be more severe on the desktop client - [#530](https://github.com/decentraland/issues/issues/530). For some users the issue seems to occur in Tominoya as well - [#521](https://github.com/decentraland/issues/issues/521). 

- Please see the additional attachments provided by the DG Team: [https://app.zenhub.com/files/337227404/ee3512b8-37c3-4e85-9fd3-49981c20bdb3/download](https://app.zenhub.com/files/337227404/ee3512b8-37c3-4e85-9fd3-49981c20bdb3/download).
- [https://app.zenhub.com/files/337227404/d5ffe1f0-174e-4e09-8fa7-ac3fe858241b/download](https://app.zenhub.com/files/337227404/d5ffe1f0-174e-4e09-8fa7-ac3fe858241b/download)

![#3137_01.png](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/86c529ee-19e1-49c3-9638-9e501b72db26), ![#3137_02.png](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/a50bb4a3-9cd7-4853-94b4-f6ae38a10652), ![#3137_03.png](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/27fbd51e-8d46-45d1-8b88-4984cae9b2ab)

**Comment by davidejensen** [comment]
### Introduction

This bug appears to be happening only (and not always) when reaching an ice poker scene through a teleport (i.e. the teleport from genesis plaza) or spawning inside that scene.
I've tried reproducing this problem in other scenes with UI elements but I didn't succeed.
With the ICE Poker scenes I managed to reproduce the bug in unity editor by going to the .org environment and enabling TLS.

### Bug analysis

1.  Scenario when the UI elements are displayed correctly:
When all the UI Elements are correctly shown we have in the hierarchy many UIImages/UITexts and such that contain the different graphical elements as in the following screenshot:

![Screenshot 2022-10-14 at 09 36 27](https://user-images.githubusercontent.com/4254522/195800398-b915e702-191e-4131-9a99-f082631e1c4c.png)

I've tried tracing the messages received from kernel to identify the received messages but it's impossible to decode the messages being in binary. I've decided then to log in the console the messages processed by the `SceneController`, by logging the method being called when going in ice poker.

![Screenshot 2022-10-14 at 10 38 01](https://user-images.githubusercontent.com/4254522/195802233-919dc5ad-c65b-4975-bf0b-a3f06523536f.png)


The result

2. Scenario when the UI elements are not displayed
When the UI Elements of the scene are not displayed they are entirely not spawned. This means that it's not a problem related to the download of the actual texture but a messaging error.
By logging the scene messages we receive the following numbers:

![Screenshot 2022-10-14 at 10 30 37](https://user-images.githubusercontent.com/4254522/195800702-6b4213df-1382-40f5-b58b-61295ca0e1ed.png)

What I'm thinking after seeing this is that it might be that we are not receiving the correct calls from kernel

**Comment by pravusjif** [comment]
This is apparently happening on another scene, at Petaverse Park (https://play.decentraland.org/?position=-61,119) there are these objects that are not appearing anymore, and the scene hasn't been changed for at least 3 weeks.

Elements that should be rendered:
![unnamed (2)](https://user-images.githubusercontent.com/1031741/196201987-c6572dd8-5dd6-4d13-8fdc-588fa2e251b0.png)

Not being rendered:
![unnamed](https://user-images.githubusercontent.com/1031741/196202067-6f9c0dea-5dd9-4929-b54c-4770992b86c6.png)

![unnamed (1)](https://user-images.githubusercontent.com/1031741/196202106-25154d1a-484d-45db-b805-eab079df40ba.png)

**Comment by pravusjif** [comment]
> In order for the assets to properly spawn, the user must exit the scene area by foot and re-enter it again.

Actually it's not necessary to completely get out of the scene and re-enter it for eveyrthing to start working again... by just moving from the initial parcel into a different one, everything starts to work again, so it makes me think that **this may have something to do with the "current scene" value that we have in kerne/renderer, maybe something related to comms as well**
