### ISSUE TITLE
Fix glitch caused by doing multiple emotes

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3140]
When doing emote combos you can cause the animations to glitch. Combos mean you press an emote and then press another when the first is still in the process.

<details>
<summary>Videos</summary>

https://user-images.githubusercontent.com/7646450/193037722-d61ff2d6-6429-426d-9342-26030c0851f5.mp4

https://user-images.githubusercontent.com/7646450/193037743-cc13fb3c-0dff-485c-b7ed-fcaecccf3874.mp4

</details>

**Comment by m3taphysics** [comment]
Closed as dupe: https://github.com/decentraland/unity-renderer/issues/3173
