### ISSUE TITLE
Migrate the calls made directly to thegraph to lambdas in catalysts. Unify calls into one request.

### ISSUE THREAD

**Issue by menduz** [decentraland/unity-renderer#3148]
To gracefully react to this kind of outages:

![Screen Shot 2021-12-23 at 14 05 16](https://user-images.githubusercontent.com/260114/147271703-3ccd8ca7-b652-47c5-97d7-3e7759b811a7.png)

**Comment by xavi-dcl** [comment]
@eordano  Should this one be done by the Platform / Resilience stream, or stay in Explorer / Core Experience?

**Comment by menduz** [comment]
@xavi-dcl I think it should be a co-joined effort between both. The platform team will provide the endpoints, the explorer should implement them
