### ISSUE TITLE
[QA] Swiftly switching between the menu tabs results in incorrect message being displayed

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3160]
**Description:**
If the user quickly switches between two different tabs during the tutorial for the main menu, the displayed message becomes inconsistent with the presently opened tab.

**Steps to reproduce:**

1. Load into the platform as a guest or via a wallet.
2. Go to Settings (P) and launch the tutorial.
3. Reach the menu tabs explanation (explorer, backpack, etc.)
4. Swiftly switch between two different tabs a couple of times.
5. Observe the issue.

**Results:**
Switching between the menu tabs quickly during the menu tutorial, causes an incorrect message to pop up. 

**Expected results:**
The correct tutorial message is always displayed when opening a specific menu tab.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/e2c89f40-0b92-404d-82f7-494fe241762d/_3160.mp4.

- Platforms: Web client, Windows client.

- The issue is less prominent on the Windows client.

**Comment by anicalbano** [comment]
Unable to repro at the moment:

https://images.zenhubusercontent.com/337227404/0746906e-6664-4ac0-85d3-ec8b8a427af5/20_07_2023_09_24_23_rec.mp4
