### ISSUE TITLE
The Avatar preview camera is displayed incorrectly for specific tabs when reopening the backpack

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3167]
**Description:**
Reopening the Backpack menu after saving the visual changes from any section of the Head or Accessories tab, causes the camera to zoom out. Moreover, until the tab is changed, it is possible to modify the facial appearance with a zoomed out camera.

**Steps to reproduce:**

1. Load into the platform as a guest or via a wallet.
2. Go to Backpack menu (I).
3. Switch to any section in the Head or Accessories tab in order for the camera to zoom in.
4. Click the Done button to save the changes (no actual changes need to be applied).
5. Reopen the Backpack menu.
6. Observe the issue.

**Results:**
Saving the visual changes to Avatar's appearance from the Head or Accessories tab (zoomed in sections), causes the camera to zoom out after reentering the backpack.

**Expected results:**
The camera is always zoomed in when opening the relevant Backpack sections.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/a766f173-9123-49b4-80e2-63c602ccd52b/_3167.mp4.

- Platforms: Web client, Windows client.

**Comment by olavra** [comment]
@Antivortex could you please estimate this task for the planning? thanks

**Comment by kwssbocian** [comment]
Cannot reproduce - after introduction of the new Backpack issue is no longer reproducible. On the new backpack camera behavior works correctly for the outlined scenario.
