### ISSUE TITLE
DestroyParticlesOnFinish is super slow when we have a lot of avatars

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3168]
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/486cb0c0-332e-434d-aa6a-d1379e991b85)

When we have 100 avatars running, we have a lot of particles spawning and being destroyed.

![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/939bf219-5c7f-473c-a7e2-5a64f5697b74)

Almost 9% of the frame time is being used by 7846 MonoBehaviuours checking if that object should be destroyed, this is costing us the same CPU time as the GPUSkinning.

We should investigate how we can deal with this without a lazy polling system. We can:
- Pool them.
- Manage their updates on a centralized update manager.
- Avoid using `!= null` and `IsAlive` as they are expensive calls.

**Comment by PalauiDCL** [comment]
I did observe a very weird behaviour in the elevators, the first time you step on them, they take you to the second floor and stay there, but:
If you disable and enable the gameobject, they start animating again with inconsistent behaviour. Sometimes they go up and down, sometimes they loop teleporting from the second to the first floor, just going up infinitely and teleporting when on top.
It can also happen to go down infinitely and teleporting to the first floor when reaching the base.
Those behaviours change from one to another when the player steps on the elevator but the changes are not consistent.
