### ISSUE TITLE
DM chat history not loading & inconsistent friendship status

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#3172]
- The DM chat history is not loaded for one user after accepting a friend request. The chat is only added after writing a new message to the friend. - https://user-images.githubusercontent.com/110464313/194051156-f8e9d7f1-eadb-468e-b071-f80856cf6c24.mp4.

- When accepting the invitation from the passport, the friend is added to the list with a noticeable delay for one user - https://user-images.githubusercontent.com/110464313/194051735-790111d0-3a19-4dd2-8c75-302f7264872a.mp4.

- In rare cases, after a friend is removed, the DM's and passport randomly do not register the update for one or both users. As a result, even though the friend was removed from the friend list, the user is described as friend in the passport. Moreover, even though the DM history is correctly deleted from the channel menu, the DM can still be accessed via the search feature. No stable repro was found for the issue, however, it seems more prone to occur, if there are at least four avatars are present in the area. After adding all of the avatars as friends and then removing them, the issue randomly occurs for one of the avatars located in the area.
![194052177-efd2231f-9f18-411a-bc45-9bcc7da08601.jpeg](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/d084134d-7362-4985-860e-88aacb9b08cc)

### Additional tasks
- When we send the "GetFriendsWithDirectMessages" message to kernel, if we don't have ay conversation, kernel is not sending us any response and the loading keeps visible indefinitively. For these cases we should add a timeout to this loading to be hidden after a maximum time.

**Comment by xavi-dcl** [comment]
@kwspgoliasz could you please validate this one?

**Comment by kwssbocian** [comment]
@xavi-dcl Out of the 3 issues listed in the ticket only the first (DM chat history) still occurs on both production and dev. The other 2 could not be reproduced

**Comment by xavi-dcl** [comment]
Pretty good news. Would you mind please closing this ticket and creating a new one with the single remaining issue? Thanks a lot. @kwspgoliasz @kwssbocian

**Comment by kwssbocian** [comment]
Raised the first issue separately under #3725. Closing
