### ISSUE TITLE
[QA] Issues with the preview mode for the emotes

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3173]
**Description:**
If the user swiftly switches between two set emote slots, the preview mode for the emotes is not updated correctly, causing the preview for the presently chosen emote to not play. Moreover, if the switch is executed from a non-looping emote, the previewed avatar freezes after the emote animation ends.

**Steps to reproduce:**

1. Load into the platform as a guest or via a wallet.
2. Go to Backpack menu (I) and enter the Emote section.
3. Set two non-looping emotes.
4. Swiftly switch between the two emote slots.
5. Observe the issues.

**Results:**
Quickly switching between two emote slots results in the displayed preview not updating correctly. When switching from a non-looping emote, an additional issue with avatar freeze can be observed.

**Expected results:**
The preview is correctly updated when changing the emote slots.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/6b73adcc-2c8f-4fa9-b26e-673a4e44a0d3/_3173.mp4.

- Platforms: Web client, Windows client.

**Comment by anicalbano** [comment]
Applied to the old backpack view.
