### ISSUE TITLE
Invisible Objects with isPointerBlocker=false

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#3181]
Setting a `isPointerBlocker=false` in a shape makes it invisible.

Check with this scene
[https://app.zenhub.com/files/337227404/895f1be4-92f1-4a29-a849-1073bf15f571/download](https://app.zenhub.com/files/337227404/895f1be4-92f1-4a29-a849-1073bf15f571/download)

A prior evaluation has shown that the issue is related to the Layer due to this logic in `BaseShape.cs`
![image.png](https://images.zenhubusercontent.com/5d91ff0b2836200001244acf/e4a642fd-0c47-40ed-9de0-23be04f457b1)

Acceptance Criteria:
- [ ] `isPointerBlocker=false` shouldnt make objects invisible

**Comment by xavi-dcl** [comment]
@AjimenezDCL did we introduce this issue or has it always been like this? Wondering how urgent is this fix, and if changing this could cause issues to content created based on current (wrong) behavior.

**Comment by xavi-dcl** [comment]
Alex said that indeed we might break some content (old scenes relying on wrong default value to set colliders).
But let's go ahead preparing the PR and as mitigation we agreed to do:
- Do good QA
- Let @nearnshaw know about this change (Xavi will do it now)
- Make sure this is in the release notes (which should be reaching the wider community)

**Comment by nearnshaw** [comment]
what is the purpose of this fix?

of course It's not intuitive for isPointerBlocker to make something invisible, but we're about to release SDK7 and start fresh
if there's a risk we'll break older content, and this change only benefits a small cohort of creators that build something between now and when SDK7 is out,  I wouldn't do this change

Adding isPointerBlocker=false is a pretty niche thing to want to configure, while having collisions=true is something you want for almost all 3d models
if this affects the default behavior of all entities in old scenes, just to benefit a very specific use case of having a visible entity that is not pointerBlocker, might not be worth the risk

**Comment by m3taphysics** [comment]
@AjimenezDCL can we agree that this is no longer necessary and close it off?
