### ISSUE TITLE
AssetBundles detection commands stop working when triggered again outside the initial range

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3191]
Description: 
Using the `/detectabs` command then going outside the initial highlight range, onto the unhighlighted tiles, causes all of the `/detectabs` commands to stop working. Issue stops occurring only after having restarted the client.

Steps to reproduce:    
1. Log in with either a guest or a wallet account.   
2. Use the command "/detectabs" to turn on detection of AssetBundles for the nearby loaded tiles.
3. Go beyond the range of the loaded tiles until you encounter non-highlighted tiles and walk into one such tile.
4. When standing on a non-highlighted tile use the "/detectabs" command again.
5. Notice new nearby tiles not being highlighted.
6. Use any combination of "/detectabs" and "/detectabs off".
7. Observe the nearby tiles.

Results:    
All AB detection commands stop working after using "/detectabs" command on an initially non-highlighted tile.

Expected results:    
All AB detection commands continue working after using "/detectabs" command on an initially non-highlighted tile.

Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot for reference.
https://images.zenhubusercontent.com/337227404/18498c79-67e6-4809-ab2b-f2bd3ce2b953/2022_10_07_16_26_47.mp4

**Comment by PalauiDCL** [comment]
I think the description for this task talking about the trams is a mistake, just notifying that I am ignoring that

**Comment by kwssbocian** [comment]
@PalauiDCL fixed 😄
