### ISSUE TITLE
Use local assets or dummy assets for Avatar Tests

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#32]
Currently the AvatarShape/Renderer/Wearables tests are loading a catalog.json from `TestResources`.

This catalog is pointing to the assets in production. If something changes in production (like a hash) all the tests will break. To prevent this, a basic set of wearables/bodyshapes must be downloaded and included in the repository and the catalog must point to them.

**Comment by olavra** [comment]
This will be removed with the refactor of the AvatarRenderer and no longer applies
