### ISSUE TITLE
Security breach at kernel part 

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#320]
Right now there is a security breach that we need to look into for builder in world

Los controllers que están en shared/apis , cuando tienen el @registerAPI('SceneStateStorageController'), se pueden llamar desde las escenas

Es decir que alguien podría hacer algo como:
const module = dcl.loadModule('SceneStateStorageController')
module.call('publishState', '0,0', {})

Y eso haría que una escena pueda cambiar la escena deployada en tus parcelas, lo que no está bueno

**Comment by Suduck** [comment]
We need to talk with Nico Chamo about this issue

**Comment by olavra** [comment]
@pbosio please talk to @Suduck before he leaves to take over this task

**Comment by olavra** [comment]
@pbosio could you please comment why this task is blocked?
