### ISSUE TITLE
[QA] The commands do not work when used in any chat other than the nearby channel

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3210]
**Description:**
The chat commands do not activate when used in any chat other than the nearby channel.

**Steps to reproduce:**

1. Load into Decentraland via a wallet.
2. Add a friend.
3. Open a DM with a friend.
4. Input any chat command in the chat (ex. /help).
5. Observe the issue.

**Results:**
Lack of functionality for chat commands used in DM's.

**Expected results:**
Chat commands are functional when used in DM chats.

**Notes:**

- The issue can be reproduced only on wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/ecf0abf9-3ecb-4749-85bf-7da46cc65c74/_3210.mp4.

- Platforms: Web client, Windows client.

**Comment by anicalbano** [comment]
This issue is still active:

https://images.zenhubusercontent.com/337227404/9ac17244-dea8-4150-b802-62cf2ed7e497/20_07_2023_09_29_21_rec.mp4
