### ISSUE TITLE
[QA] Movement during the tutorial causes Alice to fall off screen

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3216]
**Description:**
Alice the tutorial robot disappears from the screen if the avatar is moving during specific sections of the tutorial. Launching the tutorial while riding a tram is the easiest way to reproduce the issues.
Alice disappears from the screen during the following tutorial sections:

- [ ] The introduction message after locking the cursor (Web client only) - this issue can be reproduced either by walking around the map or by riding the tram while the message is displayed: https://images.zenhubusercontent.com/337227404/8cca8814-87d7-4d03-aed4-047ac84193ff/_3216_01.mp4, https://images.zenhubusercontent.com/337227404/d9914607-8516-4a99-93fc-ec09bd2276e6/_3216_02.mp4.

- [ ] The section with explanations regarding all of the menu tabs (Map, Backpack, etc.) - in order to reproduce the issue, the user needs to switch between different tabs while the tram is moving: https://images.zenhubusercontent.com/337227404/ec1caafe-5f2c-4abf-b5df-5caba8269b0a/_3216_03.mp4.

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Reach the tram station (ex. **-11,0**).
3. Enter the tram.
4. Open the Settings menu (P).
5. Launch the tutorial.
6. Click on the screen to lock the cursor.
7. Observe that Alice falls off screen after a moment.
8. Reach the section of the tutorial explaining the specific menu tabs (ex. Map, Settings, etc.).
9. Switch between different tabs while the tram is moving.
10. Observe the issue.

**Reproduction rate:** 
5/5

**Results:**
Alice falls off screen if the avatar is moving during specific sections of the tutorial.

**Expected results:**
Alice is always present next to the tutorial message.

**Notes:**

- The issue can be reproduced on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached videos for reference.

- Platforms: Web client, Windows client.

**Comment by anicalbano** [comment]
Re tested and unable to reproduce the issue

https://images.zenhubusercontent.com/337227404/919ecd57-90cf-49fe-b61c-be38933cbe52/20_07_2023_16_08_16_rec.mp4
