### ISSUE TITLE
[QA] Animation glitch while falling from Genesis Plaza whirlpool

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3227]
Description: 
After jumping down into the whirlpool in the at the top of Genesis Plaza the falling animation glitches out by the end of the fall causing the player character to abruptly change the direction it is facing.

Steps to reproduce:    
1. Log in either on guest or a wallet account.
2. Use the command /goto 0,0 to teleport to the top of Genesis Plaza.
3. Jump down the whirlpool in the middle of the swimming pool.
4. Observe the player character.

Reproduction rate:
5/5 (100%)

Results:
Player character before the end of the fall abruptly changes the direction it is facing.
 
Expected results:
Player character retains its original facing direction during the fall.
 
Notes:    
-Platforms: web and desktop, wallet and guest login. 
-Issue occurs for both production and dev branches. 
-Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/d54cca0b-278d-47ea-b640-983e1642b12e/2022_10_12_11_00_22.mp4

**Comment by anicalbano** [comment]
The issue is still active:

https://images.zenhubusercontent.com/337227404/c7b32c5b-bbe6-491b-a620-dffec3c56b2a/20_07_2023_09_36_45_rec.mp4
