### ISSUE TITLE
Selective collectibles loading bug

### ISSUE THREAD

**Issue by Antivortex** [decentraland/unity-renderer#3237]
## Description

Collectibles are not being loaded with the exception of collectibles that the user is currently wearing. Happens in production.

Reported by Waan Chin

Waan Chin:
>Myself only tested for the first time yesterday. The user said it happened for months already.

![image.png](https://images.zenhubusercontent.com/62fb937fa41da238b0ed7951/cd441481-d9f6-44a4-9b29-48dcde1ac250)
![image.png](https://images.zenhubusercontent.com/62fb937fa41da238b0ed7951/c8148cba-5d41-48ca-8db4-f9748e437d74)
![image.png](https://images.zenhubusercontent.com/62fb937fa41da238b0ed7951/60d9c64e-fa32-4deb-8309-f5dd1d583fcc)

## Acceptance Criteria

1. All collectibles are loading, both equipped and not equipped
2. Equipping of collectibles and wearables is being saved persistently after the game restart

**Comment by Antivortex** [comment]
Update:

Waan Chin owned wearables request shows all wearables coming to the client without issues: 
https://peer.decentraland.org/lambdas/collections/wearables-by-owner/0x14c9b847EdE1C5a20E86F37AaCfa4a167f59A119

The log in the screenshot is from renderer and indicates that there are a lot of wearables coming to the renderer, which means most likely the issue is in the Renderer, though it does not reproduce for a test user in Goerli. We need to have an access to a user to diagnose it better.

![image.png](https://images.zenhubusercontent.com/62fb937fa41da238b0ed7951/b93035f5-d756-41d9-bc45-c3a40b752945)

**Comment by m3taphysics** [comment]
@kwspgoliasz @kwssbocian  I doubt this still happens? If so can you close it off :)

**Comment by m3taphysics** [comment]
Waan Chin confirmed this is still occurring for him.

**Comment by anicalbano** [comment]
Applies to the old backpack.
