### ISSUE TITLE
NFT Images are not loading

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3239]
Suddenly NFT images request to open sea are failing with this error.

![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/4081d2c7-90b3-4ef5-b424-8af2a74f0804)

This might be related to `unity-renderer` making generic requests without an API key.

We have to check if using this endpoint `https://builder-api.decentraland.org/v1/nfts/:contractAddress/:tokenId` works for us as well. 

- Check `RequestController` class at OpenSea folder
- Change the base URL at `Constants` class.
- Be aware that our URLs contain a batch of contractAddresses and we might have to split them for this new endpoint to work.

This is an example of our current request:
```
https://api.opensea.io/api/v1/assets?asset_contract_addresses=0x06012c8cf97bead5deae237070f9587f8e7a266d&token_ids=1540722&asset_contract_addresses=0x2a46f2ffd99e19a89476e2f62270e0a35bbf0756&token_ids=20606&asset_contract_addresses=0xfbeef911dc5821886e1dda71586d90ed28174b7d&token_ids=165777&asset_contract_addresses=0xf5b0a3efb8e8e4c201e2a935f110eaaf3ffecb8d&token_ids=265&asset_contract_addresses=0x273f7f8e6489682df756151f5525576e322d51a3&token_ids=50040004&asset_contract_addresses=0x8c9b261faef3b3c2e64ab5e58e04615f8c788099&token_ids=101663&asset_contract_addresses=0xd73be539d6b2076bab83ca6ba62dfe189abc6bbe&token_ids=64359&asset_contract_addresses=0x7fdcd2a1e52f10c28cb7732f46393e297ecadda1&token_ids=23221&asset_contract_addresses=0x3cd41ec039c1f2dd1f76144bb3722e7b503f50ab&token_ids=4&asset_contract_addresses=0x9255ed258dcbafe165dccd93ea0a72f4ed88e24d&token_ids=4252&asset_contract_addresses=0xecf7ef42b57ee37a959bf507183c5dd6bf182081&token_ids=100&asset_contract_addresses=0x41a322b28d0ff354040e2cbc676f0320d8c8850d&token_ids=3734&asset_contract_addresses=0x2a46f2ffd99e19a89476e2f62270e0a35bbf0756&token_ids=20343&
```

**Comment by Kinerius** [comment]
@xavier238 thank you for the suggestion! We are already in contact and progressing through a solution right now

**Comment by dalkia** [comment]
The issue has been fixed by open-sea, as they fixed their CORS configuration
More info on this thread:
https://decentralandteam.slack.com/archives/C02CNQT2D3M/p1665761510882979
