### ISSUE TITLE
Debug SSL Connection error in UnityGLTF observed in Atari Casino launch event

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#324]
`Unable to complete SSL connection - https://peer.decentral.games/lambdas/contentv2/contents/QmampaPP81wus1LCHSeEytaRzK67ffAwNBhsJgALByiKPZ
UnityEngine.Debug:LogError (object)
UnityGLTF.Loader.WebRequestLoader/<CreateHTTPRequest>d__19:MoveNext () (at Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs:77)`

![Screen Shot 2021-04-28 at 17.17.44.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/7aa6e327-c1f7-43e7-96e4-e84f4dbbfa25)

![Screen Shot 2021-04-28 at 17.16.30.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/ca49019f-e142-4e66-a0d1-0a49432d11c4)

**Comment by olavra** [comment]
Brian: Esto solo falla desde Unity, no desde el Browser
