### ISSUE TITLE
Adapt map and minimap for Worlds

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3252]
Worlds experiences won't have a specific integration to render the map per instance, which invalidates the mini map view.
By default, all scenes running in a World will hide the mini map.

Also, the map functionality won't be available so we need to display a message explaining what and why is happening that.

**Acceptance Criteria**
- [x] Mini map is not shown in a World
- [ ] Map is blurred and unavailable

[Link](https://www.figma.com/file/6EKamT36BbZT9dwTcho6ut/Spaces?node-id=2%3A7369) to figma project.
![Screenshot 2022-10-14 at 22.39.20.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/70e071b4-ecdb-4244-b5af-972bbc030553)

**Comment by menduz** [comment]
Mini map is OK to be hidden. On the contrary, keeping the full map may be convenient as a quick way to exit the scene and teleport back to the genesis city. I wouldn't disable it, just like the explore feature. Think about the onboarding tutorial, if you already know where you are going to you may want to click on explore or the map directly to exit the tutorial

**Comment by dalkia** [comment]
Since there is no map to disable, there is no configuration to be done for worlds. We can close this task
