### ISSUE TITLE
Jump in Genesis City button for Worlds

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3253]
Individual scenes running in a World, will need a consistent way to go to the Genesis City. As the mini map wont be displayed in Worlds, we will use that space to place a button stating "Jump to Genesis City"

**Acceptance Criteria**
- [x] This new button will always be available during a World
- [x] This button cant be render behind any other scene UI
- [x] Clicking on this button will teleport the player to any realm in the position 0,0
- [x] Mini map can be disable in world depending on the AboutConfigurations

[Link](https://www.figma.com/file/6EKamT36BbZT9dwTcho6ut/Spaces?node-id=1%3A212) to Figma.

![Screenshot 2022-10-14 at 22.39.34.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/f8878660-fc52-48df-a361-2389acfb0f8a)

**Comment by menduz** [comment]
Can you change the "jump to the home point" instead of 0,0?
