### ISSUE TITLE
Disable green blockers while in Worlds

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3254]
Worlds experiences do not need a green blocker to limit the surrounding scenes. As it happens while you walk through the border of the world, and empty parcels load, the player will experience the same while exiting the boundaries of the World scene

**Acceptance Criteria**
- [x] Green blockers are disabled during a World scene
- [x] Player can walk outside the World scene boundaries, and empty parcels will load infinitely

**Comment by menduz** [comment]
Just a detail, empty parcels are disabled for worlds since they consume lots of memory resources
