### ISSUE TITLE
UI scene alert box visible despite UI being turned off

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3267]
Description: 
The scene alert box that notifies of special conditions being applied to the player by the scene is being shown despite the UI being turned off.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in either on guest or a wallet account.   
2. Use the `/goto -29,55` command to teleport to Wondermine and walk over to the nearby purple Craft-O-Matic machine.
3. Press the U key on the keyboard to deactivate the UI.
4. Observe the user interface.

Results:    
Scene alert box is being shown despite UI being turned off.

Expected results: 
Scene alert box is hidden when the UI is turned off.

Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/468850ba-be72-4d04-a095-8d25c132b60d/2022_10_18_13_17_03.mp4

**Comment by 0xD-Fabio** [comment]
This has been fixed by another task completed by @dalkia
