### ISSUE TITLE
Initial chat notifications are displayed on incorrect background

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3268]
**Description:**
Any chat notifications shown when accessing the platform as a new user are displayed on a grey background if the tutorial is skipped.
The background for the notification becomes transparent again after the cursor is locked for the second time.

**Steps to reproduce:**

1. Load into Decentraland as a new user (ex. logging in as a guest via the incognito mode).
2. Wait for the tutorial to start.
3. Skip the tutorial.
4. Observe the issue.

![#3268_01.jpg](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/ff10414f-a940-4176-8b49-5ea1ff6a721e)

**Reproduction rate:**
5/5

**Results:**
The initial chat notifications are displayed on a grey background for new users who skipped the tutorial.

**Expected results:**
The chat notifications are always displayed correctly.

**Notes:**

- The issue occurs only for newly created avatars.

- The issue was reproduced on the guest account.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/6cbd78df-dca5-46f3-a764-37b333a3e0e0/_3268.mp4.

- Platforms: Web client, Windows client.

- The issue can be also seen momentarily after opening the Control Panel during the tutorial.
![#3268_02.jpg](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/62514b49-c642-40a5-925b-8cc061b41cfe)

**Comment by PalauiDCL** [comment]
Blocked due to:
Could not reproduce the issue,
There seems to be some changes in the chat system since this issue was raised, will talk to QA in order to unblock it

**Comment by PalauiDCL** [comment]
As the issue can not be reporducen anymore and the system changed, this issue is now closed
