### ISSUE TITLE
FPS Drop when Video Streaming is playing on WebGL

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3278]
Our team discovered that when playing videos on WebGL we had an fps drop from 60 to 45, since this feature only works on WebGL builds it's pretty hard for us to profile this issue. 

Test link with a video that can be played and paused.
`https://play.decentraland.zone/?renderer-branch=fix%2Fbug-video-throttled-even-if-close&NETWORK=mainnet&position=-74%2C-99&CATALYST=peer-testing.decentraland.org&realm=testing`

Video Proof:

https://user-images.githubusercontent.com/7646450/196703715-49342d0c-f63b-4ad8-853f-9f54bda66c3c.mov

- We have to investigate the root cause
- We can also try the new AVPro implementation since it supports WebGL and compare their performance.

**Comment by dalkia** [comment]
Investigated if AVPro was a viable option.

Nonetheless, how we need AVPro to copy textures is not an option in WebGL. So is not an option we can use
