### ISSUE TITLE
[QA] Body of tram not rendering while tram is in motion

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3284]
Description: 
Trams of all four tram lines that travel between Genesis Plaza and other plazas occasionally appear with their body, with the exception of windows, not rendered while being in motion. Issue occurs seemingly at random as no graphical settings appear to have any influence on the result. Reproducing the issue will likely require jumping between different tram stops.

Reproduction rate: 
1/5

Steps to reproduce:    
1. Log in either on guest or a wallet account.
2. Open up the map interface and teleport to any road tile around the Genesis Plaza that is close to any of the four tram lines.
4. Observe the nearby incoming tram. If the tram appears to be rendered correctly open up the map interface again and teleport next to any other tram station adjacent to Genesis Plaza.

Results:    
Tram's whole body except for windows is not rendered while the tram is moving.

Expected results: 
Tram's body is being rendered at all times.

Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for the production and dev branch.
- Please see the attached video for reference.
https://user-images.githubusercontent.com/110463715/199515512-8cb5730c-4866-47d7-87e8-e107a33db907.mp4

**Comment by JorgeDecentraland** [comment]
Hi @PalauiDCL @kwspgoliasz @kwssbocian could you double check if this is still valid, please?

**Comment by kwssbocian** [comment]
We have rechecked the issue and it still occurs in production and dev, although the reason for the issue doesn't seem to be the object culling as it was now able to be reproduced without the option turned on in the settings. I have modified the ticket accordingly.
