### ISSUE TITLE
New friends are not saved correctly for all of the players

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3286]
**Description:**
Newly added friends are removed from the friend list if the user logs out soon after the invitation is accepted. The issue was confirmed to occur when logging out after 1 minute since the invitation was accepted.
After the relog, one of the following results can be observed:

- [ ] In most cases, the friend is removed from the list for one user.  Moreover, the affected user automatically receives an invitation in their requests tab upon a relog.

- [ ] In rare cases, the friend is removed from the list for both users.

**Steps to reproduce:**

1. Load into Decentraland via a wallet with two avatars.
2. Have the two avatars become friends.
3. Log out with both avatars.
4. Relog into Decentraland with both avatars.
5. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
Logging out of the wallet soon after becoming friends with someone, results in the friend getting removed from the friend list after a relog.

**Expected results:**
The added friends are saved properly at all times.

**Notes:**

- The issue can be reproduced only with a wallet account.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/ea9e40fd-c9ec-4183-a1e1-2c056cdc27de/_3286.mp4.

- Platforms: Web client, Windows client.

**Comment by anicalbano** [comment]
Unable to repro with the current settings:

https://images.zenhubusercontent.com/337227404/fa8cae22-30c9-4e75-ae0d-8d382811838a/21_07_2023_09_30_45_rec.mp4
