### ISSUE TITLE
Character Preview loses face features after swapping and saving body changes

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-renderer#3289]
Description: 
After saving a couple of times the avatar in the backpack, the character preview eventually loses the face features. Therefore, an incorrect avatar snapshot gets saved.

Reproduction rate: 
1/5

Steps to reproduce:    
1. Log in either on guest or a wallet account.   
2. Open up Backpack -> Avatar -> Body.
3. Switch the body type to the other one than the avatar is currently using.
4. Click done to save the changes and exit the menu then quickly open up the backpack's body section again.
5. Keep repeating steps 4 and 5 until the avatar's face disappears.
6. Observe the avatar's face.

Results:    
Avatar's face disappears after quickly changing appearance and saving the changes.

Expected results: 
Avatar's face does not disappear after quickly changing appearance and saving the changes.

Notes:    
- Platforms: Windows web, wallet and guest login. 
- Issue occurs for production branch.
- Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/e28e3cc3-c520-498b-8009-386bab1c0e40/2022_10_20_12_43_19.mp4

**Comment by JorgeDecentraland** [comment]
@kwspgoliasz @kwssbocian could you try to reproduce this issue, transform it into a bug and add any relevant information missing, please?

**Comment by kwssbocian** [comment]
Issue has been reformatted to be in line with the proper template. As for the reproduction we were unable to reproduce the issue on both production and dev branches and on all platforms - Web, Windows desktop and MacOS.
