### ISSUE TITLE
[QA] Changing the window size during the tutorial causes issues with specific messages

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3291]
**Description:**
Changing the window size/screen resolution has a negative effect on the tutorial messages with an arrow pointer. The position of these messages is not readjusted after the resolution is changed, causing the message to become offset from its intended position.

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Enter the Settings (P).
3. Launch the tutorial.
4. Continue with the tutorial until a message with an arrow pointer appears (ex. message regarding the voice chat).
5. Change the window size/resolution.
5. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
The tutorial messages with an arrow pointer are not readjusted after the window size is changed.

**Expected results:**
The tutorial messages are adjusted to the changes in the window size/resolution.

**Notes:**

- The issue can be reproduced on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- The issue occurs for all of the messages with arrow pointers.

- Please see the attached videos for reference: https://images.zenhubusercontent.com/337227404/b12d21b7-4afb-46a9-8639-bc7671359b6e/_3291_01.mp4, https://images.zenhubusercontent.com/337227404/d3abf683-8e7d-46cb-89ab-dba0ccb5dfab/_3291_02.mp4.

- Platforms: Web client, Windows client.

**Comment by aixaCode** [comment]
The tutorial at current state will be removed, and replaced with new onboarding.
