### ISSUE TITLE
Crash in profiles with many emotes

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#3300]
Note: might be same as #3695

https://twitter.com/fancydcl/status/1583828236634828800?s=46&t=lAfyimSP_3pmGgLo6ilC1A

Users are reporting crashes when dealing with many emotes.

Take a look at the equipped emotes for the backpack, we are probably not using pagination there.

Acceptance criteria
- [ ] Users with an arbitrarily large amount of emotes do not crash.

**Comment by m3taphysics** [comment]
@kwspgoliasz can you try to reproduce this?

**Comment by kwspgoliasz** [comment]
@m3taphysics Unfortunately, we won't be able to test this issue, as we don't have access to large amount of NFT emotes.

**Comment by xavi-dcl** [comment]
Closing as we tackled this in a separate issue (long json mitigation)
