### ISSUE TITLE
Profile Video Streaming

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#3301]
We've received some reports of Video Streaming in WebGL having a worse performance compared to previous Metaverse Festival.

Research regressions and take a look at different codec/video formats.

Acceptance Criteria:
- [x] Analysis of performance (if possible comparison with previous year)
- [x] List of recomendations of codecs and formats for better performance.

**Comment by popuz** [comment]
First investigations
1. It seems that this issue only appears in pure Chromium-based browsers. Such browsers as Firefox, Safari, and even Edge do not have it.
2.  Issue relates mainly to the rendering of the RenderTexture on the Canvas. See notes on this page
https://www.notion.so/decentraland/Video-Streaming-10-2022-5bd80fbea58e41d3a07793ba08565fda

**Comment by popuz** [comment]
While testing different formats, it would be good to know what are the requirements for us. How crucial for us video quality, alpha channel quality, colors precision and etc. @aixaCode, can you bring some light on it? :)
