### ISSUE TITLE
Add message feedback for video error

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-renderer#3303]
### Description
Right now, while videos are loading, of if videos fail, there is no feedback message. 

### Deliverables
- [ ] Feedback to show a video has failed loading

**Comment by RominaMarchetti** [comment]
@dalkia can you provide an example on where should I design this feedback?

**Comment by RominaMarchetti** [comment]
As we discussed already, keep in mind to make this feedback adaptable to any resolution. The UI elements such as icon, animated spinner and text always in the center as a group.
The camera assets are attached below.

![VideoFailedIcn](https://user-images.githubusercontent.com/51088292/200417036-ba33267c-3d53-49d8-ad15-6d90d99c447f.png)
![VideoCamIcn](https://user-images.githubusercontent.com/51088292/200417039-e67f5094-a557-433c-bf59-a2ca69e6e15d.png)

**Comment by PalauiDCL** [comment]
On it

**Comment by PalauiDCL** [comment]
![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/dbe199a0-bdd6-4488-b662-6f95e1b82fea)

**Comment by RominaMarchetti** [comment]
The copy must be fixed: is `could` instead of `cold`.

**Comment by PalauiDCL** [comment]
![image](https://user-images.githubusercontent.com/113350816/215087414-10945f91-a8bb-44c4-9737-ce53f5c1ea8d.png)

**Comment by RominaMarchetti** [comment]
Great, Mark <3

**Comment by PalauiDCL** [comment]
Update info for this task, QA has not been able to find a video that is not working so they could not confirm yet the task.
@kwssbocian , @dalkia informed me that there is a video for him in coordinates 63,62 that is failing, I will try myself too

**Comment by m3taphysics** [comment]
See: #4315
