### ISSUE TITLE
Channels refinement iteration 5

### ISSUE THREAD

**Issue by davidejensen** [decentraland/unity-renderer#3317]
- [x] The [pop up](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3167%3A24291) that prevents the player to create a new channel after reaching the limit is not being shown. We shouldn't be showing that feedback here:

<img width="371" alt="issue1" src="https://user-images.githubusercontent.com/4254522/197775088-81209f0a-5d2f-4752-91b3-99b78f6cd39d.png">

This affects the flows when you try to create a channel from the searching error message [example 1](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3423%3A34559) [example 2](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3423%3A34781) and from the chat window as well.

- [x] The pop up with the message saying that you can't create a new channel after reaching the limit doesn't match the design: container size, buttons, fonts, etc. Use the modal Are you sure you want to leave this channel as reference which is correctly implemented.

- [x] The members button width container must be dynamic. The distance between the icon and the number a constant. [Example 1](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=3197%3A31407), [Example 2](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=2829%3A21201)

<img width="67" alt="Issue2" src="https://user-images.githubusercontent.com/4254522/197775484-4e499c2a-9ec3-4093-8d8a-26db6594e194.png">

**Comment by lorux0** [comment]
We have decided with @RominaMarchetti to leave the channel creation flow as it is now. Because the most certain way to know that the user has not exceeded the amount of channels is try to create it. The changes prevents the user to open the channel creation window, and show the error toast instead. We cannot anticipate this information, at least is not 100% certain

**Comment by xavi-dcl** [comment]
@olavra please check the recommendation, should we keep the flow as it is now?
