### ISSUE TITLE
Update profile card in explore menu

### ISSUE THREAD

**Issue by davidejensen** [decentraland/unity-renderer#3329]
As explained in https://www.notion.so/decentraland/PRD-Extended-Passport-c427c485ede9480bb106389f5a4441f7
we need to update the current profile card that can be edited in the explore menu.

![Screenshot 2022-10-26 at 10 00 41](https://user-images.githubusercontent.com/4254522/197968925-35925f70-5e9e-4480-a212-df5f64d045fe.png)

Acceptance criterias:
- [x] Implement behind feature flag
- [x] Enlarge the card
- [x] Allign name to the left
- [x] Rename "About" to "Intro"
- [ ] Increase max characters from 140 to 400 (Verify if this limit is only on renderer)
- [x] Add dynamic height to text box depending on the text length
- [x] Add the pencil icon as always visible
- [x] Clicking on icon or on the box will allow to edit the text
- [x] The Pencil icon changes to a check icon in edit mode. To confirm the edition is complete the person must click that icon or press enter
- [x] Add possibility of defining clickable links in the description with the format [text](url)
- [x] If a url is written in plain then the link should show the domain name
- [x] Add a view passport button that will open the passport of our user
- [x] Add a new info button. When mouse hover it shows a [toast](https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Passport-%2F-Profile?node-id=2034%3A5038) telling Add links at the end of your intro if you want them to be interpreted as a separate section.

Technical assessment: https://www.notion.so/decentraland/RFC-Technical-Assessment-extended-passport-WIP-2bb32a1811114313b96e74a4efe3b855#ee03ba78b0664665be1559a805dda78e
Figma design: https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Passport-%2F-Profile?node-id=2055%3A5217

**Comment by PalauiDCL** [comment]
@davidejensen @m3taphysics 

![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/51375299-28da-41ba-adfa-0e630bbc342b)

Image for the wallet users

![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/55cf418e-0c9c-46df-b433-a132da4c5d51)

This one for non wallet users.

Note that some icons are missing, I still do not have access to figma (Is requested) and as soon as is granted, I will add the remaining icons and create the PR

**Comment by PalauiDCL** [comment]
Figma permission received

**Comment by PalauiDCL** [comment]
![image.png](https://images.zenhubusercontent.com/631f1a6f95c037ac427fe0c2/5dc5833b-c8ac-498f-9000-c049c8025b4e)

Some links
