### ISSUE TITLE
The user gets stuck on the loading screen after creating a new avatar

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3336]
**Description:**
Newly created avatar gets stuck on the loading screen after the Terms of Use are accepted. While the user is stuck, the Genesis Plaza BGM can be heard along with the sound of Alice robot spawning.
Reloading the page allows the user to load into the platform.
The issue is thought to be related to profile not downloading. 

**Steps to reproduce:**

1. Clear the browser cache or open the incognito mode.
2. Load into Decentraland as a guest.
3. Create the avatar and approve the Terms of Use.
4. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
The platform gets stuck on the loading screen after a new avatar is created.

**Expected results:**
A new avatar is correctly loaded after creation.

**Notes:**

- Link to the slack thread: https://decentralandteam.slack.com/archives/C03RCNGSV2B/p1666861729160779.

- The issue was reproduced on the guest account.

- The issue occurs on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/b59200ac-ad2f-4f60-bdb4-63edb0735401/_3336.mp4.

- Platform: Web client.

**Comment by dalkia** [comment]
Fixed on [kernel](https://github.com/decentraland/kernel/commit/6541f9dd577c296b68bcd72beabe2c7eb84cc3ae)

This issue will eb further investigated and solved with RFC-1
