### ISSUE TITLE
TextShape 'billboard' property is not working anymore

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#3342]
This can be tested at the beginning of the Salmonomicon, the Textshape above Mika's head has the `TextShape.billboard` in `true` and it's not working anymore.

<img width="1548" alt="Screen Shot 2022-10-27 at 19 37 06" src="https://user-images.githubusercontent.com/1031741/198360396-15f181de-fb9a-494d-8797-7f21839278f7.png">

**Comment by PalauiDCL** [comment]
Very weird bug, it seems that Unity "Compiled" incorrectly, once the method was modified with nothing else than a Debug.Log, started working again.
