### ISSUE TITLE
Logged out avatars are visible in-world

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3347]
**Description:**
A logged out avatar is spawned in-world when loading into the platform with another account. The aforementioned avatar is visible and interactable for for a couple of minutes before properly disappearing.
Usually, the avatar can be seen right after logging in, however, sometimes it spawns after a short delay. In some cases, the logged out avatar is displayed with a different username but the same code after the # sign.

**Steps to reproduce:**

1. Clear the browser cache.
2. Have two avatars created on separate browsers (guest or wallet).
3. Load into Decentraland with the first avatar (ex. from Mozilla Firefox).
4. Move around the starting location.
5. Exit the platform.
6. Load into Decentraland with the second avatar (ex. from Chrome).
7. Approach the last position of the logged out avatar.
8. Observe the issue.

**Reproduction rate:**
4/5

**Results:**
The logged out avatar stays in-world for prolonged period of time after the logout.

**Expected results:**
The avatar is removed from the world after logging out.

**Notes:**

- The issue occurs on both the guest and wallet accounts.

- The issue occurs on both the production and development configurations.

- Please see the attached videos for reference: https://images.zenhubusercontent.com/337227404/fc173dd7-31ae-47d2-8e82-c20b042f22f6/_3347_01.mp4, https://images.zenhubusercontent.com/337227404/fff51dff-f674-474f-8ec5-be1a5553874f/_3347_02.mp4.

- Platform: Web client, Windows client.

**Comment by JorgeDecentraland** [comment]
@menduz could you help us assessing this issue? Is this caused by SDK behavior?

**Comment by menduz** [comment]
Sure.. @hugoArregui can you check the comms side of things?

**Comment by hugoArregui** [comment]
Sure, I'll take a look

**Comment by hugoArregui** [comment]
This should do the trick: https://github.com/decentraland/lighthouse/pull/67

**Comment by davidejensen** [comment]
I've just finished testing this and it appears to be properly fixed!
