### ISSUE TITLE
Billboards optimization

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3363]
## Moving the camera
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/3251393b-d93a-4f39-9590-8ec546ab11c8)

When moving the camera all billboards get updated with the same information at the same time, that's 255 calls every frame while moving the camera at -66,-55 during Halloween event, there are 255 billboards there to test.

## Pasive degradation
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/e8512127-3825-4519-9043-74cf9055b7b3)

Billboards also contain polling logic that are pretty slow for what they do.

## What to do?

Since all those components do the same thing, we can create a system to do the same thing in one single update to avoid most of the overhead of calling hundreds of methods.

**Comment by xavi-dcl** [comment]
@PalauiDCL could you make the changes requested by QA so we can review again and close? Thanks
