### ISSUE TITLE
Desyncronization when changing wearables 

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3379]
We have evidence that confirms that when changing wearables the final state of the avatar goes back to one version for some reason.

https://images.zenhubusercontent.com/337227404/d4386a4a-6c51-4a66-a2b7-b77d503cec41/screen_recording_2022_11_01_at_12_32_17__1___1_.mov

## Possible repro steps

These repro steps are based on a previous experience with this bug and might change.
- Change a wearable, try changing a hat
- When pressing done if you observe your avatar without a hat, it means that next time you change another wearable you are going to have that next version
- Change other wearable, this time some pants
- When pressing done this time the avatar should have the new hat but not the new pants

**Comment by PalauiDCL** [comment]
Blocked: Waiting for SDK to answer on the problem found by @davidejensen

**Comment by PalauiDCL** [comment]
Closed due to: Closed by sdk team
