### ISSUE TITLE
[QA] The in-world audio stops working at times

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3380]
**Description:**
It has been reported by the developers that the in-world audio may suddenly stop playing when standing around at random locations. The issue was observed at Genesis Plaza and Vegas Plaza.

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Stand around at various places in Genesis Plaza/Vegas Plaza.
3. Observe the issue.

**Reproduction rate:**
1/5 - the issue could not be reproduced by QA.

**Results:**
In rare cases, the audio may suddenly stop playing.

**Expected results:**
Lack of audio issues in-world.

**Notes:**

- The issue was tested on both the production and development configurations.

- The issue was tested on both the guest and wallet accounts.

- Link to the Slack thread: https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1666707072992649.

- Please see that Slack thread and the screenshot for more information.
![#3380.png](https://images.zenhubusercontent.com/62e91e7768dcacf1dc4a4c39/9b531519-001f-49db-9759-a7369bf2c0dd)

- Platform: Web client.

**Comment by m3taphysics** [comment]
See notes in: #4488
