### ISSUE TITLE
Realtime change the internal Fog Based On Player Position (Infinite Floor

### ISSUE THREAD

**Issue by MichaelBitsakis** [decentraland/unity-renderer#3398]
When Player is closer to the edges we need a smaller internal Fog radius in order to cover the ground

## Is this something you can **debug and fix**? 

Send a pull request! Bug fixes and documentation fixes are welcome. You can avoid the issue.

---

Acceptance Criteria : 

- [x] Cover All 4 edges
- [x] Dynamically Adjust the fog 
- [x] Option to adjust the radius AND keep the original value
- [x] Supply Player Position to Shader (Alex)

**Comment by MichaelBitsakis** [comment]
![edge_4.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/ac61696f-77bd-4574-bf7b-7263258e7afc)

**Comment by xavi-dcl** [comment]
@MichaelBitsakis could we try reviewing and getting this out?

**Comment by MichaelBitsakis** [comment]
@xavi-dcl This version was pushed to the festival. There is a new one pending review. Ticket #3421

**Comment by xavi-dcl** [comment]
OK so if this means we should close this ticket, let's do it.
