### ISSUE TITLE
Issues with avatar spawning at Genesis Plaza island

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3399]
**Description:**
Teleporting to the floating island on top of Genesis Plaza causes multiple issues with the avatar spawning. The aforementioned issues are:

- [x] The black screen is displayed instead of the loading screen (clicking the mouse button makes it disappear) - https://images.zenhubusercontent.com/337227404/f0c152c2-d10f-4314-a5ca-9bc58023ab64/3399_01.mp4

- [ ] The user is spawned at the ground floor of Genesis Plaza main building - (occurring approx 1/50, could potentially be related to low-performance PC's/timing issue) https://images.zenhubusercontent.com/337227404/7380b065-5acc-4dd7-bd1f-08df7dfe8a2d/3399_02.mp4

- [x] The user is spawned on the roof of the Genesis Plaza main building - https://images.zenhubusercontent.com/337227404/20edd927-ac17-4a89-9d52-9b20925175ef/3399_03.mp4

- [ ] The text bubble from one of the NPC's is displayed on spawn, which results in the BGM turning off after a couple of seconds - https://images.zenhubusercontent.com/337227404/2b6988b9-31e5-4360-abfb-d1a1c7393545/3399_04.mp4 

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Teleport outside of Genesis Plaza.
3. Teleport back to Genesis Plaza (ex. by using /goto 1,1 command).
4. Observe the issue.

**Reproduction rate:**
4/5

**Results:**
Teleporting to Genesis Plaza causes multiple in-world issues.

**Expected results:**
The user is always spawned correctly when teleporting to Genesis Plaza.

**Notes:**

- The issue occurs on both the production and development configurations.

- The issue occurs on both the guest and wallet accounts.

- Please see the attached videos for reference.

- Platforms: Web client, Windows client.

- On the windows client the issue occurs very rarely.

**Comment by popuz** [comment]
@aixaCode, I tested kernel PRs and all these issues started to happen after merging [this PR]( https://github.com/decentraland/kernel/pull/595). 
Because [previous one](https://github.com/decentraland/kernel/pull/594) works smooth regarding these problems

**Comment by m3taphysics** [comment]
@kwspgoliasz can you re-test the above issue. Our current belief is that the black-screen is still potentially still there but all the rest are fixed.

**Comment by kwspgoliasz** [comment]
@m3taphysics Most of the issues were fixed. The user no longer spawns outside of the island, but, as you mentioned, the black screen issue still occurs from time to time.
The text bubble from the fourth scenario is still spawned, but only at the welcome screen displayed when loading into the area for the first time.
Additionally, a new issue with BGM and radio music playing simultaneously started to occur after teleporting on top of the island.
Should these two additional issues be dealt with separately?

**Comment by xavi-dcl** [comment]
@m3taphysics do you prefer one ticket or separate bugs for what is outstanding?

**Comment by xavi-dcl** [comment]
@kwspgoliasz how critical is this now, should we remove the 'high priority' pin or should it be fixed ASAP.

**Comment by kwspgoliasz** [comment]
@xavi-dcl The main issues with black screen and spamming on the roof are no longer present, so in my opinion the high priority tag could be taken off.

**Comment by kwssbocian** [comment]
@xavi-dcl As requested, issues raised separately under #3714 and #3715. Closing.
