### ISSUE TITLE
[QA] Incorrect label is applied for the ultra graphics quality configuration

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3405]
**Description:**
When changing the graphics quality to ultra, the label for the setting is automatically switched to custom instead.

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Open the settings menu (P).
3. Choose the Graphics section.
4. Change the Graphics Quality to Ultra.
5. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
Incorrect label is applied for the ultra quality settings.

**Expected results:**
The correct label is applied for every graphics quality configuration.

**Notes:**

- The issue occurs on both the production and development configurations.

- The issue occurs on both the guest and wallet accounts.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/652cb5f6-7bc6-47c1-9cde-082c28b6ba3f/_3405.mp4.

- Platform: Web client.

**Comment by kwssbocian** [comment]
Fixed in #4156. Closing
