### ISSUE TITLE
Sometimes messages are getting duplicated in nearby

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#3413]
In the #nearby channels, sometimes the messages gets duplicated. There are no detected repro-steps yet. Need analysis.

![Screenshot 2022-11-03 at 12.47.42.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/cc534a0c-95a3-4eae-a3b4-a393bd540821)
![Screenshot 2022-11-03 at 12.31.42.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/b6b0043a-916d-4bd5-885a-ec3f8ecab4c8)

**Comment by hugoArregui** [comment]
I think the problem may be we are not using the chat id sent in comms, but a random id: https://github.com/decentraland/kernel/blob/main/packages/shared/comms/handlers.ts#L277 and idea could be to use the message timestamp

**Comment by lorux0** [comment]
cannot reproduce it

**Comment by lorux0** [comment]
i could not reproduce this issue anymore, will leave it blocked for a while. If i see that it does not happen anymore then i will close it

**Comment by xavi-dcl** [comment]
@nlorux I hope you don't mind if I close this. If we see it again and figure out how to reproduce it or it is happening way too often, we can always reopen it.
