### ISSUE TITLE
Random objects spawn on the tram lines

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3417]
**Description:**
An issue with objects spawning in the middle of the road occurs when walking down the tram lines. The issue can be observed on multiple roads, however, the object spawning seems to be the most prominent when walking down the tram line from 50,-50 to 0,-50. The objects may spawn either in front, or behind the user.

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Teleport to the road at 50,-50.
3. Walk down the tram line towards 0,-50.
4. Observe random objects spawning in the middle of the road.

**Reproduction rate:**
5/5

**Results:**
Objects are spawning randomly when walking down the tram lines.

**Expected results:**
No object spamming occurs when traversing through the world.

**Notes:**

- The issue occurs on both the production and development configurations.

- The issue occurs on both the guest and wallet accounts.

- Please see the attached videos for reference: https://images.zenhubusercontent.com/337227404/2256032d-f4fc-41be-9089-7a6037ce6cd0/_3417_01.mp4, https://images.zenhubusercontent.com/337227404/92e7c184-349d-4da1-ac37-f0d815659b33/_3417_02.mp4.

- Platforms: Web client, Windows client.

**Comment by AjimenezDCL** [comment]
I couldnt find the root cause, Im rolling out a mitigation fix.
