### ISSUE TITLE
Procedural Skybox Ground gradient FIX 

### ISSUE THREAD

**Issue by MichaelBitsakis** [decentraland/unity-renderer#3421]
Procedural Skybox Ground FIX 

Feature exists in a WRONG implementation.

Gradient on Horizon Plane exists and works.

BUT 

1. It takes the colours from the gradient and INSTEAD of applying a polar gradient only to the ground
to give this full blown gradient we are looking for it adds the System Time of top of that , as a result we have the colors changing during the day.
It follows the gradient coloration BUT it changes each color based on time.

2. Just like the penetrating sun WHEN we use the smoothness NOW we have a new BUG with STARS penetrating the ground
and giving a SEA REFLECTION look to it.... could be used in a like scenario but not right here.

3. Centre the ground polar coordinate to the infinite floor transform position.

Showing the issues in images

![TimeAppliedOnColors.png](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/948ee8db-8ca2-4b8b-b8e1-3f0432d9cdaf)

![TimeAppliedOnColors_2.png](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/b5b58604-a4db-45b7-a09e-e0140892e659)

![StarsPenetratingGround.png](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/0bca474c-9dfb-4b84-9d64-ee73fb6439c3)

![WrongPolarCoordinates.png](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/13b1ab6a-3008-45f6-9b9b-3ca183482d6d)

NEW BUG AFTER FIXING THE STARS PENETRATION![NewBug_Loosing Sky.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/76cfaadb-9c7d-4640-98fc-1abc5008809d)

Detailed explanation of issues via video:

https://images.zenhubusercontent.com/337227404/7fee51b9-dd3d-4e38-ae7b-92098c388657/proceduralskyboxfullblowngradient_1.m4v

Must :

Have gradient of the floor from internal Fog radius and up to the END of the ground where it meets the Mountains

checklist

---

- [x] Check existing code
- [x] Check existing shader
- [x] Check editor tool
- [x] Problem identification 
- [x] Proposed solution

- [x]  Find and estimate possible brakes on the infinite Floor from those changes as they are closely developed.

- [x] Add a separate gradient for the ground that is not changed by time of the day
- [x] FIX stars penetration to the floor
- [x] Centre the ground polar coordinate to the infinite floor transform position.

- [x] Stars penetration fix generates a new bug due to wrong functionality in the shader.
Now along with the stars we also loose the sky layer as well. Adding this to the ticket and i will fix that as well

Images and videos will follow explaining the current issues and solutions.

Acceptance Criteria 

As an update to the latest version we created now we need to take it to the next step : 

- [x] Remove light from Fog on the Floor to have a uniform colour between the two elements
- [x] Completely connect the two elements of Procedural Skybox and Infinite Floor to a continues gradient 
- [x] Edges cases for player position to hide the end of the floor

NEW EFFECTS

- [x] Alternative method for covering the outer edges of the floor quad when avatar/player is near.
- [x] Grass at the edges of the map itself can been shown

---

**Comment by MichaelBitsakis** [comment]
Fixed polar coordinates and added opacity control to mask the stars.
Next is star layer masking to end up with the new gradient

![fixed_polar coordinates.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/fe6d8d9a-495d-4e0b-bf96-69156f057372)

**Comment by MichaelBitsakis** [comment]
Fixed stars penetrating the ground (and every other 2d layer that supports texture input)

![fixed_stars_and_all2d_layers.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/787a20ef-4965-42d3-8548-e5e4818141b2)

**Comment by MichaelBitsakis** [comment]
Stars penetration fix generates a new bug due to wrong functionality in the shader.
Now along with the stars we also loose the sky layer as well. Adding this to the ticket and i will fix that as well

**Comment by MichaelBitsakis** [comment]
Fixed the sky not showing BUG that was created from the 2D Layers Ground Cut.
Also re arranged and fixed the order of the internal layers so we dont get this again in other layers as well.

**Comment by MichaelBitsakis** [comment]
Full Blown Ground Gradient without having Sun or Sky passing through .
Also fixed the radial and polar settings on this layer as well so we get the effect we are after.![Full_Blown_Ground_Gradient.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/548e6a1d-b80f-465c-8fd1-4047e9370ed0)

**Comment by MichaelBitsakis** [comment]
Detailed video with the fix

https://images.zenhubusercontent.com/337227404/b46df083-1fd5-42cd-9dee-b53da6ebed44/proceduralskyboxfullblowngradient_1.m4v

**Comment by MichaelBitsakis** [comment]
High ground effect look

![high_ground.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/89ac9ce5-267d-4ea9-9e93-f6725c690a28)
![highground_2.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/3c72dc4d-86b7-4e47-bc22-3edeb81183f4)

**Comment by MichaelBitsakis** [comment]
![highground_3.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/b92e3265-0387-4799-989a-93e80cd06471)

**Comment by MichaelBitsakis** [comment]
New Fog pallete to get a match with the full blown ground effect

https://images.zenhubusercontent.com/337227404/d87a9b68-52da-4d77-95e1-d146eed89179/fullblowngroundgradient_color_match_1.m4v

**Comment by MichaelBitsakis** [comment]
Set it to review

**Comment by MichaelBitsakis** [comment]
Reduced Gradient transparency more.
If we go more we loose the gradient effect 

![transparency_reduced.jpg](https://images.zenhubusercontent.com/6310d8645178a7423f8cf237/35eb1465-1473-4fdb-9e9e-eec36169ead4)

**Comment by MichaelBitsakis** [comment]
EXPERIMENTAL FEATURE 

Managed to pass color data from Procedural Skybox to Infinite Shader via pixel touch. We can now have a complete seamless connection.
[Uploading... Passingcolorthoughtseparateshaderviapixeltouch-1.m4v]

**Comment by MichaelBitsakis** [comment]
Latest Update everything is connected regarding Procedural Skybox - Infinite Floor
Radius of infinite fog is reduced if player goes above certain coordinates to avoid showing the end of the floor.

Further explanations in the attached video.

Will test further on Monday to get any weird position cases (if any)
Branch is updated for testing as well.

https://images.zenhubusercontent.com/337227404/264a431f-5e25-4b91-9ddd-a6bad6179d3c/latest_update_infinitefloor_skybox_1.m4v

**Comment by MichaelBitsakis** [comment]
- Changed the logic in the shader that changes the inner fog radius based on the player position due to weird cases.

- Wrote Shader graph debugger to solve weird cases in a numeric - visual form

- Fixed workaround with flipped uvs (from previous TA in order to read the players negative values) . Now Player position works as expected . Tested and pushing for review.

**Comment by MichaelBitsakis** [comment]
Visual result with all bugs fixed and Player position working with full setup including the real infinite floor - Procedural Skybox connection.


[Uploading... Infinitefloor Progress-1.m4v]

**Comment by MichaelBitsakis** [comment]
Found a serious error in the calculations of the previous infinite floor Fog position versus the position of the player. 

In editor : Player 100,100 -> Fog 100,100
in Runtime : Player 100,100 -> Fog 40,40

Tested with several numbers and its exactly the same , we are off by 60 units.

I found the areas that this happen and i am applying a fix as well

**Comment by MichaelBitsakis** [comment]
- Effect for covering the outer edges at the end of the map specification changed .
- Working on new effect foundation .

**Comment by MichaelBitsakis** [comment]
Latest updates pushed to branch 3421-procedural-skybox-ground-gradient-fix
BEWARE branch is on 2020 , if effect is approved then i will need to change the shader to 2021 for Dev.

**Comment by MichaelBitsakis** [comment]
Approved and ready to be merged.

**Comment by m3taphysics** [comment]
@kwspgoliasz @kwssbocian can you validate this does not have an affect on the performance.
