### ISSUE TITLE
spike: investigate loading time increase

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#3422]
Between 28.09 and 30.09 we introduced some changes that increased the initialization time of Unity, the same happened again between 11.10 and 13.10

![image.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/4848ffae-c3d2-4e30-b7e1-4f29fc3b42fa)

https://metabase.decentraland.systems/question/1265-loading-time-unity-download-initialization-daily?days=60

### Acceptance criteria
- [ ]  Task breakdown created
- [ ]  created RFC with proposal and findings

**Comment by eordano** [comment]
This is likely to be the 42mb limitation on resource cache by browsers
