### ISSUE TITLE
Rename Explore section of the Start Menu to "Discover"

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3452]
To avoid confusion between the "Explorer" and the "Explore tab", propose changing the name of the Explore tab to "Discover".

Requirements:
- Rename "Explore" to "Discover" in the start menu. Leave the keyboard shortcut the same (X).
- Update this page in the documentation: https://docs.decentraland.org/player/general/meet-with-friends/

I don't believe there are other locations which refer to Explore.

**Comment by ef3n9r98** [comment]
Hi @olavra, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/
).


Thanks!

**Comment by eordano** [comment]
This should be an easy one: ![image.png](https://images.zenhubusercontent.com/5d8ba4376484360001b6f6df/a981925b-0471-4914-9c35-a399dc326e15)

**Comment by louiseDecentraland** [comment]
Will need to update this page in the docs https://docs.decentraland.org/player/general/meet-with-friends/

**Comment by davidejensen** [comment]
Docs updated in PR https://github.com/decentraland/documentation/pull/143 @louiseDecentraland
