### ISSUE TITLE
Decentraland do not load while the tab is in background

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3454]
In order to load Decentraland, or while you are teleporting, the tab needs to be focus.

**Acceptance Criteria**
- [ ] Decentraland loads while the tab is not selected or in background

**Comment by m3taphysics** [comment]
Run in background is enabled for our WebGL builds but browsers can still throttle the content while it is being sent to the background. Chrome does this for performance reasons, see: https://blog.chromium.org/2020/11/tab-throttling-and-more-performance.html
