### ISSUE TITLE
Link to Marketplace not working

### ISSUE THREAD

**Issue by EmaCivaz** [decentraland/unity-renderer#3468]
### What happened?

With my win PC in Decentraland app

### Steps to reproduce

, if I browse the objects to Collectibles and I try to link the Marketplace link, nothing happend

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

### GPU

NVIDIA GeForce MX150 1983MB

### RAM

16198MB

### Kernel Version

1.0.0-3285052342.commit-225796f

### Unity Version

desktop-1.0.648-20221013174545.commit-75db7ad

### Realm

dg

### NameTag

EmanuelaCvt#3894

**Comment by kwspgoliasz** [comment]
The issue is temporarily blocked by issue [#3469](https://github.com/decentraland/unity-renderer/issues/3469).

**Comment by aixaCode** [comment]
@kwssbocian Is this still an issue with new backpack?

**Comment by kwssbocian** [comment]
Issue no longer reproducible - does not occur for the new version of Backpack.
