### ISSUE TITLE
Issues with the loading spinner for the channel list on guest accounts

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3472]
**Description:**
When opening the channel list as a guest, the loading spinner is constantly spinning on the upper section of the list. For the Windows client, the spinner is also visible, but instead of spinning it is frozen in one spot.
Muting the nearby channel makes the spinner disappear.

**Steps to reproduce:**

1. Load into Decentraland as a guest.
2. Open the channel list.
3. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
The loading spinner is constantly present at the upper part of the channel list.

**Expected results:**
Lack of visual issues for the channels feature.

**Notes:**

- The issue was reproduced on both the production and development configurations.

- The issue occurs only on the guest account.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/ebf60cca-6ec3-4c84-9e62-fe5c3250171a/_3472.mp4.

- Platforms: Web client, Windows client.

**Comment by anicalbano** [comment]
This issue tends to happen in Mac also. I figure it might be a problem with connections
