### ISSUE TITLE
Assign to full table, all the time

### ISSUE THREAD

**Issue by tschmidt82** [decentraland/unity-renderer#3473]
### What happened?

After connecting, always be assigned to full tables

### Steps to reproduce

reconnected three times still the same issue

### Operating System

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

M1

### GPU

ANGLE (Apple, Apple M1, OpenGL 4.1) 512MB

### RAM

8GB

### Kernel Version

1.0.0-3341809574.commit-c511576

### Unity Version

1.0.60046-20221027193715.commit-d817558

### Realm

baldr

### NameTag

TheFrozen#7702

**Comment by xavi-dcl** [comment]
Closing since there is too little information to investigate this issue. It may be specific to a scene, in that case please try reporting it to the scene owner who has access to the scene code and is in better position to debug it.
