### ISSUE TITLE
Add missing data and buttons in player's context menu

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#3477]
### **Description**
Nowadays there are some actions that are not accessible at all, such us seeing and copy other person's address, jump into someone, or send a private message.
This options will be available on the new passport implementation but we must add them in the context menu too in order to enhance accessibility.

![Screenshot 2022-11-25 at 11.20.46.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/fd7f846b-c9b7-4607-aa22-ecdc8eb3a84a)

**Notes**
Have into consideration that this context menu appear when
- Clicking a player's name in a chat channel
- Clicking the menu button in a player's row in the chat list and friends list view
- Clicking the menu button in a private conversation 

### **Requirements**
**Player Address**
- [ ] Add player's address bellow the person name. 
- [ ] Add the copy address button, including mouse hover animation and feedback after effectively having copied the address.
![Screenshot 2022-11-11 at 10.23.06.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/99b02fb8-d60d-4b38-86f7-c084353f6ce0)

**Jump in button**
- [ ] Show the jump in button when the player is online. Include mouse hover animation.

**Message button**
- [ ] Show the message button when the person is a friend. In the future this won't be a restriction anymore. Include mouse hover animation.
As an exception, don't show this button in the context menu inside the private conversation because it is redundant.

**Profile button**
- [x] Replace wording `Passport` for `Profile`

Figma file [here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Social-Improvements?node-id=604%3A14905)

**Comment by davidejensen** [comment]
@RominaMarchetti the jump in functionality works only for friended users, should we show it only for friended users and hide it for others?
