### ISSUE TITLE
Auto-join channels are not getting reported to analytics

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#3482]
The channels marked as auto-join are not getting reported as joined: `player_joins_channel`
We should follow a refactor to be able to identify specific auto-joins: https://github.com/decentraland/unity-renderer/pull/3351#discussion_r1014121739. Right now the system does not trigger any event for it.

**Comment by xavi-dcl** [comment]
@kwspgoliasz could you please QA?
