### ISSUE TITLE
Tech assessment for worlds beta

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#3483]
Create technical assessment for worlds beta scope
PRD: https://www.notion.so/decentraland/PRD-Worlds-Beta-draft-13f159c58c734bca8dbf781c9d22eb89
Roadmap and scope: https://www.notion.so/decentraland/Worlds-Roadmap-bf96c60c3dde474bb2e0b3873427b194

### Acceptance Criteria

- [x] Tasks breakdown
- [x] RFC created in https://rfc.decentraland.org/rfc

**Comment by xavi-dcl** [comment]
https://dc3569f8.adr-cvq.pages.dev/adr/ADR-125
