### ISSUE TITLE
Fix GLTFSceneImporter Animation multithreading 

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3499]
In the MVMF we found out that the GLTF Animation processing while using multithreading was super slow because it was wrongly implemented.

We launched a hotfix using this branch https://github.com/decentraland/unity-renderer/pull/3479

The branch wasn't merged but it was released on Desktop.

## TODO
- [ ] Fix the multithreading on that code so it doesn't open one thread for every single curve, but instead just one for every animation, that should be fast enough and should avoid any hiccup.

**Comment by xavi-dcl** [comment]
We are deleting this old system
