### ISSUE TITLE
[Desktop] Missing Script References

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3517]
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/b079142c-4609-4aa5-b660-0d8d8fc38d9b)

When running Decentraland on Desktop we get 999+ warnings of `UILoadingSpinner` being missing on a certain UI prefab, we have to check why its missing since the Script does exist.

**Comment by xavi-dcl** [comment]
Fixed
