### ISSUE TITLE
Implement SDK7 UI Components

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#3520]
As part of the SDK7 implementation we need to create generic set of UI components described here: 
https://github.com/decentraland/adr/issues/125

The components should be based on the Yoga layout system, documentation can be found here: https://docs.unity3d.com/Manual/UIE-LayoutEngine.html

Acceptance Criteria:
Can render each of the following components from the SDK:
- [x] UiText (it was implemented before)
- [x] UiBackground
  - [x] UVs special processing (float array)
  - [x] Unit Tests
- [x] UiButton
- [x] UiInput
  - [x] Placeholder logic
  - [x] Unit Tests
- [x] UiDropdown
  - [x] Default Selection special case
  - [x] Unit Tests
- [x] Interactivity for UI
  - [x] Compatible events
  - [x] Unique events
  - [x] Unit tests
- [x] Generalization with existing components
- [x] Tidying up
- [x] Integration with SDK (debugging, testing, protocol adjustments)
  - [x] UIInput
  - [x] UIDropdown
  - [x] UIBackground
  - [x] Generic Events

**Comment by xavi-dcl** [comment]
Closing this one as all components were implemented. We will open a new issue if additional work is discovered. @mikhail-dcl @leanmendoza @m3taphysics @menduz

**Comment by menduz** [comment]
Hello @xavi-dcl, we've identified this ones 

decentraland/sdk#549
decentraland/sdk#547
decentraland/sdk#552
decentraland/sdk#551
