### ISSUE TITLE
Opening a list of channel members causes the interface to appear as if on a guest login

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3531]
Description: 
On a wallet login opening a members list of any joined channel causes the interface to start appearing as if it was on a guest login instead. This causes the direct messages section, the channel browser and the profile description section to become unavailable as a result. Issue occurs only for the interface as it still allows to send and receive messages through channels and DMs and appears to have no effect on NFT wearables.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in on a wallet account.   
2. Open up the Chat window from the taskbar and from the Channels section open up any of the joined channels.
3. In the channel window open up the members list then go back to the general Chat window view.
4. Observe the user interface.

Results:    
Interface starts appearing as for a guest login.

Expected results: 
Interface continues to appear as for a wallet login.

Notes:    
- Platforms: Windows, web and desktop, wallet login. 
- Issue occurs for both production and dev branches.
- Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/889e9a96-69a0-4e48-bca1-8f0f8c6c57e0/2022_11_17_13_39_13.mp4

**Comment by m3taphysics** [comment]
@kwspgoliasz  -  to test

**Comment by kwssbocian** [comment]
Issue still fully occurs on production but is partially fixed on dev. 
On dev the chat window no longer appears like for a guest login after showing the channel members list, but the profile window is still broken. The player avatar also continues to disappear. On prod no changes. 
(Video showing the current status on dev)https://images.zenhubusercontent.com/337227404/20beb3f6-ab95-433a-a509-721dcce8fe7c/2022_12_01_15_25_59.mp4

**Comment by m3taphysics** [comment]
Awaiting information from SDK

**Comment by m3taphysics** [comment]
Fixed in: https://github.com/decentraland/kernel/pull/783

**Comment by 0xD-Fabio** [comment]
Changes have been merged from the kernel team.
https://github.com/decentraland/kernel/pull/783
