### ISSUE TITLE
Connect wallet message is being shown when you already connected your wallet

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#3545]
I was logged in with my wallet and my DMs/Friends appeared in the chat window, but it told me that I had to connect my wallet and the pop-up turned up too.

![Screen Shot 2022-11-18 at 16.51.05.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/99b9ef4c-cd7a-41e6-8fc0-473005c2986e)

**Comment by kwssbocian** [comment]
Issue still fully occurs on production and dev. Additionally the player avatar now also disappears and the wearables in backpack all become greyed out.
(Video showing the current status on dev)https://images.zenhubusercontent.com/337227404/20beb3f6-ab95-433a-a509-721dcce8fe7c/2022_12_01_15_25_59.mp4

**Comment by m3taphysics** [comment]
Awaiting information from SDK
