### ISSUE TITLE
Tutorial handling

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#3554]
### Description:
When a player enters a self-contained World, the tutorial is never triggered.

### Acceptance Criteria:

- [x] The tutorial is not triggered when a new user goes into a world
- [x] Tutorial only triggers when you first enter genesis city but not after you have previously entered a world

**Comment by popuz** [comment]
@xavi-dcl, first acceptance criteria is clear: **When** user enters world realm **Then** tutorial is never triggered

But what happens: **When** user enters back from world realm to any non-world realm **Then** ?? What happens with the tutorial - should it be triggered in any realm or only if it is a Genesis Plaza

**Comment by xavi-dcl** [comment]
As @olavra said, we won't trigger the tutorial in that case, the user will already know the basics. We only trigger the tutorial if a new user starts directly in Genesis City.
