### ISSUE TITLE
[Unity 2021] Explore and Backpack tabs appear blank

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3559]
Description: 
In the Unity 2021.3.13f1 feature branch the Explore and Backpack tabs in the menu appear completely blank.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in either on guest or a wallet account.
2. Open up the menu and navigate to the Explore tab and then to the Backpack tab.
4. Observe the user interface.

Results:    
Explore and Backpack tabs appear blank.

Expected results: 
Explore and backpack tab appear showing their contents.

Notes:    
- Platforms: Windows desktop, wallet and guest login. 
- Issue occurs for the Unity 2021.3.13f1 feature branch. [(link)](https://github.com/decentraland/explorer-desktop/pull/351)
- Please see the attached screenshots for reference.
![1.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/b87d8252-2c4f-4039-acb1-d6c71482f627)![2.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/bbe86663-c9af-44b2-bf65-dbb12422fdc6)

**Comment by popuz** [comment]
@kwssbocian, on the daily I heard that all issues with desktop were solved. Do you still encounter this bug there?

**Comment by kwssbocian** [comment]
@popuz In the Unity 2021.3.14f1 Windows desktop build this issue no longer ocurrs. No confirmation yet for the web build though.

**Comment by kwssbocian** [comment]
Issue confirmed to no longer occur for web as well on the dev branch after merging in the upgrade to Unity 2021.
