### ISSUE TITLE
The home coordinates are shared between separate accounts

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3574]
**Description:**
Home coordinates set on one account (wallet or guest) are shared with all of the accounts accessed from the same client.

**Steps to reproduce:**

1. Load into Decentraland as a guest.
2. Move the avatar to a random location outside of Genesis Plaza (ex. by using the /goto random command).
3. Set the location as home. 
4. Log out of the guest account.
5. Log into Decentraland via a wallet.
6. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
The set home locations is shared between all of the accounts accessed from the same client.

**Expected results:**
Individual home coordinates can be set for every account.

**Notes:**

- The issue occurs on both the production and development branches.

- The issue occurs on both the guest and wallet accounts.

- The issue occurs only for accounts launched on the same client, ex. Desktop client, Chrome client, etc.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/91f99487-38e5-41cb-9d93-e570fde567b0/_3574.mp4.

- Platforms: Web client, Windows client.

**Comment by eordano** [comment]
Works as expected
