### ISSUE TITLE
JS heap size limit on MacOS is 2GB instead of 4GB

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3594]
Description: 
On MacOS desktop client the JS heap size in /showfps Control Panel is being shown to have 2GB maximum size despite on other platforms it being 4GB.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in either on guest or a wallet account.   
2. Use the '/showfps' command to open up the Control Panel and navigate to the "Memory JS" section.
3. Observe the value for the JS Heap Size Limit.

Results:    
JS Heap size limit is shown to be 2GB.

Expected results: 
JS Heap size limit is shown to be 4GB.

Notes:    
- Platforms: MacOS desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot for reference.
![Screenshot 2022-11-25 at 13.57.32.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/3272778a-672a-4102-9e58-5747348d6eb4)

**Comment by Kinerius** [comment]
I can't really reproduce this issue, I've tested this with my Macbook Pro 2021 (M1) and got the results:
- WebGL: 4 GB
- Desktop:  4 GB
- Unity Editor: 4 GB

This probably is related to specific hardware and software specs.
