### ISSUE TITLE
Issues with the functionality of the onboarding for new users on the desktop client

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3595]
**Description:**
The welcome screen and the tutorial are not launched for the user after a new avatar is created on the desktop client.

**Steps to reproduce:**

1. Clear Decentraland app's data.
2. Launch Decentraland as a guest.
3. Create an avatar and load into the platform.
4. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
New user gets spawned directly in-world with the welcome screen and the tutorial sections being omitted.

**Expected results:**
The welcome screen and the tutorial are always initiated after a new avatar is created.

**Notes:**

- The issue was reproduced on the guest account.

- The issue doesn't occur on the Web and MacOS clients.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/63199026-7f8b-48ce-857c-2b2a4a0b205c/_3595.mp4.

- Platforms: Windows client.

**Comment by m3taphysics** [comment]
@kwssbocian is this fixed can we close it?

**Comment by m3taphysics** [comment]
This will be obsolete with the new onboarding.
