### ISSUE TITLE
Avoid auto-joining channels you left

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#3620]
Users should not be auto-joined a channel that they manually left.

To solve this problem, we can do a local registering (PlayerPrefs) of the channels you left, so the next time you start the session, we can avoid auto-joining the user on the channel.

**30/11/2022 - This feature can be implemented, but currently auto-joining of any channel is disabled due to memory constraints on the matrix servers**

Acceptance Criteria:
- [ ] After user leaves a channel they are not auto-joined

**Comment by m3taphysics** [comment]
This feature can be implemented, but currently auto-joining of any channel is disabled due to memory constraints on the matrix servers.

**Comment by xavi-dcl** [comment]
Blocked by:
[ ] Moving channels persistence to kernel / user profile
[ ] scalability

We need to plan this with dServices
