### ISSUE TITLE
Trigger teleport without showing the loading screen if destination is loaded

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-renderer#3652]
### Acceptance criteria

- [x] The loading screen should NOT be shown if the teleport destination is to a scene already loaded

**Comment by xavi-dcl** [comment]
@dalkia added "NOT" to the acceptance criteria, I think it was a typo?

**Comment by dalkia** [comment]
> @dalkia added "NOT" to the acceptance criteria, I think it was a typo?

Indeed. Thanks Xavi
