### ISSUE TITLE
[QA] Switching the UI visibility temporarily spawns an obsolete controls panel

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3659]
**Description:**
When switching the UI on, an obsolete controls panel flashes on screen for a short period of time.

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Turn the UI off and on with the 'U' key.
3. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
Controls panel is spawned for a brief moment when turning the UI on.

**Expected results:**
Nothing is spawned on screen when switching the UI.

**Notes:**

- The issue was reproduced on both the guest and wallet accounts.

- The issue was reproduced on both the production and development branches.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/b9ad0c22-725a-4db2-ab1e-9cb68f3d6e95/_3659.mp4.

- Platforms: Web client, Windows client.

**Comment by kwssbocian** [comment]
Issue fixed in [#4047](https://github.com/decentraland/unity-renderer/pull/4047). Closing
