### ISSUE TITLE
Attribute for a path of assets loaded from Resources

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-renderer#3702]
### Problem definition
Currently we have `Resources.Load` all over the place so the paths are hardcoded and it's hard to track them.

### Solution
Introduce an attribute with a string as a path, classes can be annotated with, and a factory that will load an asset by type; it assumes that there is a 1 to 1 match between an asset type and path.

### Acceptance Criteria

- [ ] Introduce an attribute
- [ ] Create a factory that will accept a type and return an instance of a prefab
- [ ] This factory should be static (it makes little sense to make it a service as attributes are static by nature)
- [ ] This factory should cache prefabs by type
- [ ] Replace existing occurencies with the new approach
- [ ] Add a Unit Test that will validate the persistence of the attributed assets
- [ ] Optional: Introduce code generation to fetch all classes marked by the attribute at compile time instead of reflection at runtime

**Comment by aixaCode** [comment]
Closing, out of scope for the time being.
