### ISSUE TITLE
Remove: comment `package decentraland....` in the renderer-protocol generation

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/unity-renderer#3705]
Now the pre-process of protocol generation adds the comment to the lines that set the `package` line in the `.proto` files.
This should work as the SDK-components protocol generation. Where the `package` line is still there, instead of commenting it, is adding the `csharp_namespace`.

The problem is when you're referencing other files with a different level of package. For example:
``` 
// decentraland/level_a/sub_level_a.proto
package decentraland.level_a.sub_level_a;
enum EnumB {
   EB_SOME = 0;
   EB_OTHER_ITEM = 1;
}


// decentraland/level_a.proto
package decentraland.level_a;

import "decentraland/level_a/sub_level_a.proto";

message MessageA {
   sub_level_a.EnumB a_field = 1; // this line FAILS because the package line is being commented
}
```

**Comment by kuruk-mm** [comment]
Fixed at https://github.com/decentraland/unity-renderer/pull/3755
