### ISSUE TITLE
[QA] Issues with the cursor behavior when exiting the controls panel

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3732]
**Description:**
Accessing the control panel with the cursor locked, results in it staying locked after exiting the panel.
The issue becomes more prominent if the user opens the emote wheel or the main menu, while the control panel is displayed. This results in the menus staying opened after exiting the panel, while the cursor remains locked.
The issue does not occur when using the 'Esc' key to exit the control panel.

**Steps to reproduce:**

1. Load into Decentraland as a guest or via a wallet.
2. Lock the cursor.
3. Access the control panel (C).
4. Open the emote wheel (B) or main menu (ex. P).
5. Exit the control panel by using any method other than the 'Esc' key.
6. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
The cursor stays locked after exiting the controls panel, if it was initially locked when the panel was opened.

**Expected results:**
Exiting the controls panel leaves the cursor unlocked at all times. Alternatively, the affected menus cannot be accessed while the control panel is opened.

**Notes:**

- The issue can be reproduced on both the guest and wallet accounts.

- The issue can be reproduced on both the production and development branches.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/a7dad9a3-a151-41ac-8d95-c7b95273653c/_3732.mp4.

- Platforms: Web client, Windows client.

**Comment by anicalbano** [comment]
Unable to repro:
https://images.zenhubusercontent.com/337227404/e17368b7-11b9-46eb-911a-1b0af3202504/21_07_2023_13_38_53_rec.mp4
