### ISSUE TITLE
GameObject.SetActive is called while the object is destroyed

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-renderer#3735]
It corresponds to this log https://drive.google.com/file/d/1CRapRZOkHEBrvVQFP7vRps-USDFcifGK/view?usp=share_link

According to the stack trace:
```
	  at <unknown> <0xffffffff>
	  at UnityEngine.GameObject:SetActive <0x0009b>
	  at ImageComponentView:SetLoadingIndicatorVisible <0x0005a>
	  at ImageComponentView:SetImage <0x00092>
	  at ProfileCardComponentView:SetProfilePicture <0x00079>
	  at ExploreV2MenuComponentController:UpdateProfileInfo <0x00107>
	  at System.Action`1:invoke_void_T <0x000cc>
	  at UserProfile:SetAvatarExpression <0x0018a>
	  at RPC.Services.EmotesRendererServiceImpl:TriggerSelfUserExpression <0x00042>
	  at <<RegisterService>b__0>d:MoveNext <0x00152>
	  at <>c__DisplayClass1_0`1:<RegisterService>b__0 <0x00142>
	  at rpc_csharp.UnaryCallback`1:invoke_UniTask`1<ByteString>_ByteString_TContext_CancellationToken <0x000ce>
	  at <TryCallUnaryProcedure>d__23:MoveNext <0x00233>
	  at rpc_csharp.RpcServerPort`1:TryCallUnaryProcedure <0x0015a>
	  at <HandleRequest>d__8:MoveNext <0x002c2>
	  at rpc_csharp.RpcServer`1:HandleRequest <0x00192>
	  at <<AttachTransport>b__0>d:MoveNext <0x003f2>
	  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start <0x000e2>
	  at <>c__DisplayClass10_0:<AttachTransport>b__0 <0x0011a>
	  at System.Action`1:invoke_void_T <0x00121>
	  at rpc_csharp.MessageDispatcher:<.ctor>b__7_2 <0x001c3>
	  at RPC.Transports.WebSocketTransport:OnMessage <0x0002d>
```

It probably happens when:
- Application receives a signal to exit or an object to destroy
- At the same frame but in a different moment of Game Loop Kernel invokes a RPC

Moreover, the call refers to
```
public void SetLoadingIndicatorVisible(bool isVisible)
    {
        image.enabled = !isVisible;
        loadingIndicator.SetActive(isVisible);
    }
```

Can be connected to: [#3665](https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/3665) because the faulty object refers to the object without the script

Or can be a non-checked version of:
`GameObjects can not be made active when they are being destroyed`
the latter is possible to check in Editor

**Proposal:**

1. Wait for [#3656](https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/3656)
2. If it still crashes try the following:
   1. Stop processing messages if Application Exit is called
   2. Introduce a check for nullity
   3. Introduce a barrier that will be fired on Application.Exit and make calls to `GameObject.SetActive` through it.

**Comment by m3taphysics** [comment]
Verify when release is out

**Comment by m3taphysics** [comment]
The fix is now on production - verify if this is happening or not on release

**Comment by kwssbocian** [comment]
Cannot reproduce the issue - walking around in the world to have various different scenes load then unload and then exiting the client did not cause `GameObject:SetActive` to appear anywhere in the Player.log file.
