### ISSUE TITLE
Enable A/B testing of GLTFast & Gather performance metrics

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#3753]
With the current implementation we can't split the targeting of the feature flag to only be available on desktop.
The test should only run on desktop, and we need to have support for variants in the code to use continuous performance A/B test.

Acceptance criteria
- [ ] Test running on desktop only

**Comment by aixaCode** [comment]
I have created the flag here https://features.decentraland.systems/#/features/strategies/explorer-gltfast

**Comment by xavi-dcl** [comment]
@Kinerius is this not done already?

**Comment by Kinerius** [comment]
Yes it is :)
