### ISSUE TITLE
Support in launcher for realm parameter

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#3760]
With worlds having requirements for friendly URLs, we need to add support for the launcher to properly process the URL.
Currently, we have created the redirects in CloudFlare, to map URLs to this format.
https://play.decentraland.org/world/paralax  -> https://play.decentraland.org/?realm=paralax.dcl.eth
https://play.decentraland.org/world/paralax.dcl.eth -> https://play.decentraland.org/?realm=paralax.dcl.eth 

Acceptance criteria
- [ ] launcher is able to recognize URLs with realm param and load properly worlds

**Comment by dalkia** [comment]
No task needs to be done here. 

As discussed in this [thread](https://decentralandteam.slack.com/archives/C0417M33E2J/p1671116520237239), the artifacts url we are going to use to start in a world has the form of `dcl://?realm=menduz.dcl.eth` which already works with the launcer. We are not implementing urls with form `dcl://?world/menduz.dcl.eth`

On the other hand, if the user opens the app without the renderer's artifact url, it has been agreed that there will be now way to start directly on a world. 

We can analyze to add an input field in the launcher, but for now this is just an idea.
