### ISSUE TITLE
[QA] Taskbar icons are not interactable with the emote wheel open

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3773]
Description: 
On the 14/12/2022 release branch having the emote wheel open causes the other taskbar buttons to not be immediately interactable. Clicking anywhere away from the emote wheel causes it to close after which the other menus can be opened.

Reproduction rate: 
5/5

Steps to reproduce:    
1. Log in either on guest or a wallet account.   
2. Open up the Emote wheel using the B key or via the taskbar icon.
3. With the emote wheel open click on any of the other taskbar icons.
4. Notice the emote wheel close and the other menu not opening.
5. Click any other taskbar icon again.
6. Observe the user interface.

Results:    
Other menus do not open up right away after clicking on them while the emote wheel is open.

Expected results: 
Other menus open up right away after clicking on them even while the emote wheel is still open.

Notes:    
- Platforms: Windows and MacOS, web and desktop, wallet and guest login. 
- Issue occurs for the 14/12/2022 release branch.

**Comment by anicalbano** [comment]
Could not reproduce.
