### ISSUE TITLE
spike: task breakdown of desktop repository merge

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#3787]
**Description**
We need a breakdown of tasks for the desktop merge, an initial investigation can be read here:  [https://www.notion.so/decentraland/Merge-Desktop-Breakdown-d48413341e2341cabd1283f7e4822035](url)

**Deliverables**
- [ ] Breakdown of tasks
- [ ] Assign each to the desktop breakdown epic

**Comment by AjimenezDCL** [comment]
I created a ticket with the breakdown #4066, IMO it's difficult to split it into deliverables and should be worked on the same branch/ticket.
