### ISSUE TITLE
spike: run a performance profile session

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#3791]
**Description**
In order to attack rendering performance we need to have a profiling session across various parts of the application to see where we can get the biggest improvements.

**Deliverables**
- [ ] Run a profile session and observe any specific bottlenecks
- [ ] WebGL 
- [ ] Desktop
- [ ] Create an RFC with a breakdown of the issues found
- [ ] Create list of performance tasks prioritised by the biggest gains first

**Note**: some tasks may require larger technical implementations to overcome, these should be documented in the RFC for further breakdowns so they can be scheduled within a future roadmap.

**Comment by eordano** [comment]
Particularly look at investigating decrease in FPS / increase in heap usage since release 2023.01.11

**Comment by Kinerius** [comment]
Progress is being written here:
https://www.notion.so/decentraland/Performance-Profiling-2023-1-16-f6ad6b9ef07647298e78d4610efd5c1e

**Comment by Kinerius** [comment]
Created https://github.com/decentraland/unity-renderer/issues/4034

**Comment by Kinerius** [comment]
Created https://github.com/decentraland/unity-renderer/issues/4036

**Comment by Kinerius** [comment]
Created https://github.com/decentraland/unity-renderer/issues/4045
