### ISSUE TITLE
spike: run a memory profiling session

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#3793]
Description
In order to attack memory issues we need to have a profiling session across various parts of the application to see where we can get the biggest improvements.

Deliverables

- [ ] Run a profile session and observe any specific areas of larger allocations
- [ ] Run a profile session and observe any specific areas of memory leaks
- [ ] Create an RFC with a breakdown of the issues found
- [ ] Breakdown of memory improvement tasks

Note: some tasks may require larger technical implementations to overcome, these should be documented in the RFC for further breakdowns so they can be scheduled within a future roadmap.

**Comment by xavi-dcl** [comment]
@m3taphysics kind of duplicate/overlapping with #3068, which we actually added to Next Sprint.

Do you want to keep them separate or merge into #3068? Let's ensure we do what makes most sense on next sprint.

**Comment by m3taphysics** [comment]
Happy to keep one, delete the other!
