### ISSUE TITLE
Don't load "map.png" images after minimap/estatemap is implemented

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#3801]
Currently, the explorer is loading all these assets:

![image](https://user-images.githubusercontent.com/42750/208653651-6f479694-591b-4dc9-ab38-a85950379d3f.png)

They should be replaced with the new minimap shader renderer. Make sure we are not downloading these map.png files anymore once https://github.com/decentraland/unity-renderer/issues/3666 is fully implemented.

**Comment by m3taphysics** [comment]
We need shader efforts for this one :(

**Comment by aixaCode** [comment]
We are tracking the issue here #4950
