### ISSUE TITLE
[QA] Scrolling through resolution dropdown on desktop is extremely slow

### ISSUE THREAD

**Issue by kwspgoliasz** [decentraland/unity-renderer#3803]
**Description:**
Using the mouse wheelie to scroll through the resolution list feels very slow and heavy.

**Steps to reproduce:**
1. Load into Decentraland as a guest or via a wallet.
2. Open the Settings menu (P).
3. Go to Graphics section.
4. Open the resolution list.
5. Scroll the list with the mouse wheelie.
6. Observe the issue.

**Reproduction rate:**
5/5

**Results:**
Scrolling through the resolution list feels extremely slow.

**Expected results:**
Scrolling the resolution list with the mouse wheelie is functioning smoothly.

**Notes:**

- The issue can be reproduced on both the guest and wallet accounts.

- The issue was reproduced only for the resolution setting. Scrolling with mouse wheelie is working correctly for all of the other menu sections and UI elements.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/3bb4f30b-7b46-457c-a53b-7882d13d7fcf/_3803.mp4.

- Platform: Windows client.

**Comment by kwssbocian** [comment]
Issue no longer occurs - fixed in [#4402](https://github.com/decentraland/unity-renderer/pull/4402)
