### ISSUE TITLE
Fix "Metamask is Locked"

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#3812]
After unlocking metamask, the explorer doesn't load and the "Retry" button is not working.

![image](https://user-images.githubusercontent.com/42750/208860031-15774b03-adeb-407d-b0a9-b9a37c544cea.png)

Steps to reproduce:
* Close all browser windows or lock Metamask
* Open play.decentraland.org
* Click on "Continue With Wallet"
* Click on "Metamask"
* Unlock Metamask
* Click Retry

Expected behavior: the loading of the explorer continues
Actual behavior: the user needs to reload the screen

OS: Linux and Chromium; Can't reproduce on Mac and Chrome.

**Comment by Walletsuppport** [comment]
@eordano We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by m3taphysics** [comment]
@2fd I think this is just purely that the refresh button doesn't do anything.
