### ISSUE TITLE
Visibility issues since some days ago

### ISSUE THREAD

**Issue by pabloes** [decentraland/unity-renderer#3819]
### What happened?

Some gltf models suddenly disappear in different cases.

### Steps to reproduce

One case is, after modifying the position of an entity, the shape can become hidden, and when we rotate the entity, it suddenly appear again, see example here: https://www.youtube.com/watch?v=dSRqDn2JXxM&t=59s

Other case is that, when spawning children entities, rotation was not applied correctly, that could make some entities be out of scene, we workarounded with something like following, that. is removing from scene and adding again with timeouts:
```
    setTimeout(()=>{//TODO REVIEW: this is a workaround to avoid wrong rotation/position bug introduced by decentraland, search other comments like this one
        hide();
    },100)

    setTimeout(()=>{//TODO REVIEW: this is a workaround to avoid wrong rotation/position bug introduced by decentraland, search other comments like this one
        show();
    },200)
```

And other case we have at Golfcraft , which is really annoying for users and harmful for the project and that was not happening some time ago, is that the ball is not appearing at random situations, when is not appearing, it won't appear for a while, no matter if the ball is removed from scene and added again.
![image](https://user-images.githubusercontent.com/2302722/206484169-a17ef2b0-2ec6-47da-83d3-dd2229b9377c.png)

### Operating System

MacOS Monterey 12.2.1

### Wallet

Metamask

### CPU

M1 pro

### GPU

M1 pro

### RAM

16GB

### Kernel Version

2.0.0-3640389337

### Unity Version

latest

### Realm

baldr

### NameTag

pablo.dcl.eth

**Comment by xavi-dcl** [comment]
To validate after releasing new culling controller

**Comment by pabloes** [comment]
> To validate after releasing new culling controller

thx, we can check once done.
Some issues were also related with rotations.
if you need anything don't hesitate to contact via discord pabloest#8208

**Comment by kwssbocian** [comment]
@pabloes Hi, since this issue was reported there have been multiple updates to the client. Could you please check if it still occurs for you? Thank you!

**Comment by pabloes** [comment]
I think the rotation issues seem solved, but still users report the ball to be hidden sometimes.

**Comment by EibrielInv** [comment]
Update on the second part of the issue "_when spawning children entities, rotation was not applied correctly_". Adding some images to illustrate the issue.

![imagen](https://github.com/decentraland/unity-renderer/assets/172656/37292db5-ca83-4740-9fc1-65850c647e91)

![imagen](https://github.com/decentraland/unity-renderer/assets/172656/54eaae7f-be9e-4701-b0c4-0eb2540dcccf)

**Comment by EibrielInv** [comment]
Hi! We added a debug game mode that allows to load several maps in a short amount of time.

How to use it:

- Go to https://play.decentraland.org/?position=48%2C-43 
- Press `1` to start a game
- Press `2` to end a game

I created a list of different maps, the debug game mode will load the next map in the list every time you press `1`

Video reference: https://www.youtube.com/watch?v=uJeXHdRSXHM

Let us know if you have some feedback on the debug mode.

**Comment by Juliendcl** [comment]
Adding Player logs

[GolfCraft_BuildingMissing.log](https://github.com/decentraland/unity-renderer/files/12172390/GolfCraft_BuildingMissing.log)
[GolfCraft_PlayingAGame.log](https://github.com/decentraland/unity-renderer/files/12172392/GolfCraft_PlayingAGame.log)
