### ISSUE TITLE
BiW Editor clicking on an entity of the collection hides the collection menu

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#382]
While creating new entities using the Collections menu, it usually happens that entities get created behind the panel. To avoid this, the panel will be hidden as soon as the player clicks on an entity.

This won't be the behaviour while dragging and dropping.

Make 2 tests:
- [ ] One hiding the panel
- [ ] One making the panel opacity something like 0.2

**Comment by sandrade-dcl** [comment]
No BiW scene seems to be loading since Nico Chamo commited [cb9f1ff38](https://github.com/decentraland/explorer/commit/cb9f1ff384f60054160ce65b2aee0c08db6a2d17) in the `explorer` repo. He has been informed and meanwhile this task keeps awaiting for his fix.
