### ISSUE TITLE
Implement renderer protocol for RequestWearables flow

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-renderer#3820]
### Description

We should implement the [new renderer protocol](https://github.com/decentraland/unity-renderer/blob/dev/docs/how-to-renderer-protocol.md) into the Wearable retrieve flow. Having the ability to use protobuf and streams will allow us to stop using the long json string, which produced a crash for users with many wearables.

We need to have a retro-compatible solution with the current web interface flow. A good reference is the new friend request flow, which uses a proxy bridge and a feature flag to decide which flow is used in that request

This is not a replacement for pagination, since it may still be needed and it could coexist with this flow

### Acceptance criteria:
- [ ] Wearables are retrieved using streams and RPC calls
- [ ] WebInterface flow is functional 
- [ ] We can chose which flow to use through a feature falg

**Comment by mikhail-dcl** [comment]
Closed because Renderer will be consuming Lambdas directly and no middleware is needed anymore
