### ISSUE TITLE
"Esc" is not closing the Chat Dialogue

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#3840]
When on #nearby (or any other public channel, or private conversation), the Esc key is not closing the dialogue as expected by the "C" in-game quick help.

![image](https://user-images.githubusercontent.com/42750/209667464-025d8551-cf04-48ad-b397-c63ba1abe5f1.png)

![image](https://user-images.githubusercontent.com/42750/209667360-f838035e-736b-42b0-8eb4-17cd1d18406c.png)

**Comment by eordano** [comment]
This only happens on the Passport refinement branch

**Comment by lorux0** [comment]
Looks like it happens on prod aswell. Only on builds, not in unity editor

**Comment by anicalbano** [comment]
https://images.zenhubusercontent.com/337227404/15825dea-689c-47f7-9e90-95184e16ce84/21_07_2023_13_02_50_rec.mp4
