### ISSUE TITLE
Lazy-load built-in emotes as Addressables instead of using an in-build asset

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#3878]
robot.anim, clap.anim, kiss.anim, and others can be lazyloaded and taken out of the core bundle. That should save about 30Mb (after decompression) from the initial download.

- [ ] Only load idle, walk, run (x2: Female and Male bodytypes)
- [ ] Create one AB per each platform with the rest of the emotes
- [ ] Warm-load them after the world has been loaded and rendered

**Comment by Kinerius** [comment]
We need to define how and where we upload those AB's.

Then we also need to define how we download them, do we request a hash map from an endpoint? do we embed the hashes directly in the code?

**Comment by eordano** [comment]
@agusaldasoro could you provide information on how are we uploading `base-wearables` to cataysts? These emotes should be hosted in catalysts

**Comment by agusaldasoro** [comment]
@eordano Currently, the base wearables are deployed using the scripts in https://github.com/decentraland/avatar-assets that upload the files included there. That flow is used also for old L1 wearables too. Also, the base emotes are now hardcoded in the client while the emotes deployed in the catalysts are the L2.
