### ISSUE TITLE
BiW editor random lands pop up around the edited scene

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#389]
Steps to reproduce:
None
![image](https://user-images.githubusercontent.com/41490935/117290095-aeaa5980-ae6d-11eb-9c81-beb555fb3dcc.png)

Suggestions:
Maybe the player is moving while pressing AWSD in camera mode

**Comment by sandrade-dcl** [comment]
I have not been able to reproduce this bug, but I have added a "security" fix ([commit](https://github.com/decentraland/unity-renderer/pull/430/commits/f90b8b331b3f96e67b5a04ad050a83686ed430c1)) for avoid to move the player during the Builder In World edition.

**Comment by olavra** [comment]
This is still happening
![image](https://user-images.githubusercontent.com/41490935/123625269-e3a0b000-d80f-11eb-9fca-ca9a8f64ee07.png)

**Comment by Suduck** [comment]
I will add some info for the issue:

Tenenmos un bug en el builder in world en el que a veces carga una tierra lejana extra que no tiene nada que ver con la que estamos editando, he conseguido reproducirlo y me he fijado que es un problema con el pool manager, he mirado un poco el codigo del pool manager y se asegura de que el objeto este desactivado pero por alguna razon queda activado ( algo lo esta activando una vez que esta en el pool manager imagino).

Me he fijado que esto ya aparece nada mas inicias unity aunque todavia no se ha cargado el mundo, ya esta precargado y activo.
No es del prewarm porque ya tiene nombre, tiene pinta de que tiene que no es problema del pool manager, sino de algun sistema que cree las empty parcel, sabeis donde se manejan las empty parcel?

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/c313dbf6-1600-4272-a3e7-06306d040020)

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/b57c84fd-bfa9-406f-9855-195d50d8f829)

**Comment by Suduck** [comment]
This is not just the lands but also some objects as stated in this screenshot, the log is there but it shouldn't be visible

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/bb46160e-65f3-4f70-85ad-f380b4fd7962)

**Comment by Suduck** [comment]
Also is curious how another item in the same pool have the collider while the previous doesn't have it

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/cb3735f0-68cc-499a-9d55-b589ec393c20)
