### ISSUE TITLE
Investigate objects leaking between scene loadings

### ISSUE THREAD

**Issue by 0xD-Fabio** [decentraland/unity-renderer#3899]
Analyzing memory allocation with the memory profiler, there are different objects which are not being disposed.
To reproduce and observe this behavior, you should:

1. Load Genesis Plaza on an empty instance. Wait a bit and take a Memory Snapshot.

2. Teleport to a random empty parcel

3. Teleport back to Genesis Plaza. Wait a bit and take another Memory Snapshot.

**Between teleports and Snapshot do not click on the taken snapshot**, or anything else, just teleport using goto.
Otherwise the second Snapshot will have in memory the first opened Snapshot.

4. Once the 2 snapshots are done, compare them, and group them on the "Diff" column.

5. Investigate the followings in the "New in B" group

- [ ] Investigate about TMPro objects not being disposed

- [ ] Investigate about String objects not being disposed

- [ ] Investigate about Meshes not being disposed

- [ ] Investigate about remaining leaking objects not being disposed

- [ ] Make new memory snapshots to check if the memory leak has been reduced

![Leak TMP.png](https://images.zenhubusercontent.com/633adb3e5510f3d8ef8164d7/98bac5d7-1d23-48d9-9d5c-760f942818cf)

**Comment by m3taphysics** [comment]
@0xD-Fabio did some investigations originally so please contact him if you want further insight from the initial investigation.
