### ISSUE TITLE
Activate "Loading The Latest Version" while Unity is being downloaded, not as the last step of the wallet login

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#3902]
Right now, when Unity is still getting loaded, the wallet shows a spinner:

![image](https://user-images.githubusercontent.com/42750/210637587-24c1396e-e87e-4411-bdcc-c76bf0839432.png)

But, we immediately shift to this other loading screen:

![image](https://user-images.githubusercontent.com/42750/210637715-7b95c2a3-6223-43fc-834a-9a4619686425.png)

This issue is even worse when the user first logs in with their wallet, and we're currently spending ~20s here (where the user is  prompted to cancel their login!!!)

![image](https://user-images.githubusercontent.com/42750/210637967-2bcc84bd-72b3-431f-8566-b28c4f67ef54.png)

**Comment by eordano** [comment]
User feedback: ![image.png](https://images.zenhubusercontent.com/5d8ba4376484360001b6f6df/5162ef57-3bd3-496d-9a29-0ae6dd522d67)

**Comment by kuruk-mm** [comment]
https://github.dev/decentraland/explorer-website/blob/8bf1e9bc766d6fadc91ecf5ca23edf2e429aa2c8/src/state/reducers.ts#L147-L153

Here is the data of the progress of the downloading. We should connect that to the UI.
