### ISSUE TITLE
Debug cat headwear wearable loading problem

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#391]
We should identify the cat headwear wearable and debug its AB conversion (and/or GLTF loading) from the editor.

![E0qZcckVgAAzAEN.jpeg](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/24a7ad58-c53c-499d-a7ef-c7086b0c61ae)

![E0qbPuZXoAIyazp.jpeg](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/12bef110-c3cf-4990-86bb-8dc80c66694e)

seen at https://twitter.com/juxton/status/1390092282116800512

**Comment by olavra** [comment]
This is fixed with the ticket #1209
