### ISSUE TITLE
[Friendship management] Create a feature flag to enable/disable friendship changes

### ISSUE THREAD

**Issue by moliva** [decentraland/unity-renderer#3914]
As part of the release of the new Social Service, a migration is due requiring a window of time where the service won't be able to process changes in the friendships (creating new requests, deleting, canceling or responding to existing ones). During this window the optimal solution is to disable this from the UI and advise players about the current situation.

@olavra to finalize design & tasks
- [x] hide the friends taskbar button
- [x] hide the options in the user contextual menu
- [x] hide the friendship options in the passport

**Comment by lorux0** [comment]
the feature flag name is: `explorer-friends_enabled`
