### ISSUE TITLE
Crash at DG scene

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#3926]
Reported via Slack: https://decentralandteam.slack.com/archives/CS8SCNYUV/p1668625576204919

This is 2 months old, it's blocking a content developer every day, and we should investigate and fix or give an answer.

Adding key details here:

"It crashes the scene when I load in at random. Sometimes within 5 minutes, other times it takes 20 minutes. But it always happens. "
"This didn't occur until the last update to decentaland-ecs. I really need help to prevent this from happening because I'm unable to test anything with this crashing always."

Web Client (Chrome v107.0.5304.87 on Linux)
![crashDG.jpg](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/95a63dfb-99f0-4d15-986e-25855f5552a9)

Repro steps (not 100%):
- Opening two tabs in different browser profiles using different wallets, in the same scene.
- Continue using chrome on a different tab on either browser profile
- After some unspecified amount of time (could be 1 minute, could be 10 minutes or more), both of the browser profiles will Flash light blue for a split second, then it will show the error Critical error: The rendering engine failed
At the same time, several hundred new browser warnings appear
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/387da16e-3697-4266-b87c-8baad6cd6d18)

VIDEO: https://decentralgames.slack.com/files/U01SHM0QREV/F04DDQ2TFD5/simplescreenrecorder-2022-12-05_12.51.50.mkv

**Comment by aixaCode** [comment]
Closing as duplicate
