### ISSUE TITLE
Wearable textures inconsistent between test and live

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#3927]
Wearables that have textures the dimensions of which are not a power-of-two do not show consistently in test and live.

This causes wearables getting approved by the curator's committee and then looking broken in-world.

This issue surfaced on this Slack thread:  https://decentralandteam.slack.com/archives/C022VUR8LCX/p1672756853803789

The thread also mentions another issue arising when UV islands go outside UV square or they are too big, this will be reported separately.

**Comment by eordano** [comment]
I think this can be another issue where asset bundle conversion gets in the way. What other reasons could explain why "test" works different from "live"?

**Comment by Kinerius** [comment]
The issue was fixed by the wearable owner since there was an issue with the texture.

Anyways it seems to be an issue with our gltf importer itself (the old one) I might need an example of the gltf to analyze the source of the issue.

**Comment by eordano** [comment]
Let's drop it for now, thank you
