### ISSUE TITLE
[spike] Potential issue with wearable UVs

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#3928]
There is a potential issue with wearables when UV islands goes outside UV square or they are too big. It seems to be affecting wearable content creators and curators.

Issue was reported on Slack, see this thread for details: 
https://decentralandteam.slack.com/archives/C022VUR8LCX/p1672857993933109?thread_ts=1672756853.803789&cid=C022VUR8LCX

**Comment by xavi-dcl** [comment]
There is a potential issue with wearables when UV islands goes outside UV square or they are too big

**Comment by anicalbano** [comment]
No more reports found.
