### ISSUE TITLE
Outline shader highlights invisible avatars

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#3933]
Invisible avatars should never get the mouse over outline shader.

![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/a49e6c7f-1c28-4b92-84a8-b4d5dc6de8c0)

Test link: https://play.decentraland.zone/?renderer-branch=feat/passport-names-lands-integration&kernel-branch=feat/add-friend-status-message&ENABLE_AVATAR_OUTLINER

**Comment by Kinerius** [comment]
I've found an avatar at the same place that was hidden and I could highlight him, the thing is, the bug is that the avatar itself was not visible for some reason, it being highlighteable is ok. 
I think we always had this bug but with this it's being noticeable.

**Comment by Kinerius** [comment]
If you reload the client you should be able to see that avatar

**Comment by Kinerius** [comment]
I'm re-opening this since the fix I made was rolled-back due to NFT emotes not working, we have to test this further and analyze the change to find the root cause.

**Comment by AjimenezDCL** [comment]
That image shows a loaded avatar that has not been revealed; the issue must be in the revealing process.
