### ISSUE TITLE
GLTFast shaders Feature Flag

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#3937]
In order to get GLTFast working properly we need to use their shaders since they are more advanced than ours.

### Acceptance criteria:
- [ ] implement the feature flag
- [ ] check that all materials are using gltfast shaders
- [ ] check that there are no visual differences with the feature flag off unless some of those models contain some sort of vertex color that they weren't being rendered before. 

This feature should affect non-ab meshes for WebGL and everything on Desktop.

**Comment by aixaCode** [comment]
Closing, out of scope for the time being.

**Comment by aixaCode** [comment]
Closing, out of scope for the time being.
