### ISSUE TITLE
Play an special sound when receiving a Friend Request

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3952]
The notification of a friend request should be pretty important and needs to have its special sound, when received, or accepted.

**Acceptance Criteria**
- [ ] New sound is played when I receive a notification of Friend Request, or my friends requests are accepted. 

Sound File:
https://drive.google.com/file/d/1xeiuMG8AQwn8W4VCHDdku8Jx8Tdef6Gn/view?usp=share_link

**Comment by RominaMarchetti** [comment]
The request has been sent to Mordi.
