### ISSUE TITLE
Enable #channels links for everyone

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3953]
Channels links were disabled as we didn't enabled channel creation for everybody, and clicking on a #channel link that didnt exist, automatically created it,  but this is really preventing channel usage. Lets do a workaround.

**Acceptance Criteria**
- [x] Enable #channels patterns links that allow access to a channel.
- [x] Clicking on a #channel link will first verify if the channel exists
- [x] If the channel does not exist, a prompt will appear with the following text: "The channel you are trying to access do not exist"
- [x] If the channel exists, It will prompt the currently implemented dialog to Join

**Comment by xavi-dcl** [comment]
Please take into account kernel side for the estimation

**Comment by lorux0** [comment]
@olavra @RominaMarchetti in case there is an error with the channel operation, i've added a toast saying:

> There was a problem trying to process the channel, try again later

Is that ok?

**Comment by RominaMarchetti** [comment]
@lorux0 I suggest to use the same generic toast message for this type of errors. The sentense is close :P `There was an error while trying to process your request. Please try again.`

<img width="463" alt="Screenshot 2023-02-01 at 10 08 10" src="https://user-images.githubusercontent.com/51088292/216051917-a61a33ab-b65c-4663-af62-dc24e015f355.png">
