### ISSUE TITLE
Play the selected emote on the avatar of an open passport

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3958]
In order to see all the emotes that a player have, is not enough just clicking on them. It should play it on its avatar.

**Acceptance Criteria**
- [ ] Clicking on an emote in the collectibles section of an avatar passport will play it in the avatar renderer.
- [ ] If the emote is not loaded, it will show a spinner on top of the avatar while it is downloaded and unpacked.

**Comment by olavra** [comment]
Consider the emotes need to be loaded in real time when clicked, and unloaded whenever other emote is selected, so it doesnt take spaces in memory.

**Comment by aixaCode** [comment]
Closing, not part of the scope
