### ISSUE TITLE
Address technical debt introduced in friend request feature

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#3960]
TDB After meeting with leads

**Comment by mikhail-dcl** [comment]
- `Rpc Client` does not support Cancellation
  - Modify the package itself
  - Or introduce Cancellation on a higher level
- `IFriendAPIBridge` related API:
 ```
UniTask<AcceptFriendshipPayload> AcceptFriendshipAsync(string friendRequestId);
UniTask<FriendshipStatus> GetFriendshipStatus(string userId);
UniTask<RequestFriendshipConfirmationPayload> RequestFriendshipAsync(string userId, string messageBody);
UniTask<AddFriendRequestsV2Payload> GetFriendRequestsAsync(int sentLimit, int sentSkip, int receivedLimit, int receivedSkip);
UniTask<RejectFriendshipPayload> RejectFriendshipAsync(string friendRequestId);
UniTask<CancelFriendshipConfirmationPayload> CancelRequestAsync(string friendRequestId);
```
- Review consumers in `FriendsController`: Cancellation should be supported here as it is directly consumed by `HUD Controllers`
- Review `await UniTask.SwitchToMainThread();`: try put it in a single place; currently, it's scattered around. There is no reason to return `HUDController` in a background thread so it can be encapsulated in the `Requests Controller`
- `SendFriendRequestHUDController`:
  - Unify timeout: we should have something like a system and not a timeout defined per `HUD Controller`
  - `hideCancellationToken` should be unified for every `HUDController`: the logic everywhere is similar:
    - `Cancel` if `View` is closed
    - `Cancel` on `Dispose`
    - `Cancel` the previous flow correctly if new input data is set
  - Thus, consider introducing an abstraction for such controllers
  - Make sure every such `Controller`-`View` follows this principle: e.g. `SendFriendRequestHUDController` does not `Cancel` on `Dispose`
  - Use generic `BaseComponentView` for `model`, make `model` a record
  - Looks strange. The code is unreachable as `OperationCancelledException` is thrown before and there is no suppression. 
```
if (!hideCancellationToken.IsCancellationRequested)
                    view.Close();

```
- `FriendsHUDController` - right the same concerns
- `ReceivedFriendRequestHUDController` - right the same concerns, no cancellation tokens at all
- Decide on which API is provided by `HUDController`: either `async` and then return `UniTaskVoid`/`UniTask` or `sync` and then `UniTaskVoid` method should be launched and `Forgotten` inside the class itself. Avoid having a mix of both worlds.
- Think of handling analytics in the `FriendsController` itself, not in the `HUDController`: the logic looks generic and some boiler-plate can be avoided
E.g.:
You repeat
```
socialAnalytics.SendFriendRequestError(request?.From, request?.To,
                        "modal",
                        e is FriendshipException fe
                            ? fe.ErrorCode.ToString()
                            : FriendRequestErrorCodes.Unknown.ToString());
```
in `PassportPlayerInfoComponentController` and `ReceivedFriendRequestHUDController`
- Review Timeout everywhere, it's set to `10`, somewhere as a `magic constant`. Just move it to the `FriendsController`. Also try to align with other requests: why `10`?

**Comment by lorux0** [comment]
Regarding to this point:

> Review await UniTask.SwitchToMainThread();: try put it in a single place; currently, it's scattered around. There is no reason to return HUDController in a background thread so it can be encapsulated in the Requests Controller

I've moved the main thread switch to `RPCFriendsApiBridge` since its the only place where goes to a worker thread. Seems an overhead to me to create a controller exclusively for this.
