### ISSUE TITLE
Unfriending /blockin should have a confirmation dialog

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3964]
Unfriending / blocking does not confirm the action with the player. All no revertible actions should have this kind of confirmation.

**Acceptance Criteria**
- [ ] When Unfriending, a confirmation dialog will appear with the following text: 
"This player and you will no longer be friends, you will no longer be able to send each other private messages. Are you sure you want to break this friendship?"
- [ ] This needs to be extended to the BLOCK functionality with a different message:
"Are you sure you want to block this player? Blocking will prevent you from seeing their chat messages in public or private conversations"

**Comment by RominaMarchetti** [comment]
Block prompt [here](https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Profile-Card?node-id=1960%3A17134&t=HWyANJwmwMGgNEFN-1)

Unfriend prompt [here](https://www.figma.com/file/iPUCfxQLHKXbLYqPlHZcg2/Profile-Card?node-id=1990%3A14055&t=HWyANJwmwMGgNEFN-1)
