### ISSUE TITLE
Spike: Investigate if we can connect unity profiler to WebGL

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#3968]
**Description**

Previously we have not been able to connect our profiler to WebGL to observe if there are any obvious optimizations to be made. We may now be able to connect since we have upgraded Unity to 2021. We need to verify this and also document how it is done. 

If it cannot be done we can create a ticket in the "Unity Support" epic to be handled by Unity.

**Deliverables**

- [ ] Document how to create a local WebGL build, connect to Decentraland services & connect the unity profiler

**Comment by m3taphysics** [comment]
Couldn't get this working with the remote build @kuruk-mm is going to build this locally and explain the steps.

**Comment by Kinerius** [comment]
https://github.com/decentraland/unity-renderer/pull/4282

I'm trying some emscripten params to see if I can fix the development build
