### ISSUE TITLE
Some player names appear truncated in the Notifications Area

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#3969]
Some names appear truncated in the notification area.

(It should be SantiHisteria, instead of SantiHiste)

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/f4a21106-038a-497e-ac4c-fde2408728c3)

**Comment by lorux0** [comment]
This issue has been already fixed in previous prs:
![Screen Shot 2023-02-15 at 16.02.10.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/882cb4b2-c563-46b6-822b-eea9d3b995ac)
