### ISSUE TITLE
Latest deployment seemed to break the client on my end and it keeps connecting to comms forever

### ISSUE THREAD

**Issue by ottodevs** [decentraland/unity-renderer#3977]
## Bug report

I am using Intel macOS Monterey, NO VR headset.

The game was working perfectly till the new update came out about 2-3 hours ago, now it does not load on Browser or Desktop client...

I am not familiar with the codebase, so I didn't do a lot of debug...

To reproduce just load the game normally and try to join any realm...

Browser (Brave, up to date version):

![Screenshot 2023-01-11 at 22 08 11](https://user-images.githubusercontent.com/5030059/211952531-a0277ac5-edd5-4611-b0f1-5dbeee9a8627.png)

Desktop:
![Screenshot 2023-01-11 at 22 14 57](https://user-images.githubusercontent.com/5030059/211952569-a283bbdc-fcc2-41a2-a0bd-4684b9507cea.png)

System Specs:
![Screenshot 2023-01-11 at 22 08 43](https://user-images.githubusercontent.com/5030059/211952653-f1102eba-22bd-4061-b7d8-d4607d5ab858.png)

**Comment by xavi-dcl** [comment]
@ottodevs this issue should have been resolved
