### ISSUE TITLE
Sentry Transactions Iteration #1

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-renderer#3979]
https://docs.sentry.io/product/performance/transaction-summary/

**Acceptance Criteria:**
- [x] Wrap Lambdas transactions in scope, the name of the scope should omit query parameters (https://docs.sentry.io/platforms/unity/enriching-events/transaction-name/) as it will create too much irrelevant noise, though they could be included as extra data if needed
- [x] ~~Add Scope for each scene to identify issues per individual scene~~ Done by @m3taphysics 
- [x] ~~Add the number of shown users as extra data per report~~ Done by @m3taphysics 
- [ ] ~~Add a document on how to modify the scope of the report~~ Straightforward

**Comment by m3taphysics** [comment]
My changes have been merged - we will need to test this ourselves on development
