### ISSUE TITLE
Write RFC for error metrics data structure

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#398]
We should write an RFC to get everyone onboard about how errors are going to be reported. 

This RFC should define a data structure that cover the following use cases:
- How product/business/growth may use the data to identify points of improvement (i.e. funnel issues)
- How engineering may use the data to go deeper and fix the issues

This said the RFC should cover:
- Error categorization
- Error data structure
- Error pipeline, infra
- Error implementation details (we use rollbar or segment API?, etc)

**Comment by olavra** [comment]
https://www.notion.so/decentraland/RFC-Error-Metrics-For-Explorer-55a356d48c3442a7ba108b274e90739b
