### ISSUE TITLE
[QA] Desktop clients are showing the old profile instead of the new one

### ISSUE THREAD

**Issue by kwsskulinski** [decentraland/unity-renderer#3980]
Description:
Desktop clients still show old version of the profile. On the web clients the issue does not appear.

Reproduction rate: 
5/5

Steps to reproduce:    
1. Login to desktop client.
2. Select the avatar icon in the right upper corner.
3. Open profile.
4.Observe the issue.
 
Results:    
Old version of the profile is being shown.
 
Expected results:
New version of the profile is shown.
 
Notes:    
- Platforms: Windows, MacOS, desktop, wallet login. 
- Issue occurs for production branch.
- Please see the attached screenshots for reference.

View on web client:
![new.jpg](https://images.zenhubusercontent.com/63bed9dceb9087129e33fd0a/deb86319-577f-42f1-ad67-2751352841a0)
View on desktop client:
![old.jpg](https://images.zenhubusercontent.com/63bed9dceb9087129e33fd0a/60de54b8-b73c-4503-a695-983b03a3a943)

**Comment by kwssbocian** [comment]
Issue no longer occurs. Closing
