### ISSUE TITLE
[QA] Typo and missing spacing between MANA balances in new player profile

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#3987]
Description: 
The new player profile has two visual issues. The wallet address text has a typo which says "WALLETADRES" and lacks a space between the two words. Additionally the MANA and Polygon MANA balance sections do not have a space between them.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in on a wallet account.   
2. Open up the Explorer menu and then navigate to the profile in the top right corner.
3. Observe the section with the wallet address and wallet balance.

Results:    
Profile appears with a typo and the MANA balance buttons lacking spacing between each other.

Expected results: 
Profile appears without typos and the MANA balance buttons have spacing between each other.

Notes:    
- Platforms: Windows, web, wallet login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot for reference.
![Screenshot 2023-01-12 130109.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/fa8442e0-0ea3-4f2b-9926-7942d8b7a551)

**Comment by anicalbano** [comment]
Does not apply with the new view.
