### ISSUE TITLE
Settings should not be cleared when user logs out

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#3999]
Settings should be local to the machine the user is using, and independent of the avatar.

Acceptance Criteria Journey:

1. Load into the platform with a wallet.
2. Open the Settings menu ('P').
3. Change any of the settings.
4. Log out using the "Logout" button on the avatar's menu (top right)
5. Log into the platform again with the same wallet
6. Access the Settings menu
7. See the same options

Alternative journeys to test: Wallet, then Guest; Guest, then Wallet; and Guest, logout, and Guest again.

**Comment by eordano** [comment]
From: #3112

**Comment by popuz** [comment]
From several play-tests, I noticed that settings get saved only if you close this UI. But even in this case not all settings are saved...

**Comment by popuz** [comment]
@eordano, I noticed, that not only "HOME" but also all other User Settings are shared between accounts. It means, that GUEST account can easily mess up settings that were setup for a Wallet on this machine. Should we take it in consideration as well and keep Settings Locally per-wallet (similar to "HOME")?

**Comment by popuz** [comment]
However, saving new "HOME" is handled on the kernel side.
