### ISSUE TITLE
spike: User falls when spawns on a model that hasn't been loaded

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4013]
Relation between Loaded assets and Kernel "ActivateRendererACK" might be causing most problems here. 

The outcome of this spike should be:

- Understand clearly why the asset loading lifecycle doesn't load the assets (or the colliders) before enabling the Rendering.

This happens very frequently on Genesis Plaza (when doing a clean install and speedrunning avatar creation), and -105,-143 (Vroomway)

**Comment by eordano** [comment]
![image.png](https://images.zenhubusercontent.com/5d8ba4376484360001b6f6df/41bc3717-abfa-4e40-8c24-81c53ad573da)

**Comment by eordano** [comment]
![image.png](https://images.zenhubusercontent.com/5d8ba4376484360001b6f6df/866aaf03-23b9-47bc-b186-ffddfdc451c1)

**Comment by mikhail-dcl** [comment]
I was able to reproduce it at -69, -139 with network throttling enabled: latency 250 ms, down: 1000 kb, up: 1000kb

**Comment by PalauiDCL** [comment]
Currently Investigating this

**Comment by mikhail-dcl** [comment]
The result of the spike:
https://app.zenhub.com/workspaces/workstream-core-experience-63aaac346e1c8d00104586e8/issues/gh/decentraland/unity-renderer/4068
https://github.com/decentraland/kernel/pull/850
