### ISSUE TITLE
Contextual Menus are out of bounds sometimes

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#4015]
Clicking on some profiles in the chat / friends menus, the context menus appear out of the screen and are impossible to interact. This also happens with other context menus, like the ones in the backpack.
This may be happening with other popup menus everywhere. We need to create a reusable edge detection and vertical / horizontal reallocation functions to prevent this

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/5f850a3d-3eca-44d2-ae58-ebaa6d75f245)
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/9554c848-cc70-4e6d-a04e-01c24247324a)

**Comment by anicalbano** [comment]
Does not apply anymore.
