### ISSUE TITLE
Some wearables information panel do not show the category or don't have an icon

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#4019]
Some wearables information panel do not show the category or dont have an icon.
So far I think this is for:
- Skins
- Top heads
- Earrings
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/9c92217d-fb25-47c8-b20a-6fb85cd95b28)

**Comment by sandrade-dcl** [comment]
It belongs to the old backpack. This issue doesn't apply to the new one.
