### ISSUE TITLE
[QA] Turning UI off and on in Worlds causes minimap to become visible

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4026]
Description: 
Inside any of the worlds the minimap becomes visible after toggling the UI off then back on.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in either on guest or a wallet account.   
2. Use the `/world menduz.dcl.eth` command to teleport to a world. Notice the minimap not being available in the top left corner of the screen.
3. Press the U key on the keyboard to deactivate the UI then press it once again to turn the UI back on.
4. Observe the user interface.

Results:    
Minimap is shown after turning the UI back on.

Expected results: 
Minimap is not shown after turning the UI back on.

Notes:    
- Platforms: Windows and MacOS, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot and video for reference.
![Screenshot 2023-01-16 110056.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/04280579-1ad3-4550-9785-e288aa243f21)
https://images.zenhubusercontent.com/337227404/925c33ce-a06f-4b5b-b457-4d2b2603f655/2023_01_16_10_57_37.mp4

**Comment by anicalbano** [comment]
Unable to repro this case.
