### ISSUE TITLE
Asset Bundle Converter 

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#403]
Asset Bundle Converter needs to be updated:

See: https://www.notion.so/decentraland/1P-Asset-Bundle-Conversion-improvements-ce69ac7c5334403ea72897e43bb14451

**Comment by eordano** [comment]
1P to be analyzed and approved; then if accepted, split into taks: https://www.notion.so/decentraland/1P-Asset-Bundle-Conversion-improvements-ce69ac7c5334403ea72897e43bb14451
