### ISSUE TITLE
ThrowAddingDuplicateWithKeyArgumentException

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#4031]
## Info

We have a recurring issue when loading certain avatars.

Sentry Report: 
https://sentry.io/organizations/decentraland/issues/3870475555/?project=4504361738698752&query=is%3Aunresolved&referrer=issue-stream

This exception causes some avatars to never end loading. 

## Steps to Reproduce

- It really depends on the users so it might be random
- Go to a crowded scene ( Wondermine / ICE Poker )
- Wait for avatars to load, there is a chance that one of them failed because another user had the same NFT emote and we are trying to load the same one, causing the exception.

**Comment by aixaCode** [comment]
Closing as duplicate https://github.com/decentraland/unity-renderer/issues/4061
