### ISSUE TITLE
Some avatar tags are being displayed for a split second after turn off the "Hide UI" feature

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#4039]
We notice when I turn the UI off then back on there is a text pop up for a split second.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/33c135a3-742c-43a7-850a-a953fb065d03)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/cb783ee4-116a-4e6f-8b50-caedd156a522)
https://decentralandteam.slack.com/files/U02BVFW88TS/F04K20NKVKP/bug.mp4

## Steps to reproduce
1. Enter the world.
2. Press [U] to hide the UI.
3. Press [U] again to show the UI.
4. Notive the issue.

**Comment by kwssbocian** [comment]
Issue related to #3659

**Comment by pbosio** [comment]
update: issue is not related to avatar tags but sdk7 hover interaction canvas
fix: https://github.com/decentraland/unity-renderer/pull/4047
