### ISSUE TITLE
Reduce Graphics.Raycast overhead

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#4045]
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/0e18ac05-f3f3-4920-a7ed-34cd0771d8d2)

## Problem

Right now when the cursor is unlocked and we can freely click on stuff, we have an overhead of `~6ms` on an empty scene (a third of the CPU usage on an empty scene based on the example), it gets a bit bigger on scenes with custom UI.

This is mainly caused by 2 calls to `EventSystem.RaycastAll()`. One is made by unity itself to handle the functionality of buttons, scrolls, etc, and the other one is caused by us trying to detect if we are hovering over a UI or a Character to draw the outline. 
Both use cases are completely normal, **_the issue is elsewhere_**.

The issue here is the amount of raycastable Graphics available.
Right now we have a lot of enabled Canvases with Alpha 0, while this is great on performance when enabling and disabling them, there's also the downside of the GraphicsRaycaster being also enabled.

If we were to disable all GraphicsRaycasters the overhead goes down a lot

![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/8d4becce-288b-4035-8a96-7710843e4328)

Obviously, I've disabled ALL of them, so if we leave just the ones that are visible we might get a similar number.

## Solution

We should carefully manage the lifecycle of our UI elements and disable their Graphics Raycaster when the views are hidden

**Comment by sandrade-dcl** [comment]
Good catch @Kinerius ❤️ We could easily make the `ShowHideAnimator` class to activate/deactivate the `GraphicsRaycaster` component associated to the current game object in the Show/Hide methods. We would gain a lot with a very simple change!

**Comment by aixaCode** [comment]
We could also check prefabs to remove unnecessary `RaycastTarget` bool set in Images or Text components. Or at least for all new prefabs pay more attention to that. This will lower the amount of processing it needs to do.

**Comment by popuz** [comment]
I extracted @aixaCode's comment to [this issue](https://github.com/decentraland/unity-renderer/issues/4151)
