### ISSUE TITLE
Fix delay of ~2s when opening the render of an Avatar in their Profile

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4046]
When clicking on a user to see its details, the avatar takes some time to load... is it possible that the resources are being fetched again over the network? They should be already in memory, since I'm already seeing a 3D render of it in world space. See attached video

https://user-images.githubusercontent.com/42750/212974991-2a151f1b-dc7c-4d2d-90d2-7aef281e2409.mp4

### Acceptance criteria
- [ ] Upon clicking on an avatar to see their profile, rendering the avatar should not be delayed more than a couple of frames

May be fixed with caching on the avatars #4134

**Comment by m3taphysics** [comment]
We are going to implement caching on the avatars #4134

**Comment by eordano** [comment]
I changed the description of the issue. Please re-evaluate.

**Comment by m3taphysics** [comment]
@eordano this issue opened #4134 should cover this can we close it?
