### ISSUE TITLE
Improvements in Profile Editing card

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#4048]
### Profile editing card
- [ ] The edit name section doesn't match at all the design. The title is missing, the button is not in the right place, the edit/done button is missing, the claim name toast should be updated, the container is missing.
- [ ] When the edit mode is active in the name input the claim name button must disappear and the non editable string must be aligned on the right with a very light grey color. The characters counter must be aligned bellow its container.
- [ ] Clicking on the input of the Profile editing card, cancels edit mode after pressing the edit icon. It should put the caret on the clicked space. 
- [ ] One click on the input of the Profile editing card should activate the edit mode and pressing enter confirm the edition.
- [ ] The description text must be aligned on the left.
- [ ] The info tooltip doesn't match the original design and it's not well aligned in relation with the info icon.
- [ ] The wallet padding between the title an address is wrong.
- [ ] The balances containers are overlapping.
- [ ] The intro characters counter is not in the right place.
- [ ] The corner radius of the intro container is wrong.
- [ ] The copy button is missing next to the wallet address.

**Comment by xavi-dcl** [comment]
To be clarified in the context of new profile UI

**Comment by xavi-dcl** [comment]
To be clarified in the context of new profile UI

**Comment by aixaCode** [comment]
Closing, not part of the scope
