### ISSUE TITLE
Migrate Loading Screen to Unity

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#407]
Loading screen is currently a web overlay. In order to move in the direction of a Desktop Client, we need to recreate this inside Unity.

There are 2 types of loading screens:

- [ ] ~Preloading web overlay~ 

- [x] Implement First loading screen
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/c36cbf83-e4f5-4579-b7d2-276abf347430)

- [x] Implement Teleport loading screen
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/4b53447d-b27e-4a1c-8cbd-7e3d3624f90b)

Once this screen is ported, the web overlay must be deleted

- [x] Delete web overlay

**Comment by olavra** [comment]
@RominaMarchetti we need to design a preloading screen in web

**Comment by RominaMarchetti** [comment]
<img width="770" alt="Screen Shot 2021-05-10 at 15 52 14" src="https://user-images.githubusercontent.com/51088292/117709784-b76d9900-b1a7-11eb-9ac2-fc87841a857e.png">

**Comment by olavra** [comment]
@RominaMarchetti al parecer Stefi estaba trabajando en algunas animaciones para esto?

**Comment by RominaMarchetti** [comment]
Stefi no esta trabajando nada relacionado a la Loading Screen por el momento. 
Mi comentario a Agus fue de probar que ella haga algunas animaciones con el logo si fuera necesario ir por una pantalla de carga austera por no pasarnos de listos con piezas graficas grandes.

Aca va el Figma con las variables.
https://www.figma.com/file/akmeRX6da0lnNuJuN50eMC/LoadingErrorsScreens?node-id=664%3A1397

**Comment by AjimenezDCL** [comment]
Stroke the first point `Preloading web overlay`. Now the spinner is preventing you from clicking `Play` and `Enter as guest` until the client is ready.

**Comment by olavra** [comment]
@AjimenezDCL move this to blocked, we need to focus on bug fixing and stability for a few more days

**Comment by olavra** [comment]
@AjimenezDCL we need an evaluation of how much time we need to spend on this task in otrder to finish it so we can prioritize

**Comment by AjimenezDCL** [comment]
Bear in mind the bugs detailed here https://app.zenhub.com/workspaces/unity-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/786. Are still presented in the porting.
