### ISSUE TITLE
[QA] Skybox time slider is not greyed out after relogging from guest account to wallet account

### ISSUE THREAD

**Issue by kwsskulinski** [decentraland/unity-renderer#4087]
Description:
The slider of the time setting is not greyed out after player logs into the wallet account. Only the title greys out. After switching off and on the issue disappears. 

Reproduction rate: 
5/5

Steps to reproduce:    
1. Log into the Decentraland on the guest account.
2. Open the settings [P].
3. Make sure the Dynamic Skybox is turned on.
4. Log into the wallet account.
5. Open settings [P].
6. Observe the issue.
 
Results:    
Only the Skybox Time title is greyed out.
 
Expected results:
Title and slider are greyed out.
 
Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Please see the attached screenshots for reference.
- Issue occurs for the [release/release-20230119 branch](https://github.com/decentraland/explorer-desktop/pull/464).

Not greyed out after logging into wallet acount.
![not greyed.jpg](https://images.zenhubusercontent.com/63bed9dceb9087129e33fd0a/fae86e06-3e25-4422-ad79-1ed98f781ed1)
Greyed out after switching option off and on.
![greyed.jpg](https://images.zenhubusercontent.com/63bed9dceb9087129e33fd0a/29a0a581-68c7-4663-a34f-1476eae0901e)

**Comment by anicalbano** [comment]
Current behaviour:

![image.png](https://images.zenhubusercontent.com/64ad62442a830229041f8802/f96da70e-8d48-4f0d-afa7-3af120340e9a)

![image.png](https://images.zenhubusercontent.com/64ad62442a830229041f8802/43c2d912-ec1e-4cb1-9475-8f64f1da8e53)
