### ISSUE TITLE
Create Unity Desktop repository and pipeline

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#409]
A new repository has to be set according to the design specifications of this ADR. 
https://github.com/decentraland/adr/blob/main/docs/ADR-25-explorer-repositories-decoupling-.md

It contains:
- [x] A new Unity project that contains unity-renderer as a UPM package.
- [x] This project has its own main scene
- [x] This scene has its own Main class implementation. This implementation will override whatever unity-renderer systems are necessary to work with the desktop version. 

The desktop specific systems have to live in the desktop version repository. Changes that are not specific to desktop have to remain and be pushed exclusively to unity-renderer.

Then, the continuous integration of the desktop repository can deploy the following artifacts:
- [x] For development branches, a unique .zip package per OS for MacOS, Windows and Linux builds. This enables the contributors to test the builds without having to resort to run some installer.

- [ ] ~~For master and release, the CI prepares the installers that match the end user experience. These installers are going to be linked by our landing page.~~

**Comment by kuruk-mm** [comment]
New repo is building for Windows, Linux and Mac correctly. The result executes DCL, but only shows a white screen. We need to deel with this problem inside unity-renderer.

![image.png](https://images.zenhubusercontent.com/60647b38cc4b79842895cb82/4987e253-25d7-46ff-af1e-a4941a5221db)

**Comment by kuruk-mm** [comment]
The import is working well, just one issue that is blocking this to merge to master (reported in #513)
