### ISSUE TITLE
[QA] Brief zoom-in before teleportation on fullscreen on macOS desktop

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4096]
Description:
On MacOS desktop client set to fullscreen a brief zoom-in to the bottom-left corner occurs before every kind of teleportation. Zoom occurs after issuing the teleportation command but before the loading screen is shown. Issue is best observable wit hthe usage of the `/goto` command.

Reproduction rate:
5/5

Steps to reproduce:

1. Launch the desktop client on macOS with either guest or wallet login.
2. Log in either via a guest or a wallet account. Ensure that the client is set to fullscreen in the graphical settings.
3. Use the `/goto random' command to teleport to a random place.
4. Observe the renderer window. Notice the bottom-left section of the screen is briefly zoomed-in before the loading screen appears.

Results:
Bottom-left section of the screen is briefly zoomed-in before the loading screen appears.

Expected results:
No zoom-in occurs before the loading screen appears.

Notes:
- Platforms: MacOS desktop, wallet and guest login.
- Issue occurs for both production and dev branches.

**Comment by m3taphysics** [comment]
@kwssbocian can we add a video here so we can see how bad this looks?
