### ISSUE TITLE
Introduce Guest Mode inside Sign In options

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#410]
Play as Guest option should be included inside the Sign-in or Create an Account dialog, and to be removed from the bottom of the play button.

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/73a7a67c-415c-4ee8-873c-804d80aa16e7)

A third button will be added on the right side with a new Icon and "Play as Guest" text

**Comment by olavra** [comment]
@RominaMarchetti while we decide the right flow for the Application First vs Sign in method first, Desktop vs Web, Signed vs Guest workflow, we should work on the introduction of the Guest button inside this panel. Can you prepare some assets for this?

**Comment by kuruk-mm** [comment]
This was addressed here: https://github.com/decentraland/explorer/pull/2428

Maybe this is not from `Desktop Client` epic.

@olavra
