### ISSUE TITLE
Spike: Investigate unity initialization load time

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#4101]
## Context ##
The unity initialization time for Unity is currently over 15 seconds (see [https://metabase.decentraland.systems/question/1242-loading-time-unity-download-initialization-weekly](url).

We also have a sentry issue which indicates there is a 5000ms freeze on startup. See [https://sentry.io/organizations/decentraland/issues/3863272273/?project=4504361738698752&query=is%3Aignored&referrer=issue-stream&statsPeriod=14d](url). During loading the world the experience gets frozen for >5 seconds (see #4003). We have to pin-point when this is happening and if it's desirable.

For this task we should look at the loading times as a whole and create a breakdown of which parts of the unity initialization is taking so long and look to rectify and improve this.

## Acceptance Criteria
- [ ] Breakdown of the unity initialization load time
- [ ] Prioritised list of tasks to improve the load time
- [ ] Decision if the 5000ms pause (WebGL) is needed or can we mitigate this.

**Comment by eordano** [comment]
Marking this as "later", after we refactor the minimap. We know from https://www.notion.so/decentraland/Performance-Profiling-2023-1-16-f6ad6b9ef07647298e78d4610efd5c1e#28292217d7f5420e8e01f0826115b2d6 that at least 500ms are spent at instantiating the map

![image.png](https://images.zenhubusercontent.com/5d8ba4376484360001b6f6df/a68b970f-4fee-4665-b174-63a9594c1b18)
