### ISSUE TITLE
Port Audio Streaming to be played inside Unity

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#412]
This feature is tightly coupled to browsers right now. If it’s not ported, the sound will come from the browser’s tab. This is not viable UX-wise, so a new solution that streams audio right off the desktop client is needed.

**Acceptance Criteria**
- [ ]  Audio streaming should be played inside Unity

**Comment by kuruk-mm** [comment]
@pbosio, do you know if this works on Desktop?

**Comment by pbosio** [comment]
> @pbosio, do you know if this works on Desktop?

It won't
For audio streaming we are using an Audio HTMLElement
https://github.com/decentraland/kernel/blob/main/packages/unity-interface/audioStream.ts

**Comment by kuruk-mm** [comment]
The Audio Streaming is working fine, but the audio output is from the Launcher like the Voice Chat.

We should prioritize this anyway?

**Comment by JorgeDecentraland** [comment]
@kuruk-mm is this still needed?
