### ISSUE TITLE
Highlight messages with mentions to you

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#4127]
If any players @mentions you in the chat, that message will be highlighted with a different background color to differentiate it from the rest.
The conversation list will also show special icons for conversation with unread messages that contain mentions

**Acceptance Criteria**
- [x] Chat messages that mentions you will be highlighted with a different color
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/ce124331-107b-4499-ae69-4e4328d4c1ae)
- [x] Conversations with unread messages will show a @ icon next to the number of unread messages
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/5132f099-cf80-4e3a-88a0-72aaa66fb2de)
[PRD Documentation](https://www.notion.so/decentraland/PRD-Chat-Mentions-ffd23437a8c34cddadc401fabd7f5139#a5abd61e7d1646b492f2733821c42743)

**Comment by RominaMarchetti** [comment]
Check Figma link [here](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Private-Channels?node-id=4305%3A27258&t=oab7wQMHtUdTUKGl-1)

<img width="336" alt="Screenshot 2023-01-26 at 13 34 32" src="https://user-images.githubusercontent.com/51088292/214893806-d4a6c11d-ae50-49d1-8a1c-68c71d3df719.png">
<img width="326" alt="Screenshot 2023-01-26 at 13 34 26" src="https://user-images.githubusercontent.com/51088292/214893823-e68208a8-f297-4d46-9648-bf9135566421.png">
