### ISSUE TITLE
Cache created avatar meshes

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4134]
### Description
Whenever we want to display another avatar, we're creating a mesh combining all of the avatar's wearables. This issue is to analyze how this gets done (if there are any perf gains we could gain from it), where is this getting done (is there a strategy to allow users to upload their joined meshes? could it get abused?), and whether we could cache these meshes locally (maybe a LRU cache, on disk, that avoids fetching wearables)

### Deliverables
- [ ] Implement a solution that caches the avatar creation process so we can avoid long load times when viewing the passport.

### Acceptance criteria
- [ ] The avatar of another user should be visible immediately when the passport is loaded.

**Comment by mikhail-dcl** [comment]
Considering it is not the issue causing N seconds delay of passport opening, instead of caching I'm optimizing the flow of `Avatar Mesh Combiner`.
Once it is done I will analyze if such cache is needed
