### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#4136]
### What happened?

A creator reported that certain video ads that are shown before their main videos are not displayed at all in a scene.
On the streaming platform used behind the scenes, the ads are accounted for as shown, but the screen remains black.

The streaming of these video ads should be no different from regular videos from the scene's side, and in fact it used to work in the past.

From the user who reported this: The videos are uploaded in mp4 format, 20 mb max size.

### Steps to reproduce

Enter this scene:
https://play.decentraland.org/?realm=hephaestus&position=-4%2C-37&island=I37sp

Click on the large black screen mounted on the outside of the building, see that the screen remains black.

Apparently, in the past the creator had videos in the same format & quality and they worked well. So this should likely work properly with older renderer versions.

### Operating System

Chrome, Mac

### Wallet

Metamask

### CPU

2,6 GHz 6-Core Intel Core i7

### GPU

AMD Radeon Pro 5300M 4 GB

### RAM

16 GB 2667 MHz DDR4

### Kernel Version

latest

### Unity Version

latest

### Realm

hephaestus

**Comment by 0xD-Fabio** [comment]
@nearnshaw  I've tried the scene both on the web and desktop client, and Instead of black screens, I see these ads.
Is that correct, or am I missing something?
![VideoAdsNotPlaying.png](https://images.zenhubusercontent.com/633adb3e5510f3d8ef8164d7/63598658-e2b5-4a4a-ae95-3bd249611bfb)

**Comment by 0xD-Fabio** [comment]
The issue is not reproducible anymore on the scene, and we don't have the creator's contact info, so we can't investigate further about this issue.
