### ISSUE TITLE
WonderMine

### ISSUE THREAD

**Issue by AlexST03** [decentraland/unity-renderer#4138]
### What happened?

Don't work wonderMine, doesn't interact with objects. Re instal PC cliend, clear cash browser, don't halp me... Please help!
<img width="1919" alt="Screenshot_2" src="https://user-images.githubusercontent.com/17242481/213868935-65a25dea-db76-4067-8c6f-f5440436d586.png">

### Steps to reproduce

doesn't interact with objects in start

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

i3 8350k

### GPU

ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16

### Kernel Version

2.0.0-3960655822.commit-e2fea21

### Unity Version

1.0.71809-20230112133213.commit-14d33f9

### Realm

hephaestus

### NameTag

Slaqeoriman#cdf9

**Comment by m3taphysics** [comment]
@kwssbocian @kwsskulinski can we verify that this is still a problem? we did a fix with colliders on custom UI elements which may be related.

**Comment by m3taphysics** [comment]
We cannot reproduce this
