### ISSUE TITLE
Disable unneeded raycastTarget on UI

### ISSUE THREAD

**Issue by popuz** [decentraland/unity-renderer#4151]
### Description
As was discovered [here](https://github.com/decentraland/unity-renderer/issues/4045), `RaycastAll` from `EventSystem` was causing performance drop. It was partially resolved in [#4118](https://github.com/decentraland/unity-renderer/pull/4118), but it would be even better to disable `raycastTarget` flag on all elements of UI prefabs, that don't need it (as proposed by @aixaCode in [this comment](https://github.com/decentraland/unity-renderer/issues/4045#issuecomment-1387007485)) . This work was partially done in mentioned PR, but several folder remained untouched, namely:
 "Assets/Scripts/MainScripts/DCL/Controllers/ChatController",
 "Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2",
 "Assets/Scripts/MainScripts/DCL/Controllers/HUD",
 "Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer",
 "Assets/Scripts/MainScripts/DCL/Controllers/VoiceChat",

The task would be to go through each UI prefab in these folders and validate UI elements with enabled `raycastTarget` if they really need it or it can be disabled (and disable it in such case).

Bigger priority should be addressed to the HUD elements (UI elements that are visible together with 3d objects, like miniMap)

### Note 
To iterate through these prefabs in organized way, you can use this code-snippet in your editor script. It will log prefabs that contains UI element with `raycastTarget` property enabled. You can click on the console message to locate the parent prefab in Project window, open it and then paste in the hierarchy search (of opened prefab) its children names printed in the console (for further validation). 
I suggest to go folder by folder, i.e. leaving uncommented only one folder path in PREFAB_PATHS -> run the script -> fix prefabs -> make a commit -> remove this checked path from PREFAB_PATHS -> uncomment next and repeat the cycle

```
private static readonly string[] PREFAB_PATHS =
{
    "Assets/Scripts/MainScripts/DCL/Controllers/ChatController",
    "Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2",
    "Assets/Scripts/MainScripts/DCL/Controllers/HUD",
    "Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer",
    "Assets/Scripts/MainScripts/DCL/Controllers/VoiceChat",
};

            foreach (string prefabPath in AllPrefabPaths())
            {
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);

                if (prefab.GetComponentsInChildren<Graphic>().Any(graphic => graphic.raycastTarget))
                {
                    Debug.Log("----: " + prefab.name, prefab);

                    foreach (var graphic in prefab.GetComponentsInChildren<Graphic>())
                        if (graphic.raycastTarget)
                            Debug.Log(graphic, graphic.gameObject);
                }
            }

            IEnumerable<string> AllPrefabPaths() => AssetDatabase
                                                   .FindAssets("t:Prefab", PREFAB_PATHS)
                                                   .Select(AssetDatabase.GUIDToAssetPath);
```

**Comment by aixaCode** [comment]
Closing, not part of the scope for the time being.
