### ISSUE TITLE
[QA] Guest avatars occasionally appearing faceless and with stuttering animations

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4152]
Description: 
Occasionally guest avatars of other users appear without any facial features and with their animations playing out at a much lower framerate. Issue appears to occur randomly and only within Genesis Plaza. Issue subsides and the avatars appear correctly once a refresh of the browser tab is performed.

Reproduction rate: 
1/5 

Steps to reproduce:    
1. Log in either on guest or a wallet account.   
2. Use the `/goto 0,0` command to teleport to Genesis Plaza.
3. Look around in search for a guest avatar with a blank face and stuttering animations.
4. Observe the guest avatar.

Results:    
Guest avatar appears faceless and its animations are stuttering.

Expected results: 
Guest avatar appears with all its features rendered and with animations playing smoothly.

Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot and video for reference.
![Screenshot 2023-01-27 162903.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/e0ce0fb0-be76-4ff6-83c4-f7397e218c8e)
https://images.zenhubusercontent.com/337227404/3e6bebae-97cd-46dc-a1a4-3d97ddbb27e4/2023_01_27_16_15_58.mp4
https://images.zenhubusercontent.com/337227404/3619184b-d555-44ba-ae31-4714f0561b82/2023_02_01_11_05_25.mp4

**Comment by popuz** [comment]
however, I found one more strange behaviour with this class - it is called in every Update from AvatarWithHologram even if it is not presented on the scene
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/1a1f2955-0570-4822-bd9b-7cbbd08052e8)

**Comment by popuz** [comment]
in case of big avatar in fashion week, it caused by distance calculation LOD system calculating distance wrong
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/32a0cd44-aada-4197-9657-bb78c8798b78)

**Comment by popuz** [comment]
If regression will bring it back, I suggest to track it via logs inside `AvatarsLODController.RegisterAvatar`/`UnregisterAvatar`, because the issue relates to this part of the system. You can put smth like that
`Debug.Log($"Registering {player.name}", player.collider.gameObject);`

**Comment by popuz** [comment]
If regression will bring it back, I suggest to track it via logs inside `AvatarsLODController.RegisterAvatar`/`UnregisterAvatar`, because the issue relates to this part of the system. You can put smth like that
`Debug.Log($"Registering {player.name}", player.collider.gameObject);`
