### ISSUE TITLE
[QA] Wallet avatars occasionally failing to load in and appearing as blue hologram outlines

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4153]
Description:
Occasionally guest avatars of other users continuously appear as if they are still loading in (as a blue hologram outline). Whenever such user is present nearby a message in the console can be observed that reads `Failed curating avatar wearables` `Avatar.Load failed with wearables: (...)`. Issue often subsides and the avatars appear correctly once a refresh of the browser tab is performed.

Reproduction rate:
1/5

Steps to reproduce:
1. Log in either on guest or a wallet account.
2. Use the `/goto 0,0` command to teleport to Genesis Plaza.
3. Look around in search for a wallet avatar continuously appearing as a blue hologram.
4. Observe the wallet avatar avatar.

Results:
Wallet avatar appears continuously as a blue hologram and fails to load in with its wearables.

Expected results:
Wallet avatar appears normally with all its features and wearables loaded in.

Notes:
- Platforms: Windows, web and desktop, wallet and guest login.
- Issue occurs for the dev branch.
- Please see the attached screenshot and video for reference.
![avatar1.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/56a5e98c-761d-498a-92d4-fc381345456b)
https://images.zenhubusercontent.com/337227404/8464f916-6f3c-4960-a8b3-c82522f3fda4/2023_01_27_16_56_26.mp4

**Comment by m3taphysics** [comment]
Investigate why this happens to see if we can prevent it - if not, its not a bug because it has failed to load.

**Comment by m3taphysics** [comment]
@RominaMarchetti could we have some input on how it should look if an avatar fails to load?

**Comment by RominaMarchetti** [comment]
@m3taphysics I have a few questions before providing a solution:
1- Is it possible to change the avatar shader when it doesn't load? 
2- Is it possible to do mouse-over those models and showcase some feedback?

**Comment by kwsskulinski** [comment]
Issue no longer occurs
