### ISSUE TITLE
[MVFW23] AvatarShape scaling issues

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#4179]
## Problem

When we scale AvatarShapes to big values they start to look weird, also their bounds are not updated so when you look up to the giant avatar, it stops being rendered.

https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1674837856105669

Attaching test scene for testing:
https://drive.google.com/file/d/1zjQW6br3uCGVRuN_May6s23wHSW7D1wo/view?usp=share_link

**Comment by m3taphysics** [comment]
This would be great to fix ready for MVFW
