### ISSUE TITLE
 Manually re-convert and upload the empty parcels

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#418]
- [x] Manually create the assets of empty parcel in local
- [x] Upload the assets to S3

**Technical Info:** 
The kernel empty parcels path will probably break because of the repos separation

**Comment by pravusjif** [comment]
I updated the kernel empty parcels path and added a comment regarding that in [this pr](https://github.com/decentraland/unity-renderer/pull/423/files).

I could convert the empty parcels locally and uploaded them to the S3 bucket with no problems.

Also tested that we loaded GLTFs previously and now we load ABs.
