### ISSUE TITLE
Convert all scenes in the world to Asset Bundles

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#419]
-[ ] Force conversion in all scenes (check with @menduz)
-[ ] Convert all asset from all scenes in production

**Comment by menduz** [comment]
Well, this is _very_ expensive, nearly 15k hours of computing in a worst case scenario. Can we get a prioritized list of scenes to start with and validate the approach?

**Comment by olavra** [comment]
We need first to reach a really stable version of the AB converter after months without problems to consider this. Maybe do this in local and manually upload it in the future.

**Comment by pravusjif** [comment]
This is impossible to do because of the cost.
