### ISSUE TITLE
[QA] Video players on some scenes are not functional

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4199]
Description: 
Video players located at some scenes are not functioning. Walking up to one and clicking Play Video results in no video being played and a message in the console appearing saying `VIDEO PLAYER: fatal network error encountered, try to recover`. Issue observed on scenes at `62,-1` and `108,-120`.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in either on guest or a wallet account.   
2. Use the `/goto 62,-1` command to teleport to the scene with a video player.
3. Walk up to the screen nearby and press the interact button to play the video.
4. Observe the video screen.

Results:    
Video is not playing after pressing Play Video.

Expected results: 
Video plays correctly after pressing Play Video.

Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/938f3bcb-a7f0-4130-9837-953cb07e4a48/2023_02_01_13_39_25.mp4

**Comment by m3taphysics** [comment]
Lets verify if this is a real bug or a specific scene issue so we can feed this back to the scene creators if needed.

**Comment by 0xD-Fabio** [comment]
Both scene 62,-1 and 108,-120 try a GET request on something that returns 404. 
So the requested files cannot be found on the servers.

Additionally the 62,-1 scene, seems to have some CORS errors:
`/?realm=heimdallr&position=62%2C-2&island=peer-wc17l6v:1 Access to XMLHttpRequest at 'https://theuniverse.club/live/genesisplaza/index.m3u8' from origin 'https://play.decentraland.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by 0xD-Fabio** [comment]
Since the problem are all server side with 404 errors, I'm going to close this ticket.
