### ISSUE TITLE
Fix issues with livekit-client 1.6.3

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4228]
Since we enabled livekit comms v3, there are a number of invalid connection states/messages incorrectly being processed. [This issue](https://github.com/livekit/client-sdk-js/pull/568) will fix them -- we need to wait for livekit-client 1.6.4.

**Comment by kuruk-mm** [comment]
CC @hugoArregui

**Comment by eordano** [comment]
Closed by https://github.com/decentraland/unity-renderer/pull/4239
