### ISSUE TITLE
spike: Performance degradation after a long time

### ISSUE THREAD

**Issue by Kinerius** [decentraland/unity-renderer#4244]
We had a report in slack with evidence that we have great a performance drop after the client is open 10 minutes or more.

## Acceptance criteria

- [x] Analyze what's the issue and fill a report with the potential fix on a new issue.

**Comment by dalkia** [comment]
A test was done comparing using the Profiler after ten minutes of usage on an empty scene. A 100% repro degradation was visible, as shown in this [video](https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1675259138800659).

The first culprit comes from the canvas update. When moving the camera around, after ten minutes, we have an increased number of updates, even though no new `Canvas Renderers` should have been created

Start (`PostLateUpdate.PlayerUpdateCanvases` takes 2.11ms)
![image.png](https://images.zenhubusercontent.com/62a9e908660cd151471c312d/a86abe7c-499f-485a-af30-863568b08514)

vs

Ten Minutes In (`PostLateUpdate.PlayerUpdateCanvases` takes 4.4ms)
![image.png](https://images.zenhubusercontent.com/62a9e908660cd151471c312d/4cbbebd8-4c35-40ca-b8c0-a1ab6f6045ef)

We can see a clear increase in the number of canvases that are being updated, going from x to y. 

To find a first origin, I used this very simple script to find which `CanvasRenderers` were instantiated through time.

```
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class CanvasRendererCounter : MonoBehaviour
{
    private List<CanvasRenderer> originalCanvasRenderers;
    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.H))
        {
            List<CanvasRenderer> newSearch = FindObjectsOfType<CanvasRenderer>(true).ToList();
            if (originalCanvasRenderers == null)
            {
                Debug.Log($"ORIGINAL CANVAS RENDERER COUNT {newSearch.Count}");
                originalCanvasRenderers = new List<CanvasRenderer>(newSearch);
            }
            else
            {
                Debug.Log($"NEW CANVAS RENDERER COUNT {newSearch.Count}");
                foreach (CanvasRenderer analyzedCanvasRenderer in newSearch)
                {
                    if(!originalCanvasRenderers.Contains(analyzedCanvasRenderer))
                        Debug.Log($"HERE IS A NEW ONE {analyzedCanvasRenderer.gameObject.name}");
                }
            }
        }
    }
}
```

First duplication was found with POIs, but they may be more still. This needs to continue a further investigation
