### ISSUE TITLE
Create Input Dependent Components

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-renderer#4264]
**Acceptance Criteria**
- [x] Define Abstraction for `Map Input Controller`
- [x] Implement `Map Input Controller` and enrich its API according to the usages required by the components listed below
- [x] Create Parcel Navigation Layer
- [x] Create Parcel Highlighter Layer
   - [x] Create an abstraction
   - [x] Create an implementation based on the prefab

**Comment by AjimenezDCL** [comment]
We no longer need this

**Comment by mikhail-dcl** [comment]
We need to make a layer to convert coordinates from UI `RawImage` to the SpriteRenderer's coordinates based on the current camera
