### ISSUE TITLE
spike: Many hiccups in some scenes

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4275]
### Description
We have some reports in slack of hiccups in some scenes, right now we are unsure of the cause. The user reported the issue in scene 129,130. It appears that the "warning: 70+ FS.syncfs operations in flight at once" could be related but this is likely warning and it is due to caching many items at once.

See link: [https://drive.google.com/file/d/1ZKjL-LiAd-0CgJyjdVW8bEUScRrfQho8/view?usp=sharing](url)

### Deliverables 
- [ ] Understand why the hiccups are happening

**Comment by mikhail-dcl** [comment]
1. I checked with "DISABLE_AB_CACHING" and didn't see any correlation between that and performance
2. There are tons of exceptions happening at a time (SDK exceptions, investigation in progress)
3. I create two more bugs to resolve
