### ISSUE TITLE
Check multiple get friendships requests on refreshFriends (startup)

### ISSUE THREAD

**Issue by moliva** [decentraland/unity-renderer#4298]
From the browser-interface sagas for friendships, the endpoint for getting the friends of the current user seem to be getting called multiple times in a single flow of startup.

**Comment by agusaldasoro** [comment]
<img width="920" alt="Screenshot 2023-02-27 at 09 55 48" src="https://user-images.githubusercontent.com/8031515/221597652-7437e0f9-94be-406d-9304-da3b6ea12978.png">

Couldn't reproduce it, after trying to emulate the issue, I found only two requests to the endpoint (HEAD + GET). Closing the issue.
