### ISSUE TITLE
Cybermike Suit appearing too bright in Decentraland character renderer 

### ISSUE THREAD

**Issue by cybermikedent** [decentraland/unity-renderer#4308]
Cybermike Suit appearing too bright in Decentraland character renderer 

Perhaps there was an update on the character renderer which caused this.

Although the texture detail might have been enhanced which looks good, the suit is far too bright now and not like the original vision.

Many Thanks

-Cybermike

![CM_Suit_Issue_A01](https://user-images.githubusercontent.com/56007113/217331916-3d292f6e-03fc-4117-b2c9-750773b19859.jpg)
![CM_Suit_Issue_A02](https://user-images.githubusercontent.com/56007113/217331933-b0958d8e-5951-4c7d-a8d0-e8e94c71596c.jpg)

**Comment by m3taphysics** [comment]
Hi @cybermikedent could you show a screenshot within the "character renderer" where it is brighter?

If you can clarify the issue it would help.

Thanks!

**Comment by cybermikedent** [comment]
Hi @m3taphysics 

The "Character Renderer/ Shader" within Decentraland as shown above

You can see the previous Character shade/ render was much different

Many Thanks

Cybermike

![CM_Suit_OriginalB01](https://user-images.githubusercontent.com/56007113/217667177-e331af52-0486-4fbe-9f64-e1b7a3f97f55.jpg)

![CYArManWIP_A43E3](https://user-images.githubusercontent.com/56007113/217666491-29456e0d-e12c-4817-ac2c-45abf5ee4704.jpg)
![CYArManWIP_A43E2](https://user-images.githubusercontent.com/56007113/217666506-ca5fa3c0-7dcd-4cdd-9724-fb8dcfec69ce.jpg)

**Comment by cybermikedent** [comment]
Its been a month, no one has got back to me @m3taphysics

**Comment by cybermikedent** [comment]
Hi @m3taphysics I have the contracts for each of the items below (i think the id's for each wearable from the set is 59, 56, 55, 52, 51, 42) Ethereum chain

https://market.decentraland.org/contracts/0x24d538a6265b006d4b53c45ba91af5ef60dca6cb/tokens/59
https://market.decentraland.org/contracts/0x24d538a6265b006d4b53c45ba91af5ef60dca6cb/tokens/56
https://market.decentraland.org/contracts/0x24d538a6265b006d4b53c45ba91af5ef60dca6cb/tokens/55
https://market.decentraland.org/contracts/0x24d538a6265b006d4b53c45ba91af5ef60dca6cb/tokens/52
https://market.decentraland.org/contracts/0x24d538a6265b006d4b53c45ba91af5ef60dca6cb/tokens/51
https://market.decentraland.org/contracts/0x24d538a6265b006d4b53c45ba91af5ef60dca6cb/tokens/42

- I think perhaps the "character shader" was changed from "toon" to "unity" which has caused the suit to appear much more brighter than before, losing its dark appeal. This is only a rough guess, im not sure.

Many Thanks! 

-Cybermike

**Comment by cybermikedent** [comment]
Its Fixed! Thanks to whoever just did it!! <3
