### ISSUE TITLE
Update Explorer Desktop launcher on Windows Store

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#4317]
### Description

After merging desktop repository to uniyt-renderer, we have to update desktop launcher to proplery consume the new artifacts.
Currently, we have DCL version available in the Windows Store, which should be updated and kept in sync with standalone one.

### Acceptance criteria
- [ ] Explorer desktop launcher is updated and release in Windows Store.

**Comment by 2fd** [comment]
![Screenshot 2023-03-02 at 10.32.58.png](https://images.zenhubusercontent.com/5e3c030aa21fc98c7daa9b14/799e6d18-12fc-4815-aba3-fac9d30589d8)
