### ISSUE TITLE
Spike: Investigate connecting renderer to RPC server for social

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4346]
### Description
We need to connect the renderer to the RPC server and avoid this extra work via the browser-interface. We need the ability to subscribe to events which the RPC already provides. This will allow us to receive events such as "friend request" received without any polling mechanism.

### Deliverables
- [ ] Allow the renderer to connect directly to the RPC server

**Comment by kuruk-mm** [comment]
Spike at https://github.com/decentraland/unity-social-client
