### ISSUE TITLE
Dockerize the unity builds

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4347]
### Description
We want to more easily replicate the build process on a local machine to be able to run, test and profile the builds. If we dockerize the process it will work for each platform & the same across different machines without worrying about NPM versions and such. It will also improve the build process via using base images.

### Deliverables
- [ ] Docker-Compose / Dockerized WebGL & Desktop builds
- [ ] Integrate with the CI

### Notes
We would like to have simple command interface

examples:
```
docker-compose up --profile --platform=webgl
docker-compose up --profile --platform=desktop
```

**Comment by kuruk-mm** [comment]
Tried on branch:
https://github.com/decentraland/unity-renderer/tree/chore/dockerization

I'm trying with the following steps:
```bash
# set unity license
export DEVELOPERS_UNITY_LICENSE_CONTENT_2020_3_BASE64=...

# build docker image
docker build . -t unity

# runs the container and attach the console (self-destruct, 16gb ram needed)
./ci-docker-build.sh

# joins to the docker locally
./ci-build.sh
```

The docker crashes with the following [build-logs.txt](https://app.zenhub.com/files/337227404/175e5d83-46cb-44fd-8458-9eb161b31e10/download)

It looks like it is not downloading the packages properly.

We decided to stop the task to avoid losing more time and trying another approach.
