### ISSUE TITLE
SDK Scenes to get an event when player changes wearables

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#435]
Derived from #300

**Comment by Suduck** [comment]
Almost implemented, I will like to know which is the use for this event so I can the information in a way that is useful for the user.

Right now I am thinking to send two items

OldWearable

- WearableId
- Rarity
- Description?
- Category?

NewWereable
- WearableId
- Rarity
- Description?
- Category?

**Comment by Suduck** [comment]
The PR has been closed since this will be done entirely in the SDK team because kernel already have the information
