### ISSUE TITLE
The Places sub-section seems to be refreshing in a different way in web and desktop

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#4354]
It seems the menu sub-sections are not being refreshed each time we open the explore menu. This was something that we already fixed in this PR (https://github.com/decentraland/unity-renderer/pull/3490) but maybe we have changed the flow in later changes/refactors.

**Image from Desktop:**
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/39916b7d-dfa8-4d1e-8fb4-ad24b49c8dd9)

**Image from Web:**
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/b06d0c8b-1889-44d9-9951-ef1f57080b03)

**Video 1:**
https://decentralandteam.slack.com/files/U02BVFW88TS/F04P3EXEWHZ/2023-02-10_12-58-22.mp4

**Video 2:**
https://decentralandteam.slack.com/archives/C01QTN7BU73/p1676053580983639?thread_ts=1668195021.351789&cid=C01QTN7BU73

### Context (Slack's thread)
https://decentralandteam.slack.com/archives/C01QTN7BU73/p1675981378784209?thread_ts=1668195021.351789&cid=C01QTN7BU73

**Comment by davidejensen** [comment]
I will update here the latest findings:
- When requesting the hotScenes from the same catalyst all the informations are correct and aligned
- When requesting the hotScenes from different catalysts, often there are big variations (could be normal that they are not in sync in real time). You can try by requesting hotScenes from https://peer-wc1.decentraland.org/lambdas//explore/hot-scenes and then from https://interconnected.online/lambdas//explore/hot-scenes to see the differences
- The explore menu requests on open the hotScenes to the current catalyst we are connected to
- If we change catalyst the menu is not instantly refreshed but it will be refreshed the next time we close and open the explore menu

Possible solutions:
- [ ] Act on the lambdas to find a way to provide always the same result no matter which catalyst we are connected to (I don't know if it's doable)
- [ ] Force a refresh of the explore menu places list on catalyst change (would look ugly but would always display the correct catalyst places response)
- [ ] Leave it all as it is (it's always minor differences and they will be correctly displayed as soon as we close and re open the explore menu)

**Comment by aixaCode** [comment]
This behavior is expected, so closing the issue.
More context from platform teams:

> The information in /hot-scenes is reloaded in each catalyst every 2 minutes. So if you query the same catalyst during the same 2 minutes, the information must be the same. If you’re in the “corner” of the 2 minutes windows, the requests with a difference of seconds might have different result.
> In addition, each catalysts calculates this information and saves it in cache at different times. So again there might be differences between catalysts.
> Why is that? Well, the calculation of the information exposed in GET /hot-scenes is really expensive. It involves querying every catalyst to GET /parcels and calculate it. So this work cannot be done for each request to /GET hot-scenes.
> Possible mitigation: we might evaluate enlarging the window of 2 minutes, so querying the same catalyst from different sources might be consistent for more time. The downside of this is that the information would be more outdated
