### ISSUE TITLE
Retriggering non-looping animations not working

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#436]
Mateo has been changing how animations work in @next, and in many cases that's been fixed, but not everywhere.

Check this example:
https://github.com/decentraland-scenes/Hummingbirds/tree/6.6.5

I should be able to re-run the animation on the tree every time I click on it. But it only runs the first time. Even if I wait till the animation fully finishes.

If I uncomment line 20 in game.ts, so that I do stop() before play(), it works as expected.  It should play the animation again each time I click on it.

**Comment by kuruk-mm** [comment]
Note: To make this works we need to send a timestamp on each `play`, and check in the renderer if the animation stopped playing.
