### ISSUE TITLE
[QA] 'Loading scene timeout' error is popping out after loading into events

### ISSUE THREAD

**Issue by kwsskulinski** [decentraland/unity-renderer#4392]
Description:

'Loading scene timeout' error pops out after loading into '2023 AMOREPACIFIC' and 'BCBGMAXAZRIA' events. Other events loaded without the error.

Reproduction rate: 
5/5
Steps to reproduce:    

1. Load into Decentraland.

2. Enter Events menu.

3. Load into '2023 AMOREPACIFIC'/'BCBGMAXAZRIA' event.

4. Observe the issue.
 
Results:    
Several loading scene timeout errors appear.
 
Expected results:
Scene is loaded with no errors.
 
Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot for reference.

![Timeout.jpg](https://images.zenhubusercontent.com/63bed9dceb9087129e33fd0a/9356816c-a672-4f07-91d7-70aace38a94b)

**Comment by m3taphysics** [comment]
@eordano could we get a definition of what we would expect to happen in this case?
