### ISSUE TITLE
[QA] Failure to load avatar face snapshot and wrong fallback image

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#4426]
Often (quite randomly but I suspect it happens more when there are plenty of users in a scene) you click on some avatar and the snapshot is shown as in the following screenshot:

![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/20db932d-6c58-431a-83e1-cb5e8fc6c04a)

Proposed steps:
- [ ] Fix the default avatar image (replace by a grey default profile icon)
- [ ] Clarify why the snapshots are failing to load so often
- [ ] Fix the root of the issue and/or make the client more robust to load failure (e.g. implementing retries?) 

------------------

Causes of this issue:
- [x] [Wrong profile announcement through comms](https://github.com/decentraland/unity-renderer/pull/5696)
- [ ] Weird/incorrect snapshots generated & stored in Catalyst profiles - [Slack thread](https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1695132203469979)
- [ ] Snapshots in profiles pointing to same empty image - [Slack thread](https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1695133549785459)
- [ ] Correct snapshots in profile are not rendered properly - [Slack thread](https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1695222552544669)

**Comment by lorux0** [comment]
I've been debugging and looks like the profile is sent with the wrong information. The face256 snapshot is a default avatar. Looks like its not a renderer issue, but kernel or catalysts:
![Screen Shot 2023-03-20 at 17.47.03.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/7014cc46-13cb-4a4b-9396-7081cdfcb99c)

**Comment by lorux0** [comment]
Continued further investigations. Making a request for a user, for example:
```
https://peer-wc1.decentraland.org/lambdas/profiles/0x3fbe902031290ff52bd449c3e32a75665d31ed3b?no-cache=0.9613263442949931
```
Returns the correct face256 information.
When renderer receives the update from kernel about the profile information, we get the data wrong:
![Screen Shot 2023-03-20 at 18.02.02.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/e96b89b5-1c23-450f-8bd6-f720620862c7)

So its gotta be something in kernel

**Comment by anicalbano** [comment]
![image.png](https://images.zenhubusercontent.com/64ad62442a830229041f8802/9973ad5f-5288-482b-bc8b-8107d89cb564)

**Comment by lorux0** [comment]
@moliva can you post your investigations in kernel?

**Comment by moliva** [comment]
> @moliva can you post your investigations in kernel?

Hey @lorux0 , you can check my findings [in this PR](https://github.com/decentraland/unity-renderer/pull/5696)

**Comment by anicalbano** [comment]
As for now, the snapshots can be seen correctly

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMURhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d556495f088f0f4d6b5330fa842278ce707c0ce5/15.11.2023_14.06.40_REC.mp4)
