### ISSUE TITLE
`openNFTDialog` info screen not showing info for L2 NFTs

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#443]
Looks like the NFT info screen doesn't show data for L2 NFTs

From the community:

Im using OpenNFTDialog to load the information about an opensea item in my scene. Its not showing the owner (shown as 0x000000...) and it says the PRICE is NOT FOR SALE, when they item is in fact for sale. Is there something i need to add to the OpenNFTDialog to make this show correctly?

```
openseaNFT1.addComponent(
  new OnPointerDown((e) => {
    openNFTDialog(
      "ethereum://0x495f947276749ce646f68ac8c248420045cb7b5e/5262891988546837561105015844193485043522642740109692523483004304804406099969",
    )
  })
)
```

from looking at other opensea sales, this appears to be a problem for all

Is the NFT minted on the Matic network or on Ethereum? I've encountered this issue with Matic NFTs listed on OpenSea

![image.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/3098fdc0-e58a-4697-afe6-bdec7a0542e1)

**Comment by olavra** [comment]
This may be related to this ticket:
https://github.com/decentraland/unity-renderer/issues/164

**Comment by pbosio** [comment]
I can confirm that his is a semi-fungable ERC1155 token.
So it's related to #164
