### ISSUE TITLE
Add frame time CPU and GPU measurements

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#4431]
### Description
In the project, there are multiple ways of reporting fps and frame time. We should standardize the approach and use ProfilerRecorder API instead of `LinealBufferFPSCounter` which provides not consistent results.
For supported platforms, it would be great to have GPU render time

### Acceptance Criteria
- [x] Update all places using fps and frame time (`FPSDisplay`, `PerformanceMetricsController`, `PerformanceMeterController`)
- [x] Add render time (`FPSDisplay`, `PerformanceMetricsController`, `PerformanceMeterController`)

### Notes
To keep the data compatible with the metrics we still need to send frame time in the same format in  WebInterface.PerformanceReportPayload (frame time is multiplied by 1000)

For collecting data we can use Unity API
```
cpuTimeRecorder = ProfilerRecorder.StartNew(ProfilerCategory.Internal, "Main Thread", 15);
gpuTimeRecorder = ProfilerRecorder.StartNew(ProfilerCategory.Internal, "Render Thread", 15);
```

We also have LinealBufferHiccupCounter that is using frame time to detect hiccups and to keep the compatibility we can feed it with the frame time, and no changes are needed.

**Comment by popuz** [comment]
helping resources on `ProfilerRecorder`
https://resources.unity.com/unitenow/onlinesessions/capturing-profiler-stats-at-runtime
https://docs.unity3d.com/ScriptReference/Unity.Profiling.ProfilerRecorder.html
https://docs.unity3d.com/Manual/ProfilerRendering.html

**Comment by popuz** [comment]
@aixaCode, this ProfilerRecorder has a lot of other stats we can be interested in. Apart of what listed in links 
https://docs.unity3d.com/Manual/profiler-markers.html
https://docs.unity3d.com/Manual/ProfilerRendering.html
https://docs.unity3d.com/Manual/profiler-virtual-texturing-module.html

there are also much more not documented (but possible to get with [ProfilerRecorderHandle.GetAvailable](https://docs.unity3d.com/ScriptReference/Unity.Profiling.LowLevel.Unsafe.ProfilerRecorderHandle.GetAvailable.html). In the [Unite video](https://resources.unity.com/unitenow/onlinesessions/capturing-profiler-stats-at-runtime) at 10min he printed the list of all of them. 

Probably we can create a spike to investigate which stats could be useful for us.
And second initiative would be to add our own ProfileMarkers to most critical parts of our code base ;)

**Comment by popuz** [comment]
by the way, @aixaCode, it seems that Render Thread is not working (WebGL and Desktop). It always gives 0 (you can check it on this [draft](https://github.com/decentraland/unity-renderer/pull/4574))

**Comment by popuz** [comment]
`Render Thread` works only in **Editor** while **Profiler** is recording... Seems we cannot integrate it in our metrics

**Comment by popuz** [comment]
this [Unity issue report](https://issuetracker.unity3d.com/issues/profilerrecorder-render-thread-statistic-reports-the-lastvalue-as-0-when-the-profiler-window-isnt-open) is directly related to the `Render Thread`. It was fixed in 2022.2.X. I will check if it was backported to 2021

**Comment by popuz** [comment]
As for GPU measures: 
- I tried also `ProfilerRecorder.StartNew(ProfilerCategory.Internal, "Gfx.PresentFrame");` and this one worked only in Development Build.
- I also tried enabling `FrameTimingStats` in build settings, and it also didn't work (as well as [FrameTimingManger](https://blog.unity.com/engine-platform/detecting-performance-bottlenecks-with-unity-frame-timing-manager))

So I would suggest wait until Unity 2022 LTS released and then use frame timing manager instead. As for now only CPU will come inside the PR

**Comment by popuz** [comment]
Also, I would like reference this good [forum thread](https://forum.unity.com/threads/getting-the-rendering-time-progromatically.906167/) here
