### ISSUE TITLE
Host the Installer on `.decentraland.org`

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4453]
Right now, the "download for windows" button redirects to the github installer. Under some circumstances (particularly when Github has been never visited, meaning, for 99% of users), the user is redirected to Github's page.

We should host the installer in the CDN to avoid this

![image.png](https://images.zenhubusercontent.com/5d8ba4376484360001b6f6df/c523f958-64ee-4d3d-8e8e-8a8bd6040420)

**Comment by aixaCode** [comment]
I think it depends on the browser and platform, on windows and chrome/brave it directly trigger the download from https://decentraland.org/download/. Can you give an example when does that happen to you?

**Comment by eordano** [comment]
@aixaCode I can reproduce this, on windows, with 100% reproducibility after clearing all my cookies and browsing data, on Edge and Chrome. On Firefox it doesn't happen.

https://images.zenhubusercontent.com/337227404/291b2038-465f-4623-87f0-eb1ce1c68923/simplescreenrecorder_2023_03_09_19_32_13.mp4
