### ISSUE TITLE
Artifacts showing when "loadingScreen" saga is disabled

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4460]
<img width="860" alt="20230226_171922" src="https://user-images.githubusercontent.com/42750/221566362-724f029c-fe5c-4022-b0a0-d39cfc805db8.png">

This looks like it could be fixed by:

* Ensuring the loading state is visible as soon as the Unity Renderer starts
* Moving back the Loading assets from addressables into the main build

**Comment by dalkia** [comment]
The original ticket was solved by adding the LoadingScreen back to Resources.

I took the opportunity to remove the feature-flag as well, so the LoadingScreenPlugin creates the view without having to wait for the flag configuration. Therefore, as soon as the renderer is created, the loading screen is present.

Further work should be done to complete the deprecation of the old loading screen

1. Integrate the preloading screen for desktop
2. Cleanup the ActivateRendering logic
