### ISSUE TITLE
Rick's labyrinth teleport crashes explorer

### ISSUE THREAD

**Issue by sicarul** [decentraland/unity-renderer#447]
Trying to teleport to "Rick's labyrinth" on genesis plaza crashes the client for me

Video: https://drive.google.com/file/d/1nE2S_tzG6QIAeMJywMeEw0cNu7u-x7c3/view?usp=sharing

I'm using Google Chrome 90.0.4430.93 on Manjaro with Kernel 5.10.32-1, with hardware acceleration enabled (Dell XPS 17 with i9 and RTX 2060)
It is using the intel GPU: ANGLE (Intel, Mesa Intel(R) UHD Graphics (CML GT2), OpenGL 4.6 (Core Profile) Mesa 21.0.3)

**Comment by BrianAmadori** [comment]
Coords: 25,-60

**Comment by olavra** [comment]
Can't reproduce
