### ISSUE TITLE
FMOD error code 10

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4488]
### Description
FMOD is returning an error code and spamming the console. This is likely due to a large number of sounds being created and some incorrect pooling within the FMOD library. We should review the way sounds are played within scenes and ensure scenes are prevented from causing these problems. Refer to ICE Poker: [Slack link](https://decentralandteam.slack.com/archives/CS8SCNYUV/p1676667804541719)

### A/C's
- [ ] Correctly handle audio-clips to ensure we do not run out of channels

**Comment by popuz** [comment]
can be also connected with [this issue](https://app.zenhub.com/workspaces/workstream-core-experience-63aaac346e1c8d00104586e8/issues/gh/decentraland/unity-renderer/4644)

**Comment by popuz** [comment]
Initial report was only reproducible in the Preview Environment (dcl cli), but also very rarely

**Comment by popuz** [comment]
- [doc](https://docs.unity3d.com/Manual/webgl-audio.html) how FMOD works in Unity WebGL
- [doc](https://docs.unity3d.com/Manual/ProfilerAudio.html) how to profile FMOD channels in Unity Profiler

**Comment by popuz** [comment]
- As I see in `Build Settings` -> `Player Settings` -> `Audio`, we have quite a high Max for such channels (`Max Virtual Voices`) = 512;
- Maybe in WebGL it can be caused  by Memory problems
