### ISSUE TITLE
Adding a button in-world to the Support system

### ISSUE THREAD

**Issue by Kaze-No-Kai** [decentraland/unity-renderer#4490]
### What happened?

Hi team,

As discussed we would like to add an option for users to reach out to our Support team in-world.
The suggested option is to include a button in the Settings / Help & Support.
The button title could be "Contact Support".
The design should be the same as for the Discord and FAQ, positioned above Discord (to be the first from the top)
Functuonallity, to redirect to Decentraland.org and to open the chat box directly in a small sized window as in the screenshot.
We could also create a new support.decentraland.org (may be we need Frami for this) or similar with only the intercom chat if possible to avoid the background of docs/marketplace being visible (not sure what would be the best option, may be we can chat about it).
As Lastraum would be building a similar button for the PX on the MVFW, may be we can use the code to avoid double work?

Let me know in case of any questions
Stoyan

### Steps to reproduce

N/A
<img width="1651" alt="Screenshot 2023-02-28 at 12 12 29" src="https://user-images.githubusercontent.com/117974851/221825907-050f9c6d-f0e9-44c8-8e60-e127ce445e2b.png">
<img width="612" alt="Screenshot 2023-02-28 at 12 15 50" src="https://user-images.githubusercontent.com/117974851/221825916-c290e74a-8c98-47bf-974d-042d32e0bdbf.png">

### Operating System

Mac OS X 13.2.1

### Wallet

Metamask

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro 10922MB

### RAM

16384MB

### Kernel Version

desktop-1.0.84207-20230227202521.commit-bc9219c

### Unity Version

desktop-1.0.84207-20230227202521.commit-bc9219c

### Realm

heimdallr

### NameTag

KazeNoKai

**Comment by dalkia** [comment]
Blocked until we have the chatbox in DCL homepage (more info [here](https://decentralandteam.slack.com/archives/C04HLT59NBZ/p1678288335722719))

**Comment by dalkia** [comment]
Figma design https://www.figma.com/file/P6mm2kRNslX6GWxDiorEQG/Settings-V2?node-id=1876%3A854&t=Me70LldT05dMqZRp-1

**Comment by m3taphysics** [comment]
intercom.decentraland.org

**Comment by 2fd** [comment]
https://github.com/decentraland/intercom-chat-page
