### ISSUE TITLE
No asset bundles detected with the new assetbundle cdn flow feature flag

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4508]
With the &ASSET_BUNDLES_DOMAIN=https://ab-cdn.decentraland.org&ENABLE_AB-NEW-CDN feature flag on on webGL no asset bundles are being detected in the world. Everything appears in red

**Comment by Kinerius** [comment]
Can I get more info about this?

In 0,0 I see all green with `/detectabs`

also, you only need `ENABLE_AB-NEW-CDN` parameter

**Comment by m3taphysics** [comment]
@eordano @kuruk-mm 

Can we close this or advise pato?
