### ISSUE TITLE
Change Island is interpreted as Realm Reconnection

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4513]
Related to: https://github.com/decentraland/unity-renderer/issues/4489

It looks like the catalyst decided to change my island, and the kernel interpreted it as a disconnection+reconnection.

The likely function responsible for this behavior is [handleCommsReconnectionInterval](https://github.com/decentraland/unity-renderer/blob/dev/browser-interface/packages/shared/comms/sagas.ts#L388).

<img width="521" alt="image" src="https://user-images.githubusercontent.com/42750/222294132-11373e74-0c5b-4c9c-88c5-bcc4db96330e.png">

Additionally, this triggers many profile fetches at once, probably hitting some query limit:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/42750/222294268-3bed495d-ba44-47e6-88c9-a5929183883d.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/42750/222294327-576ba610-8442-4129-b02b-bf51b338297c.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/42750/222294362-1e247d5c-d1d8-4df2-81e4-0907af74ea1b.png">

**Comment by xavi-dcl** [comment]
This is causing a lot of trouble during the event.

"I’m not being teleported to another space, but rather being constantly teleported to the spawn points in each space/scene"
"Anyone else having a chat issue? It just shows me changing realms over and over but I can’t get the actual chat to load fully (it shows it greyed out not in the chat box)--- on desktop client"

More details on the [issues tracker](https://docs.google.com/spreadsheets/d/1AttGJQli1cQJV1nLLNK1y2RJQP8b4VhQHz6NxX2ejjU/edit#gid=1672801883&range=B10) and on [Slack](https://decentralandteam.slack.com/archives/C04EBK18XS6/p1680043110531339)

![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/3766dbcd-e72f-402d-8077-b09c7ab86337)
