### ISSUE TITLE
[QA] Profiles of far away users not being loaded

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4529]
Description: 
Profiles of users that are far away are not being loaded. This results in being unable to send a friend request to such user by putting in their username in the Requests tab. Additionally the profiles of far away wallet users in the Channel members list are being shown as generic guest login profiles instead.
Exceptions when attempting to send a friend request:
![image](https://user-images.githubusercontent.com/110463715/225864522-ce58ffa5-a541-46fe-badb-cef7722ad8a4.png)
Exceptions when attempting to view another channel member's profile:
![image](https://user-images.githubusercontent.com/110463715/225864657-64778d63-1157-4d63-81c2-1118caad20a6.png)

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in using two wallet accounts on two far away parcels (for ex. one on 150,-150 and the other on -150,150.
2. Open up the Friends menu from taskbar end go to Requests tab. Use it to attempt to send a friend request to the other wallet. Notice that the other login did not receive the request.
3. Teleport to the parcel where the second user is located. Repeat the process with the Requests tab. Notice that this time request went through.
4. Open up the Chat menu on both accounts and Join the same channel.
5. Open up that channel's members list and view profiles of the other wallet login you used and various other members.
6. Observe the contents of the passport.

Results:    
Cannot send a friend request and view passport via a channel's members list of a wallet user that is far away.

Expected results: 
Far away users can be sent a friend request to and their passport can be viewed via the Channel's members list.

Notes:    
- Platforms: Windows, web and desktop, wallet login. 
- Issue occurs for both production and dev branches.
- Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/ff75a2d2-262d-4426-9e90-c4875fea3c2b/2023_03_03_13_52_56.mp4
https://images.zenhubusercontent.com/337227404/092ee6ae-0834-4187-8e9f-11ce91289c2b/2023_03_03_13_54_37.mp4

**Comment by xavi-dcl** [comment]
This was fixed by fixing or undoing the problem this PR introduced: https://github.com/decentraland/unity-renderer/pull/4312

@m3taphysics, can we close this? Let's make sure the code and dev/main branches are healthy with regards to this issue.
