### ISSUE TITLE
White screen when entering the world with new onboarding

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#4557]
When entering new onboarding, seems like fullscreen image is not loaded fast enough and appears as white sprite for a second.

Repro steps:
- Clear cache/or open browser in incognito mode
- Enter world as guest
- Wait for loading of new onboarding
- White screen appears for a second before full screen image

Expected Result:
- proper image should appear on start

![Screenshot_1090.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/a32b58e6-c2f4-4667-9024-52bb7c6cfb61)

**Comment by dalkia** [comment]
Duplicate #4629
