### ISSUE TITLE
Bug: Avatar doesn't load properly (ghost mode)

### ISSUE THREAD

**Issue by cyaiox** [decentraland/unity-renderer#4584]
## Bug report

When users try the `see in world` emotes for testing purposes, start having a strange behavior that doesn't load the avatar properly after a custom emote is equipped.

How to reproduce the error:
In the [builder app](https://builder.decentraland.org)
1. Create a new collection
2. Create a new emote
3. `See in world` the emote
4. Equip the emote in the wheel
5. Remove the `WITH_ITEMS` parameter and reload the page without it
6. Go to backpack and equip some wearable and click Done

https://user-images.githubusercontent.com/3170051/224065343-4e614e39-d7a4-47ac-b511-81b6fe7f1f59.mp4

* [ ] Provide a **minimal code snippet** / video example that reproduces the bug.
* [ ] Provide **screenshots** where appropriate
* [ ] Does this occur on chrome or firefox? `Chrome`
* [ ] Are you using Mac, Linux or Windows? `Mac`
* [ ] Are you using a VR headset? Which one? `None`

**Comment by Kinerius** [comment]
This can be easily be reproduced

The error is: `PromiseException: Emote from context not found in response: `

It seems that we are trying to load an emote that doesn't exist in the catalog and this causes the avatar to fail to load. We probably have to unequip the emote and set that emote slot to its default value.
