### ISSUE TITLE
Implement ability to search for a wearable (M2)

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#4587]
The new backpack includes a new functionality to search for an specific item by name.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/adcfef96-4cc3-4bac-872d-d839a9da8383)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/5727adb4-9230-47a7-bc61-f2d48a0d0abd)

**Acceptance Criteria**
- [ ] Input terms can be introduced in the search box
- [ ] After entering the search terms, the grid will be "loading" the results
- [ ] After search, the search box will be emptied
- [ ] A new label will be created in the breadcrumbs with the search prompt and the number of results
- [ ] Clicking on this label will remove the search
- [ ] If there are no results with that search, the empty grid will appear
- [ ] Search results will be affected by other toggles and selectable in the filters bar

[Documentation](https://www.notion.so/decentraland/PRD-Backpack-V2-13fd81cca29a45a180af6b73c2ca49b5?pvs=4#d7a2c0f8512248f09dcc21ead6d646e7)
[Figma](https://www.figma.com/file/ZU7m0Tiizgef5X6VoIEzWV/%F0%9F%97%BA%EF%B8%8F-Backpack-2.0-%7C-Explorer-%7C-03%2F23?node-id=7-1126&t=Ai9n9VJ89KdhDdrQ-0)

**Comment by moliva** [comment]
Done.
