### ISSUE TITLE
Adapt color picker tool in backpack (M1)

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#4589]
The colour selector will remain the same to the current production version: a dropdown menu accessible from each of the categories that allow you to edit this variable. We need to re-adapt the UI a bit: not the droptdown but the button to open it.

![Screenshot 2023-04-17 at 11.16.36.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/bdf18488-71f4-4423-988a-74cfd1516093)

**Acceptance Criteria**
- [x] Categories with color picker will show the dropdown button next the category title.
- [x] The arrow changes its vertical position depending if the dropdown is opened or not.
- [x] Colours, presets and ability to customise should be procedurally generated from a hardcoded dictionary to support future avatars. 
- [x] Changes in the colour will be applied directly to the avatar and color preview in the picker button as the sliders move.

[Documentation](https://www.notion.so/decentraland/PRD-Backpack-V2-13fd81cca29a45a180af6b73c2ca49b5?pvs=4#5262ce3f523c4d8e9fcd1e2c8c323caa)
[Figma](https://www.figma.com/file/ZU7m0Tiizgef5X6VoIEzWV/%F0%9F%97%BA%EF%B8%8F-Backpack-2.0-%7C-Explorer-%7C-04%2F23?node-id=301%3A33334&t=IahFBCJcSBUP3h38-1)

**Comment by RominaMarchetti** [comment]
@sandrade-dcl should we close this task considering we decided to stick with the version live in production of the color picker?

**Comment by sandrade-dcl** [comment]
@RominaMarchetti we're going to keep this task but we will modify it in order to contemplate the integration of the old color picker logic in the new Backpack. Thanks!
