### ISSUE TITLE
Implement analytics for Quests V1

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#459]
- [x] Quest discovered
- [x] Quest completed
- [x] Task complete
- [x] Task progress
- [x] Rewards obtained
- [x] Quest Panel time opened
- [x] Unpinned/ Pinned Quests
- [x] Jump In button
- [x] Shortcut vs Button of Quest
- [ ] ~Quest lifetime~

- [ ] Design panels in Metabase to diplay this information and create funnels

**Comment by AjimenezDCL** [comment]
Unless I'm missing something, `Quest lifetime` can be tracked through the rest of quests events.
