### ISSUE TITLE
Implement new oufits section in the backpack (M3)

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#4590]
The new section of the backpack allow players to store their current outfit and wear it later.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/7a5dcb29-7944-44e5-8c8c-5d560db6b9d8)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/10faca9a-671f-4d7f-aa4f-fe023759c7d7)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/885bc90c-e8d2-4725-9450-a6a764312bec)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/a6b45731-d66d-4386-a46e-e0c453e05681)

**Acceptance Criteria**
- [ ] Outfits section is accessed thought the outfits icon
- [ ] This section will be rendered on top of the grid
- [ ] Players can save up to 5 slots for free
- [ ] Empty slots will show a random silhouette from a collection
- [ ] Clicking on an empty slot, it will save the current configuration of the avatar.
- [ ] While saving, the UI won't be interactable
- [ ] Each outfit stored will display the avatar with that configuration
- [ ] Saved outfits needs to be available everywhere independently of the device
- [ ] Clicking on equip on an outfit, will equip all wearables (if still available), and color choices
- [ ] Clicking on the close icon of an existing outfit will prompt a confirmation dialog to delete it
- [ ] For each NAME the player has, it will show a new Slot
- [ ] After the last NAME slot, a "buy slot" card will appear. This will take the players to the builder in the NAME section
- [ ] Clicking on Back will take players to the grid of items
- [ ] Implement cool and nice effects on mouse hover, clicking, saving and fancy things :)

[Documentation](https://www.notion.so/decentraland/PRD-Backpack-V2-13fd81cca29a45a180af6b73c2ca49b5?pvs=4#5c2e1a212ea343b7a8aab22883d937e0)
[Figma](https://www.figma.com/file/ZU7m0Tiizgef5X6VoIEzWV/%F0%9F%97%BA%EF%B8%8F-Backpack-2.0-%7C-Explorer-%7C-03%2F23?node-id=7-1126&t=Ai9n9VJ89KdhDdrQ-0)

**Comment by sandrade-dcl** [comment]
### Technical requirements (pending to discuss)
- [ ] Create / Edit outfit
- [ ] Equip outfit
- [ ] Delete outfit
- [ ] Manage extra slots
- [ ] Manage outfits images
