### ISSUE TITLE
Error while pressing "enter as guest" as soon as website loads

### ISSUE THREAD

**Issue by pbosio** [decentraland/unity-renderer#461]
It seems that "enter as guest" is enabled before unity is loaded
So pressing it too fast result in an error that has nothing to do with what is really happening (something about adblocker)

steps to reproduce:
-disable metamask
-open play.decentraland.zone
-press on "enter as guest" as soon as possible

![Screen Shot 2021-05-18 at 18.59.14.png](https://images.zenhubusercontent.com/5d91fc4041d63100014d4ee5/573ca278-98e0-454e-ad24-6cdc92dc8861)

**Comment by olavra** [comment]
Fixed by @menduz in this PR
https://github.com/decentraland/explorer/pull/2382
