### ISSUE TITLE
Fix bad user experience on Login screen

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#4631]
As a returning user, I often land into the login screen in this state:
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/c3d764dc-c5d1-48d3-91dd-562b2fdfd86b)

I am presented with two options (play with wallet or as a Guest) but the first one is auto-selected and the whole UI is waiting for me to sign the login on Metamask. As a user, understanding what is going on here is not straightforward,

If we auto-select playing with Wallet, we should make that part of the UI full screen, like:
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/bb8573f6-5801-489c-b917-8d2886bed365)

Then if the user wants to log out of that wallet / play as Guest, they can hit the CANCEL button. Overall, way less confusing.

**Comment by aixaCode** [comment]
Closing, not part of the scope
