### ISSUE TITLE
Mentions UI-UX fixes

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#4739]
### **Remember to use [Figma](https://www.figma.com/file/SxxomcIZI1zyytMZmFJAvS/Private-Channels?node-id=4305%3A27258&t=aB62O699l09jg2yu-1) and [Notion](https://www.notion.so/decentraland/PRD-Chat-Mentions-ffd23437a8c34cddadc401fabd7f5139?pvs=4) as source of truth.**

- [ ] Show the spinner while searching matches for mentions.
![Screenshot 2023-03-24 at 09.50.23.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/769595d3-abac-42b1-bab0-96490c9bf661)

- [ ] If there are no matches please show the message `No results found :( `
![Screenshot 2023-03-24 at 10.08.50.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/aed59b5a-90fb-44aa-8d32-bbac495ce77c)

- [ ] The color of the mention icon must be #43A5FF in the notification panel.![Screenshot 2023-03-24 at 09.55.54.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/7add4da1-c8c2-4106-9965-dacb02be3019)

- [ ] The mask of the avatars, stroke (color #DADADA), and background (color #FFFFFF) of the avatars snapshots are missing. 

- [ ] Replace the names font style to Semi-Bold style. Don't use regular.
![Screenshot 2023-03-24 at 09.50.41.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/5227f27d-cce6-465c-9227-c3886d73af01)

- [ ] Don't show my own name in the suggestions of players to mention.

**Comment by aixaCode** [comment]
Closing, not part of the scope
