### ISSUE TITLE
Tutorial Robot is not disabled

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4741]
### Description
The tutorial robot Alice isn't disabled after the tutorial has finished.

![image.png](https://images.zenhubusercontent.com/63566805658b35a37eaf393c/fdcf23b4-0b5a-49e0-a92a-efb758b4bade)

### Deliverables
- [ ] Disable Alice :(

**Comment by m3taphysics** [comment]
Do we want to completely disable this tutorial now we have the new onboarding?

**Comment by louiseDecentraland** [comment]
The onboarding experience only applies to users who enter via play.decentraland.org. It is important that we keep the Alice tutorial for those users who enter via deep links. We do not show the onboarding to deep link users as we believe they want to quickly get to the content they are linked to, and creators would prefer users to directly enter their scene (e.g. get to ICE Poker as quickly as possible).

I'm not sure what this ticket is about, but the cases are as follows:

New user enters via play.decentraland.org
- Get the new onboarding experience
- Do not see the Alice tutorial

New user enters via deep link
- Do not get the new onboarding experience
- See the Alice tutorial

Returning user enters via play.decentraland.org or deep link
- Do not see the onboarding experience
- Do not see the Alice tutorial
