### ISSUE TITLE
AB converter issue with external textures

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#4745]
There is an issue apparently only with textures that are not embedded in the GLTF asset.

A texture that should look like this:
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/21e2e855-7f67-4ab1-85cb-9a1383def3ff)

AB converter downloads it like this:
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/d7f7e7a9-fefe-4605-8619-9e6519d9b566)

As a result, transparency of the object is lost in-world.

There is a workaround: leave the texture embedded in the GLTF. But then performance is lower. External texture performs better because it can be shared across different models.

**Comment by AjimenezDCL** [comment]
We are not fixing this. The old AB converter is gonna be deprecated.

We fixed an edge case so textures in the max size threshold wouldnt be resized, but that's it.
