### ISSUE TITLE
PlayerLoop has been called recursively causing freeze

### ISSUE THREAD

**Issue by aixaCode** [decentraland/unity-renderer#4762]
### Description
At random occasions, mostly related to loading scenes or avatars whole game freezes and reload is needed
During that time browser is responsible and this error appears in the console:
![Screenshot 2023-03-27 at 17.30.09.png](https://images.zenhubusercontent.com/62a72d26a0aaf429ea6ec817/5df25f35-6a70-4cd5-a3e9-cefa213df4f6)

This is only occurring on WebGL

**Comment by dalkia** [comment]
When it happened to me, it came along this error
![image (1).png](https://images.zenhubusercontent.com/62a9e908660cd151471c312d/1695cc23-0348-4716-88db-bfcfc3819876)
