### ISSUE TITLE
Fix the FPS Cap setting for non-web platforms

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#478]
The FPS Cap setting we have in the Explorer is only working for the web build, as it doesn't use the [`Application.targetFramerate`](https://docs.unity3d.com/ScriptReference/Application-targetFrameRate.html), and that's OK because for the web we need more control and that setting alone is no good, but we need to filter based on the platform and use that for non-webGL Unity deployments.

**Comment by Kinerius** [comment]
This issue is being solved here https://github.com/decentraland/unity-renderer/issues/1507
Closing to avoid duplicates
