### ISSUE TITLE
Roland scene: images not part of scene shown on Web

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#4789]
On web, the Roland scene is showing an image that is not part of the scene. On Desktop images are correct.

Reported here: https://decentralandteam.slack.com/archives/C04EBK18XS6/p1680021756993429

### Incorrect images
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/546ea116-e624-420c-a5df-968d9e4f9dd6) 
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/675b37de-a6b5-424c-a6d5-1d08b1386d49)
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/bf0f41bf-5de6-4dbd-b4ad-50b592f9a3bc)
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/26d2db8a-fd5e-440c-af2d-6ad3adb216fb)

### Correct images
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/636731f9-7a8a-4cc6-b0a3-3d8853c69a0a)
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/3ab072cd-f6bc-4777-82c5-0534f4989623)

**Comment by kwssbocian** [comment]
Cannot reproduce. On all platforms appropriate images belonging to the scene are shown within the frames.
