### ISSUE TITLE
Invisible objects in the scenes

### ISSUE THREAD

**Issue by xavi-dcl** [decentraland/unity-renderer#4813]
Will and Esteban reported on [Slack](https://decentralandteam.slack.com/archives/C04EBK18XS6/p1680108728296469) that they often encounter invisible items in the scenes.

One example:
![image.png](https://images.zenhubusercontent.com/636b99a62654f2e351ceea55/5931c17b-617c-4f8f-a8e5-2aa27130f751)
"that is the plaza road, one of the wearable tubes, just never loaded but the hover text still shows "claim wearable".  this reminds me of the issues we had for Festival.  things would just never load but their colliders were still there"

**Comment by 0xD-Fabio** [comment]
I wasn´t able to reproduce the bug on any platform.

**Comment by m3taphysics** [comment]
Moving to the backlog while we investigate better streaming solutions
