### ISSUE TITLE
Enable Depth Priming

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#4824]
### Description
SSAO has
negligible overhead in a deferred renderer, but in forward rendering it requires a depth prepass to calculate
the normals of the scene geometry. This prepass can be a very expensive operation considering the large
amount of geometry that is being rendered in the game. The depth information created by the depth
prepass can be used by the main camera’s opaque rendering pass to discard any fragments which will be
hidden by geometry, which would amortize the cost of the depth prepass by reducing the costs of the
opaque pass. This is called Depth Priming and can be enabled in the URP settings asset

### Deliverables
- [ ] Enable depth priming to Auto

### Notes
See Unity review: https://drive.google.com/file/d/1hob-9c4MCTZRFKMGj9bMcQTAQyQL8lq7/view

**Comment by dalkia** [comment]
Sent a [support ticket](https://support.unity.com/hc/en-us/requests/1528940) to Unity looking for possible workarounds

**Comment by eordano** [comment]
@m3taphysics what do you think about disabling SSAO? Community members have pointed out that the benefits are negligible

**Comment by m3taphysics** [comment]
- Disable SSAO by default for web

**Comment by dalkia** [comment]
Currently not compatible with our `DCL/Universal Render Pipeline/Unlit` and `DCL/Unlit Cutout Tinted` (This last one gets fixed if the render queue is moved to the opaque values; but the extent of changing this value has not been analyzed)

**Comment by dalkia** [comment]
Currently not compatible with our `DCL/Universal Render Pipeline/Unlit` and `DCL/Unlit Cutout Tinted` (This last one gets fixed if the render queue is moved to the opaque values; but the extent of changing this value has not been analyzed)
