### ISSUE TITLE
AvatarSwap gets stuck - WORLDs

### ISSUE THREAD

**Issue by Kaze-No-Kai** [decentraland/unity-renderer#4844]
Hi team,

Nikki Fuego shared that her team expierenced that AvatarSwap sometimes get stuck in WOLRDs.
They use the browser version.

Let me know what information you need so i can check with her.

**Comment by xavi-dcl** [comment]
Yes, we need the usual, including a better description, steps to reproduce and ideally some links, screenshots or video.

**Comment by Kaze-No-Kai** [comment]
Will check with Nikki

**Comment by Kaze-No-Kai** [comment]
no info from Nikki, closing
