### ISSUE TITLE
Marketplace tab open - the stream freezes in WORLDs

### ISSUE THREAD

**Issue by Kaze-No-Kai** [decentraland/unity-renderer#4845]
Nikki Fuego shared that If you have a marketplace tab open while in a worlds server that has a stream, the stream freezes until you close the marketplace tab.

let me know what information you may need for this one.

Stoyan

**Comment by xavi-dcl** [comment]
Need more details, video or repro steps...

**Comment by Kaze-No-Kai** [comment]
no info from Nikki, closing
