### ISSUE TITLE
Different set of wearables equipped in WORLDs than in Genesis city

### ISSUE THREAD

**Issue by Kaze-No-Kai** [decentraland/unity-renderer#4846]
Hi Team,

Nikki Fuego shared that sometimes when she loads into worlds, she has a different set of wearables equipped than she do in genesis. As well as sometimes a different NAME is equipped (this is the case with client too).

Let me know if any informaiton is needed from her.

Stoyan

**Comment by xavi-dcl** [comment]
Would appreciate more information. A video would be ideal, otherwise at least more detailed repro steps, user wallet address and world URL could also help. Thanks.

**Comment by xavi-dcl** [comment]
May be related to #4758 (Incorrect profile state)

**Comment by Kaze-No-Kai** [comment]
Will check with Nikki

**Comment by Kaze-No-Kai** [comment]
no info from Nikki, closing
