### ISSUE TITLE
[QA] Map tile info missing when viewing from worlds

### ISSUE THREAD

**Issue by kwsskulinski** [decentraland/unity-renderer#4858]
Description:

Map title is missing from the card in worlds. Only the 'Untitled Scene' is shown at every scene.

Reproduction rate: 

5/5

Steps to reproduce:    

1. Launch DCL.
2. Enter any world (/world menduz.dcl.eth).
3. Open the map.
4. Observe the issue. 
 
Results:    
Every scene has 'Untitled Scene' title in the card.
 
Expected results:
Every scene has its own name in the card.
 
Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for production and dev branches.
- Please see the attached screenshot for reference.
![UntitledScene.jpg](https://images.zenhubusercontent.com/63bed9dceb9087129e33fd0a/be594ef8-da2e-4aab-8741-b2ceb525e0d4)

Same issue with other steps:
1. Launch DCL.
2. Enter any world (/world ile.dcl.eth).
3. Then go back Home.
4. Open the map and you will see  
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/35e8ecc3-ec2f-419d-b7de-5b53e882be2b)

**Comment by xavi-dcl** [comment]
#4842 should close this
