### ISSUE TITLE
[QA] Cannot highlight own avatar

### ISSUE THREAD

**Issue by kwsskulinski** [decentraland/unity-renderer#4859]
Description:

Player is not able to highlight their own avatar. Other avatars can be highlighted.

Reproduction rate: 

5/5

Steps to reproduce:    

1. Launch DCL.
2. Login into the Genesis Plaza.
3. Hover the mouse over your character.
4. Observe the issue.
 
Results:    
The highlight does not appear.
 
Expected results:
Highlight appears over the character.
 
Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs on production.

**Comment by m3taphysics** [comment]
This is a feature, not a bug :)
