### ISSUE TITLE
Integrate headless chromium for Explorer Desktop

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#486]
In order to run the kernel and all its web dependencies in the Desktop build of the Explorer, it's required to integrate a headless chromium browser.
https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md

Acceptance criteria:
- [ ] Explored desktop build (for all OS) runs the kernel using headless chromium
- [ ] Explorer Desktop build can use a execution parameter to launch the application using the browser. (ie: decentraland.exe --debug)
- [ ] Developers will also be able to run the headless chromium while coding in WSSController

**Comment by kuruk-mm** [comment]
Blocked by #585

**Comment by kuruk-mm** [comment]
Puppeteer Sharp requires C# 9 from .NET 5. So maybe it will be discarded.

Chromium Headless now it's working, maybe it's related to the bug from the workers that we have. I'm investigating this.

**Comment by kuruk-mm** [comment]
We changed our plan. We're going to try to use NodeJS instead of Chromium Headless.

**Comment by olavra** [comment]
We changed our plan. We're going to try to use NodeJS instead of Chromium Headless.
