### ISSUE TITLE
Faceless avatar for user personal avatar

### ISSUE THREAD

**Issue by popuz** [decentraland/unity-renderer#4863]
## Description
Some face features are glitching on the face. Mainly this issue seen with spiral eyes, but also normal face features looks not normal. 
- zooming to the face helps to fix it.
- reproducible in `/changerealm offline` mode
- reproducible in Ultra quality settings
- issue easier to spot on Web, than on Desktop

### Note
This feature is different from the LOD problem fixed [here](https://app.zenhub.com/workspaces/workstream-core-experience-63aaac346e1c8d00104586e8/issues/gh/decentraland/unity-renderer/4152). There main difference is that it is occurring on the user personal avatar/character and not other players, and it is possible to reproduce it in the `offline` realm

## Referneces
In the screenshots you can see how it behaves for different face features and with the different zoom to the face
![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/83b7e257-6373-4a59-9281-4fbdadb66fe2)![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/572a3e47-7761-480e-9710-48d2f47f2fa9)![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/dbfebdfb-2d73-4cf5-95d6-1e92c975883f)![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/fedf8f0e-5925-4f9e-8b1e-cb9a791125f4)![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/34e99901-d584-4077-9fea-ed515e0be095)![image.png](https://images.zenhubusercontent.com/631628793fb7f60ae36ae984/99b3955f-58bd-4070-a03d-4492599ea3b2)

**Comment by Juliendcl** [comment]
Tested with the browser version, simply log in everywhere and check your avatar from different angles. Some eyes/mouth look better than others, but in general the avatar is faceless if we don't zoom too close. It looks better on the desktop version although some textures are still missing![Faceless Avatar 1.PNG](https://images.zenhubusercontent.com/63cfbeca93b308235855e8c3/9fbaf3f9-0fa3-48dc-ab53-5a2a62c7e6b9)![Faceless Avatar 2.PNG](https://images.zenhubusercontent.com/63cfbeca93b308235855e8c3/67eaa0c1-9c30-4d77-a829-ab4cb771be88)![Faceless Avatar 3.PNG](https://images.zenhubusercontent.com/63cfbeca93b308235855e8c3/3f43cde9-c9be-457b-a302-6ea5389d7c19)![Faceless Avatar 4.PNG](https://images.zenhubusercontent.com/63cfbeca93b308235855e8c3/acc73b19-2619-440d-8d21-9ad24d91096b)![Faceless Avatar 5.PNG](https://images.zenhubusercontent.com/63cfbeca93b308235855e8c3/850c4f1c-c206-4934-a60a-93d7d8b0867d)!![Faceless Avatar 6.PNG](https://images.zenhubusercontent.com/63cfbeca93b308235855e8c3/711a0213-f8f1-433e-8e16-e8ab4daac8e0)

**Comment by m3taphysics** [comment]
Is this simply the mipmaps?

**Comment by aixaCode** [comment]
Closing, not part of the scope
