### ISSUE TITLE
E&F action keys overlaps with chat

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#4871]
Sdk inputs are getting triggered when they type E or F in chat while the UI is open.

![image.png](https://images.zenhubusercontent.com/615af652539a0a743b87eaaa/001cb25b-bcc2-4b78-bafc-e6ccdcb6ced5)

Acceptance criteria:

- [ ] If the chat is open, dont trigger sdk action keys

**Comment by dalkia** [comment]
Didnt have luck reproducing it. I tried two different version, when the window appeared with chat on and off. And in both cases, the chat blocked the SDK function correctly. 

Chat off
https://images.zenhubusercontent.com/337227404/29df0109-02c1-45b8-8fa6-74d9bdb00bf7/openingwindowwhilechatoff_lq.mov

Chat On
https://images.zenhubusercontent.com/337227404/7a240372-09b0-41a8-ad4e-d01f630514ce/openingwindowwhilechaton_lq.mov

**Comment by xavi-dcl** [comment]
Adding comment from Spicy Prawn: "It's dependent on using "enter" to type into the chat box. When using "enter" to open the chat box the inputs will count for the hot keys. If I select the chat box by clicking it does not effect the hot keys."

**Comment by Juliendcl** [comment]
Spicry Prawn provided us with some extra videos and details for repro. 

They tried different scenes, resolution settings, etc and could not repro the issue.
However they were able to reproduce the issue once  they closed the console logs. 
Quote: 
```
"After this I was able to reproduce (around 0:50 in the 1st video - colosseum)
Upon further testing (After 1:00 in the 2nd video - stronghold) it seems potentially related to where my curser is or moving it in general. I had more luck reproducing it if it was highlighting another user (without clicking) or maybe something else in the scene. This was still somewhat inconsistent.
"
```

https://decentralgames.slack.com/files/U0295EE4S3C/F05948W7355/hotkey1.mov
https://decentralgames.slack.com/files/U0295EE4S3C/F059FSW379B/hotkey2.mov

**Comment by popuz** [comment]
I found some stable repro steps without opening console. Main point here 
1. Lock cursor with left-mouse button (permanent mouse lock)
2. Press Enter to open the chat with locked mouse state
3. type E or F in the chat 
4. **Result:** it will trigger UI button press
