### ISSUE TITLE
Implement wearable's details modal popup (M2)

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#4880]
The descriptions (and future extended meta information) of a wearable might be too big to show in the information tab. In this case, a View More button will allow you to expand this container, overlaying the rest of the elements in the grid. The rest of the screen will be darkened, and will be locked, until the user clicks on the close icon at the top right of the tab or outside the card.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/c3878edf-dfa9-492d-af27-66312f7a2036)

[Documentation](https://www.notion.so/decentraland/PRD-Backpack-V2-13fd81cca29a45a180af6b73c2ca49b5?pvs=4#b4df8b0534814cc199c8eb4690d8df0a)
[Figma](https://www.figma.com/file/ZU7m0Tiizgef5X6VoIEzWV/%F0%9F%97%BA%EF%B8%8F-Backpack-2.0-%7C-Explorer-%7C-03%2F23?node-id=7-1126&t=Ai9n9VJ89KdhDdrQ-0)

**Comment by aixaCode** [comment]
Closing, moved as part of shape up.
