### ISSUE TITLE
Implement "NEW" label for new NFTs (M1)

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#4883]
If an item has been obtained in the last 24 hours, the label “New” will appear on top of the item preview.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/593b5240-35e2-4713-82e7-d9cca0b4f009)

[Documentation](https://www.notion.so/decentraland/PRD-Backpack-V2-13fd81cca29a45a180af6b73c2ca49b5?pvs=4#e54158cca37c4457b08c1db85ae9554f)
[Figma](https://www.figma.com/file/ZU7m0Tiizgef5X6VoIEzWV/%F0%9F%97%BA%EF%B8%8F-Backpack-2.0-%7C-Explorer-%7C-03%2F23?node-id=7-1126&t=Ai9n9VJ89KdhDdrQ-0)

**Comment by lorux0** [comment]
We need to add the `transferredAt` field to our current wearable/emote DTOs to be able to solve this information
