### ISSUE TITLE
3D View for New Info card for selected items in the grid (M1)

### ISSUE THREAD

**Issue by lorux0** [decentraland/unity-renderer#4889]
When an item is selected in the grid, it will display the information in the new info card

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/eefd3b7e-54a7-490a-ae14-8c69c57d9055)

**Acceptance Criteria**
- [ ] The wearable preview shows the 2D version, while loading.
- [ ] After loading the wearable, it will be displayed spinning slowly.
- [ ] Transition between 2D and 3D version should be smooth
- [ ] Clicking and dragging on 3D view of the wearable, rotate it in any axis

[Documentation](https://www.notion.so/decentraland/PRD-Backpack-V2-13fd81cca29a45a180af6b73c2ca49b5?pvs=4#d845d2f952524dee8e20412f52b78207)
[Figma](https://www.figma.com/file/ZU7m0Tiizgef5X6VoIEzWV/%F0%9F%97%BA%EF%B8%8F-Backpack-2.0-%7C-Explorer-%7C-03%2F23?node-id=7-1126&t=Ai9n9VJ89KdhDdrQ-0)

**Comment by lorux0** [comment]
The main concern is the possibility of loading and displaying the wearable independently from an avatar. The second part is to be able to render it accordingly to the visual quality requirements.

**Comment by aixaCode** [comment]
Closing, moved as part of shape up.
