### ISSUE TITLE
[QA] Crash on first login via fresh guest on Desktop

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4897]
Description: 
On dev branch and various other PR branches that are then merged into dev have their desktop build produce a crash every time on a first guest login attempt after the local files are removed. After clicking Reload button on the crash screen guest login can then proceed without further problems. Issue cannot be reproduced on prod.

Reproduction rate: 
5/5 

Steps to reproduce:
0. Ensure that the explorer-desktop-launcher directory in your %appdata% (on Windows) has been deleted.
1. Launch the desktop client using the following link: `https://renderer-artifacts.decentraland.org/desktop/index.html?dcl://DESKTOP-BRANCH=dev&DESKTOP-DEVELOPER-MODE`. Tick the box next to custom-url and in the text field below it put in `http://play.decentraland.zone`. After that press Start.
2. Choose the guest login option. 
3. In the DevTools window press the button to resume script execution.
4. Notice that the client window contains a crash message.
5. Press reload and log in via guest again.
6. Observe the client window.

Results:    
On first launch after clearing local files guest login always produces a crash.

Expected results: 
Logging in as guest after clearing local files proceeds normally.

Notes:    
- Platforms: Windows, desktop, guest login. 
- Issue occurs for the dev branch and feature branches that are being merged into dev.
- Please see the attached screenshot and video for reference.
![image.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/2418ed2a-81e1-488f-a8d8-a7926e49f644)
https://images.zenhubusercontent.com/337227404/f06f0e0b-2c05-4767-839f-b14125491f6e/2023_04_06_12_51_01.mp4

**Comment by m3taphysics** [comment]
- Delete local storage folder

**Comment by popuz** [comment]
It could be that it is reproducible only on Win 10 machine

**Comment by 0xD-Fabio** [comment]
I couldn't reproduce it in Windows 11

**Comment by m3taphysics** [comment]
Only reproducible on a windows 10 machine

**Comment by 2fd** [comment]
https://decentraland.sentry.io/issues/?query=is%3Aunresolved+Renderer+unexpected+exit&referrer=issue-list&statsPeriod=14d

**Comment by dalkia** [comment]
On a Windows 10 machine, using this [link](https://renderer-artifacts.decentraland.org/desktop/index.html?dcl://DESKTOP-BRANCH=fix/getting-active-scenes-from-world-context&DESKTOP-DEVELOPER-MODE)

- Could not reproduce the issue on a fresh install
- Could not reproduce by deleting `LocalStorage `folder 
- Could not reproduce either with Wallet or Guest

**Comment by kwssbocian** [comment]
As of today the issue no longer reproduces on Win10 by deleting `explorer-desktop-launcher` directory in AppData or by completely reinstalling the desktop client, despite multiple attempts.
