### ISSUE TITLE
Update UI Canvas in Batches

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#4900]
A significant part of the frame time is currently being taken up by UI Canvas updates. While costing 2 ms on average, it can spike up to 17 ms on certain frames (Figure 4). Many canvases have Animator components attached to them or their children, which will lead to them being marked as dirty every frame, causing layout batches to be rebuilt. This can be seen as a UGUI.Rendering.UpdateBatches marker in the Unity profiler. If possible, we recommend the team replace simple animations with tweeners or utilize the legacy animation system and manually control animation evaluation.

It is recommended to break the UI down into several sub-Canvases to reduce the amount of batch update work each frame. Consider creating a Canvas for static graphical elements that never change and another for dynamic graphical elements that change every frame or often (animated elements, timers, etc).

![image](https://user-images.githubusercontent.com/42750/230393121-99eedffe-95c8-4ad1-9abe-a6ef8e71e9c2.png)

**Comment by aixaCode** [comment]
Closing, not part of the scope for the time being.
