### ISSUE TITLE
Ghost avatars/ avatars not loading

### ISSUE THREAD

**Issue by Kaze-No-Kai** [decentraland/unity-renderer#4909]
Hi Team, as reported by PB/Nikki Fuego and another user, they are noticing ghost avatars/avatars not loading in some scenes with a lot of users. The example scene provided by Nikki is Ice Poker. Seems to be more related to the browser version.

Thanks in advance,
Stoyan
![image (1)](https://user-images.githubusercontent.com/11797485
![image](https://user-images.githubusercontent.com/117974851/230561413-03dd3863-fb7f-4ce4-bcd4-6e6716c8f980.png)
1/230561381-a9a2fd9d-8e64-4b8d-b5a2-022225e312a6.png)
![image (2)](https://user-images.githubusercontent.com/117974851/230561400-79cfa931-58cf-47f2-94fd-0b127baee92a.png)

**Comment by xavi-dcl** [comment]
@dalkia is this still an issue? Reported after closing #4584.

**Comment by dalkia** [comment]
@xavi-dcl not related to #4584 . That was an issue ocurring in the builder
