### ISSUE TITLE
[QA] Heavy stuttering on webGL client

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#4912]
Description: 
Currently on the dev branch a significant amount of frame stuttering is observable at all times on webGL client. Issue appears to occur regardless of graphical settings, current location, realm population or wearable choice.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in using two guest accounts with the same wearables chosen - one on the dev branch using the link `https://play.decentraland.zone` and the other on prod using the link `https://play.decentraland.org`. 
2. On both accounts open up the Explore menu and in the top left corner go to the realm options and change the realm to one that is the least populated.
3. On both accounts close the menu then walk around the area a bit. Notice the stuttering occurring on the dev branch login.
open up chat window and type in `/showfps` command.
4. Notice the difference in hiccups, hiccup loss and bad frames percentile between the dev and prod login. For the dev login it is much higher.

Results:    
Stuttering occurs when logged in on the dev branch.

Expected results: 
No frame stuttering occurs when logged in on the prod branch.

Notes:    
- Platforms: Windows, web, wallet and guest login. 
- Issue occurs for the dev branch.
- Please see the attached screenshot and video for reference.
![image.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/1626709e-f94d-4d2a-8a5e-371afbde9324)
https://images.zenhubusercontent.com/337227404/9f72b7b2-ffef-4eda-9baa-4b3e359c8483/2023_04_07_15_06_39.mp4

**Comment by m3taphysics** [comment]
![image.png](https://images.zenhubusercontent.com/63566805658b35a37eaf393c/466bf513-adf4-416f-8290-9ee68b9e9189)
