### ISSUE TITLE
Implement new EMOTES section (M4)

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#4921]
The new backpack (emotes section) is a completely different UI that before and will require a new basic layout that adapts to the screen resolutions and holds all the different components

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/e7100f94-11a9-4d87-aeff-3c794143ce95)

**Acceptance Criteria**
- [ ] Implement the new EMOTES section.
- [ ] The layout should be adapted to different screen sizes, always keeping a minimum horizontal and vertical proportion for 16:9

[Documentation](https://www.notion.so/decentraland/PRD-Backpack-V2-13fd81cca29a45a180af6b73c2ca49b5?pvs=4#fa710b46bded481eac16b3b7fbcd5523)
[Figma](https://www.figma.com/file/ZU7m0Tiizgef5X6VoIEzWV/%F0%9F%97%BA%EF%B8%8F-Backpack-2.0-%7C-Explorer-%7C-03%2F23?node-id=7-1126&t=Ai9n9VJ89KdhDdrQ-0)

**Comment by aixaCode** [comment]
Closing, moved as part of shape up.
