### ISSUE TITLE
Remove brotli compression server log in the browser console when the app loads

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#493]
Apparently brotli compression gain is marginal so we should find a way of removing these 3 logs that appear when loading the application

![Screen Shot 2021-05-24 at 09.28.56.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/18ec1ae9-fc9f-4dce-b7e4-38589ca63bf3)

**Comment by JorgeDecentraland** [comment]
This is not appearing anymore
