### ISSUE TITLE
User unable to load Decentraland or web or client

### ISSUE THREAD

**Issue by Kaze-No-Kai** [decentraland/unity-renderer#4952]
A user is not able to load the client see below recording and details:
Mac/Metamask, Address: 0x2b48Ab477975eB2a53c4D032a09F8bC8fe1A574a
https://drive.google.com/file/d/11HkndDfTpku0CLgwjPj6VbmBzkZ6Lasv/view

https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1681206049156919

**Comment by m3taphysics** [comment]
This looks to be downloading the client? What is their connection speed?
 Is it possible they did not wait long enough for the download to complete?
What happens if they try a guest user?

**Comment by Kaze-No-Kai** [comment]
User replied that the latest version works fine, closing this as resolved
