### ISSUE TITLE
BiW disable paint tool while placing Voxels

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#500]
Currently if you want to place a voxel, a custom tool will be triggered that allows you to drag and drop creating a matrix of voxels. This tool is not refined and needs to be disabled for the scope of this version.

- [x] Enable Voxels back again
- [x] Disable paint tool enabled while placing Voxels in the scene

**Comment by sandrade-dcl** [comment]
Blocked until Nacho updates the .io catalog (https://builder-api.decentraland.io/v1/assetPacks) with the voxels asset pack.

**Comment by sandrade-dcl** [comment]
Blocked until iterate and decide with Álvaro what to do with the voxels tool.
