### ISSUE TITLE
[QA] Backpack sections visible in new character creation screen

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#5008]
Description: 
Backpack section buttons are visible at the top of the character creation screen for new users.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Open up incognito mode then go to https://play.decentraland.org/ and use the guest log in.
2. Proceed through the login flow until the character creation screen is reached.
3. Observe the top section of the screen.

Results:    
"Avatar' and "Emotes" buttons are visible on top of the new character creation screen.

Expected results: 
"Avatar' and "Emotes" buttons are not available during the new character creation screen.

Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot for reference.
![image.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/54a56f13-8437-4c62-b9b6-bc1349bad637)

**Comment by anicalbano** [comment]
Not able to repro:

![image.png](https://images.zenhubusercontent.com/64ad62442a830229041f8802/33a8f48e-9c58-4b09-9ecf-3ca5fa0b265f)
