### ISSUE TITLE
[QA] Voice input activation can get stuck on first use since login

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#5021]
Description: 
When activating voice input for voice chat  it can get stuck on the ON state and constantly transmit voice without further holding the T key or the voice activation button in taskbar. Issue could be reproduced only when trying to activate voice for the first time since logging in. 
It can also be triggered more consistently on WebGL on a fresh guest login in an incognito window with unset browser microphone access permissions by activating voice input then clicking allow on the mic access popup.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in either on guest or a wallet account.   
2. Do a short press of the T key or a short click on the voice activation button in the taskbar.
3. Observe the status of the voice activation indicator.

Results:    
Voice transmission after activation gets stuck and does not deactivate.

Expected results: 
Voice transmission always deactivates when the T key or the voice taskbar button are not pressed.

Notes:    
- Platforms: Windows and MacOS, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached videos for reference.
https://images.zenhubusercontent.com/337227404/704b5558-6efa-4297-94aa-93d39cab7c7c/2023_04_21_11_38_16.mp4
https://images.zenhubusercontent.com/337227404/8fc63e34-78e7-4449-a171-7e4cd44a9be7/2023_04_21_11_38_16.mp4
https://images.zenhubusercontent.com/337227404/e025a26e-0430-405a-86b1-60cad9e04c3d/2023_04_21_11_43_42.mp4

**Comment by aixaCode** [comment]
https://github.com/decentraland/unity-renderer/issues/5612

**Comment by anicalbano** [comment]
Fixed with #5691
