### ISSUE TITLE
[QA] Freeze when loading scene at -20,27

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#5026]
Description: 
Triggering the loading of the scene at -20,27 causes a complete freeze of the client that lasts for a few seconds. Issue occurs on all platforms and regardless of login type.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in via either a guest or a wallet account and set your Scene Load Radius to 2 in the General Settings.
2. Use `/goto -21,29` command then after teleporting walk down the road in the direction of scene at -20,27.
3. When the scene starts loading observe the state of the client window.

Results:    
Client window freezes for a few seconds when the scene starts loading in.

Expected results: 
Loading the scene does not cause any freezes of the client.

Notes:    
- Platforms: Windows and MacOS, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/a33da7ab-ce7d-45d9-a1a6-19a6ce613f7e/2023_04_20_10_45_30.mp4

**Comment by m3taphysics** [comment]
We should investigate the cause?

1. SDK messages
2. Instantiation / Loading of assets
