### ISSUE TITLE
[QA] FMOD error messages spam in console on WebGL

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#5080]
Description: 
On the WebGL client in the browser console there is a constant stream of FMOD error messages that appear whenever any type of sound is played in the scene.

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in on WebGL client via either a guest or a wallet account.
2. Open browser DevTools and navigate to Console tab. Ensure you have Info messages configured to be shown in the filter settings.
3. Use `goto 150,-150` command to teleport to a remote location without much activity going on nearby.
4. Walk around the scene and perform other various actions that produce a sound effect.
5. Observe the contents of the browser console. Notice that whenever a sound is played an FMOD error message is shown in the console.

Results:    
FMOD error messages constantly appear in the browser console.

Expected results: 
FMOD error messages no longer appear in the console.

Notes:    
- Platforms: Windows and macOS, webGL only, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached screenshot for reference.
![image.png](https://images.zenhubusercontent.com/62e91e01ed547029fd717bd4/6ffd1d59-9a9f-47dd-a5df-f45eced3d861)

**Comment by xavi-dcl** [comment]
This is a Unity issue

https://forum.unity.com/threads/fmod-returns-error-code-36-fmod_err_invalid_handle-executing-setrelativeaudibility.1377675/

Upgrading to 2023 will eventually solve it:
https://issuetracker.unity3d.com/issues/fmod-returns-error-code-36-fmod-err-invalid-handl[…]ed-after-the-scene-reload-or-an-audiosource-is-destroyed

**Comment by m3taphysics** [comment]
@aixaCode - We have a ticket opened with Unity for this.

**Comment by sandrade-dcl** [comment]
Current status of this Unity's ticket: https://support.unity.com/hc/en-us/requests/1553531
