### ISSUE TITLE
[QA] Missing animations in Genesis Plaza and Onboarding world on webGL

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#5156]
Description: 
Animations for NPC characters and various objects at Genesis Plaza and the onboarding world are missing. The affected objects are:
Genesis Plaza:
- all NPC characters
- automatic doors
- platform elevators
New onboarding world (dclonboarding.dcl.eth):
- all NPC characters
- animated bridges
- portals at the end

Reproduction rate: 
5/5 

Steps to reproduce:    
1. Log in via either a guest or a wallet account and `/goto 0,0` to Genesis Plaza.
2. Jump down the whirlpool and walk around the building. Attempt to exit via one of the doors, try to use the platform elevators and talk to the NPCs around.
3. Notice that all of those NPCs and objects are not animated. Doors and platforms aren't moving and cannot be used.
4. Use the command `/world dclonboarding.dcl.eth` and proceed through the tutorial.
5. Notice that here NPCs, bridges and end portals are also not animated.

Results:    
Animations for NPCs and various objects are missing.

Expected results: 
Animations for NPCs and objects are present and play out correctly.

Notes:    
- Platforms: Windows, webGL only , wallet and guest login. 
- Issue occurs for the dev branch.
- Please see the attached videos for reference.
https://images.zenhubusercontent.com/337227404/9c7e3ff2-f9b9-4eaa-8531-1b611431fd4d/2023_05_10_14_52_50.mp4
https://images.zenhubusercontent.com/337227404/978bdc86-deec-4006-afb2-fa27ec60f97d/2023_05_10_14_53_42.mp4

**Comment by popuz** [comment]
checked on dev Windows 11, WebGL and for me all animations worked as usual

**Comment by kwssbocian** [comment]
Cannot reproduce on both dev and prod with webGL and desktop clients. Genesis and Onboarding have correct animations and can be progressed correctly.
