### ISSUE TITLE
BiW set Name and Description while Publishing

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#519]
Players should be able to set a name and description of the scene that they are about to publish during the publishing process.

When players push the publish button: 
- [x] A new Modal will appear
- [x] It will contain two inputs of Name and Description
- [x] Name Input should be one line
- [x] Description input should be multiline
- [x] Description should be optional
- [x] Initial information should be retrieved from the Project Scene
- [x] If no information is retreived, default should be "My new place" for the name, and empty for the description
- [x] The modal will also contain a Publish and Cancel button.
- [x] After clicking on Publish, the flow will continue as normal, starting from the confirmation dialog.
- [x] This information should be pushed to the Project Scene through the builder API and to the Content Server

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/a947f79b-65f4-41df-b7c0-6fd2741a6a47)
* This is not final design and needs to be supervised

**Comment by olavra** [comment]
@RominaMarchetti needs to double check this design

**Comment by RominaMarchetti** [comment]
Figma link -> https://www.figma.com/file/Wq4ZQ1mfsofPphv3uzjgts/BuilderPanelsV1?node-id=1201%3A2

![PublishModal](https://user-images.githubusercontent.com/51088292/120195261-ed28ff00-c1f4-11eb-944f-bbb924e5f0a7.png)

Things to have into account:
- **Name** is a required field. The "publish" button is blocked until the player enters one.
- Each field has a characters limit. Once it is reached the text color changes from grey to red.
- The active text field has an outline.
- The modal can be close clicking the close button, the cancel button or the black overlay.
