### ISSUE TITLE
BiW take screenshot while publishing

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#520]
In order to have screenshots for the published scenes, the BiW Editor will capture an imagen from the current scene during the Publishing workflow.

- [x] When players click on the publish button, a screenshot of the scene will be taken from the current camera
- [x] That screenshot will be displayed next to the inputs
- [x] Continuing with the publishing workflow, this screenshot will be submitted to the content servers
- [x] The screenshot will also be submitted to the Project Scene through the builder API
- [x] Add Romi final design

![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/efa80758-6ff7-4ac0-9cd5-a9d5263ace25)
* This is not final design and needs to be supervised

**Comment by olavra** [comment]
@RominaMarchetti needs to double check this design

**Comment by RominaMarchetti** [comment]
Figma link -> https://www.figma.com/file/Wq4ZQ1mfsofPphv3uzjgts/BuilderPanelsV1?node-id=1201%3A2

![PublishModal](https://user-images.githubusercontent.com/51088292/120199892-14ce9600-c1fa-11eb-9984-44b8c6bf3ed2.png)

Things to have into account:
- "Name" is a required field, so the "publish" button is blocked until the player enters one.
- Each field has a characters limit. Once the limit is reached the text color changes from grey to red.
- The "default text" color is grey #919094. It changes to white #FFFFFF when the user introduces text.
- The active text field has an outline.
- The modal can be close clicking the close button, the cancel button or the black overlay.
