### ISSUE TITLE
@Mentions message bubble coloring always yellow

### ISSUE THREAD

**Issue by moliva** [decentraland/unity-renderer#5224]
As originally reported by @kwssbocian:
> Coloring for message bubbles containing @mentions is always shown in yellow even for the users not actually mentioned in the message

![Screen Shot 2023-05-22 at 12.49.23.png](https://images.zenhubusercontent.com/6409d7cdf250fe6ab39eca87/545e9ac2-c42d-48da-a6dd-3dc35217ffc2)

**Comment by kwssbocian** [comment]
Fixed in [#5470](https://github.com/decentraland/unity-renderer/pull/5470)
