### ISSUE TITLE
Optimise SDK6 Pooling / EntityComponentCreateOrUpdate

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#5271]
### Description
During profiling we discovered a number of areas within SDK6 that do not appear to be utilizing the pooling as we expect.

![image.png](https://images.zenhubusercontent.com/63566805658b35a37eaf393c/b4ef729e-e42a-4db0-acb2-6e314503e039)

![image.png](https://images.zenhubusercontent.com/63566805658b35a37eaf393c/e681f7ea-2825-406d-9ca7-b16a6a163e0e)

![image.png](https://images.zenhubusercontent.com/63566805658b35a37eaf393c/ead2d86d-28e2-4fa6-b272-45aee3723a86)
### Deliverables
- [x] Optimise UIShape to properly use its pool
- [x] Add pooling to `UIContainerStack.RefreshContainerForShape` for `stackContainer`
- [x] Optimise PoolableComponentFactory to include more components (TextShape, AudioSources, etc.)
- [x] Refactor UIScreenSpace which is instantiating objects and component every time from scratch
- [x] Review EntityComponentCreateOrUpdate and verify it is pooling correctly
- [x] Expand on any further optimisations in this area
- [x] Optimize RefreshDCLLayout

**Comment by popuz** [comment]
`UIContainerStack.cs` has object Instantiation on line 136, that can be replaced by pooling
``var stackContainer = Object.Instantiate(Resources.Load("UIContainerStackChild"),referencesContainer.childHookRectTransform, false) as GameObject; ``

**Comment by popuz** [comment]
Another `UIShape `class that doesn't have pooling in the `UIShape `pooling PR is `UIScreenSpace.cs`. This is because it is not spawned from prefab, but gameObject is created at runtime in its `InitializeCanvas` method. Such prefab can be created manually, then path to it should be passed in `UIComponentsPlugin` constructor similar to other UIShape's.

**Comment by popuz** [comment]
Consider removing Resource.Load with Addressables in this system

**Comment by aixaCode** [comment]
Closing, as it was deprioritized because of complexity on the code side.
