### ISSUE TITLE
Optimise DCL.WebSocketService.SendBinary

### ISSUE THREAD

**Issue by m3taphysics** [decentraland/unity-renderer#5272]
### Description
Sending messages back to the kernel is incredibly costly, we copy large buffers in and out of memory, causing large heap allocations at runtime. As part of the sending process it also blocks the main thread, its unknown at this point if this is nessecary.

### Deliverables
- [ ] Investigate and optimize DCL.WebSocketService.SendBinary for potential to be moved to a background thread and ran asynchronously
- [ ] Investigate the possibility of improving the memory allocations.

**Comment by pravusjif** [comment]
Possible approaches thought up front:
* Saving messages payload in memory (from explorer/kernel) and then reading them from the same memory (at explorer/kernel)
* Otherwise, pre-allocating memory for the current memory copy process to avoid runtime allocation and its performance impact.

**Comment by pravusjif** [comment]
FYI everything websocket related only affects the desktop client (and unity editor)
