### ISSUE TITLE
Basket balls placed in Genesis Plaza can not be picked up

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#5295]
## Issue
Afte this [**change**](https://github.com/decentraland/unity-renderer/pull/5251), there were a regression where you cannot pick up objects in the scene.

### BEFORE
![image](https://github.com/decentraland/unity-renderer/assets/64659061/b6a0f30d-e4b5-438f-89ba-0c1e58e6cf4f)

### AFTER
![image](https://github.com/decentraland/unity-renderer/assets/64659061/2cbb6cd3-06ab-4d04-b0c9-f674dd378188)

## Steps to reproduce it
1. Enter the world using `&CATALYST=peer-testing.decentraland.org` to the `0,0` position.
2. Go to the floor below.
3. Try to pick up the basket balls that are on the floor.
4. Notice you can't.

**Video**: https://decentralandteam.slack.com/files/U0368CBHSDS/F05B9V5DNP2/screen_recording_2023-06-01_at_4.13.59_pm.mov

### More context
Reported in this slack's thread: https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1685654458530679

**Comment by aixaCode** [comment]
Closing - issue with scene configuration
