### ISSUE TITLE
Cannot log in using Wallet Connect

### ISSUE THREAD

**Issue by WilczynskiT** [decentraland/unity-renderer#5405]
I cannot log in using Wallet Connect, I tried:
- web and desktop version
- different wallets
- different computers (Win10 and Win11)
 
It was working correctly a week ago, but when I tried to log in today, it was not working.

![image](https://github.com/decentraland/unity-renderer/assets/102859171/b0f7d744-b539-47af-b80e-2ef3d4053cd2)

**Comment by WilczynskiT** [comment]
Hello, thanks for response.

I tried re-install the decentraland desktop client. 

I using latest version of Unstoppable wallet which using WalletConnect. [Unstoppable client](https://github.com/horizontalsystems/unstoppable-wallet-ios)

I tried use different wallet like: [Edge](https://github.com/EdgeApp/edge-react-gui)

And I still can't log in

**Comment by WilczynskiT** [comment]
The unstoppable wallet for sure use Wallet Connect v 2.0

[OpenSea](https://opensea.io) also need connection with v 2.0 WalletConnect and there is working correctly

**Comment by WilczynskiT** [comment]
@aixaCode  Also log it to decentraland marketplace working correctly

**Comment by aixaCode** [comment]
@WilczynskiT Do you still experience this issue?

**Comment by WilczynskiT** [comment]
@aixaCode it is working correctly now, thanks 😄
