### ISSUE TITLE
[Backpack] In desktop windowed mode, the content is missing a right margin

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#5449]
In desktop windowed mode, the content of the backpack is missing a right margin, causing the content to be slightly cut off.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/11904eb9-380b-4d13-b74e-aa9b8d616f45)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/775382d8-f596-4617-a257-e8e6ec33e15c)

**Comment by anicalbano** [comment]
Fixed by #5894
