### ISSUE TITLE
Query the WITH_COLLECTIONS param from unity

### ISSUE THREAD

**Issue by dalkia** [decentraland/unity-renderer#5451]
Since we moved the emotes and wearables request to Unity using the lambdas, we lost the ability to query the `WITH_COLLECTIONS` param.

Currently, the `WITH_COLLECTIONS` param only work when going through [kernel](https://github.com/decentraland/unity-renderer/blob/dev/browser-interface/packages/shared/catalogs/sagas.ts#L150). When the param is present, kernel fetches the entities of the collection and then forces them into the response that is sent back to Unity. Therefore, if the request does not go through kernel, the param does not work. Since we want to stop supporting kernel, we should properly implement this functionality in Unity.

Some suggested steps would be:

1) Inject the param from kernel into Unity (The kernelConfig could be use for this)
2) Fetch the collections (Kernel uses the endpoint https://builder-api.decentraland.org/v1/collections/${collectionUuid}/items to fetch them)
3) Add the resultant urns to the wearable and emotes request, respectively

**Comment by aixaCode** [comment]
https://github.com/decentraland/unity-renderer/issues/5401

**Comment by lorux0** [comment]
In order to be able to preview wearables/emotes from builder the `WITH_ITEMS` has been implemented as well

**Comment by lorux0** [comment]
Blocked until dapps implements the auth chain signing with timestamp.{metadata}

**Comment by lorux0** [comment]
PR: https://github.com/decentraland/unity-renderer/pull/5652
