### ISSUE TITLE
Implement MVC properly in the ProfileHUD

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#549]

**Comment by AjimenezDCL** [comment]
The ProfileHUD contains a lot of technical debt.

At a first glance we can see how the controller is subscribing directly to some buttons or UI elements from the UI, finding components in Unity's hierarchy or interacting directly with some panels submenues.

Some actionables prior deep analysis of the issues could be:
- [ ] Decouple controller/view properly
- [ ] Extract an interface from the view to make it mockable
- [ ] Move display related code from the controller to the view

**Comment by olavra** [comment]
This do not apply anymore as this HUD will dissapear in the future or be converted into a plugin.
