### ISSUE TITLE
Backpack is not working for PREVIEW mode

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#5497]
The new backpack is not working for preview mode. It keeps loading forever.

It works fine if we use the old backpack (using the feature flags `DISABLE_backpack_editor_v2&ENABLE_backpack_editor_v1`).

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/1a02a03d-163f-4088-922d-f4a5e9db70a5)

### Steps to reproduce
1. `npx @dcl/sdk-commands@next init` (in an empty folder)
2. `npm start`

### Discussion thread
https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1689695073056039

**Comment by sandrade-dcl** [comment]
The problem is that we cannot access to the new backpack's endpoint (`/explorer/...`) from the PREVIEW mode because it's not accessible from `http://127.0.0.1:8000/`. I have been talking with Gon about this and it seems he can proxy that with the preview server and hit the catalyst instead, so it would be solved.

I'm going to wait for him to do it and lets see if it's enough.

**Comment by sandrade-dcl** [comment]
**CURRENT STATUS**: Waiting for Gon to implement the proxy from the preview server to the backpack's endpoint.

**Comment by sandrade-dcl** [comment]
**Handover of the task to the new support champion**: @davidejensen this task is blocked waiting for a change from Gon's side (read the comment above).

**Comment by lorux0** [comment]
We need to fetch directly to the catalyst in preview mode in the client. Something like:
```
// replace localhost or 127.0.0.1 url
if (previewMode)
    baseUrl = catalystUrl;

fetchWearables(baseUrl);
fetchEmotes(baseUrl);
```
