### ISSUE TITLE
Script to generate top-view of single parcel

### ISSUE THREAD

**Issue by sicarul** [decentraland/unity-renderer#550]
I thought i had created a ticket for this, now i see i didn't (facepalm)

We need a script that generates a top-view of just one parcel, to generate a map similar to https://decentraland.icu/, i can create the scripts to concatenate the maps and save them. Unfortunately the developer that created that page lost the code to generate the top-view image

So the script would receive X/Y as parameters (e.g. ./generate-map -10 10) and output a png with the top-view for the scene currently on that parcel.

Thanks!

**Comment by xavi-dcl** [comment]
Do we still need this @olavra @eordano ?

https://decentraland.icu/ does not have the content anymore.

**Comment by sicarul** [comment]
It's now on https://genesis.city/

**Comment by xavi-dcl** [comment]
Oh, thanks! I was aware of genesis.city but did not know this was the actual reference.

We are moving away from loading png's and going into rendering the map directly. I wonder if we could ever get similar results rendering a map (or at least the mini-map) based on low LOD data from scenes. I guess high effort and not a priority for now.
