### ISSUE TITLE
The flow for loading preview scenes in Unity is broken

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#551]
These instructions no longer work:
https://github.com/decentraland/explorer/blob/master/docs/how-to-test-parcels-and-preview-scenes.md#unity-editor-debugging-with-dcl-scene-in-preview-mode

The data is never sent to Unity, there are some errors in the browser console:
![Screen Shot 2021-06-07 at 14.09.40.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/2ed7759b-dc5b-4eac-98dd-95094b1c3674)

A discord user was asking about this and when I tried it locally before answering himI saw that the flow is broken.

When we fix this we could also update the URL and remove the `UNITY_ENABLED=true` param

**Comment by pravusjif** [comment]
I think we should prioritize this as we need it for debugging preview scenes

**Comment by sandrade-dcl** [comment]
The updated steps for executing preview scenes from our Unity editor are:

### Unity Editor debugging with dcl scene in "preview mode"
1. From the console, go to the scene folder.
2. Compile the scene dendencies executing one of the next lines:
2.1. To use @latest execute: `npm i decentraland-ecs@latest`
2.2. To use @next execute: `npm i decentraland-ecs@next`
3. Execute the scene with `dcl start`.
4. In Unity, deactivate the “Open Browser When Start” flag (in the `WSSController`).
5. Click on PLAY.
6. Go to the browser window opened by the previous `dcl start` and add the next in the url: `&ws=ws://localhost:4999/dcl`

### DCL scene in preview mode using a local Kernel version
1. From the console, execute `make watch` in the kernel folder and wait for the build process ends.
2. Cancel this `make watch`.
3. Execute `node static/default-profile/download_all.js`
4. Execute `make npm-link` and wait for the process ends.
5. Go to the scene folder and execute `npm link decentraland-ecs`
6. Execute the scene with `dcl start`.
7. In Unity, deactivate the “Open Browser When Start” flag (in the `WSSController`).
8. Click on PLAY.
9. Go to the browser window opened by the previous `dcl start` and add the next in the url: `&ws=ws://localhost:4999/dcl`
