### ISSUE TITLE
Scenes past and present have most textures displaying in red

### ISSUE THREAD

**Issue by cybermikedent** [decentraland/unity-renderer#5530]
Hey folks

Most of my scenes past and present are displaying nearly all of the textures in red. I have tried redeploying and the problem still persists.

If someone could look into this i would greatly appreciate it.

Decentraland locations of scenes showing graphic anomalies 

-35,75
54,43
49,61
-70,-12 (takes a v long time to load the castle)
-44,63

-Some of the scenes were built over a year ago and I'm unsure where the source files are. Perhaps there is some simple code which was altered in a recent update causing these graphic anomalies to show up.

Many thanks

-Cybermike 

![Builds_DCL_Errors_A01](https://github.com/decentraland/unity-renderer/assets/56007113/e4ba868d-0b3e-47a9-a27e-3bfd050a44bf)
![Builds_DCL_Errors_A02](https://github.com/decentraland/unity-renderer/assets/56007113/582756f8-dc2d-4cb7-943d-7696ff45b02f)
![Builds_DCL_Errors_A03](https://github.com/decentraland/unity-renderer/assets/56007113/ea782e33-e492-42ac-9a37-55d68e648e1f)
![Builds_DCL_Errors_A04](https://github.com/decentraland/unity-renderer/assets/56007113/d8dd64b3-9d89-49c6-bead-0936d4f3d12f)
![Builds_DCL_Errors_A05](https://github.com/decentraland/unity-renderer/assets/56007113/b2905f69-fe88-4212-bc32-24de7f1e1ae5)

**Comment by cfravel** [comment]
The Unity Cafe in the Conference Center. Too
14,100

**Comment by cfravel** [comment]
with rebuilding and redeploying with dcl 3.18.0 and ecs 6.12.0  the magenta materials are back to normal in the Unity Cafe.

**Comment by cybermikedent** [comment]
Can someone on the foundation please look into this, we are trying to get this build to run correctly which will host dj's and live music. The scenes look fine in sdk and builder, there must be some simple code causing these anomalies in world. Thank you
![Vesca P Club_WIP_A96](https://github.com/decentraland/unity-renderer/assets/56007113/f727cf14-cfcb-4782-b8d4-e3bd60a95002)
-location 138,1

**Comment by aixaCode** [comment]
Yes, we have been able to identify the issue, we are taking a look at that.

**Comment by cybermikedent** [comment]
That's super news, many thanks!!! @aixaCode

**Comment by aixaCode** [comment]
@cybermikedent The issue appears because you are using the same texture as albedo and normal map, with some changes on our side, the pre-processing we do on the assets it's always setting those as normal map. In general, you should avoid using the same image file for both the albedo texture and the normal map or the emissive map of a material. Use separate files, even if identical. That's how you can fix the issue.

**Comment by cybermikedent** [comment]
Thanks for the feedback @aixaCode Is there any way that error flag could simply be disabled in this instance? have multiple scenes deployed for various community members from way back and not even sure where the source files are... it was never an issue in the past. Regards - CM

**Comment by cybermikedent** [comment]
Redeployed 2 scenes and they look perfect, if someone did something, Thank you so much!

**Comment by cybermikedent** [comment]
my 2nd deploy reverted to red again unfortunately. https://play.decentraland.org/
![Builds_DCL_Errors_A06](https://github.com/decentraland/unity-renderer/assets/56007113/2ee24bd4-087c-4849-aeb4-c3215c5bc9db)
?position=48%2C61&realm=heimdallr&island=peer-wc11hla  

if there was a way of disabling this error flag it would be really great, thank @aixaCode

**Comment by cybermikedent** [comment]
Can this error flag be removed, if i replace the texture with a lower size black and white for the normal map it will be counting extra materials in scene and will go over the limits. Can you please put the state back to how it was before this error ruined all my scenes please

**Comment by cybermikedent** [comment]
got cyberpunk alley working all good now, when i get another scene sorted, i will close this topic, many thanks
