### ISSUE TITLE
Test editing State scenes deployed with Builder

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#555]
Builder can create Projects bigger than 1x1, including irregular sizes (ie: 2x3). Those Projects can be deployed in States with available space.

Builder in-world should be able to retrieve edit this Scenes, retrieving the Project from Builder:

Steps to reproduce:

- [ ] Go to Builder and create a Project Scene of 2x1
- [ ] Deploy it in a available parcel, rotating the Scene first (1x2)
- [ ] Go to Builder in-world and check the Scenes in the Builder panel
- [ ] Edit the scene: check that the Project retrieved is the origina Project and not one created by BiW
- [ ] Check the scene boundaries are right while editing.
- [ ] Make some changes
- [ ] Publish the scene
- [ ] Go to builder a check the status of the Project, and the status of the Scene deployed.
- [ ] Try the same thing by adding other sizes: 2x2, 3x1, 1x3, etc.

**Comment by Suduck** [comment]
For this to work correclty, we should have into consideration the rotation of the deployment 

https://peer.decentraland.zone/content/deployments?onlyCurrentlyPointed=true&pointer=140,140
You can see here the rotation attribute
