### ISSUE TITLE
BiW does not retrieve original Project from Builder

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#556]
If you edit a Scene that was originally created with Builder, Builder in-world won't retrieve this Project but will create a new one.

Steps to reproduce:
- [ ] Go to Builder and create a new Project, adding several assets
- [ ] Deploy the project in a available Land
- [ ] Go to Builder in World and edit the deployed Scene
- [ ] Be amazed who Builder in-world creates a new blank Project
- [ ] Go to Builder and check there is a new Project in the Scene section.

**Comment by pbosio** [comment]
https://play.decentraland.zone/branch/fix/builder-in-world-project-fetch/index.html?ENV=zone&ENABLE_BUILDER_IN_WORLD
