### ISSUE TITLE
AvatarModifiers.HIDE_AVATARS no longer works

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#557]
This example scene works fine on 6.6.4, but doesn't on 6.6.5

https://github.com/decentraland-scenes/avatar-swap

The player's avatar should be removed when entering the swap area, this worked fine on 6.6.4,  but in 6.6.5 the original avatar never goes away

![Screen Shot 2021-06-08 at 09.32.05.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/10f2a8f9-b98e-4e1b-a29e-cc9d601924c1)

**Comment by olavra** [comment]
@nearnshaw do you know any scene that already uses this functionality? we need to check if it's still working or is broken as well.

**Comment by nearnshaw** [comment]
hmmm I'm trying to think but I can't remember any places in-world where this functionality is being used today

**Comment by nearnshaw** [comment]
@olavra  here's an example that isn't working in-world:
https://play.decentraland.org/?position=-24%2C22&realm=unicorn-blue

**Comment by PrinceSyed** [comment]
I am using the hide avatar functionality as well
https://play.decentraland.org/?position=-46%2C-99&realm=fenrir-amber

**Comment by nftworld** [comment]
I am using it as well https://play.decentraland.org/?position=150,63
