### ISSUE TITLE
[QA] Voice chat stuck after opening chat window during voice activation

### ISSUE THREAD

**Issue by kwssbocian** [decentraland/unity-renderer#5612]
Description:
Voice chat activation gets stuck on the transmitting state if the Chat window is opened while holding the voice chat key. Issue occurs only for the Chat window and can be reproduced only by using the keyboard shortcuts for both the voice chat and Chat window (T key and Enter key respectively) and not by clicking on any of the taskbar icons with the mouse. After closing the chat window voice chat can be unstuck by pressing the T key again which deactivates the constant voice transmission.

Reproduction rate:
5/5 

Steps to reproduce:    
1. Log in using any account type on any platform.
2. Press and hold the T key to activate voice chat. Observe the voice chat icon on the taskbar.
3. While holding the T key press Enter key to open the Chat window.
4. Release T key. Notice that voice chat continues to be activated despite the shortcut key no longer being held.
5. Close the chat window then press the T key. Notice voice chat transmission stops.

Results:    
Holding T then pressing Enter to open Chat window gets the voice chat stuck on ON state.

Expected results: 
Holding T then pressing Enter to open Chat window does not get the voice stuck in any way.

Notes:    
- Platforms: Windows, web and desktop, wallet and guest login. 
- Issue occurs for both production and dev branches.
- Please see the attached video for reference.
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUVaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f8ef7bffa90658816c36bd94e82f7e9f9bb86615/2023-08-17_10-43-26.mp4

**Comment by anicalbano** [comment]
Fixed with #5691
