### ISSUE TITLE
BiW editor should be able to edit deployed Stateless Scenes

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#567]
Sometimes players will edit deployed scenes that do not have an associated Project in Builder, so BiW always ends up creating an empty project, preventing them from editing the content of the current scene. This can be for the following reasons: 
- The Project has been deleted from Builder (which does not delete the scenes deployed).
- The Project was originally created with the SDK

In case that Project does not exist, the system must try to create a new one using the content already deployed on the content servers. For this, the scene must have been deployed with the Stateless scene definition format (aka the Scene was deployed using BiW). In any other case it will be impossible to recreate the deployed scene and an empty Project will be created.

IF BUILDER PROYECT EXIST:
- LOAD Builder PROJECT

ELSE IF DEPLOYED SCENE IS STATELESS:
- CREATE Builder PROJECT with Stateless Manifest
- LOAD created Builder PROJECT

ELSE:
- CREATE empty Builder Project
- LOAD empty Builder Project

**Comment by pbosio** [comment]
test-link: https://play.decentraland.zone/branch/fix/builder-in-world-project-fetch/index.html?ENV=zone&ENABLE_BUILDER_IN_WORLD
