### ISSUE TITLE
Both musics, avatar editor and genesis plaza, playing during Backlog, BiW and Tutorial

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#571]
During the SignUp process, when we reach the Avatar Editor screen, we're listening 2 musics at the same time: the music of the own Avatar Editor and the background music of the Genesis Plaza.

This is also happening when we open the BiW editor or the Tutorial.

We should mute any kind of sound related to the world while we have open these features.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/38733c49-5273-4829-8e37-669b103aa0eb)

**Steps to reproduce:**
1. Enter Decentraland as incognito mode.
2. Select the "Enter as Guest" option.
3. When the avatar editor is showed, notice both musics being played.

**Comment by olavra** [comment]
@sandrade-dcl please consider the refactor done by @Landeplage on the settings panel and sound mixer

**Comment by sandrade-dcl** [comment]
**Useful info from Mordi:**

Basically, there are five types of sound in DCL:
- Native unity audio
   - Used for UI, Avatar Editor music, Tutorial music, Builder music and Avatar SFX (footsteps, etc)
   - These go through an AudioMixer, which is a native Unity asset
- Scene SFX
   - Sounds that creators put in their scenes.
- Streaming audio
   - Background music in casinos that creators put in.
- Streaming video
- Voice chat audio

All these have different places where their volume is set, but I have a document that explains where this happens ("Where volume is applied"):
https://docs.google.com/document/d/1v6eOOIyr6d7uM4ex2k_SYHGHMGeLUju8s_vJTnP-jGA/edit#heading=h.p3oeova1a66e

For example, this is where we set the volume of all the Scene SFX:
https://github.com/decentraland/unity-renderer/blob/2f4f6e35cec65bf885a5f742fc3c8d[…]sets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs

**Comment by sandrade-dcl** [comment]
We're going to wait for Mordi ends with the refactor implemented here: https://github.com/decentraland/unity-renderer/pull/862

**Comment by olavra** [comment]
This also should be extended to builder in world editor and Tutorial.
