### ISSUE TITLE
[QA] Prevent a blocked user to send friend requests

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-renderer#5734]
## **Issue Description:**
Currently, if a User A blocks a User B, User B is still able to send friend requests to User B.
Since the user is blocked, it's not possible to reject the invite given the error on this ticket #5718 

### **Steps to reproduce:**

1. Send a friend requests to User A
2. User A rejects the requests and blocks User B
3. User B sends a friend request again

### **Expected behaviour:**
A blocked user should not be able to send another friend request to the user that blocked it.

### **Current behaviour:**
It's possible to send a new friend requests, and User A cannot reject it because of the mentioned issue.

### **Reproduction rate:**

5/5

### **Severity:**

Medium

### **Platforms:**
- [ ] Windows
- [ ] Mac
- [x] Not platform specific

### **Browser:**
- [x] Google Chrome
- [x] Microsoft Edge
- [x] Firefox

### **Environment:**
- [x] Production
- [ ] Branch specific
- [ ] Release Branch

**Comment by lorux0** [comment]
The blocked user list only exists in the client, there is no such thing in the client service. In order to get it working properly it needs to be implemented in the backend
