### ISSUE TITLE
[QA] Camera Icon is being rendered behind the scene UI

### ISSUE THREAD

**Issue by anicalbano** [decentraland/unity-renderer#5763]
## **Issue Description:**
As reported by the content creator: the camera icon can be seen in worlds but it's not clickable.

### **Steps to reproduce:**

1. Enter a world (boedo.dcl.eth as an example)
2. Click on the Camera Icon

### **Expected behaviour:**
The camera icon works as expected

### **Current behaviour:**
The camera icon is currently unresponsive for the UI render

### **Reproduction rate:**

5/5

### **Severity:**

Medium

### **Platforms:**
- [ ] Windows
- [ ] Mac
- [x] Not platform specific

### **Browser:**
- [ ] Google Chrome
- [ ] Microsoft Edge
- [ ] Firefox
- [x] Not browser specific

### **Environment:**
- [ ] Production
- [ ] Branch specific
- [ ] Release Branch
- [x] Worlds

### **Evidence:**

![image](https://github.com/decentraland/unity-renderer/assets/139157886/c3902db5-099a-4082-97e1-9bf72e82c27a)

**Comment by Kaze-No-Kai** [comment]
Works at the moment. closing
