### ISSUE TITLE
BiW error publishing a Project from Builder

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#578]
Projects created with BiW and published with Builder seems to break.

Steps to reproduce:
- [ ] Go to an empty land in BiW
- [ ] Enter edit mode and add some assets, rotate, scale and rest of stuff
- [ ] Publish the scene and exit the Editor
- [ ] Go to Builder and edit the recently created Project
- [ ] Add 1 item to the scene (ie: some bananas)
- [ ] Publish the Scene from Builder
- [ ] Wait until the scene has been propagated
- [ ] Go to the world and check the scene: it should only contain the entity you added in Builder, without floor or any other thing.

**Comment by pbosio** [comment]
can be tested using this builder dapp https://builder-git-fix-export-component-undefined-decentraland1.vercel.app/
