### ISSUE TITLE
Teleport particles not working

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/unity-renderer#5808]
## Severity:
SEV-5 | Cosmetics issue

## Description:
On the loading screen the teleport animation particles are missing.

## Operating system:
MacOS

## Error:
null

## Browser (version):
Chrome

## Steps to reproduce:
Load lecentraland or jump into scenes

## Ticket number:
NA

**Comment by anicalbano** [comment]
The issue is no longer visible in present versions of the platform.
