### ISSUE TITLE
[QA] Map Filters - Missing Icons for 'Friends' and 'People' Layers 

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-renderer#5841]
**Issue Description:**
The icons for the 'Friends' and 'People' layers are not appearing as expected in the map filters section. These icons should be visible to provide users with a visual reference for these layers on the map.

**Steps to reproduce:**

  1. Launch Decentraland.
  2. Access Map [M]
  3. Click on "Filters"

**Expected behaviour:**
Users should see icons corresponding to the 'Friends' and 'People' layers.
![expectedresult](https://github.com/decentraland/unity-renderer/assets/146741383/a15ef335-eb12-472e-9f10-088db2fb745e)

 **Current behaviour:**
The icons for the 'Friends' and 'People' layers are currently not visible in the map filters.
![actual result](https://github.com/decentraland/unity-renderer/assets/146741383/55e00937-9be8-4915-9b80-028612f36b8c)

 **Reproduction rate:**
100%

 **Severity:**
- [ ] Cosmetic
- [X ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

**Priority:**
- [ ] High
- [ ] Medium
- [ X] Low

 **Platforms:**
- [ ] Windows
- [ ] Mac
- [ X] Not platform specific

**Browser:**
- [ ] Google Chrome
- [ ] Microsoft Edge
- [ ] Firefox
- [ ] Desktop
[ X] Not Browser Specific

 **Environment:**
- [X] Release Branch (20231020)

**Comment by RominaMarchetti** [comment]
Issue fixed and merged in the RC 😎
