### ISSUE TITLE
Builder in world Keyboard shortcuts

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#59]
We need to change the current keyboards shortcuts because they are colliding with the current browser shortcuts

Current shortcuts:
https://docs.google.com/spreadsheets/d/1SAu9YAtGD_Hx6-9VvJ-1JWchFXqq7u_lWt5PvsZ1peY/edit#gid=0

Extra info that can be helpful:
https://stackoverflow.com/questions/11941180/available-keyboard-shortcuts-for-web-applications

List of shortcuts to implement
https://docs.google.com/document/d/1kZPJT6Kt94-f_2AwEaICfixFsvdBY-IKvWo2-zAp_sA/edit#heading=h.p3x9p89yzoaa

- [x] The panel of controls should also me updated to reflect these changes and to reduce the size of the font and icons

**Comment by olavra** [comment]
My suggestion tries to achieve 3 things:
1) Avoid the use of CTRL or ALT as much as possible to prevent conflicts with browsers. Use SHIFT instead.
Conflicts:
CTRL+D = Add Bookmark
CTRL+H = History
CTRL+R = Refresh
2)
Left click is operational (move, rotate, select...)
Right and Middle clicks are for camera.
Both modes exclude each other
3) Stick with standard controls well known in tools like Blender and Unity
Shortcut List
Mouse
LMC =  Select / Deselect
LMC + Drag = Square Select
Shift + LMC = Select Multiple
RMC = Rotate View
RMC + AWSD = Navigation (where A=Left Strife, D=Right Strife, W=Forward, S=Backward, Q=Up, E=Down)
MMC = Shift + RMC = Pan View
MMScroll = Zoom In / Zoom Out
Tools
G = Grab (Move)
R = Rotate
S = Scale
F = Focus
D = Duplicate
DEL = Delete
R = Reset
H = Hide
Shift + H = Unhide All
Others
U = Hide / Show UI
C = Controls (Shortcuts) Cheatsheat
History
Shift + Z = Undo (I have my doubts about this)
Shift + Y = Redo (edited)

**Comment by olavra** [comment]
https://docs.google.com/document/d/1kZPJT6Kt94-f_2AwEaICfixFsvdBY-IKvWo2-zAp_sA/edit#
