### ISSUE TITLE
Guest mode + backpack: Crash after clicking DONE button before the avatar finishes loading

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#590]
This bug seemingly only happens in FF and Safari, but we may have to double check.

1. Clear localStorage, refresh page
2. Enter as guest
3. Click on "Done" before the avatar renders for the first time -> Fails 100% of the times, in FF and safari

When testing on FF, make sure you don't use incognito mode, just use normal mode and clear the localStorage using FF dev tools. (FF incognito has an IDB problem).

**Comment by AjimenezDCL** [comment]
The issue might be related to the way we handle the interactable status of our AvatarEditor's Done button. It's being set On/Off by different sources and we probably have an edge case when you can press Done with a corrupted profile.

**Comment by olavra** [comment]
Confirm this also happens in Google Chrome
