### ISSUE TITLE
Add tracking to external links from scenes

### ISSUE THREAD

**Issue by sicarul** [decentraland/unity-renderer#594]
We need to track when a user opens an external link, e.g. an NFT sale. This is useful to measure engagement e.g. with an Art Gallery. Would like to have in the event:
* NFT being linked (if possible? I'm not sure how this works, sorry)
* URL that the user is opening
* Scene that it hapenned on
* Parcel (x/y) where it happened on

**Comment by Suduck** [comment]
External links are generic and don't need to be a NFT, do we want to track all the URLS, or only the NFTs urls?

**Comment by sicarul** [comment]
Ideally, both, but if it's an NFT i'd like to have the NFT token address as well, is this possible?

**Comment by Suduck** [comment]
It is possible but it will require a major refactor, right now the OpenURL generic function is used in 22 places so if the token address is not mandatory I will try to extract it from the URL if possible

**Comment by Suduck** [comment]
Ok, and what info do you want when you say Scene? Parcel x/y do you mean the parcel of the scene or the exact parcel inside the scene?

**Comment by sicarul** [comment]
With scene i mean the scene hash, with Parcel X/Y i mean the tile id, the same you see in the URL, e.g. if
https://play.decentraland.org/?position=20%2C-20
Then it's 20,-20

**Comment by Suduck** [comment]
This will be the format :

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/af000182-6924-4c13-adcb-df0597102374)

If the url is not an NFT the nft_token_id field won't exists
