### ISSUE TITLE
BiW confirmation dialog while exiting the editor

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#602]
While editing a Scene, the Player may decide to exit without publishing the changes. This does not mean the player loose the Project done so far, but they will need to be reminded:

- [ ] When the player exit the editor with unpublished changes, a prompt must appear warning:
"There are unpublished changes in this project. But don't worry, next time you enter the editor you will be able to continue where you left off!" 
A "Got it!" button will allow you to exit the editor. 
A "Back" button will cancel the Exit action
- [ ] Otherwise, the current exit confirmation dialog will be promtped

**Comment by RominaMarchetti** [comment]
**Replace the current exit editor modal** with those copies mentioned by Alvaro.
