### ISSUE TITLE
BiW create a new Project prompt

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#603]
When players edit a Land that has no Project associated to it, BiW automatically creates a Project for them. In order to have a coherent name an description for this Project, it will be prompted  before the creation of the Project.

> "Welcome to the editor! Let's create a new Project! It allow you to automatically save your changes until you are ready to publish your Scene to the world!"
> 
> A couple of inputs will be placed to add the Name and the Description of the Project
> - "Create Project" will continue the editor workflow
> - "Cancel" will cancel the creation of the Project and exit the editor.

When the player hits Create Project, a loading popup will appear with the message:

"Creating new Project..."

OUTDATED

IF the land / Scene does not have a Project associated, but there is a compatible Published Scene, the next prompt will appear:

> "We have not found a Project for this Place! However, we can retrieve the data from the published scene. What do you want to do?"
> 
> "Create a new empty project"
> "Create a project from the published scene (recommended)"

If the player chooses to create a Project with the Scene data, it will be also be created with the same name and description of the Scene.~~

**Comment by RominaMarchetti** [comment]
![Screen Shot 2021-06-21 at 13.39.24.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/fbc58323-55ce-481f-9dbb-2e272f30dc54)

Figma link: https://www.figma.com/file/Wq4ZQ1mfsofPphv3uzjgts/BuilderPanelsV1?node-id=1260%3A2

**Comment by sandrade-dcl** [comment]
**Note for when we implement this in the future:** We already have the prefab `NewProjectDetailsView.prefab` created in our project to be use along this new flow.

**Comment by olavra** [comment]
This is not longer necessary as we will implement the Projects in BIW
