### ISSUE TITLE
Teleport using the builder in world panel is not working 100%

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#609]
If you haven't loaded beforehand your land and you try to teleport and edit the land using the builder in world panel, sometimes it won't work

This is causing other issues like sometimes reset the camera is not aiming at the correct land

![mvp4.gif](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/ce00d901-55bc-438f-8ff8-39a7995ec6f0)

**Comment by olavra** [comment]
Related to https://github.com/decentraland/unity-renderer/issues/606
