### ISSUE TITLE
BiW sometimes editor does not load asset in the Scene

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#619]
Sometimes, when you enter to edit a Land that has an associated Project, the assets (3D Models) do not load until you add another entity to the scene.

The circumstances to reproduce this situation are unknown.

**Comment by pbosio** [comment]
99% sure that it is related to the objects culling 
https://app.zenhub.com/workspaces/unity-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/624

**Comment by Suduck** [comment]
I have investingating this issue and it seems to be related to have the mesh renderer inactive in the GLTF for some reason

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/db07b580-e78a-4bfa-a7d7-bb3a7e5955d2)
