### ISSUE TITLE
Builder In-World Publish Flow

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#63]
https://www.figma.com/file/jwcjNS7tibLm1Qbwx4LKif/Builder-in-world?node-id=732%3A2

![image](https://user-images.githubusercontent.com/41490935/113690183-6ca1c280-96cb-11eb-84e2-341db10bfe6d.png)

![image](https://user-images.githubusercontent.com/41490935/113690255-7f1bfc00-96cb-11eb-96f9-94a072492974.png)

![image](https://user-images.githubusercontent.com/41490935/113690298-893dfa80-96cb-11eb-971b-ca3e6c998673.png)

**Comment by olavra** [comment]
@ShibuyaMartin  This is blocked as we need an updated design of the UI for the publish workflow

**Comment by sandrade-dcl** [comment]
As we curently don't have any way to know the progress of the publish process, we are going to display a fake progress in the bar. This will be temporal until we implement the way of return the publish progress from the kernel side.
