### ISSUE TITLE
Avatar skin texture issue on avatar builder

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#640]
From @cazala :
>Hey guys, i dunno if this is the right place to ask, but maybe someone here has an idea on what’s causing an issue i’m experiencing with the builder. I added some dropdowns that allows the user to change some of the default wearables of the avatar. It works fine on the hair and facial_hair wearables, but when using it on the upper_body and lower_body ones they look either too white or too red, and I dunno why. Here are some screenshots:

![image](https://user-images.githubusercontent.com/6875814/122580676-97de5180-d02c-11eb-9e6c-349645986099.png)

**Comment by cazala** [comment]
Figured it out, when I copied the wearables from the catalyst into a json on the builder side I accidentally lowercased the last character of some hashes (i had to do some replaces and I think I used a hot key to lowercase without noticing). The hashes that I modified where the `Avatar_FemaleSkinBase.png` (which causes the red skin in the female avatar) and the `AvatarWearables_TX.png` which made some wearables white.
