### ISSUE TITLE
Manage feedback for NFTs not loaded

### ISSUE THREAD

**Issue by pbosio** [decentraland/unity-renderer#657]
## OLD ISSUE (discarded at the moment due to incompatibilities on the OpenSea API)
According to someone from the community, there are some NFTs that used to load in picture frames that no longer do
for example with: `ethereum://0x272f20cb476ef250e6e8478740dc62416040bdf0/17`

>Hi everybody, I had a couple of nfts in matic showing as NFTShape objects in my scene, they were displaying correctly until a couple of days ago. Now instead of the images I see a circle progress that never loads. Has the way of displaying nfts in matic changed? This address was working: `ethereum://0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465` It has changed to another address, type `matic://0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465` or something similar? Or is it no longer supported?
>

Apparently Opensea changed the path to include `/matic` in the middle, maybe they did the same with their API?

If we can’t know if a token is on matic or not, maybe we could try requesting again the asset (if the firsrt request fails) and use the new `/matic` in the request?

Another example: https://opensea.io/assets/matic/0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465

![image (11).png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/e60ac927-6a5a-4c31-91ad-6b82f4a5e29c)

## NEW ISSUE
Due to the incompatibility on the OpenSea API side, while the API is updated to the V2 where we will be able to support the loading of Polygon assets, we are going to manage the feedback that the user/developer will receive when an asset can't be loaded in the NFT frame and details dialog.

For both components we will show an image that represents when an assets couldn't be loaded (it has to be designed by Romi), instead of let the loading spinner remaining visible forever. This will give more visual information to the users about what happened.

We will also update the messages that we receive in the browser console when an asset can't be loaded, in order to give more information to the scenes developers.

**Comment by sandrade-dcl** [comment]
This issue will keep blocked until OpenSea API supports Polygon retrieving assets. It will be supported in their V2 API but it is not quite ready yet.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/1acea69b-b4cb-4c34-a98e-073f65b0ab6b)

Ref.: https://docs.opensea.io/reference#api-overview

**Comment by sandrade-dcl** [comment]
Current behavior without Polygon compatibility:
### Create a NFT frame from SDK
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/cb5f9374-747f-4dae-8f0f-c5f3890252ab)

- If the user introduce the url in this way: `ethereum://0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465`
  - The loading spinner never ends.
  - Message in browser console: `Couldn't fetch NFT: '0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465' OpenSea error fetching 0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465 asset 0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465 not found in api response`
- If the user introduce the url in this way: `matic://0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465`
  - The loading spinner never ends.
  - Message in browser console: `Couldn't fetch DAR url 'matic://0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465' for NFTShape. The only protocol currently supported is 'ethereum'`

### Create a NFT dialog from SDK
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/d7766f9f-bc5a-427d-8d47-971823555933)
- If the user introduce the url in this way: `ethereum://0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465`
  - The dialog opens and then closes after a second.
  - Message in browser console: `OpenSea error fetching 0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465 asset 0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465 not found in api response`
- If the user introduce the url in this way: `matic://0xbccaa7acb552a2c7eb27c7eb77c2cc99580735b9/5465`
  - The dialog never opens.
  - No message in the console.
