### ISSUE TITLE
Explore V2 Technical Analysis

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#658]
https://www.notion.so/decentraland/Technical-Design-f2cb9c7ae4404c6f893f537e28423061

- [x] UI Library definition (wip)
- [x] Feature Controller definition (wip)
- [ ] Top Bar
- [ ] Explore: Events
- [ ] Explore: Highlights
- [ ] Profile

Back-end definition
- [ ] High level definition (WIP)

**Comment by BrianAmadori** [comment]
The research of this analysis is in progress. Documentation has already been produced, but was halted due to shift in priorities.

**Comment by pbosio** [comment]
Here is the doc of the research regarding APIs https://www.notion.so/decentraland/Explore-v2-API-Research-001d94503a3d4df3a2eeeb5111a4cd5e
