### ISSUE TITLE
Draw distance changes based on the rotation of the camera

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#666]
Draw distance should be consistent and render the same things independently of the rotation of the camera

[Video](https://images.zenhubusercontent.com/337227404/385c8027-0b74-4b90-bb75-7fe041e8051b/2021_06_23_12_11_16.mp4)

**Comment by Kinerius** [comment]
Unity draw distance is based on the camera frustum, the lower it is, the more noticeable this artifact will be.

This is a brief graphic explanation of how this happens, having the same object and player at the same position, but the player rotates its view on the second panel
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/818ce4a5-158a-412b-8117-76e7b43ecef3)

Sadly we can't change this as this is how unity works
Now that we can increase the draw distance, this artifact is less noticeable, so I will consider this closed for now.
