### ISSUE TITLE
Allow quests in preview explicitly

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#684]
Currently the feature toggle is enabling quests for `.zone` `localhost` and `127.0.0.1`. Some users are reporting issues when trying to access through local IPs such s `192.168.1.101`.

We can make an exception in kernel to enable quests always for preview mode.

**Comment by AjimenezDCL** [comment]
Currently the feature toggle is enabling quests for `.zone` `localhost` and `127.0.0.1`. Some users are reporting issues when trying to access through local IPs such s `192.168.1.101`.

We can make an exception in kernel to enable quests always for preview mode.

**Comment by AjimenezDCL** [comment]
After talking with @nearnshaw and @menduz we agreed to unprioritize this and communicate with the quests creators to use `ENABLE_QUESTS` url param or access through `localhost` or `127.0.0.1`.

**Comment by olavra** [comment]
This does not make sense anymore as this is active in all enviroments already and can also be tested in Preview Mode
