### ISSUE TITLE
Add particles to avatars locomotion

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#7]
@BrianAmadori commented on [Mon Mar 01 2021](https://github.com/decentraland/explorer/issues/2131)

Add particle system when the avatar run and jump.

![Screen Shot 2021-02-22 at 12.59.41.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/94253aca-e87e-4975-8079-86c6b164d7cb)![unnamed (1).png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/28379804-594a-446d-9130-06f89d995b61)

**Comment by olavra** [comment]
@ShibuyaMartin are this assets ready?
