### ISSUE TITLE
Calculate test coverage for unity-renderer

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#700]
We need to have the coverage of test for every commit to master the master branch
Do this after the artefacts are created
We need to evaluate the time cost of this calculation to decide in which repo events will be integrated.

We also need to decide if the data generated will be sent to metabase or graphana, or it will be retrieved externally by another server calling CircleCI

Tasks: 
- [x] Upload HTML generated by the coverage tool to S3

**Comment by kuruk-mm** [comment]
We need to consider if we're going to use coveralls.
