### ISSUE TITLE
Preview mode takes a long time to load

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#711]
Even with the default `dcl init` scene that only has a rotating BoxShape, the scene takes a long time to activate the renderer.

This may be related to #252.

**Comment by BrianAmadori** [comment]
This can be related to the unity loader kicking the JS fallback compression when it shouldn't

**Comment by olavra** [comment]
@nearnshaw can you verify this is still happening?

**Comment by menduz** [comment]
Fixed by new sdk
