### ISSUE TITLE
Implement and document performance impact of drawing all avatar names in 1 canvas for massive events

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#717]
* Document: https://docs.google.com/document/d/1Acc5yWt_Q_2Zc-jNkGm_W7mBRILnXBtKm6_GjXlwHLs/edit#
* Profiling results document: https://www.notion.so/decentraland/Bots-for-Massive-Events-7471e8cb14c048b38152968d073cad40
* Performance Improvement actionables: https://www.notion.so/decentraland/Performance-Sync-Minuta-24-06-29e94c1dc160486aa0eac2f84cd652ec

Tested turning 100 bots avatar names off in runtime (in editor) and we gain 1-2 FPS only so it's probably a low-impact improvement but we should implement it either way.

**Comment by BrianAmadori** [comment]
For 200 bots I measured around 5-7 milliseconds of improvement per frame (around 5 fps). I think this has bigger impact than we think.

**Comment by BrianAmadori** [comment]
Duplicated of #825 . Closing.
