### ISSUE TITLE
Add feature flags implementation guide somewhere

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#731]
Add a guide somewhere, indicating how to add feature flags in the client, basically:
 
* Kernel side:
1. Add the new feature flag to [this enum](https://github.com/decentraland/explorer/blob/d0cd54927d069507700f1f8f45e913f5e7f277b6/kernel/packages/shared/meta/types.ts#L65)

2. Add a new bool to [this features object](https://github.com/decentraland/explorer/blob/d0cd54927d069507700f1f8f45e913f5e7f277b6/kernel/packages/unity-interface/kernelConfigForRenderer.ts#L16) and connect it to the previously-created enum flag like so: `isFeatureEnabled(globalThis.globalStore.getState(), FeatureFlags.AVATAR_LODS, false)`.
Alternatively, if you need to wait for user authentication you update the flag [here](https://github.com/decentraland/explorer/blob/d0cd54927d069507700f1f8f45e913f5e7f277b6/kernel/packages/entryPoints/website.ts#L139)
    
* Unity renderer side:
You can read the feature flag value through the KernelConfig singleton this way: `KernelConfig.i.EnsureConfigInitialized().Then(config => EnableFeature(config.features.enableBuilderInWorld));` 

* Gitlab feature flag configuration:
Write something based on: https://playbooks.decentraland.systems/ops/feature-flags.html

**Comment by dalkia** [comment]
How to add a feature flag in Client Side (Unity)

1) Create the flag in the Unleash platform (https://features.decentraland.systems/#/features). The flag should start with the `explorer-` prefix, followed by the flag and using underscore when necessary. Ex: `explorer-animation_culling_status`
2) You can read the state of the flag using the `IsFeatureEnabled(string featureName)` method in the `FeatureFlag`. This class can be accessed from the DataStore (`DataStore.i.featureFlags.flags.Get()`). Inject the datastore when possible to make cleaner code.
3) If necessary, suscribe to the OnChange method to detect changes.

NOTES

- The flag state can be overriden in the url, by using the `ENABLE_<FF_NAME>` and `DISABLE_<FF_NAME>`.  Remember to put the name with caps on. `This works for zone and org.`

**Comment by dalkia** [comment]
Guide at
https://playbooks.decentraland.systems/ops/feature-flags.html#feature-flags-types
