### ISSUE TITLE
Content Migrator Producer is not working properly

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#732]
Apparently the content migrator producer has been trying to convert the same scene continuously since 26/06/2021.

Stats:
https://grafana.decentraland.systems/d/UzieKAoGk/unity-asset-bundle-creation?orgId=1&refresh=5m

https://unityab.decentraland.io/#/scenelog

Playbook: https://playbooks.decentraland.systems/world-team/asset-bundles.html

**Comment by BrianAmadori** [comment]
I'm looking at this: QmQQMdz9v1bWA25Nz8F98scJm7UVdwXayrivZHN5Mb93EK

Apparently most of the failures come from this scene id. The visual tests seem to be failing.

**Comment by BrianAmadori** [comment]
Seems to be fixed by this commit: 
https://dcl.tools/dcl/content-migrator/-/commit/fb8c22a3209adfe00e5840cdaba06317e1354b9e

Closing the issue.
