### ISSUE TITLE
Add FOV slider to quality settings to address dizziness

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#74]
This should help with the dizzyness issue.
https://www.reddit.com/r/Guildwars2/comments/10gztt/a_solution_for_those_that_experience_dizziness_or/

**Comment by DavideJensen** [comment]
Should the FOV affect only the first person camera? generally for what i've seen games that support both first person and third person have a static FOV in thrid person and a changeable one in first person

**Comment by DavideJensen** [comment]
After the post daily of the 31st January 2022 it has been decided to have the FOV slider affect only the first person view, this to simplify the behavior of the third camera that has some visual effects when running that change the FOV and because FOV sliders generally affect only first person
