### ISSUE TITLE
Profile Avatars instantiation and document culprits

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#741]
Profile (ideally in build) avatars instantiation and load the findings in a new document similar to these ones:
* [Avatar combined meshes profiling](https://www.notion.so/decentraland/Profiling-1de3f62012f2480cb4e2d2dad99f4ba6)
* [Avatar basic LOD impostors profiling](https://www.notion.so/decentraland/Avatar-basic-LOD-Impostors-f126a916c5e64cf69ac4995b46bc34a6)
* [Avatar generic-snapshot LOD impostors](https://www.notion.so/decentraland/Avatar-generic-snapshot-LOD-impostors-a0aff14f15864f20957d0f2db6b8b5de)
* [Bots profiling for massive Events](https://www.notion.so/decentraland/Bots-Profiling-for-Massive-Events-7471e8cb14c048b38152968d073cad40)

We should analyze what hurts performance the most when instantiating avatars to generate actions to improve its performance.

**Testing with lots of avatar-bots** -> https://www.notion.so/decentraland/Performance-Sync-36542a31bd714de19eaeb0c53510e97b?p=d800d1361f1d41a0844bb385068d78d7&showMoveTo=true

**Measuring performance score** -> https://www.notion.so/decentraland/Performance-Sync-36542a31bd714de19eaeb0c53510e97b?p=550b7d14369a425ba1d8a40b5785716a&showMoveTo=true

**Comment by BrianAmadori** [comment]
We might need to wait for the merging avatar feature before tackling this one. I'm currently doing some modifications to the `AvatarRenderer` logic. i.e. we don't need to clone materials anymore like we did before.
@AjimenezDCL

**Comment by AjimenezDCL** [comment]
https://www.notion.so/decentraland/Avatar-Instantiation-a89c5f2b4ba24a4e9c6fd2a0917f341e
