### ISSUE TITLE
Genesis plaza dog meme character not renderer correctly

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#752]
While investigating other issue, after teleporting to the genesis plaza from tominoya casino The dog meme character is like these

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/a441202a-cd06-4b78-a2ad-6ce31ffe6684)

This is the hierarchy of the game object in Unity

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/cbbca351-ca8b-4b83-8b1e-bd2969a0d6a3)

**Comment by sandrade-dcl** [comment]
I have not been able to reproduced it.
