### ISSUE TITLE
Generate map procedurally from content server

### ISSUE THREAD

**Issue by sicarul** [decentraland/unity-renderer#758]
Currently, we are fetching the map by downloading 48 images of about 1-3 kb each, to generate the whole map. The total size of the underlying data is much lower and we could just do one request to get the types of tiles instead, and render it locally to reduce unnecesary network requests.

The current code that is generating the maps is here:
https://github.com/decentraland/atlas-server/blob/master/src/modules/image/component.ts

**Comment by AjimenezDCL** [comment]
After several discussions on this topic we have reached the following conclusions:
- Current implementation is fine by now regarding performance(see #2177).
- Procedurally creating it in the client will allow us to have some input on how to render it.
- Procedurally creating it would also reduce the bandwith costs of downloading the images from the API.

A handful of options are available to create the map in the client but we can split them in two types:
- CPU Generated: A simple process will read the map metadata and create the chunks for the different parts of the map.
Pros: Easy to implement and maintain, accessible to artists.
Cons: Memory consumption

- Shader Generated:
The map metadata can be feed to a shader through a small texture along the coordinates to center the view so the map can be rendererd at that position.
Pros: Efficient in processing time, almost no memory consumption.
Cons: The rendering batch can be a bit more expensive than rendering simple chunks, increased complexity both in implementation and maintenance, hard to tweak for no tech-artists.

**Comment by JorgeDecentraland** [comment]
Duplicated from /unity-renderer#2353
