### ISSUE TITLE
BIW: Materials and textures are not counted correctly

### ISSUE THREAD

**Issue by Suduck** [decentraland/unity-renderer#763]
When you are placing items in the builder in world it seems like the materials and textures are not counted as it should

This may be related to this issue :https://app.zenhub.com/workspaces/unity-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/750

Materials:

https://images.zenhubusercontent.com/337227404/22ac6f4c-43d0-450a-8f80-e3d42997983c/materials.mp4

It is also happening in the builder

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/ef8c0d08-b04c-47df-9de3-24c5518c3a66)

Textures:

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/37b50910-805c-434d-95c9-83cfb970e55a)

**Comment by Suduck** [comment]
GLTFs materials are not cached / checked but their counterpart asset bundles does. We need a way to figure out how to tackle this problem.

We could use a scene metrics controller only for biw
We could use check some properties of the materials to see if they are equals

**Comment by Suduck** [comment]
Blocked until I talk with Brian about this

**Comment by Suduck** [comment]
This should be solved when the #768 card is closed

**Comment by olavra** [comment]
@Suduck the card #768 is already closed, could you evaluate if this has been fixed?

**Comment by Suduck** [comment]
Yes this has been fixed, it has araise another issue but I will close this one and open a new one
