### ISSUE TITLE
Support CJK characters in system font

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#77]
![image](https://user-images.githubusercontent.com/6875814/72824386-ecbd4300-3c53-11ea-9a71-c88456928f85.png)

To add chinese support to DCL chat widget we need to change the default font to include the chinese glyphs.

Here is a link with the unicode ranges:
https://stackoverflow.com/questions/1366068/whats-the-complete-range-for-chinese-characters-in-unicode

https://en.wikipedia.org/wiki/List_of_CJK_fonts

**Comment by BrianAmadori** [comment]
We have to investigate. This approach may not scale very well, and Unity doesn't work with system fonts in webgl:
https://forum.unity.com/threads/unity-webgl-cannot-display-chinese-characters-in-chrome.568372/

**Comment by RominaMarchetti** [comment]
[Here](https://drive.google.com/file/d/1JbVAw9_zvHdwRAv9ku9Kz6Z4VfX-vE4u/view?usp=sharing) are the fonts for Japanesse, Korean and Chinesse (simplified and traditional).

**Comment by JorgeDecentraland** [comment]
@RominaMarchetti can you confirm if this is already implementes, please?

**Comment by sandrade-dcl** [comment]
@JorgeDecentraland I think no, @RominaMarchetti only left the fonts assets, but I guess it is not yet integrated in the project.

**Comment by sandrade-dcl** [comment]
This task are going to require time to investigate... Apart of see how we are going to include CJK characteres in our default system, as Brian said in previous comments, it seems that Unity has some problems to work with these kind of fonts in WebGL and it could be something very problematic.

**Comment by sandrade-dcl** [comment]
Some useful documentation: https://forum.unity.com/threads/support-for-cjk-language.973041/
