### ISSUE TITLE
Resize large DCLTexture

### ISSUE THREAD

**Issue by pbosio** [decentraland/unity-renderer#771]
We notice a lot of textures with large resolutions from 2k to 4k.
- [ ] Enforce a resizing of this kind of textures to 1024px
- [ ] Fix `UIImage` atlas after this change

**Comment by olavra** [comment]
Pending decision if this may be affecting the memory problems of the scenes

**Comment by olavra** [comment]
@nearnshaw we have been evaluating the need to make this change. We believe that the ideal would be to prohibit the use of textures that are larger than what is specified in the official documentation limits.

https://docs.decentraland.org/development-guide/scene-limitations/#texture-size-constraints

In that case, textures exceeding that size would be replaced by another placeholder, and a log entry would alert the console about this limitation.

We understand that this may break many scenes, and we propose to raise the limit from 512 to 1024.

Would you know how this could affect the current scenes?

**Comment by nearnshaw** [comment]
That would be a very controversial thing to do. It would break a lot of scenes.

If the limit is set to 512, it would break a lot of our own scenes even. Even the UI utils library relies on some 1024x1024 textures. We should really have a discussion about officially raising the documented limit to 1024.

Setting the limit to 1024 would surely affect a lot of art galleries and scenes with large murals, all of Cybermike's scenes, etc.

I would vote to force the limit at 2048 instead.

Maybe this could depend on performance settings?  Like if you have them on "low" then we avoid heavy textures, but not if you have the setting higher than that?

**Comment by olavra** [comment]
@BrianAmadori what do you think about this?

**Comment by JorgeDecentraland** [comment]
Duplicated from #2179
