### ISSUE TITLE
TextMeshPro materials used by TextShape are not properly destroyed

### ISSUE THREAD

**Issue by pbosio** [decentraland/unity-renderer#772]
There were lots of mesh count related to TextMeshPro on unity's profiler.
We should analyze if the `TextShape` component is destroyed correctly

**Comment by BrianAmadori** [comment]
Code reference
https://github.com/decentraland/unity-renderer/blob/a8bc1a41529ee0bbb5af13426d66b3d9ae4785c8/unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs#L133
