### ISSUE TITLE
Loading Bar behaves incorrectly

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#786]
https://images.zenhubusercontent.com/337227404/50eda415-f63e-43f1-bef2-d6e38c9f2429/loadingbar.mp4

- [ ] The loading bar appears full, then goes to 0% 
- [ ] The loading bar doesn't fill but the scene loads

**Comment by BrianAmadori** [comment]
We discussed and brought into attention that our internal loading progress logic takes into account ALL surrounding scenes, but we activate the rendering after the current scene has been loaded. 

This can give loading progress issues in zones with many small scenes.

**Comment by dalkia** [comment]
Closed, since we wont support this on the legacy loading screen.

The decoupled loading screen will show the loading percentage of the destination scene
