### ISSUE TITLE
A deployed scene bugs the character controller gravity

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#799]
NicoE reported that [this scene](https://play.decentraland.org/?position=50%2C74&realm=fenrir-amber) with the pyramid bugs the character controller gravity when jumping or even if we leave the scene, as seen on the video.

Apparently the behaviour fixes itself if we reload or get far away as to unload that scene.

The slack video is too big to be uploaded here, I leave the slack link: https://decentralandteam.slack.com/files/UB4ENQ750/F027WJJ3NBX/screen_recording_2021-07-13_at_22.30.20.mov

**Comment by nearnshaw** [comment]
I see the same proble with this scene:

https://play.decentraland.org/?position=-45%2C-100&realm=unicorn-blue

If I take the lift to the top of the flower, I then have messed up gravity too

**Comment by sandrade-dcl** [comment]
Additional info for this issue: https://decentralandteam.slack.com/archives/C01UXV234JG/p1626728927282100
