### ISSUE TITLE
Automate hotfix workflow for unity-renderer

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#802]
Implement hotfix procedure for the unity-renderer repository:
- [x] Manual creation of hotfix branch from master
- [ ] Custom test recipe for pushes to the branch, just mandatory tests.
- [x] Manual merge to master triggers release and automatice merge to develop
- [ ] Hotfix merge triggers message to #world-pr-sync and increment in patch number

**Comment by kuruk-mm** [comment]
Review: https://github.com/decentraland/cd-pipeline-playground
