### ISSUE TITLE
Assessment of changes needed for layer removal

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#804]
Layers are being deprecated inside the catalysts and will be replaced by the concept of island, which should be transparent for the unity-renderer. Determine which changes need to be done in order to assimilate this changes

**Comment by sandrade-dcl** [comment]
I'm creating this document: https://www.notion.so/decentraland/Assessment-of-changes-needed-for-layer-removal-Unity-side-44067a4e659d4bbe8d18f5e01b0421b6
