### ISSUE TITLE
Add new emotes to enum for SDK

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#816]
The last set of emotes was never added to the `PredefinedEmote` enum in the SDK (Tik, Hammer, etc)
The new one recently added also needs to be added

you can still trigger them by passing the string w the name, but would be nice to have the IDE autosuggest them too and not mark them as an error when passing the string

https://docs.decentraland.org/development-guide/trigger-emotes/

**Comment by AjimenezDCL** [comment]
Update the documentation to avoid forgetting about this again.

**Comment by AjimenezDCL** [comment]
Oh, `Fixes #TICKET_NUMBER` in the PR doesnt work when working with cross repo PRs. Good to know, thanks for closing it Agus!
