### ISSUE TITLE
Sometimes, wearable textures fail to load correctly and show with white color

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#818]
This is an old issue. It can be related to failing to fetch the external textures. We should find a way to reproduce it consistently and fix it.
![image.png](https://images.zenhubusercontent.com/5d9756603fe18d00011cfcac/f48c383f-cbec-47cf-905c-db9ee6a412bc)

**Comment by olavra** [comment]
This bug may take a lot of time to reproduce. Need to consider this in comparison with the impact of fixing it.

**Comment by olavra** [comment]
This is fixed in the ticket #1209
