### ISSUE TITLE
Disable face for far-away avatars

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#826]
On our profiling we have identified that the **mouth and eyebrows** are pretty expensive [due to the shader](https://github.com/decentraland/unity-renderer/issues/715#issuecomment-878786928) they use.

- [ ] Toggle each avatar face based on distance (off when they are far away)

**Testing with lots of avatar-bots** -> https://www.notion.so/decentraland/Performance-Sync-36542a31bd714de19eaeb0c53510e97b?p=d800d1361f1d41a0844bb385068d78d7&showMoveTo=true

**Measuring performance score to compare changes** -> https://www.notion.so/decentraland/Performance-Sync-36542a31bd714de19eaeb0c53510e97b?p=550b7d14369a425ba1d8a40b5785716a&showMoveTo=true

**Comment by AjimenezDCL** [comment]
You can find a benchmark in #860
