### ISSUE TITLE
When going around the tram line, loading objects are obstructing the road.

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#844]
When going at a fast speed back and forth over the new genesis plaza tram line, objects obstructing the road can be seen on the way back. This may be related to a pool recycling issue.

This bug already happens in master but when we apply the memory leak fix proposed in this PR #808, it happens more frequently.

**Comment by olavra** [comment]
The repro rate of this issue is quite low and the time investment to solve it is too high. Going back to the backlog for another time

**Comment by pbosio** [comment]
I will leave little more info about this issue:
* GLTF (`GLTFSceneImporter`) load it meshes progressively and those aren't check against scene bounds until the whole GLTF finishes loading
NOTE: I've tested adding submeshes to `SceneBoundsChecker` as soon as they where created by `GLTFSceneImporter` but performance was terrible and client was running frame by frame in the best scenario
* GLTFShape (`LoadableShape`) set the mesh as visible (depending on model coming from the sdk) as soon as it finish loading and then it's added to `SceneBoundsChecker` which is running a time budget queue so it may take a while before that Shape is processed
NOTE: we can't set the shape as invisible and leave it to the `SceneBoundsChecker` to set it as visible after processed cause Preview, Builder and Builder in World does not hide renderers when out of bounds

**Comment by pravusjif** [comment]
This would be solved by: https://github.com/decentraland/unity-renderer/pull/2164

**Comment by pravusjif** [comment]
fixed at https://github.com/decentraland/unity-renderer/issues/2132
