### ISSUE TITLE
Integrate QuestsUI animations

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/unity-renderer#86]
First pass to integrate the Quests UI animations:

- [x] Task progression in the Quest Tracker
- [x] Task completed
- [x] Quest completed
- [x] New Quest
- [x] New Task
- [x] Expand / Collapse Quest in the Quest Tracker
- [x] Quest gets pinned to the Quest Tracker
- [x] Quest gets unpinned to the Quest Tracker
- [x] Task in / task out the quest tracker
- [x] Section In/Out
- [x] Quest reward

**Comment by AjimenezDCL** [comment]
`quest-animations` the animations can be found there

**Comment by AjimenezDCL** [comment]
@EstefaniaColutta and I agreed to avoid the Collapse animation in the mean time. The decision is a bit technical but it's related to how some components of Unity's UI behave and the current UI implementation. Basically it's hard to animate something that realtes ContentSizeFitter, LayoutGroups and ScrollViews.

**Comment by AjimenezDCL** [comment]
@RominaMarchetti Can we curate this list to see if something is mising? Otherwise I think this ticket can be sent to review

**Comment by RominaMarchetti** [comment]
@AjimenezDCL I would add "Quest Reward" to the animations list. Other than that, it's okay to send this to review.
