### ISSUE TITLE
Text boxes with overflown text crashes the renderer

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#88]
Users are able to enter an unlimited amount of text in their text boxes through the SDK, causing two problems:
- Text box overflow, invading other parcels and breaking the limits.
- At a certain amount of text the application crashes.

![Screen Shot 2021-03-15 at 14 12 01](https://user-images.githubusercontent.com/41490935/111287869-efdb7580-8643-11eb-8b1d-12246d963403.png)

This was reported by a user, more details from @nchamo

**Comment by nchamo** [comment]
The only extra information I have, is that this causes [this area](https://play.decentraland.org/?position=-115%2C-40&realm=loki-blue) to crash
