### ISSUE TITLE
Avatars in scenes >150 in Aetheria District do not generate indicators on the minimap or M map

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#882]
Steps to reproduce:

Put two avatars in 151,151 (a 1 parcel scene in Atheria district)
Check the mini map:  no indication of the "other" avatar.
(Also not in the "M" fullscreen map)

This is a problem for Aetheria contributors and visitors.

**Comment by kuruk-mm** [comment]
Same problem from #881
