### ISSUE TITLE
You still cannot use URL to go to Aetheria north of Y=150 or east of X=150

### ISSUE THREAD

**Issue by cfravel** [decentraland/unity-renderer#883]
(issue 216 not fully addressed)

Steps to reproduce:
[https://play.decentraland.org/?positiion=151,151](https://play.decentraland.org/?positiion=151,151)
// expected to be at SW corner of 151,151
// actual:  you are at 0,0, and have two position values in resulting url:
https://play.decentraland.org/?positiion=151%2C151&position=0%2C-1&realm=baldr-amber

or you may end up at: 150,151

This: https://play.decentraland.org/?position=161%2C157&realm=loki-gold
Takes you to 160,156

**Comment by kuruk-mm** [comment]
The first URL you sent has an extra `i` (`posiition`) in the `position` parameter.
Try with this link: https://play.decentraland.org/?position=151,151

And the other issue:
I tried multiple times entering at https://play.decentraland.org/?position=161%2C157&realm=loki-gold, and sometimes I go to 161,157.
Have you tried using spawn points?
https://docs.decentraland.org/development-guide/scene-metadata/#spawn-location

Let me know if that fixes the problem.

**Comment by cfravel** [comment]
I did a lot of testing with different >150 coordinates on July 31 and saw these kinds of problems (even without the position misspelling).
today I am not seeing them, so perhaps something got fixed.
Let me confer with the user that asked for help getting this fixed, to see if he has any remaining reproducable cases.

**Comment by olavra** [comment]
@cfravel can we have confirmation that this has been resolved?

**Comment by olavra** [comment]
closing the issue
