### ISSUE TITLE
Hotkeys stop responding if we take macOS screenshot and return to the explorer

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#886]
1. Enter the world anywhere
2. Press U to remove UI
3. Release mouse, and use macOS snapshot tool (cmd+shift+4) and take a snapshot
4. Lock the mouse again in the explorer
5. You won't be able to use any hotkey (V for camera change, etc.)

If we change tabs and return to the explorer tab, the explorer continues working correctly

**Comment by xavi-dcl** [comment]
@kwspgoliasz @kwssbocian is this still happening?

**Comment by kwspgoliasz** [comment]
@xavi-dcl The issue still occurs as described by Pravus. The issue can be reproduced on Mac by executing the provided reproduction steps in the web client. No repro was found for the MacOS client.
Reproduction rate 5/5.
