### ISSUE TITLE
When hot reloading, animations start playing

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#891]
Often when doing a hot reload, 3d models that have animations that shouldn't be playing start looping

**Comment by Suduck** [comment]
I was trying this with this scene https://github.com/decentraland-scenes/Shark-animation and it is working fine

Could you please give me a test scene to reproduce the issue when you find one?

**Comment by Suduck** [comment]
We can't reproduce the issue so we are closing this issue
