### ISSUE TITLE
Add particle system based emotes (aka StickersSystem)

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#9]
Adding a basic particle system that display emojis/stickers into the world will bring more social interactivity to the world. A user can import a set of emojis in-world (similar to telegram) to show and communicate with their friends in a fun way.

I see a couple of ways that this feature can work:

1) **Through Chat**. A user select a sticker in the chat bar and automatically it display the particle system into the world.

2) **Through Emotes**. A user can select an emote and it display automatically that specific emoji into the world.

3) **Emoji System**. A user can select a set of emojis (similar to selecting emotes with a wheel) and display them in world.

4) **A mix of the previous three**

![Screen Shot 2021-02-22 at 13.50.11.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/0c218298-d354-487f-94ea-9b37dabda3df)
![Screen Shot 2021-02-22 at 13.50.43.png](https://images.zenhubusercontent.com/5dc043d4fd9840000180454c/df7590e4-c2a8-41ab-93c7-bf78034a35cb)

**Comment by AjimenezDCL** [comment]
https://docs.google.com/document/d/10Jy0JQYCK2KOf-c-lZrg-qHzrKsZlp5l8RZmhvxguSU/edit#heading=h.tc2a5041wlzy
