### ISSUE TITLE
You don't see another avatar when using archipielago in Unity Editor

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#920]
![image.png](https://images.zenhubusercontent.com/60647b38cc4b79842895cb82/3a3110f3-efbe-418e-a7be-9fb173926b70)

I didn't know where to create this task. Maybe it's for platform or unity+platform.

@pablitar suspects that is something from the avatar system.

**Comment by Suduck** [comment]
I am unable to reproduce this issue, I am able to see the other avatars

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/72efae21-df74-4eda-99d6-90b7de598d11)

**Comment by kuruk-mm** [comment]
I couldn't reproduce it again. So seems to be fixed. I don't know-how. When I tested, it was happening 10/10.

So you can close it if you want.

**Comment by Suduck** [comment]
Closed due to not being able to reproduce
