### ISSUE TITLE
Some tests scenes seem to be broken

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/unity-renderer#922]
If we try to run the test scenes placed in the `-100, 100` coords, the app is crashing.

![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/25c8f349-9703-4a1e-94c8-00cdf4d08acc)
![image.png](https://images.zenhubusercontent.com/5eb2b8ca65c88f6e391ef16e/fdb04dbe-74a4-4afc-bea1-eec797952519)

### Steps to reproduce
1. Start the regular kernel server in a terminal at '/kernel' and leave it watching for changes: `make watch`
2. In **another terminal** in '/kernel' run the following command to build the test scenes and keep watching changes on them (changes will be visible when refreshing the browser): `make watch-only-test-scenes`. Note that the test-scenes building may take a while (10 mins or more).
3. Go to: http://localhost:3000/?DEBUG_MODE&position=-100,100

**Comment by sandrade-dcl** [comment]
**NOTE**: The task has been tagged as `critical` due to Mendez comment here: https://github.com/decentraland/explorer/pull/2531/files#r683392818

**Comment by Suduck** [comment]
Since the kernel repository has been moved, I am unable to start the local kernel plus the website

**Comment by Suduck** [comment]
Blocked since I am unable to go to the test scenes because the URL is not working as before and there is no instructions in the kernel repository for this part now

**Comment by Suduck** [comment]
They re enable the task with this PR
https://github.com/decentraland/kernel/pull/56#event-5349405648

**Comment by Suduck** [comment]
It seems related to a memory leak problem ![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/7526f531-8cee-4d37-bc6c-cbd6018c1357)

**Comment by Suduck** [comment]
It seems like the empty parcels are causing the issue, so it s most likely that the GLTF are making the memory leak.

What it is interesting is that when you teleport from one place with empty parcels to another, the memory is unloaded

**Comment by Suduck** [comment]
It has been solve in the recents version of unity, unable to reproduce the crash with a  local unity build
