### ISSUE TITLE
Evaluate pre-commit hook

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#931]
Evaluate if it is possible to reduce the time of the pre-commit hook

**Comment by kuruk-mm** [comment]
Pre-commit hook: https://github.com/decentraland/reshaper-pre-commit-hook

We evaluated with @AjimenezDCL and the majority of the time is on the script from ReSharper. So it's out of our scope, and it takes a minute for small changes.

**Comment by kuruk-mm** [comment]
Outcome #964
