### ISSUE TITLE
Get an event in the ECS when the video start/stop/pause

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#941]
For static videos:
When a VideoTexture starts playing, there should be an event from Unity to Kernel signaling that the video started, the event should include the current position of the video in milliseconds.
When the video is paused or stopped, there should be also events informing the new state to the Kernel.
Once per second, if the video is playing, there should be a VideoProgressEvent(VideoTextureComponentId, offset, max) including the video component id and the milliseconds of the current playback. This event exists as a best effor to prevent synchronization/buffering issues between the Kernel and the Renderer.
Event definition
type VideoProgressEvent = {
  videoTextureId: string // component ID for the video texture
  status: number // 0 = paused, 1 = playing, 2 = buffering (paused)
  currentOffset: number // current absolute position of the video in milliseconds
  videoLength?: number // total video length in milliseconds, may be absent in streaming
}
For streaming:
When a VideoTexture starts streaming, there should be an event to know when the transmission started arriving. This event should include data about how long ago the transmission began for players that arrive late to the event (this information is typically included in any streaming data)

This is crucial for doing live events.

We often need to synchronize things that happen in the scene with a transmission, like light animations matching the music. The streaming always has a lag, which may often be up to 10 seconds, and depends on geography. If the instructions to run these animations are not properly synced to the actual arriving of the streaming, they will never be properly in sync with the video.

This task should do the changes relative to Unity and Kernel, but not the ecs
This task is relative to https://app.zenhub.com/workspaces/sdk-60febfe80dcd78000f01aca0/issues/decentraland/sdk/11

**Comment by olavra** [comment]
Pending repository of kernel to start working on it

**Comment by menduz** [comment]
Hello, kernel was never a dependency of this development. Please do start the development from unity and let's agree in this issue: decentraland/sdk#11 the event payload. We will take it from kernel from the @decentraland/sdk-team
