### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#943]
These test are failing randomly, we should fix them

- [x] AudioIsLooped
 ![image.png](https://images.zenhubusercontent.com/60647b38cc4b79842895cb82/954ac285-1896-43d9-a7d2-c6030c62ddc9)

- [x] ForgetIsCalledWhileAssetIsBeingLoaded 

![image.png](https://images.zenhubusercontent.com/60112efc21b0977dcc76d21f/71150f36-bd32-4f90-b532-40a2b21d2f62)

- [x] FeedbackIsNotDisplayedOnParent

![image.png](https://images.zenhubusercontent.com/60647b38cc4b79842895cb82/ff26bdfe-9157-4f8e-9b1c-fd4ea6140522)

The following test are using local resources but they are still making the call to the API. We should ensure that they don't call the the API so in case that the API doesn't work, the test will continue working

- [x] NFTShapeIsInvalidatedWhenStartingOutOfBounds
- [x] NFTShapeIsInvalidatedWhenLeavingBounds
- [x] NFTShapeIsResetWhenReenteringBounds

- [x] NFTShapeIsInvalidatedWhenStartingOutOfBoundsDebugMode
- [x] NFTShapeIsInvalidatedWhenLeavingBoundsDebugMode
- [x] NFTShapeIsResetWhenReenteringBoundsDebugMode

**Comment by Suduck** [comment]
Added more test that we need to fix

**Comment by Suduck** [comment]
No, I just fixed the ones related to builder in world, they weren't in this card

**Comment by Suduck** [comment]
Blocked until I talk with Brian about how to tackle the problem
