### ISSUE TITLE
Desktop Launcher developer Mode

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#944]
- [x] Select kernel and desktop build from list
- [x] input for URL params 
- [x] .exe --developer-mode
- [x] 1 folder per version

**Comment by kuruk-mm** [comment]
`Select kernel and desktop build from list` will require fetching the GitHub API to get the list of branches from `unity-renderer` and `kernel` and then create a UI to it in React JS.

I implemented it from command-line adding `--renderer-branch xxx` and `--url-params xxx`

If something really needed, I will separate that requirement to another issue.
