### ISSUE TITLE
Mention "X" (Quick help) on Skipping Tutorial

### ISSUE THREAD

**Issue by eordano** [decentraland/unity-renderer#95]
Users reported "X" as being very helpful. We should mention that when the user tries to skip the tutorial

![image](https://user-images.githubusercontent.com/42750/96446262-79138b00-1211-11eb-91dc-8babf04968eb.png)

Maybe a second dialog that lets the user know of this dialog...

![image](https://user-images.githubusercontent.com/42750/96447322-02c35880-1212-11eb-9656-0825d59664a6.png)

**Comment by olavra** [comment]
This has been integrated into the Start Menu, and is explained section by section during the tutorial
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/01d5ab4f-8a12-498d-a6b1-ae91bbfcc006)
