### ISSUE TITLE
Show loading screen at 0% when unity-renderer started by default

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/unity-renderer#959]
If we show `unity-renderer` before the kernel sent a message, we see this:

![image](https://user-images.githubusercontent.com/12563266/128939213-80b9c58f-5b52-4baa-91d5-b860a7f0c3bc.png)

We should show the loading at 0% or something else.

This usually happens with the new `play.decentraland.zone` and `explorer-desktop`.

**Comment by kuruk-mm** [comment]
This was fixed from the kernel by @menduz here: https://github.com/decentraland/kernel/commit/a9ca05e39819673744d476639137fffd42ad9b75

Maybe we can close this issue

**Comment by olavra** [comment]
I can confirm this is not happening anymore, but a new message "Teleporting 0,-1" appears at the beginning of the loading screen. We need to remove that.

**Comment by Suduck** [comment]
This message is sent by Kernel, (normally it should show "Teleporting to 0,0").

Blocked until we can modify kernel
