### ISSUE TITLE
Spike: Noticeable hiccups when loading or teleporting

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#961]
- [ ] Wondermine gets unresponsive for a moment while loading
https://play.decentraland.org/?position=-29%2C55&realm=loki-amber
- [ ] Genesis plaza
https://play.decentraland.org/
- [ ] Tominoya Casino
https://play.decentraland.org/?position=-120%2C134&realm=loki-amber
- [ ] Ethermon
https://play.decentraland.org/?position=-58%2C-46&realm=fenrir-amber

**Comment by Kinerius** [comment]
As far as I can analyze, most of the hiccups come from Decoding thousands of strings and serializing JSONs to build the scene at the same frame on the main thread, maybe this can be somehow parallelized using multithreading with async operations.
The second outlier is Texture2D.Compress() that also locks the main thread but with just a few calls

Another alternative could be delaying the loading screen until all data was processed correctly and no hiccups remain.

**Comment by Kinerius** [comment]
Notion document https://www.notion.so/decentraland/Loading-Performance-fa0140d6b52945b19f0b99a7fb2fae7d
