### ISSUE TITLE
Update all hardcoded 'peer.decentraland.org' usages

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#973]
Replace the deprecated 'peer.decentraland.org' hardcoded usage in the project with the url from the catalyst
`DataStore.i.playerRealm`.

![Screen Shot 2021-08-11 at 15.14.43.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/a1e9ba10-8279-4bae-8d1c-68168a4fa413)

**Comment by menduz** [comment]
Please look at https://github.com/decentraland/unity-renderer/pull/937 

ICatalyst.contentUrl should be used, not playerRealm
