### ISSUE TITLE
Some wearables appear repeatedly in the backpack

### ISSUE THREAD

**Issue by pravusjif** [decentraland/unity-renderer#984]
Reported by @ShibuyaMartin 

Apparently some NFT wearables appear repeated in some cases:

![Screen Shot 2021-08-13 at 14.18.09.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/a6842d02-0e47-4516-8a8e-1ffef238a9af)

Happened entering with: https://play.decentraland.zone/?WITH_COLLECTIONS=urn:decentraland:matic:collections-v2:0x72ab1ab365318a6464a50b7009ba395a58298db7

**Comment by xavi-dcl** [comment]
@kwspgoliasz is this still happening or can we close?

**Comment by xavi-dcl** [comment]
@kwspgoliasz is this still happening or can we close?
