### ISSUE TITLE
Add highlight shader to interactable entities

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#99]
In order to highlight which objects and entities are interactable in the virtual world, it is intended to include a glow effect shader that is activated when players focus on them. 

This effect will be shared by all entities that have these characteristics, and cannot be overwritten with a different shader, in order to maintain a common visual language for players. However, content creators will be able to disable this feature for their entities through the SDK.

**Acceptance Criteria**
- [x] Render an outline on interactable entities
- [x] Shader effect will activate on interactable entities on focus
- [ ] Shader effect will fade out once the player unfocus the entity
- [x] This effect should only appear on interactable objects that are focused and "on range" of interaction
- [ ] This feature will be activated by default to all interactable entities
- [ ] This will feature can be disabled per entity by the users through the SDK

![Screen Shot 2021-03-01 at 13.44.22.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/de2116e2-3c39-48e6-b5e1-4fbe7ba26d28)

**Comment by JuanSalice** [comment]
Modified the Lit shader to support the desired fresnel effect.
![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/360bf165-7946-4488-8dfd-8c7127fb771e)

https://images.zenhubusercontent.com/337227404/4245960b-d177-4f55-9c4b-4380ca06f15e/highlightv1.mp4

**Comment by JuanSalice** [comment]
- First approach. Added a new outline pass to the default lit shader.

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/ccd263c6-c5e2-430f-8497-579f5fb434d9)

**Comment by JuanSalice** [comment]
- Created a new shader iteration with outlines for plane objects.
- Started merging new shader functionalities into main outline shader.

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/13667b10-f2f7-448a-9283-cc0ceaca2612)

**Comment by JuanSalice** [comment]
- Implemented new outline approach using a render feature to override the material of some objects.
- Migrating effect from shader graph to the default lit shader in order to avoid creating extra render features.

![image.png](https://images.zenhubusercontent.com/6266af14486bbeb1de59f770/3846e7fb-58c7-4155-a313-ede5deedf598)

**Comment by JuanSalice** [comment]
- Added the outline effect to the current lit shader in the foward pass. 
- An optional renderer feature was added to get the outlines according to the normals of the object.

**Comment by JuanSalice** [comment]
- Fixed issue where the highlight was not visible when interacting.
- Adjusted values of the effect for better results in multiple shapes

https://images.zenhubusercontent.com/337227404/d959084d-750a-4aca-b39a-ffc0971ef365/2022_08_04_12_22_24_1.mp4

**Comment by JuanSalice** [comment]
- Adjusted values of the outline for it to be more noticeable.
- Outline not visible on build

**Comment by JuanSalice** [comment]
- New outline implementation test on different meshes.

https://images.zenhubusercontent.com/337227404/6d64e6cd-6a69-47d0-8527-22035a1b0e88/outline.mp4
