### ISSUE TITLE
Show network and environment ribbon in development

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-renderer#993]
Implement this RFC
https://docs.google.com/document/d/1Ezn18E_t9dHD2L093hjLvWOrdhzfrmiKPb4ZQwwb1VY/edit#heading=h.o921fa8bd20p

**Comment by BrianAmadori** [comment]
Are we sure we want the ribbon design? We should ask @RominaMarchetti for input on this.

**Comment by RominaMarchetti** [comment]
I totally agree with the intention of this document. Is this just for SDK developers or for every player? Is this a high priority feature? If so, let me know so I can think a clear and nice design for this feature - and please don't go for the ribbon design :rainbow: -
