### ISSUE TITLE
3rd person camera starts on the floor when spawning

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/unity-renderer#999]
Camera angles seem to be messed up when spawing in 3rd person into scenes that don't have a spawn point defined.

If I spawn into genesis plaza, for example, the camera is fine in 1st or 3rd person.
But if I spawn into any scene that doesn't have an explicitly defined spawn point, like an empty parcel, the camera looks fine in 1st person, but not in 3rd. The initial 3rd person camera is pointing from the floor, up.

https://play.decentraland.org/?position=-55%2C-6&realm=artemis-pink

![Screen Shot 2021-08-17 at 10.57.52.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/a1c19f7c-dfa1-4651-b3c8-e2afbab5b017)

this currently also happens in zone

I suspect the issue is with how the default camera angle of the default spawn point in 0,0,0 is interpreted.

**Comment by Kinerius** [comment]
I've noticed that opening the map for the first time makes the camera on first person to point to the sky too, the issue might be related to this

**Comment by Kinerius** [comment]
Something is not quite right, when we teleport anywhere, we receive a message from the kernel to set a specific rotation to the camera.
On the image below we can see those values for map position (0,0) and (-55,-6), I'm not sure if those are intended rotation values as Z would roll the camera and no one wants that.
![image.png](https://images.zenhubusercontent.com/61080c59fd1a374ce3f3b027/70e02a21-32df-4aa1-8c6e-129dab74d3b6)
